force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Age__c.field-meta.xml
<CustomField>
    <fullName>Animal_Age__c</fullName>
    <label>Animal Age</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>For EQUINE, see Help Text</description>
    <inlineHelpText>For EQUINE, choose one of the following: Horse, Donkey, Mule, Draft Horse, Mini Horse, Pony, Mini Mule, Mini Donkey</inlineHelpText>
    <label>Breed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;Unspecified&quot;</defaultValue>
    <label>Primary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Primary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Intake_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Intake_Date_Time__c</fullName>
    <label>Intake Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Type_of_Animal__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Animal__c</fullName>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Species</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/recordTypes/Behavior.recordType-meta.xml
<RecordType>
    <fullName>Behavior</fullName>
    <active>true</active>
    <label>Behavior</label>
</RecordType>

force-app/main/default/objects/Case/fields/Agency_Case__c.field-meta.xml
<CustomField>
    <fullName>Agency_Case__c</fullName>
    <label>Agency Case #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Primary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Bay roan</fullName>
    </customValue>
    <customValue>
        <fullName>Beige</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Blue roan</fullName>
    </customValue>
    <customValue>
        <fullName>Brindle</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Buckskin</fullName>
    </customValue>
    <customValue>
        <fullName>Buff</fullName>
    </customValue>
    <customValue>
        <fullName>Calico</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut/Sorrel</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Dun</fullName>
    </customValue>
    <customValue>
        <fullName>Fawn</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Grulla</fullName>
    </customValue>
    <customValue>
        <fullName>Hairless</fullName>
    </customValue>
    <customValue>
        <fullName>Liver chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Palomino</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Red roan</fullName>
    </customValue>
    <customValue>
        <fullName>Roan</fullName>
    </customValue>
    <customValue>
        <fullName>Seal</fullName>
    </customValue>
    <masterLabel>Primary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Species.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avian</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Cow</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Equine</fullName>
    </customValue>
    <customValue>
        <fullName>Exotic</fullName>
    </customValue>
    <customValue>
        <fullName>Fowl</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <masterLabel>Species</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestAnimalPictureUploaderController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestAnimalPictureUploaderController {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
        case objCase = new Case(Status = 'On hold',Origin='Email',Agency_Case__c = 'test');
        insert objCase ;
        
        Animal__c objAnimal = new Animal__c(Case__c =objCase.id, Name='A-001-West',type_of_animal__c='Cat',breed__c='Coonhound',gender__c='MI',Animal_Age__c=12,Color__c='Brown',Intake_Date_Time__c= DateTime.now());
        insert objAnimal;
        
        
        Attachment  objAttachment  = new Attachment (parentId=objAnimal.id,Name='test',body= Blob.valueof('test'));
        insert objAttachment ;
        
        
        PageReference pageRef = Page.AnimalPictureUploader;
        Test.setCurrentPage(pageRef);
        apexpages.currentpage().getparameters().put('cid' ,objAnimal.id);
        
        AnimalPictureUploaderController  objAnimalPictureUploaderController  = new AnimalPictureUploaderController ();
        objAnimalPictureUploaderController.initialise();
        
        
        }
   }