force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Name_Id__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name_Id__c</fullName>
    <formula>Animal_Name__c + &apos; (&apos; +  Name + &apos;)&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animal Name/Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Behavior Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Behavior Case Worker)</relationshipLabel>
    <relationshipName>Beh_Case_Worker_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Calendar_Schedule_Config__mdt/Calendar_Schedule_Config__mdt.object-meta.xml
<CustomObject>
    <description>Used to auto schedule items</description>
    <label>Calendar Schedule Config</label>
    <pluralLabel>Calendar Schedule Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Is_Generic_Contact__c.field-meta.xml
<CustomField>
    <fullName>Is_Generic_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Generic Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/test/test_AutoScheduleTasksUtil.cls
@isTest
private class test_AutoScheduleTasksUtil {
    @isTest 
    static void getCalendarConfigTetst(){
        Test.startTest();
            Map<String, Calendar_Schedule_Config__mdt> configs = AutoScheduleTasksUtil.getCalendarConfig('Playgroup');
        Test.stopTest();

        System.assert(!configs.isEmpty(), 'shold have returned configs, instead was empty');
    }

    @isTest 
    static void getDateMap(){
        Map<String, Calendar_Schedule_Config__mdt> configs = AutoScheduleTasksUtil.getCalendarConfig('Playgroup');

        Test.startTest();
            Map<String, Date> dateMap = AutoScheduleTasksUtil.getDateMap(configs.values()[0]);
        Test.stopTest();

        System.assert(!dateMap.isEmpty(), 'shold have returned configs, instead was empty');
    }

    @isTest
    static void determineResourcesSuccess(){
        Animal__c anim = TestDataFactory.createAnimalWithName('anim');
        anim = [SELECT Id, Animal_Name_ID__c, Behavior_Case_Worker__r.Is_Generic_Contact__c FROM Animal__c WHERE Id =: anim.Id LIMIT 1];

        test.startTest();
            String resource = AutoScheduleTasksUtil.determineResources(anim);
        test.stopTest();

        System.assertEquals('anim (anim);', resource);
    }

    @isTest
    static void determineResourcesNoResource(){
        Animal__c anim = TestDataFactory.createAnimalWithName('anim');

        test.startTest();
            String resource = AutoScheduleTasksUtil.determineResources(anim);
        test.stopTest();

        System.assertEquals('', resource);
    }
}