force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/Animal_Playgroup__c.object-meta.xml
<CustomObject>
    <label>Animal Playgroup</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Animal Playgroup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Playgroups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Playgroup__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Common_Playgroup_Note_Sections__c.field-meta.xml
<CustomField>
    <fullName>Common_Playgroup_Note_Sections__c</fullName>
    <label>Common Playgroup Note Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Greeting</fullName>
            </value>
            <value>
                <fullName>After Greeting</fullName>
            </value>
            <value>
                <fullName>Approached by another dog</fullName>
            </value>
            <value>
                <fullName>Handler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Common_Playgroup_Notes__c.field-meta.xml
<CustomField>
    <fullName>Common_Playgroup_Notes__c</fullName>
    <label>Common Playgroup Notes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Greeted – tense</fullName>
            </value>
            <value>
                <fullName>Greeted – politely</fullName>
            </value>
            <value>
                <fullName>Greeted – rude but playful</fullName>
            </value>
            <value>
                <fullName>Greeted – playful</fullName>
            </value>
            <value>
                <fullName>Greeted – no greeting</fullName>
            </value>
            <value>
                <fullName>Greeted – rude, aroused, not social</fullName>
            </value>
            <value>
                <fullName>Disengaged - remained tense</fullName>
            </value>
            <value>
                <fullName>Disengaged – relaxed some</fullName>
            </value>
            <value>
                <fullName>Disengaged – relaxed and milled</fullName>
            </value>
            <value>
                <fullName>Played – chase</fullName>
            </value>
            <value>
                <fullName>Played – wrestle</fullName>
            </value>
            <value>
                <fullName>Played – rude</fullName>
            </value>
            <value>
                <fullName>Played – roughly</fullName>
            </value>
            <value>
                <fullName>Played – boxed</fullName>
            </value>
            <value>
                <fullName>Played – arousal escalated</fullName>
            </value>
            <value>
                <fullName>Aggressed</fullName>
            </value>
            <value>
                <fullName>Took breaks</fullName>
            </value>
            <value>
                <fullName>Unresponsive to dogs’ correction</fullName>
            </value>
            <value>
                <fullName>Tolerated play solicitations</fullName>
            </value>
            <value>
                <fullName>Tolerated rude behavior</fullName>
            </value>
            <value>
                <fullName>Appropriately corrected rude behavior</fullName>
            </value>
            <value>
                <fullName>Overcorrected rude approach</fullName>
            </value>
            <value>
                <fullName>Defensive</fullName>
            </value>
            <value>
                <fullName>Responded to handler correction</fullName>
            </value>
            <value>
                <fullName>Unresponsive to handler correction</fullName>
            </value>
            <value>
                <fullName>Requires drag for TO</fullName>
            </value>
            <value>
                <fullName>Requires Muzzle</fullName>
            </value>
            <value>
                <fullName>Requires handler to crate breaks in play</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Playgroup_Session__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Session</label>
    <referenceTo>Playgroup_Session__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/Behavior_Evaluation__c.object-meta.xml
<CustomObject>
    <label>Behavior Evaluation</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Behavior Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Behavior Evaluations</relationshipLabel>
    <relationshipName>Behavior_Evaluations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EntityHistory__c/EntityHistory__c.object-meta.xml
<CustomObject>
    <label>Entity History</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Entity History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entity Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EntityHistory__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Entity Histories</relationshipLabel>
    <relationshipName>Entity_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EntityHistory__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>Field Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EntityHistory__c/fields/NewValue__c.field-meta.xml
<CustomField>
    <fullName>NewValue__c</fullName>
    <label>New Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EntityHistory__c/fields/ObjectId__c.field-meta.xml
<CustomField>
    <fullName>ObjectId__c</fullName>
    <label>Object Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EntityHistory__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EntityHistory__c/fields/OldValue__c.field-meta.xml
<CustomField>
    <fullName>OldValue__c</fullName>
    <label>Old Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Low_Stress_Note__c/Low_Stress_Note__c.object-meta.xml
<CustomObject>
    <label>Low Stress Note</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Low Stress Note #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Low Stress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Low_Stress_Note__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Low Stress Notes</relationshipLabel>
    <relationshipName>Low_Stress_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/Playgroup_Session__c.object-meta.xml
<CustomObject>
    <label>Playgroup Session</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroup Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup_Session__c/fields/Animal_Playgroup__c.field-meta.xml
<CustomField>
    <fullName>Animal_Playgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Playgroup</label>
    <referenceTo>Animal_Playgroup__c</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/fields/Playgroup_Leader__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shelter_Note__c/Shelter_Note__c.object-meta.xml
<CustomObject>
    <label>Shelter Note</label>
    <nameField>
        <displayFormat>SN-{00000}</displayFormat>
        <label>Shelter Note ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shelter Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shelter_Note__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Shelter Notes</relationshipLabel>
    <relationshipName>Shelter_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/Treatment_Session__c.object-meta.xml
<CustomObject>
    <label>Treatment Session</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Treatment Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Session__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Sessions</relationshipLabel>
    <relationshipName>Treatment_Sessions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/fields/Session_Contact__c.field-meta.xml
<CustomField>
    <fullName>Session_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Session Contacts</relationshipLabel>
    <relationshipName>Treatment_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <label>Treatment Plan</label>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Treatment Sessions</relationshipLabel>
    <relationshipName>Treatment_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AnimalPlacementPDFControllerTest.cls
@isTest
public class AnimalPlacementPDFControllerTest {
    
    @isTest
    static void testPlacementPDF(){
        TestDataFactory.createAdultBehaviorEvaluation(false);
        Animal__c anm = [Select Id from Animal__c LIMIT 1];
        Behavior_Evaluation__c beh = [SELECT Id, animal__c FROM Behavior_Evaluation__c LIMIT 1];
        Treatment_Plan__c plan = new Treatment_Plan__c();
        insert plan;

        Contact con = TestDataFactory.createContact();

        Treatment_Session__c session = new Treatment_Session__c(
            Treatment_Plan__c = plan.Id,
            Session_Contact__c = con.Id,
            Animal__c = anm.Id
        );
        insert session;
        
        Playgroup_Session__c pgs = createPlaygroupSession();
        Animal_Playgroup__c[] aPgs = createAnimalPlaygroups(pgs.Id, new Animal__c[]{anm});
        EntityHistory__c history = new EntityHistory__c(FieldName__c = 'Play Style Notes', 
                                                        NewValue__c = 'test1', 
                                                        OldValue__c = 'test2', 
                                                        ParentId__c = anm.Id,
                                                        ObjectId__c = anm.Id, 
                                                        ObjectName__c = 'Animal__c');
        insert history;
        EntityHistory__c history2 = new EntityHistory__c(FieldName__c = 'Overall Evaluation Grade', 
                                                        NewValue__c = 'test1', 
                                                        OldValue__c = 'test2', 
                                                        ParentId__c = beh.animal__c,
                                                        ObjectId__c = beh.Id, 
                                                        ObjectName__c = 'Behavior_Evaluation__c');
        insert history2;
        ApexPages.StandardController sc = new ApexPages.StandardController(anm);
        ApexPages.currentPage().getParameters().put('id',anm.Id);
        PageReference pageRef = sc.view();
		
        AnimalPlacementPDFController apdf = new AnimalPlacementPDFController(sc);                
		
        test.startTest();       
        AnimalPlacementPDFController.AnimalWrapper abc = apdf.anmwrapper;
        List<AnimalPlacementPDFController.animalPlaySummary> aPlayGroups = apdf.aPlayGroups;
        List<AnimalPlacementPDFController.SessionProtocolWrapper>  aTreatmentSession = apdf.aTreatmentSession;
        List<AnimalPlacementPDFController.AnimalGradeHistory>  gradeHistory = apdf.gradeHistory;
        List<AnimalPlacementPDFController.BehaviorEvaluation> behaviorEvaluations = apdf.behaviorEvaluations;
        List<Shelter_Note__c> shelterNotes = apdf.shelterNotes;
        List<Low_Stress_Note__c> lowStressNotes = apdf.lowStressNotes;

        
        
        test.setCurrentPage(pageRef);                       

        test.stopTest();
        System.assertNotEquals(null, apdf.anmwrapper);
        System.assertNotEquals(null, apdf.aPlayGroups);
        System.assertNotEquals(null, apdf.gradeHistory);
        System.assertNotEquals(null, apdf.behaviorEvaluations);
        System.assertNotEquals(null, aTreatmentSession);
        System.assertNotEquals(null, shelterNotes);
        System.assertNotEquals(null, lowStressNotes);
    }
    
    @isTest
    static void testDiscoverPDFPuppy(){
        TestDataFactory.createPuppyBehaviorEvaluation();
        Animal__c anm = [Select Id from Animal__c LIMIT 1];
        Behavior_Evaluation__c beh = [SELECT Id, animal__c FROM Behavior_Evaluation__c LIMIT 1];
        Treatment_Plan__c plan = new Treatment_Plan__c();
        insert plan;

        Contact con = TestDataFactory.createContact();

        Treatment_Session__c session = new Treatment_Session__c(
            Treatment_Plan__c = plan.Id,
            Session_Contact__c = con.Id,
            Animal__c = anm.Id
        );
        insert session;
        
        Playgroup_Session__c pgs = createPlaygroupSession();
        Animal_Playgroup__c[] aPgs = createAnimalPlaygroups(pgs.Id, new Animal__c[]{anm});
        EntityHistory__c history2 = new EntityHistory__c(FieldName__c = 'Overall Evaluation Grade', 
                                                        NewValue__c = 'test1', 
                                                        OldValue__c = 'test2', 
                                                        ParentId__c = beh.animal__c,
                                                        ObjectId__c = beh.Id, 
                                                        ObjectName__c = 'Behavior_Evaluation__c');
        insert history2;
        ApexPages.StandardController sc = new ApexPages.StandardController(anm);
        ApexPages.currentPage().getParameters().put('id',anm.Id);
        PageReference pageRef = sc.view();
		
        AnimalPlacementPDFController apdf = new AnimalPlacementPDFController(sc);                
		
        test.startTest();       
		AnimalPlacementPDFController.AnimalWrapper abc = apdf.anmwrapper;
        List<AnimalPlacementPDFController.animalPlaySummary> aPlayGroups = apdf.aPlayGroups;
        List<AnimalPlacementPDFController.SessionProtocolWrapper>  aTreatmentSession = apdf.aTreatmentSession;
        List<AnimalPlacementPDFController.AnimalGradeHistory>  gradeHistory = apdf.gradeHistory;
        List<AnimalPlacementPDFController.BehaviorEvaluation> behaviorEvaluations = apdf.behaviorEvaluations;
        List<Shelter_Note__c> shelterNotes = apdf.shelterNotes;
        List<Low_Stress_Note__c> lowStressNotes = apdf.lowStressNotes;
        
        test.setCurrentPage(pageRef);                       

        test.stopTest();
        System.assertNotEquals(null, apdf.anmwrapper);
        System.assertNotEquals(null, apdf.aPlayGroups);
        System.assertNotEquals(null, apdf.gradeHistory);
        System.assertNotEquals(null, apdf.behaviorEvaluations);
        System.assertNotEquals(null, aTreatmentSession);
        System.assertNotEquals(null, shelterNotes);
        System.assertNotEquals(null, lowStressNotes);
    }

    @isTest
    static void testTreatmentSessionHistory(){
        Session_Protocol_Scale__c[] spScales = TestDataFactory.createSessionProtocolScales();
        Animal__c anm = [Select Id from Animal__c LIMIT 1];
        
        ApexPages.StandardController sc = new ApexPages.StandardController(anm);
        ApexPages.currentPage().getParameters().put('id',anm.Id);
        PageReference pageRef = sc.view();
		
        AnimalPlacementPDFController apdf = new AnimalPlacementPDFController(sc);                
		
        test.startTest();       
        List<AnimalPlacementPDFController.SessionProtocolWrapper>  aTreatmentSession = apdf.aTreatmentSession;        
        test.setCurrentPage(pageRef);
        test.stopTest();

        System.assertNotEquals(null, aTreatmentSession);
        System.assertNotEquals(null, aTreatmentSession[0].cellInfosTopRow);
    }
    
    private static Playgroup_Session__c createPlaygroupSession(){
        Contact con = TestDataFactory.createContact();
        Playgroup_Session__c playgroup = new Playgroup_Session__c(
            Playgroup_Leader__c = con.Id
        );
        insert playgroup;
        return playgroup;
    }

    private static Animal_Playgroup__c[] createAnimalPlaygroups(Id sessionid, Animal__c[] animals){
        Animal_Playgroup__c[] aPgList = new Animal_Playgroup__c[0];
        for(Animal__c anim : animals){
            aPgList.add(new Animal_Playgroup__c(
                Playgroup_Session__c = sessionId,
                Animal__c = anim.Id,
                Common_Playgroup_Note_Sections__c = 'Greeting',
                Common_Playgroup_Notes__c = 'Airhorn',
                Play_Rating__c = 'Green',
                Playgroup_Individual_Notes__c = 'Individual note'
            ));
        }
        insert aPgList;
        return aPgList;
    }
}