force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age Estimate at Intake</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Age_Estimate_at_Intake</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Medication_Data_Time__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Medication_Data_Time__c</fullName>
    <description>This field captures the data time whenever the behavior medication flag is checked</description>
    <label>Behavior Medication Data/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Medication_Flag__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Medication_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Behavior Medication Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>For EQUINE, see Help Text</description>
    <inlineHelpText>For EQUINE, choose one of the following: Horse, Donkey, Mule, Draft Horse, Mini Horse, Pony, Mini Mule, Mini Donkey</inlineHelpText>
    <label>Breed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;Unspecified&quot;</defaultValue>
    <label>Primary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Primary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Equine_Body_Pattern__c.field-meta.xml
<CustomField>
    <fullName>Equine_Body_Pattern__c</fullName>
    <label>Equine Body Pattern</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Equine_Body_Pattern</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Equine_Leg_Marking__c.field-meta.xml
<CustomField>
    <fullName>Equine_Leg_Marking__c</fullName>
    <inlineHelpText>LF = left front, RR = right rear. Select none if no leg markings.</inlineHelpText>
    <label>Equine Leg Marking</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Equine_Leg_Marking</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Forensic_Status__c.field-meta.xml
<CustomField>
    <fullName>Forensic_Status__c</fullName>
    <label>Forensic Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Forensic Hold</fullName>
            </value>
            <value>
                <fullName>Released from Forensic Hold</fullName>
            </value>
            <value>
                <fullName>Non-Criminal Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Markings__c.field-meta.xml
<CustomField>
    <fullName>Markings__c</fullName>
    <label>Markings</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Markings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Microchip_Number__c.field-meta.xml
<CustomField>
    <fullName>Microchip_Number__c</fullName>
    <label>Microchip Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Microchip_Results__c.field-meta.xml
<CustomField>
    <fullName>Microchip_Results__c</fullName>
    <description>If scanned, Positive or Negative?</description>
    <inlineHelpText>If scanned, Positive or Negative?</inlineHelpText>
    <label>Microchip Results</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Scanned_for_Microchip__c.field-meta.xml
<CustomField>
    <fullName>Scanned_for_Microchip__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scanned for Microchip</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Secondary_Color__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Color__c</fullName>
    <label>Secondary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Secondary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Storm_Distress_Anxiety__c.field-meta.xml
<CustomField>
    <fullName>Storm_Distress_Anxiety__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Storm Distress/Anxiety</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Storm_Distress_Anxiety_Notes__c.field-meta.xml
<CustomField>
    <fullName>Storm_Distress_Anxiety_Notes__c</fullName>
    <label>Storm Distress/Anxiety Notes</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Tertiary_Color__c.field-meta.xml
<CustomField>
    <fullName>Tertiary_Color__c</fullName>
    <label>Tertiary Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tertiary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/recordTypes/Behavior.recordType-meta.xml
<RecordType>
    <fullName>Behavior</fullName>
    <active>true</active>
    <label>Behavior</label>
</RecordType>

force-app/main/default/objects/Animal_Exam_Sheet__c/Animal_Exam_Sheet__c.object-meta.xml
<CustomObject>
    <label>Animal Exam Sheet</label>
    <nameField>
        <displayFormat>EX-{0}</displayFormat>
        <label>Exam Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Exam Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Age_Estimate_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Age_Estimate_Picklist__c</fullName>
    <label>Age Estimate at Intake</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Species_PL__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Age_Estimate_at_Intake</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animal Exam Sheets</relationshipLabel>
    <relationshipName>Animal_Exam_Sheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Animal_Exam_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Animal_Exam_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Exam Sheet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Animal_Exam_Sheet__c.Animal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Animal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Animal_Exam_Sheet__c</referenceTo>
    <relationshipLabel>Animal Exam Sheets</relationshipLabel>
    <relationshipName>Animal_Exam_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <formula>Animal__r.Breeds_Combined__c</formula>
    <label>Breed</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Breed_Text__c.field-meta.xml
<CustomField>
    <fullName>Breed_Text__c</fullName>
    <label>Breed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <formula>Text(Animal__r.Color__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Color</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Equine_Body_Pattern__c.field-meta.xml
<CustomField>
    <fullName>Equine_Body_Pattern__c</fullName>
    <label>Equine Body Pattern</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Equine_Body_Pattern</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Equine_Leg_Marking__c.field-meta.xml
<CustomField>
    <fullName>Equine_Leg_Marking__c</fullName>
    <label>Equine Leg Marking</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Equine_Leg_Marking</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <formula>Text(Animal__r.Gender__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sex</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Markings__c.field-meta.xml
<CustomField>
    <fullName>Markings__c</fullName>
    <label>Markings</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Species_PL__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Markings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Microchip_Results__c.field-meta.xml
<CustomField>
    <fullName>Microchip_Results__c</fullName>
    <label>Microchip Results</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Primary_Color__c.field-meta.xml
<CustomField>
    <fullName>Primary_Color__c</fullName>
    <description>Update dependencies on Animal object too.</description>
    <label>Primary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Species_PL__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Primary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Secondary_Color__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Color__c</fullName>
    <label>Secondary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Species_PL__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Secondary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Species_PL__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Subjective__c.field-meta.xml
<CustomField>
    <fullName>Subjective__c</fullName>
    <description>This is where we can write comments on if the patient is having vomiting, diarrhea, coughing, sneezing, lethargy, urinating, eating well and comments like ‘doing significantly better today than yesterday’.</description>
    <inlineHelpText>This is where we can write comments on if the patient is having vomiting, diarrhea, coughing, sneezing, lethargy, urinating, eating well and comments like ‘doing significantly better today than yesterday’.</inlineHelpText>
    <label>Subjective/Objective Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Age_Estimate_at_Intake.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Juvenile w/dam</fullName>
    </customValue>
    <customValue>
        <fullName>&lt; 6 months</fullName>
    </customValue>
    <customValue>
        <fullName>0-4 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-8 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>8-12 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>12-16 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 1 year</fullName>
    </customValue>
    <customValue>
        <fullName>1 year - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>2-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>5-7 years</fullName>
    </customValue>
    <customValue>
        <fullName>7-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>greater than 10 yrs</fullName>
    </customValue>
    <customValue>
        <fullName>Egg</fullName>
    </customValue>
    <customValue>
        <fullName>Chick: Up To 8 Weeks</fullName>
    </customValue>
    <customValue>
        <fullName>Pullet: Female &lt; 2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Adult: &gt;2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Stag: Male &lt;2YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (with dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (without dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Weanling</fullName>
    </customValue>
    <customValue>
        <fullName>Yearling</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>4-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>6-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>11-15 years</fullName>
    </customValue>
    <customValue>
        <fullName>15-20 years</fullName>
    </customValue>
    <customValue>
        <fullName>20+ years</fullName>
    </customValue>
    <customValue>
        <fullName>Chick (0-10 wks.)</fullName>
    </customValue>
    <masterLabel>Age Estimate at Intake</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Equine_Body_Pattern.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Appaloosa</fullName>
    </customValue>
    <customValue>
        <fullName>Blanket</fullName>
    </customValue>
    <customValue>
        <fullName>Dapple</fullName>
    </customValue>
    <customValue>
        <fullName>Leopard</fullName>
    </customValue>
    <customValue>
        <fullName>Overo</fullName>
    </customValue>
    <customValue>
        <fullName>Pinto</fullName>
    </customValue>
    <customValue>
        <fullName>Roan</fullName>
    </customValue>
    <customValue>
        <fullName>Tobiano</fullName>
    </customValue>
    <customValue>
        <fullName>Varnish</fullName>
    </customValue>
    <customValue>
        <fullName>(none)</fullName>
        <isActive>false</isActive>
        <label>(none)</label>
    </customValue>
    <masterLabel>Equine Body Pattern</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Equine_Leg_Marking.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>(none)</fullName>
    </customValue>
    <customValue>
        <fullName>LF Coronet</fullName>
    </customValue>
    <customValue>
        <fullName>LF Pastern</fullName>
    </customValue>
    <customValue>
        <fullName>LF Sock</fullName>
    </customValue>
    <customValue>
        <fullName>LF Stocking</fullName>
    </customValue>
    <customValue>
        <fullName>RF Coronet</fullName>
    </customValue>
    <customValue>
        <fullName>RF Pastern</fullName>
    </customValue>
    <customValue>
        <fullName>RF Sock</fullName>
    </customValue>
    <customValue>
        <fullName>RF Stocking</fullName>
    </customValue>
    <customValue>
        <fullName>LR Coronet</fullName>
    </customValue>
    <customValue>
        <fullName>LR Pastern</fullName>
    </customValue>
    <customValue>
        <fullName>LR Sock</fullName>
    </customValue>
    <customValue>
        <fullName>LR Stocking</fullName>
    </customValue>
    <customValue>
        <fullName>RR Coronet</fullName>
    </customValue>
    <customValue>
        <fullName>RR Pastern</fullName>
    </customValue>
    <customValue>
        <fullName>RR Sock</fullName>
    </customValue>
    <customValue>
        <fullName>RR Stocking</fullName>
    </customValue>
    <customValue>
        <fullName>LF Partial Coronet</fullName>
    </customValue>
    <customValue>
        <fullName>LF Partial Pastern</fullName>
    </customValue>
    <customValue>
        <fullName>RR Partial Sock</fullName>
    </customValue>
    <masterLabel>Equine Leg Marking</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Markings.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bald</fullName>
    </customValue>
    <customValue>
        <fullName>Belted</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blaze</fullName>
    </customValue>
    <customValue>
        <fullName>Blue Point</fullName>
    </customValue>
    <customValue>
        <fullName>Bluies</fullName>
    </customValue>
    <customValue>
        <fullName>Brindle</fullName>
    </customValue>
    <customValue>
        <fullName>Calico</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate Point</fullName>
    </customValue>
    <customValue>
        <fullName>Dapple</fullName>
    </customValue>
    <customValue>
        <fullName>Double Dapple</fullName>
    </customValue>
    <customValue>
        <fullName>Grizzling</fullName>
    </customValue>
    <customValue>
        <fullName>Harlequin</fullName>
    </customValue>
    <customValue>
        <fullName>Mask</fullName>
    </customValue>
    <customValue>
        <fullName>Mask Black</fullName>
    </customValue>
    <customValue>
        <fullName>Merle</fullName>
    </customValue>
    <customValue>
        <fullName>Mottled</fullName>
    </customValue>
    <customValue>
        <fullName>Nose</fullName>
    </customValue>
    <customValue>
        <fullName>Overlay, Black</fullName>
    </customValue>
    <customValue>
        <fullName>Pointed</fullName>
    </customValue>
    <customValue>
        <fullName>Sable</fullName>
    </customValue>
    <customValue>
        <fullName>Seal Point</fullName>
    </customValue>
    <customValue>
        <fullName>Smut</fullName>
    </customValue>
    <customValue>
        <fullName>Snip</fullName>
    </customValue>
    <customValue>
        <fullName>Solid</fullName>
    </customValue>
    <customValue>
        <fullName>Speckled</fullName>
    </customValue>
    <customValue>
        <fullName>Spotted</fullName>
    </customValue>
    <customValue>
        <fullName>Star</fullName>
    </customValue>
    <customValue>
        <fullName>Star/Snip</fullName>
    </customValue>
    <customValue>
        <fullName>Star/Strip/Snip</fullName>
    </customValue>
    <masterLabel>Markings</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Primary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Bay roan</fullName>
    </customValue>
    <customValue>
        <fullName>Beige</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Blue roan</fullName>
    </customValue>
    <customValue>
        <fullName>Brindle</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Buckskin</fullName>
    </customValue>
    <customValue>
        <fullName>Buff</fullName>
    </customValue>
    <customValue>
        <fullName>Calico</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut/Sorrel</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Dun</fullName>
    </customValue>
    <customValue>
        <fullName>Fawn</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Grulla</fullName>
    </customValue>
    <customValue>
        <fullName>Hairless</fullName>
    </customValue>
    <customValue>
        <fullName>Liver chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Palomino</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Red roan</fullName>
    </customValue>
    <customValue>
        <fullName>Roan</fullName>
    </customValue>
    <customValue>
        <fullName>Seal</fullName>
    </customValue>
    <masterLabel>Primary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Secondary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agouti</fullName>
    </customValue>
    <customValue>
        <fullName>Apricot</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Blue Dilute</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Buckskin</fullName>
    </customValue>
    <customValue>
        <fullName>Champagne</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Fawn</fullName>
    </customValue>
    <customValue>
        <fullName>Gold</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Gray</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Lemon</fullName>
    </customValue>
    <customValue>
        <fullName>Lilac</fullName>
    </customValue>
    <customValue>
        <fullName>Liver</fullName>
    </customValue>
    <customValue>
        <fullName>Mahogany</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Pepper and Salt</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Rust</fullName>
    </customValue>
    <customValue>
        <fullName>Sable</fullName>
    </customValue>
    <customValue>
        <fullName>Seal</fullName>
    </customValue>
    <customValue>
        <fullName>Silver</fullName>
    </customValue>
    <customValue>
        <fullName>Tan</fullName>
    </customValue>
    <customValue>
        <fullName>Wheaten</fullName>
    </customValue>
    <masterLabel>Secondary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tertiary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Tan</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <customValue>
        <fullName>Yellow</fullName>
    </customValue>
    <customValue>
        <fullName>Mustard</fullName>
        <isActive>false</isActive>
        <label>Mustard</label>
    </customValue>
    <customValue>
        <fullName>Merle</fullName>
        <isActive>false</isActive>
        <label>Merle</label>
    </customValue>
    <customValue>
        <fullName>Buff</fullName>
        <isActive>false</isActive>
        <label>Buff</label>
    </customValue>
    <customValue>
        <fullName>Brindle</fullName>
        <isActive>false</isActive>
        <label>Brindle</label>
    </customValue>
    <customValue>
        <fullName>Tabby</fullName>
        <isActive>false</isActive>
        <label>Tabby</label>
    </customValue>
    <masterLabel>Tertiary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AnimalExamSheetTriggerHandler.cls
public class AnimalExamSheetTriggerHandler {
    
    /*public static void insertHandler(){
        
        for (Animal_Exam_Sheet__c a : (List<Animal_Exam_Sheet__c>)Trigger.new){
                    
                    system.debug(a);
                        Animal__c anim = [SELECT Id, 
                                        Breed__c, 
                                        Gender__c, 
                                        Age__c, 
                                        Markings__c, 
                                        Color__c, 
                                        Secondary_Color__c, 
                                        Tertiary_Color__c, 
                                        Scanned_for_Microchip__c, 
                                        Microchip_Results__c, 
                                        Microchip_Number__c, 
                                        Equine_Body_Pattern__c,
                                        Equine_Leg_Marking__c ,
                                        Forensic_Status__c
                                        	FROM Animal__c WHERE Id = :a.Animal__c];
                    
                    system.debug(anim);
                        
                        if (a.Breed_Text__c != null){
                            anim.Breed__c = a.Breed_Text__c;
                        }
                        
                        if (a.Sex__c != null){
                            anim.Gender__c = a.Sex__c;
                        }
                        
                        if (a.Age_Estimate_Picklist__c != null){
                            anim.Age__c = a.Age_Estimate_Picklist__c;
                        }      
                        
                        if (a.Markings__c != null){
                            anim.Markings__c = a.Markings__c;
                        }      
                        if (a.Primary_Color__c != null){
                            anim.Color__c = a.Primary_Color__c;
                        }
                        if (a.Secondary_Color__c != null){
                            anim.Secondary_Color__c = a.Secondary_Color__c;
                        }
                        if (a.Tertiary_Color__c != null){
                            anim.Tertiary_Color__c = a.Tertiary_Color__c;
                        }
                        if (a.Scanned_for_Microchip__c != null){
                            anim.Scanned_for_Microchip__c = a.Scanned_for_Microchip__c;
                        }
                        if (a.Microchip_Results__c != null){
                            anim.Microchip_Results__c = a.Microchip_Results__c;
                        }
                        if (a.Microchip_Number__c != null){
                            anim.Microchip_Number__c = a.Microchip_Number__c;
                        }
                        if (a.Equine_Body_Pattern__c != null){
                            anim.Equine_Body_Pattern__c = a.Equine_Body_Pattern__c;
                        }
                        if (a.Equine_Leg_Marking__c != null){
                            anim.Equine_Leg_Marking__c = a.Equine_Leg_Marking__c;
                        }    
            			if (a.Forensic_Status__c != null){
                            anim.Forensic_Status__c = a.Forensic_Status__c;
                        }    
                        
                        update anim;
                    	system.debug(anim);
                    }
        
    }*/
   
    public static void updateStormAnxietyandMedicationonAnimal(){
        Set<Id> animalIds = new Set<Id>();
        if(Trigger.isInsert || Trigger.isUndelete){
            for(SObject aes : Trigger.new){
                animalIds.add((Id)aes.get('Animal__c'));
            }
        }
        if(Trigger.isUpdate || Trigger.isDelete){
            for(SObject aes : Trigger.old){
                animalIds.add((Id)aes.get('Animal__c'));
            }
        }
        List<Animal__c> anmList = [Select Id,Storm_Distress_Anxiety__c,Storm_Distress_Anxiety_Notes__c,Behavior_Medication_Flag__c, Behavior_Medication_Data_Time__c,(Select id, Subjective__c, Exam_Type__c  from Animal_Exam_Sheets__r WHERE RecordType.Name = 'Behavior Exam' Order By CreatedDate DESC) from Animal__c where Id IN : animalIds];
        for(Animal__c anm :anmList){
            for(Animal_Exam_Sheet__c aes : anm.Animal_Exam_Sheets__r){
                //anm.Storm_Distress_Anxiety__c = false;
                //anm.Storm_Distress_Anxiety_Notes__c = '';
                //anm.Behavior_Medication_Flag__c = false;
                if(aes.Exam_Type__c == 'Storm Distress/Anxiety'){
                    anm.Storm_Distress_Anxiety__c = true;
                    anm.Storm_Distress_Anxiety_Notes__c = anm.Animal_Exam_Sheets__r[0].Subjective__c ;
                    break;
                }
                if(aes.Exam_Type__c == 'Behavior Medications'){
                    anm.Behavior_Medication_Flag__c = true;
                    anm.Behavior_Medication_Data_Time__c = system.now();
                    break;
                }
            }
        }
        update anmList;
    }
}