force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Playgroup__c/Animal_Playgroup__c.object-meta.xml
<CustomObject>
    <label>Animal Playgroup</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Animal Playgroup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Playgroups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Playgroup__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Playgroup_Session__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Session</label>
    <referenceTo>Playgroup_Session__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/Playgroup_Session__c.object-meta.xml
<CustomObject>
    <label>Playgroup Session</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroup Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup_Session__c/fields/Animal_Playgroup__c.field-meta.xml
<CustomField>
    <fullName>Animal_Playgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Playgroup</label>
    <referenceTo>Animal_Playgroup__c</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/test/Test_AnimalPlaygroupTriggerHandler.cls
@iSTest 
private class Test_AnimalPlaygroupTriggerHandler {
    private static String[] animalNames = new String[]{
        'Fido',
        'Willow',
        'AJ',
        'Apollo'
    };

    @TestSetup
    static void testSetup(){
        TestDataFactory.createPlaygroupSessionWithAnimals();
        for(String st : animalNames){
            TestDataFactory.createAnimalWithName(st);
        }
    }
    @isTest static void newPGSession() {
        Playgroup_Session__c ps = [SELECT Id FROM Playgroup_Session__c LIMIT 1];

        Animal_Playgroup__c[] apgs = new Animal_Playgroup__c[0];
        for(Animal__c anim : [SELECT Id FROM Animal__c]){
            apgs.add( new Animal_Playgroup__c(
                Animal__c = anim.Id,
                Playgroup_Session__c = ps.Id
            ));
        }
        
        test.startTest();
            insert apgs;
        test.stopTest();

        
    }   
}