force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Name_Id__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name_Id__c</fullName>
    <formula>Animal_Name__c + &apos; (&apos; +  Name + &apos;)&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animal Name/Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Shelter_Location__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Location__c</fullName>
    <label>Kennel Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/Animal_Daily_Care__c.object-meta.xml
<CustomObject>
    <label>Animal Daily Care</label>
    <nameField>
        <displayFormat>ADCN-{0000}</displayFormat>
        <label>Animal Daily Care Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals Daily Care</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animals Daily Care</relationshipLabel>
    <relationshipName>Animals_Daily_Care</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Daily_Care__c.field-meta.xml
<CustomField>
    <fullName>Daily_Care__c</fullName>
    <label>Daily Care</label>
    <referenceTo>Daily_Care__c</referenceTo>
    <relationshipLabel>Animals Daily Care</relationshipLabel>
    <relationshipName>Animals_Daily_Care</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Care__c/Daily_Care__c.object-meta.xml
<CustomObject>
    <label>Daily Care</label>
    <nameField>
        <displayFormat>DCN-{0000}</displayFormat>
        <label>Daily Care Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Care</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/test/Test_DailyCareLWCController.cls
@isTest
private class Test_DailyCareLWCController {
    @isTest
    static void getDailyCare_Success() {
        Daily_Care__c dc = TestDataFactory.createDailyCareWithAnimalDailyCares(2);

        test.startTest();
        DailyCareLWCController.DailyCareInfo dcInfo = DailyCareLWCController.getDailyCare(dc.Date__c);
        test.stopTest();

        System.assert(dcInfo != null, 'Should have returned a dcInfo, but was null');
        System.assertEquals(dc.Id, dcInfo.dailyCareId);
        System.assert(!dcInfo.animalDailyCares.isEmpty(), 'Should have returned a list of animalInfos, but was empty');
    }

    @isTest
    static void getDailyCare_NoDailyCareForDate() {
        Daily_Care__c dc = TestDataFactory.createDailyCareWithAnimalDailyCares(2);

        test.startTest();
        DailyCareLWCController.DailyCareInfo dcInfo = DailyCareLWCController.getDailyCare(date.today().addDays(-1));
        test.stopTest();

        System.assertEquals(null, dcInfo.dailyCareId);
        System.assertEquals(null, dcInfo.animalDailyCares);
    }

    @isTest
    static void getAnimalDailyCares_Success() {
        Daily_Care__c dc = TestDataFactory.createDailyCareWithAnimalDailyCares(2);

        test.startTest();
        Id[] animalDailyCareIds = DailyCareLWCController.getAnimalDailyCares(dc.Id,'Animal__r.Shelter_Location__c', 'ASC');
        test.stopTest();

        System.assertEquals(2, animalDailyCareIds.size());
    }

    @isTest
    static void getAnimalDailyCares_NoAnimalDailyCares() {
        Daily_Care__c dc = TestDataFactory.createDailyCare();

        test.startTest();
        Id[] animalDailyCareIds = DailyCareLWCController.getAnimalDailyCares(dc.Id,'Animal__r.Shelter_Location__c', 'ASC');
        test.stopTest();

        System.assert(animalDailyCareIds.isEmpty());
    }

    @isTest
    static void getAnimalDailyCareInfo_Success() {
        Daily_Care__c dc = TestDataFactory.createDailyCareWithAnimalDailyCares(2);
        Animal_Daily_Care__c[] adcList = [SELECT Id, Animal__r.Animal_Name_Id__c FROM Animal_Daily_Care__c WHERE Daily_Care__c =: dc.Id];

        test.startTest();
        for(Animal_Daily_Care__c adc : adcList){
            DailyCareLWCController.AnimalInfo aInfo = DailyCareLWCController.getAnimalDailyCareInfo(adc.Id);
            System.assertEquals(adc.Id, aInfo.animalCareId);
            System.assertEquals(adc.Animal__r.Animal_Name_Id__c, aInfo.animalName);
        }   
        test.stopTest();
    }

    @isTest
    static void getAnimalDailyCareInfo_NoAnimalDailyCare() {
        test.startTest();
            DailyCareLWCController.AnimalInfo aInfo = DailyCareLWCController.getAnimalDailyCareInfo(null);
            System.assertEquals(null, aInfo);
        test.stopTest();
    }
}