force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Additional_Comments__c.field-meta.xml
<CustomField>
    <fullName>Additional_Comments__c</fullName>
    <label>Additional Comments</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Incidents__c/Incidents__c.object-meta.xml
<CustomObject>
    <label>Incidents</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Incident Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Incidents__c/fields/Additional_Comments__c.field-meta.xml
<CustomField>
    <fullName>Additional_Comments__c</fullName>
    <label>Additional Comments</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Incidents</relationshipLabel>
    <relationshipName>Incidents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Behaviors_Exhibited_by_the_Dog__c.field-meta.xml
<CustomField>
    <fullName>Behaviors_Exhibited_by_the_Dog__c</fullName>
    <label>Behaviors Exhibited by the Dog</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Repetitive behavior (pacing - licking - drooling)</fullName>
            </value>
            <value>
                <fullName>Staring at wall or corner of kennel</fullName>
            </value>
            <value>
                <fullName>High arousal/excitement (intense - energetic activity)</fullName>
            </value>
            <value>
                <fullName>Tugging or climbing the leash</fullName>
            </value>
            <value>
                <fullName>Hard mouthing</fullName>
            </value>
            <value>
                <fullName>Climbing or high jumping up kennel walls or fence</fullName>
            </value>
            <value>
                <fullName>Escaping from kennel</fullName>
            </value>
            <value>
                <fullName>Trying to get away</fullName>
            </value>
            <value>
                <fullName>Trying to get at another dog</fullName>
            </value>
            <value>
                <fullName>Fighting with another dog</fullName>
            </value>
            <value>
                <fullName>Guarding food or chewy from person</fullName>
            </value>
            <value>
                <fullName>Guarding non-food item from person</fullName>
            </value>
            <value>
                <fullName>Resisting medical restraint</fullName>
            </value>
            <value>
                <fullName>Stiffening or freezing</fullName>
            </value>
            <value>
                <fullName>Whipping head toward person - unsure if dog would bite</fullName>
            </value>
            <value>
                <fullName>Lunging toward a person</fullName>
            </value>
            <value>
                <fullName>Muzzle punching (forceful jab with nose)</fullName>
            </value>
            <value>
                <fullName>Growling</fullName>
            </value>
            <value>
                <fullName>Showing teeth</fullName>
            </value>
            <value>
                <fullName>Snapping</fullName>
            </value>
            <value>
                <fullName>Biting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Clothing_Worn_at_Bite_Site__c.field-meta.xml
<CustomField>
    <fullName>Clothing_Worn_at_Bite_Site__c</fullName>
    <label>Clothing Worn at Bite Site</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Damage_Done_by_the_Dog__c.field-meta.xml
<CustomField>
    <fullName>Damage_Done_by_the_Dog__c</fullName>
    <label>Damage Done by the Dog</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A - there was NO bite or damage</fullName>
            </value>
            <value>
                <fullName>Bruising</fullName>
            </value>
            <value>
                <fullName>Broken skin</fullName>
            </value>
            <value>
                <fullName>Shallow scratch or abrasion</fullName>
            </value>
            <value>
                <fullName>Deep scratch or abrasion</fullName>
            </value>
            <value>
                <fullName>Puncture</fullName>
            </value>
            <value>
                <fullName>Puncture with tearing</fullName>
            </value>
            <value>
                <fullName>Torn material (leash - clothing)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Incident_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Incident_Date_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Incident Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Incident_Description__c.field-meta.xml
<CustomField>
    <fullName>Incident_Description__c</fullName>
    <label>Incident Description</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Number_of_bites__c.field-meta.xml
<CustomField>
    <fullName>Number_of_bites__c</fullName>
    <label>Number of bites</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Other_Damage_Done_by_the_Dog__c.field-meta.xml
<CustomField>
    <fullName>Other_Damage_Done_by_the_Dog__c</fullName>
    <label>Other Damage Done by the Dog</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Person_Involved__c.field-meta.xml
<CustomField>
    <fullName>Person_Involved__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person Involved</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Incidents</relationshipLabel>
    <relationshipName>Incidents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Please_explain_why_you_think_so__c.field-meta.xml
<CustomField>
    <fullName>Please_explain_why_you_think_so__c</fullName>
    <label>Please explain why you think so</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Specific_Target_of_Dog_s_Behavior__c.field-meta.xml
<CustomField>
    <fullName>Specific_Target_of_Dog_s_Behavior__c</fullName>
    <label>Specific Target of Dog&apos;s Behavior</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Supervisor_Team_Lead__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_Team_Lead__c</fullName>
    <label>Supervisor/Team Lead</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Type_of_Bite__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Bite__c</fullName>
    <label>Type of Bite</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A - there was NO bite</fullName>
            </value>
            <value>
                <fullName>Single bite</fullName>
            </value>
            <value>
                <fullName>Bite and hold</fullName>
            </value>
            <value>
                <fullName>Bite, hold and shake</fullName>
            </value>
            <value>
                <fullName>Multiple bites</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Was_Bitten_Area_Covered_with_Clothing__c.field-meta.xml
<CustomField>
    <fullName>Was_Bitten_Area_Covered_with_Clothing__c</fullName>
    <label>Was Bitten Area Covered with Clothing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A - Not applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Was_defensive_handling_used__c.field-meta.xml
<CustomField>
    <fullName>Was_defensive_handling_used__c</fullName>
    <label>Was defensive handling used?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Witnesses__c.field-meta.xml
<CustomField>
    <fullName>Witnesses__c</fullName>
    <label>Witnesses</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Would_dog_have_bitten_w_o_this_handling__c.field-meta.xml
<CustomField>
    <fullName>Would_dog_have_bitten_w_o_this_handling__c</fullName>
    <label>Would dog have bitten w/o this handling?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Behavior_Incident_Report_ControllerTest.cls
@isTest
public class Behavior_Incident_Report_ControllerTest {

    @testSetup
    static void setupData(){
        Animal__c anm = TestDataFactory.createAnimal();
        
        Incidents__c inc = new Incidents__c(
            Additional_Comments__c = 'Test'
            , Animal__c = anm.id
            , Behaviors_Exhibited_by_the_Dog__c = 'Tugging or climbing the leash'
            , Clothing_Worn_at_Bite_Site__c = 'Test'
            , Damage_Done_by_the_Dog__c = 'Deep scratch or abrasion'
            , Was_defensive_handling_used__c = 'No'
            , Would_dog_have_bitten_w_o_this_handling__c = 'Test'
            , Incident_Date_Time__c = System.now()
            , Incident_Description__c = 'Test'
            , Number_of_bites__c = 2
            , Other_Damage_Done_by_the_Dog__c = 'Test'
            , Person_Involved__c = 'Test'
            , Please_explain_why_you_think_so__c = 'Test'
            , Report_Date__c = system.today()
            , Specific_Target_of_Dog_s_Behavior__c = 'Test'
            , Type_of_Bite__c = 'Single bite'
            , Was_Bitten_Area_Covered_with_Clothing__c  = 'Yes'
            , Witnesses__c = 'Test'
            , Supervisor_Team_Lead__c = 'Test');
        insert inc;
    }
    
    @isTest
    static void testIncident(){
        Incidents__c obj = [Select Id,Animal__c from incidents__c];
        Animal__c anm = [Select Id from Animal__c];
        PageReference pageRef = Page.Behavior_Incident_Report;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf(obj.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(obj);
        Behavior_Incident_Report_Controller br = new Behavior_Incident_Report_Controller(sc);
        List<SelectOption> slo = br.getPicklistValue;
        List<Behavior_Incident_Report_Controller.Option> bo = br.getbehaviorsExhibited();
        List<SelectOption> sl = br.getTypeBitePicklist;
        List<Behavior_Incident_Report_Controller.Option> tb = br.gettypeBite();
        List<SelectOption> cp = br.getClothingPicklist;
        List<Behavior_Incident_Report_Controller.Option> gc = br.getClothing();
        List<SelectOption> dp = br.getDamagePicklist;
        List<Behavior_Incident_Report_Controller.Option> gd = br.getDamage();
        List<Behavior_Incident_Report_Controller.Option> gh = br.getHandling();
        List<Behavior_Incident_Report_Controller.Option> df = br.getDefensive();
        br.contact = null;
        br.anim = anm;
        System.assertNotEquals(obj, null);
        System.assertNotEquals(br.anim, null);
    }
}