force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Play_Pause__c.field-meta.xml
<CustomField>
    <fullName>Play_Pause__c</fullName>
    <label>Play-Pause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Play_Pause__c/Play_Pause__c.object-meta.xml
<CustomObject>
    <label>Play Pause</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Play Pause #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Play Pauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Play_Pause__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalshelters__Animal__c</referenceTo>
    <relationshipLabel>Play Pauses</relationshipLabel>
    <relationshipName>Play_Pauses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Play_Pause__c/fields/End_Play_Pause__c.field-meta.xml
<CustomField>
    <fullName>End_Play_Pause__c</fullName>
    <defaultValue>false</defaultValue>
    <label>End Play Pause</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Problem_Behavior__c.field-meta.xml
<CustomField>
    <fullName>Problem_Behavior__c</fullName>
    <label>Problem Behavior (see TEC)</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fear of People - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of People - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of People - Severe</fullName>
            </value>
            <value>
                <fullName>Fear of Handling - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of Handling - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of Handling - Severe</fullName>
            </value>
            <value>
                <fullName>Fear of Leashing, Leash Pressure, Walking on Leash - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of Leashing, Leash Pressure, Walking on Leash - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of Leashing, Leash Pressure, Walking on Leash - Severe</fullName>
            </value>
            <value>
                <fullName>Fear of Places, Objects, Novelty - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of Places, Objects, Novelty - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of Places, Objects, Novelty - Severe</fullName>
            </value>
            <value>
                <fullName>Fear of Noises - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of Noises - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of Noises - Severe</fullName>
            </value>
            <value>
                <fullName>Fear of Dogs - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of Dogs - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of Dogs - Severe</fullName>
            </value>
            <value>
                <fullName>Reactivity Toward People/Dogs (Specific to Kennel) - Mild</fullName>
            </value>
            <value>
                <fullName>Reactivity Toward People/Dogs (Specific to Kennel) - Moderate</fullName>
            </value>
            <value>
                <fullName>Reactivity Toward People/Dogs (Specific to Kennel) - Severe</fullName>
            </value>
            <value>
                <fullName>Arousal in Kennel/Shelter Stress - Mild</fullName>
            </value>
            <value>
                <fullName>Arousal in Kennel/Shelter Stress - Moderate</fullName>
            </value>
            <value>
                <fullName>Arousal in Kennel/Shelter Stress - Severe</fullName>
            </value>
            <value>
                <fullName>Arousal Out of Kennel/Jumping &amp; Mouthing - Mild</fullName>
            </value>
            <value>
                <fullName>Arousal Out of Kennel/Jumping &amp; Mouthing - Moderate</fullName>
            </value>
            <value>
                <fullName>Arousal Out of Kennel/Jumping &amp; Mouthing - Severe</fullName>
            </value>
            <value>
                <fullName>Reactivity on Leash (People) - Mild</fullName>
            </value>
            <value>
                <fullName>Reactivity on Leash (People) - Moderate</fullName>
            </value>
            <value>
                <fullName>Reactivity on Leash (People) - Severe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CRCAnimalDogListControllerTest.cls
@isTest
public class CRCAnimalDogListControllerTest {

    @testSetup
    static void setupData(){
        List<Animal__c> animals = new List<Animal__c>();
        List<Play_Pause__c> playPauses = new List<Play_Pause__c>();
        List<Treatment_Plan__c> planList = new List<Treatment_Plan__c>();
        for(Integer i = 1; i <= 5; i++){
            Animal__c a = TestDataFactory.createAnimalWithName('anm' + i);
            animals.add(a);
            playPauses.addAll(TestDataFactory.createPlayPauses(a));
            
            Treatment_Plan__c plan = new Treatment_Plan__c(
                IsActive__c = true, 
                Description__c = 'Test', 
                Animal__c = a.Id, 
                Problem_Behavior__c = 'Fear of People - Mild'
            );
            planList.add(plan);
        }
        
        for(Play_Pause__c play : playPauses){
            play.End_Play_Pause__c = false;
        }
        update playPauses;
        
        insert planList;
    }
    
    @isTest
    static void testRecords(){
        List<Treatment_Plan__c> objs = CRCAnimalDogListController.getRecords();
        System.assertNotEquals(objs, null);
        String result = CRCAnimalDogListController.saveRecords(JSON.serialize(objs));
        System.assertEquals('success', result);
        
    }
}