force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Administered_Microchip_Number__c.field-meta.xml
<CustomField>
    <fullName>Administered_Microchip_Number__c</fullName>
    <inlineHelpText>Data field only pertains to microchips that the ASPCA administered.</inlineHelpText>
    <label>Administered Microchip Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Age__c.field-meta.xml
<CustomField>
    <fullName>Animal_Age__c</fullName>
    <label>Animal Age</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name__c</fullName>
    <externalId>true</externalId>
    <label>ASPCA Animal Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <label>Assessment</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>For EQUINE, see Help Text</description>
    <inlineHelpText>For EQUINE, choose one of the following: Horse, Donkey, Mule, Draft Horse, Mini Horse, Pony, Mini Mule, Mini Donkey</inlineHelpText>
    <label>Breed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;Unspecified&quot;</defaultValue>
    <label>Primary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Primary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Animal_Age_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Current_Animal_Age_Estimate__c</fullName>
    <formula>(TODAY() - Estimated_Date_of_Birth__c) / 365</formula>
    <label>Current Animal Age (Estimate)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Animal_Age_Formatted__c.field-meta.xml
<CustomField>
    <fullName>Current_Animal_Age_Formatted__c</fullName>
    <formula>IF( ISNULL( Today_Test__c ) ,
IF(NOT(ISBLANK(Estimated_Date_of_Birth__c)),
    TEXT(FLOOR(( (TODAY() - Estimated_Date_of_Birth__c) / 365)))
    &amp;&apos; Years&apos; &amp; &apos; &apos; &amp;
    TEXT(FLOOR( (MOD( (TODAY() - Estimated_Date_of_Birth__c),365)/30))) &amp;&apos; Months&apos;,
    IF(NOT(ISBLANK(Animal_Age__c)) &amp;&amp; NOT(ISBLANK(TEXT(Animal_Age_Units__c))),
        IF(TEXT(Animal_Age_Units__c) = &apos;Days&apos;,
            TEXT(FLOOR(( (TODAY() - (Animal_Age_Units_Changed_Date__c - Animal_Age__c))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (TODAY() - (Animal_Age_Units_Changed_Date__c - Animal_Age__c)),365)/30))) &amp;&apos; Months&apos;,
        IF(TEXT(Animal_Age_Units__c) = &apos;Weeks&apos;,
            TEXT(FLOOR(( (TODAY() - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (TODAY() - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c))),365)/30))) &amp;&apos; Months&apos; ,
        IF(TEXT(Animal_Age_Units__c) = &apos;Months&apos;,
            IF(Animal_Age__c &lt; 12,
                &apos;0 Years &apos; &amp; TEXT(Animal_Age__c) &amp; &apos; Months&apos;,
                TEXT(FLOOR( (TODAY()  - ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))/365))
                &amp;&apos; Years&apos; &amp; &apos; &apos;
                &amp; TEXT(FLOOR( MOD( (TODAY()  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))),365)/30)) &amp;&apos; Months&apos;),
        IF(TEXT(Animal_Age_Units__c) = &apos;Years&apos;,
            TEXT(FLOOR(( (TODAY() - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -12 * Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD(TODAY() - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, 12)),365)/30))) &amp;&apos; Months&apos;,
        &quot;&quot;)))) ,
    &quot;&quot;)
),

IF(NOT(ISBLANK(Estimated_Date_of_Birth__c)),
    TEXT(FLOOR(( (Today_Test__c  - Estimated_Date_of_Birth__c) / 365)))
    &amp;&apos; Years&apos; &amp; &apos; &apos; &amp;
    TEXT(FLOOR( (MOD( (Today_Test__c  - Estimated_Date_of_Birth__c),365)/30))) &amp;&apos; Months&apos;,
    IF(NOT(ISBLANK(Animal_Age__c)) &amp;&amp; NOT(ISBLANK(TEXT(Animal_Age_Units__c))),
        IF(TEXT(Animal_Age_Units__c) = &apos;Days&apos;,
            TEXT(FLOOR(( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - Animal_Age__c))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - Animal_Age__c)),365)/30))) &amp;&apos; Months&apos;,
        IF(TEXT(Animal_Age_Units__c) = &apos;Weeks&apos;,
            TEXT(FLOOR(( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c))),365)/30))) &amp;&apos; Months&apos; ,
        IF(TEXT(Animal_Age_Units__c) = &apos;Months&apos;,
            IF(Animal_Age__c &lt; 12,
                &apos;0 Years &apos; &amp; TEXT(Animal_Age__c) &amp; &apos; Months&apos;,
                TEXT(FLOOR( (Today_Test__c  - ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))/365))
                &amp;&apos; Years&apos; &amp; &apos; &apos;
                &amp; TEXT(FLOOR( MOD( (Today_Test__c  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))),365)/30)) &amp;&apos; Months&apos;),
        IF(TEXT(Animal_Age_Units__c) = &apos;Years&apos;,
            TEXT(FLOOR(( (Today_Test__c  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -12 * Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD(Today_Test__c  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, 12)),365)/30))) &amp;&apos; Months&apos;,
        &quot;&quot;)))) ,
    &quot;&quot;)
)

)</formula>
    <label>Current Animal Age</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Weight_in_kgs_Num__c.field-meta.xml
<CustomField>
    <fullName>Current_Weight_in_kgs_Num__c</fullName>
    <label>Current Weight (in kgs)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Weight_in_lbs_Num__c.field-meta.xml
<CustomField>
    <fullName>Current_Weight_in_lbs_Num__c</fullName>
    <label>Current Weight (in lbs)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Estimated_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Date_of_Birth__c</fullName>
    <label>Estimated Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Intake_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Intake_Date_Time__c</fullName>
    <label>Intake Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Microchip_Number__c.field-meta.xml
<CustomField>
    <fullName>Microchip_Number__c</fullName>
    <label>Microchip Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Photo_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Photo_Document_Id__c</fullName>
    <label>Photo Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Recommendations__c.field-meta.xml
<CustomField>
    <fullName>Recommendations__c</fullName>
    <defaultValue>&quot;We recommend consulting with a veterinarian for vaccination, diet, and preventative health recommendations based on this pet’s age and medical needs. Regular heartworm and external parasite prevention are recommended year-round.&quot;</defaultValue>
    <label>Recommendations</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Secondary_Color__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Color__c</fullName>
    <label>Secondary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Secondary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Type_of_Animal__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Animal__c</fullName>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Species</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medication_Drug__c/Medication_Drug__c.object-meta.xml
<CustomObject>
    <label>Medication/Drug</label>
    <nameField>
        <label>Medication/Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medications/Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medication_Drug__c/fields/Lot_Number__c.field-meta.xml
<CustomField>
    <fullName>Lot_Number__c</fullName>
    <label>Lot Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vaccine_and_Preventative__c/Vaccine_and_Preventative__c.object-meta.xml
<CustomObject>
    <label>Vaccine and Preventative</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Vaccine and Preventative #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vaccines and Preventatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vaccine_and_Preventative__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipName>Vaccine_Administration</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vaccine_and_Preventative__c/fields/Date_Administered__c.field-meta.xml
<CustomField>
    <fullName>Date_Administered__c</fullName>
    <label>Date Administered</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vaccine_and_Preventative__c/fields/Due_On__c.field-meta.xml
<CustomField>
    <fullName>Due_On__c</fullName>
    <formula>IF( ISPICKVAL(Initial_Series_Booster__c,&quot;Initial&quot;),Date_Administered__c + Vaccine_Preventative__r.Initial_Days__c,IF( ISPICKVAL(Initial_Series_Booster__c,&quot;Booster&quot;),Date_Administered__c + Vaccine_Preventative__r.Booster_Days__c,IF( ISPICKVAL(Initial_Series_Booster__c,&quot;Series&quot;),Date_Administered__c + Vaccine_Preventative__r.Series_Days__c,null)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Due On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vaccine_and_Preventative__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vaccine_and_Preventative__c/fields/Rabies_Tag__c.field-meta.xml
<CustomField>
    <fullName>Rabies_Tag__c</fullName>
    <label>Rabies Tag #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vaccine_and_Preventative__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <label>Route</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IM</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IV</fullName>
            </value>
            <value>
                <fullName>PO</fullName>
            </value>
            <value>
                <fullName>SQ</fullName>
            </value>
            <value>
                <fullName>Topical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vaccine_and_Preventative__c/fields/Vaccine_Preventative__c.field-meta.xml
<CustomField>
    <fullName>Vaccine_Preventative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vaccine Preventative</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Medication_Drug__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vaccine/Preventative</value>
        </filterItems>
        <filterItems>
            <field>Medication_Drug__c.Expired_Drug__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Medication_Drug__c.Species__c</field>
            <operation>contains</operation>
            <valueField>$Source.Species__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Medication_Drug__c</referenceTo>
    <relationshipLabel>Vaccines and Preventatives</relationshipLabel>
    <relationshipName>Vaccine_Administration</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Primary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Bay roan</fullName>
    </customValue>
    <customValue>
        <fullName>Beige</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Blue roan</fullName>
    </customValue>
    <customValue>
        <fullName>Brindle</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Buckskin</fullName>
    </customValue>
    <customValue>
        <fullName>Buff</fullName>
    </customValue>
    <customValue>
        <fullName>Calico</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut/Sorrel</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Dun</fullName>
    </customValue>
    <customValue>
        <fullName>Fawn</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Grulla</fullName>
    </customValue>
    <customValue>
        <fullName>Hairless</fullName>
    </customValue>
    <customValue>
        <fullName>Liver chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Palomino</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Red roan</fullName>
    </customValue>
    <customValue>
        <fullName>Roan</fullName>
    </customValue>
    <customValue>
        <fullName>Seal</fullName>
    </customValue>
    <masterLabel>Primary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Secondary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agouti</fullName>
    </customValue>
    <customValue>
        <fullName>Apricot</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Blue Dilute</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Buckskin</fullName>
    </customValue>
    <customValue>
        <fullName>Champagne</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Fawn</fullName>
    </customValue>
    <customValue>
        <fullName>Gold</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Gray</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Lemon</fullName>
    </customValue>
    <customValue>
        <fullName>Lilac</fullName>
    </customValue>
    <customValue>
        <fullName>Liver</fullName>
    </customValue>
    <customValue>
        <fullName>Mahogany</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Pepper and Salt</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Rust</fullName>
    </customValue>
    <customValue>
        <fullName>Sable</fullName>
    </customValue>
    <customValue>
        <fullName>Seal</fullName>
    </customValue>
    <customValue>
        <fullName>Silver</fullName>
    </customValue>
    <customValue>
        <fullName>Tan</fullName>
    </customValue>
    <customValue>
        <fullName>Wheaten</fullName>
    </customValue>
    <masterLabel>Secondary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Species.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avian</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Cow</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Equine</fullName>
    </customValue>
    <customValue>
        <fullName>Exotic</fullName>
    </customValue>
    <customValue>
        <fullName>Fowl</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <masterLabel>Species</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VaccineCert_Controller.cls
public class VaccineCert_Controller {
    
    list<Animal__c> lstAnimal {get;set;}
    public Animal__c objAnimal{get;set;}
    public String doctorValue{get;set;}
    public Date Today { get { return Date.today(); }}
    
    public VaccineCert_Controller (ApexPages.StandardController controller)
        
        {
         lstAnimal = [select Id,
                      Name, 
                      Animal_Name__c, 
                      Type_of_animal__c, 
                      Breed__c, 
                      Gender__c, 
                      Current_Animal_Age_Estimate__c, 
                      Current_Animal_Age_Formatted__c,
                      Animal_Age__c,
                      Intake_Date_Time__c, 
                      Color__c,
                      Secondary_Color__c,
                      Current_Weight_in_kgs_Num__c,
                      Current_Weight_in_lbs_Num__c,
                      Microchip_Number__c,
                      Assessment__c,
                      Recommendations__c,
                      Administered_Microchip_Number__c,
                      Photo_Document_Id__c,
                      Estimated_Date_of_Birth__c
                      FROM Animal__c 
                      WHERE Id = :ApexPages.currentPage().getparameters().get('Id')];
         if(lstAnimal.size()>0)
             objAnimal = lstAnimal[0];
    }
    
    	public List<Vaccine_and_Preventative__c	> vaccs{
        get{
            if (vaccs == null){
                vaccs = new List<Vaccine_and_Preventative__c> ([SELECT Id, 
                                                                Vaccine_Preventative__r.Name,
                                                                Vaccine_Preventative__r.Manufacturer__c,
                                                                Vaccine_Preventative__r.Lot_Number__c, 
                                                                Date_Administered__c, 
                                                                Rabies_Tag__c,
                                                                Route__c,
                                                                Due_On__c,
                                                                Notes__c
                                                           FROM Vaccine_and_Preventative__c	
                                                           WHERE Animal__r.Id = :ApexPages.currentPage().getparameters().get('Id')
                                                           ORDER BY Date_Administered__c DESC]);
            }
            return vaccs;
        }
        private set;
    }
    
   public PageReference genCert(){

    PageReference pr = new PageReference('/apex/VaccineCert'); 
    return pr;
    }
    
    public String getDoc(){
        return doctorValue;
    }
    
    public void setDoc(String doctorValue){
        this.doctorValue = doctorValue;
    }
    

}