force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Playgroup__c/Animal_Playgroup__c.object-meta.xml
<CustomObject>
    <label>Animal Playgroup</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Animal Playgroup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Playgroups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Playgroup__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Playgroup_Session__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Session</label>
    <referenceTo>Playgroup_Session__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+ Id ,  FirstName + &quot; &quot; + LastName )</formula>
    <label>Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Playgroup__c/Playgroup__c.object-meta.xml
<CustomObject>
    <label>Playgroup</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Playgroups</relationshipLabel>
    <relationshipName>Playgroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup__c/fields/Playgroup_Location__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Location__c</fullName>
    <label>Playgroup Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indoor Play Yard</fullName>
            </value>
            <value>
                <fullName>Outdoor Play Yard</fullName>
            </value>
            <value>
                <fullName>MRC Indoor Play Yard</fullName>
            </value>
            <value>
                <fullName>MRC Outdoor Play Yard</fullName>
            </value>
            <value>
                <fullName>Monster Park</fullName>
            </value>
            <value>
                <fullName>ARC Terrace</fullName>
            </value>
            <value>
                <fullName>SBR</fullName>
            </value>
            <value>
                <fullName>Playroom 1</fullName>
            </value>
            <value>
                <fullName>Playroom 2</fullName>
            </value>
            <value>
                <fullName>Playroom 1 &amp; 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Playgroup_Contact__c/Playgroup_Contact__c.object-meta.xml
<CustomObject>
    <label>Playgroup Contact</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroup Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Playgroup_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Contact__c/fields/Playgroup__c.field-meta.xml
<CustomField>
    <fullName>Playgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup</label>
    <referenceTo>Animal_Playgroup__c</referenceTo>
    <relationshipName>Playgroup_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/Playgroup_Session__c.object-meta.xml
<CustomObject>
    <label>Playgroup Session</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroup Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup_Session__c/fields/Animal_Playgroup__c.field-meta.xml
<CustomField>
    <fullName>Animal_Playgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Playgroup</label>
    <referenceTo>Animal_Playgroup__c</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/fields/Contact_Ids__c.field-meta.xml
<CustomField>
    <fullName>Contact_Ids__c</fullName>
    <description>This field is used to hold the list of Contact Ids for this Session</description>
    <label>Contact Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/fields/Playgroup_Leader__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/fields/Playgroup_Location__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Location__c</fullName>
    <label>Playgroup Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indoor Play Yard</fullName>
            </value>
            <value>
                <fullName>Outdoor Play Yard</fullName>
            </value>
            <value>
                <fullName>MRC Indoor Play Yard</fullName>
            </value>
            <value>
                <fullName>MRC Outdoor Play Yard</fullName>
            </value>
            <value>
                <fullName>Monster Park</fullName>
            </value>
            <value>
                <fullName>ARC Terrace</fullName>
            </value>
            <value>
                <fullName>SBR</fullName>
            </value>
            <value>
                <fullName>Playroom 1</fullName>
            </value>
            <value>
                <fullName>Playroom 2</fullName>
            </value>
            <value>
                <fullName>Playroom 1 &amp; 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/test_playgroupSessionLWCController.cls
@isTest
private class test_playgroupSessionLWCController {
    @isTest 
    static void getPlaygroupSession_hasSession(){
        Playgroup_Session__c session = TestDataFactory.createPlaygroupSessionWithAnimals();

        test.startTest();
            Playgroup_Session__c returnedSession = playgroupSessionLWCController.getPlaygroupSession(session.Id);
        test.stopTest();

        System.assert(returnedSession != null, 'No session was returned');
    }

    @isTest 
    static void getPlaygroupSession_noSession(){
        test.startTest();
            Playgroup_Session__c returnedSession = playgroupSessionLWCController.getPlaygroupSession(null);
        test.stopTest();

        System.assert(returnedSession == null, 'Should have returned a null value');
    }

    @isTest 
    static void animalPlaygroups_hasPlaygroups(){
        Playgroup_Session__c session = TestDataFactory.createPlaygroupSessionWithAnimals();

        test.startTest();
            Animal_Playgroup__c[] returnedPlaygroups = playgroupSessionLWCController.animalPlaygroups(session.Id);
        test.stopTest();

        System.assert(!returnedPlaygroups.isEmpty(), 'Should have returned some animal playgroups, but was empty');
    }

    @isTest 
    static void animalPlaygroups_noPlaygroups(){
        Contact c = testDataFactory.createContact();

        Playgroup_Session__c session = new Playgroup_Session__c(
            Playgroup_Location__c = 'MRC Indoor Play Yard',
            Playgroup_Leader__c = c.Id
        );
        insert session;

        test.startTest();
            Animal_Playgroup__c[] returnedPlaygroups = playgroupSessionLWCController.animalPlaygroups(session.Id);
        test.stopTest();

        System.assert(returnedPlaygroups.isEmpty(), 'List of animal playgroups should be empty, but was: ' + returnedPlaygroups);
    }

    @isTest 
    static void getPlaygroupContacts_hasContacts(){
        Contact c1 = testDataFactory.createContact();
        Contact c2 = testDataFactory.createContact();
        String contactIds = c1.Id + ',' + c2.Id;

        test.startTest();
            Contact[] returnedContacts = playgroupSessionLWCController.getPlaygroupContacts(contactIds);
        test.stopTest();

        System.assertEquals(c1.Id, returnedContacts[0].Id);
        System.assertEquals(c2.Id, returnedContacts[1].Id);
    }

    @isTest 
    static void getPlaygroupContacts_noContacts(){
        test.startTest();
            Contact[] returnedContacts = playgroupSessionLWCController.getPlaygroupContacts(null);
        test.stopTest();

        System.assertEquals(null, returnedContacts);
    }

    @isTest 
    static void addContact_success(){
        Playgroup_Session__c session = TestDataFactory.createPlaygroupSessionWithAnimals();
        Contact c = testDataFactory.createContact();
        Animal__c newAnimal = TestDataFactory.createAnimalWithName('Doggo1');

        Playgroup_Contact__c[] initialCons = [SELECT Id, Contact__c FROM Playgroup_Contact__c WHERE Playgroup__r.Playgroup_Session__c =: session.Id];

        test.startTest();
            String response = playgroupSessionLWCController.addContact(session.Id, c.Id, new Id[]{newAnimal.Id});
        test.stopTest();

        System.assertEquals('success', response);
        Playgroup_Contact__c[] cons = [SELECT Id FROM Playgroup_Contact__c WHERE Playgroup__r.Playgroup_Session__c =: session.Id];
        System.assertEquals(initialCons.size() + 1, cons.size());
    }

    @isTest 
    static void removeContact_success(){
        Playgroup_Session__c session = TestDataFactory.createPlaygroupSessionWithAnimals();
        Playgroup_Contact__c[] initialCons = [SELECT Id, Contact__c FROM Playgroup_Contact__c WHERE Playgroup__r.Playgroup_Session__c =: session.Id];
        Set<Id> conIds = new Set<Id>();
        for(Playgroup_Contact__c pc : initialCons){
            conIds.add(pc.Id);
        }
        // List<Id> conIdList = new List<Id>(conids);
        Contact c1 = testDataFactory.createContact();
        Contact c2 = testDataFactory.createContact();
        session.Contact_Ids__c = c1.Id + ',' + c2.Id + ',' + string.join(new List<Id>(conids),',');
        update session;

        test.startTest();
            String response = playgroupSessionLWCController.removeContact(session.Id, initialCons[0].Contact__c);
        test.stopTest();

        System.assertEquals('success', response);
        System.debug('c1: ' + c1.Id);
        System.debug('c2: ' + c2.Id);
        System.debug('initialCons: ' + initialCons);
        Playgroup_Contact__c[] cons = [SELECT Id, Contact__c FROM Playgroup_Contact__c WHERE Playgroup__r.Playgroup_Session__c =: session.Id];

        System.assertEquals(initialCons.size() - 1, cons.size(), 'should have returned ' + (initialCons.size() - 1) + ' playgroup contacts, instead returned: ' + cons);
    }

    @isTest 
    static void removeContact_contactNotInContactIds(){
        Playgroup_Session__c session = TestDataFactory.createPlaygroupSessionWithAnimals();
        Playgroup_Contact__c[] initialCons = [SELECT Id, Contact__c FROM Playgroup_Contact__c WHERE Playgroup__r.Playgroup_Session__c =: session.Id];
        Contact c1 = testDataFactory.createContact();
        Contact c2 = testDataFactory.createContact();
        session.Contact_Ids__c = c1.Id + ',' + c2.Id;
        update session;

        test.startTest();
            String response = playgroupSessionLWCController.removeContact(session.Id, initialCons[0].Contact__c);
        test.stopTest();

        System.assertEquals('success', response);
        Playgroup_Contact__c[] cons = [SELECT Id, Contact__c FROM Playgroup_Contact__c WHERE Playgroup__r.Playgroup_Session__c =: session.Id];
        System.assertEquals(initialCons.size() - 1, cons.size(), 'should have returned ' + (initialCons.size()) + ' playgroup contacts, instead returned: ' + cons);
    }    

    @isTest 
    static void removeFromPlaygroup_success(){
        Playgroup_Session__c session = TestDataFactory.createPlaygroupSessionWithAnimals();
        Animal_playgroup__c[] initialAnimals = [SELECT Id FROM Animal_playgroup__c WHERE Playgroup_Session__c =: session.Id];

        test.startTest();
            String response = playgroupSessionLWCController.removeFromPlaygroup(initialAnimals[0].Id);
        test.stopTest();

        System.assertEquals('success', response);
        Animal_playgroup__c[] animals = [SELECT Id FROM Animal_playgroup__c WHERE Playgroup_Session__c =: session.Id];
        System.assert(animals.isEmpty(), 'should have returned no animal playgroups, instead returned: ' + animals);
    }

    @isTest 
    static void getAnimalContacts_hasContacts(){
        Playgroup_Session__c session = TestDataFactory.createPlaygroupSessionWithAnimals();
        Animal_playgroup__c[] animalPlaygroups = [SELECT Id FROM Animal_playgroup__c WHERE Playgroup_Session__c =: session.Id];

        test.startTest();
        Playgroup_Contact__c[] pgContacts = playgroupSessionLWCController.getAnimalContacts(animalPlaygroups[0].Id);
        test.stopTest();

        System.assert(!pgContacts.isEmpty(), 'Should have returned contacts, instead returned: ' + pgContacts);
    }

    @isTest 
    static void getAnimalContacts_noContacts(){
        Playgroup_Session__c session = TestDataFactory.createPlaygroupSessionWithAnimals();
        Playgroup_Contact__c[] initialCons = [SELECT Id, Contact__c, Playgroup__c FROM Playgroup_Contact__c WHERE Playgroup__r.Playgroup_Session__c =: session.Id];
        for(Playgroup_Contact__c pg : initialCons){
            playgroupSessionLWCController.removeContact(session.Id, pg.Contact__c);
        }

        test.startTest();
        Playgroup_Contact__c[] pgContacts = playgroupSessionLWCController.getAnimalContacts(initialCons[0].Playgroup__c);
        test.stopTest();

        System.assertEquals(null, pgContacts, 'Should have returned an emtpylist, instead returned: ' + pgContacts);
    }

    @isTest 
    static void getPlaygroupSessionInfo_hasInfo(){
        Playgroup_Session__c session = TestDataFactory.createPlaygroupSessionWithAnimals();
        Contact c1 = testDataFactory.createContact();
        Contact c2 = testDataFactory.createContact();
        session.Contact_Ids__c = c1.Id + ',' + c2.Id;
        update session;

        test.startTest();
        playgroupSessionLWCController.playgroupSessionInfo sessionInfo = playgroupSessionLWCController.getPlaygroupSessionInfo(session.Id);
        test.stopTest();

        System.assert(sessionInfo != null, 'Should have returned some info, instead: ' + sessionInfo);
        System.assert(!sessionInfo.animalPlaygroups.isEmpty(), 'Should have returned some animal playgroups, instead: ' + sessionInfo.animalPlaygroups);
        System.assert(sessionInfo.playgroupSession != null, 'Should have returned some playgroup session info, instead: ' + sessionInfo.playgroupSession);
        System.assert(!sessionInfo.playgroupContacts.isEmpty(), 'Should have returned some playgroup contacts, instead: ' + sessionInfo.playgroupContacts);
    }

    @isTest 
    static void getAnimalInfo_hasInfo(){
        Playgroup_Session__c session = TestDataFactory.createPlaygroupSessionWithAnimals();
        Contact c1 = testDataFactory.createContact();
        Contact c2 = testDataFactory.createContact();
        session.Contact_Ids__c = c1.Id + ',' + c2.Id;
        update session;

        Animal_Playgroup__c[] aPGList = [SELECT Id FROM Animal_Playgroup__c LIMIT 1];
        System.assert(!aPGList.isEmpty(), 'Should have returned a list of animal playgroups, but was empty');

        test.startTest();
        playgroupSessionLWCController.playgroupAnimalInfo info = playgroupSessionLWCController.getAnimalInfo(aPGList[0].Id);
        test.stopTest();

        System.assertNotEquals(null, info, 'Should have returned playgroup animal info, but was null');
        System.assertNotEquals(null, info.animal, 'Should have returned an Animal Playgroup record, but was null');
        System.assertNotEquals(null, info.animalContacts, 'Should have returned animal contacts, but was null');

    }

}