force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Play_Rating__c.field-meta.xml
<CustomField>
    <fullName>Play_Rating__c</fullName>
    <label>Play Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Playgroup_Individual_Notes__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Individual_Notes__c</fullName>
    <label>Playgroup Individual Notes</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/Animal_Playgroup__c.object-meta.xml
<CustomObject>
    <label>Animal Playgroup</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Animal Playgroup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Playgroups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Playgroup__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Common_Playgroup_Note_Sections__c.field-meta.xml
<CustomField>
    <fullName>Common_Playgroup_Note_Sections__c</fullName>
    <label>Common Playgroup Note Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Greeting</fullName>
            </value>
            <value>
                <fullName>After Greeting</fullName>
            </value>
            <value>
                <fullName>Approached by another dog</fullName>
            </value>
            <value>
                <fullName>Handler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Common_Playgroup_Notes__c.field-meta.xml
<CustomField>
    <fullName>Common_Playgroup_Notes__c</fullName>
    <label>Common Playgroup Notes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Greeted – tense</fullName>
            </value>
            <value>
                <fullName>Greeted – politely</fullName>
            </value>
            <value>
                <fullName>Greeted – rude but playful</fullName>
            </value>
            <value>
                <fullName>Greeted – playful</fullName>
            </value>
            <value>
                <fullName>Greeted – no greeting</fullName>
            </value>
            <value>
                <fullName>Greeted – rude, aroused, not social</fullName>
            </value>
            <value>
                <fullName>Disengaged - remained tense</fullName>
            </value>
            <value>
                <fullName>Disengaged – relaxed some</fullName>
            </value>
            <value>
                <fullName>Disengaged – relaxed and milled</fullName>
            </value>
            <value>
                <fullName>Played – chase</fullName>
            </value>
            <value>
                <fullName>Played – wrestle</fullName>
            </value>
            <value>
                <fullName>Played – rude</fullName>
            </value>
            <value>
                <fullName>Played – roughly</fullName>
            </value>
            <value>
                <fullName>Played – boxed</fullName>
            </value>
            <value>
                <fullName>Played – arousal escalated</fullName>
            </value>
            <value>
                <fullName>Aggressed</fullName>
            </value>
            <value>
                <fullName>Took breaks</fullName>
            </value>
            <value>
                <fullName>Unresponsive to dogs’ correction</fullName>
            </value>
            <value>
                <fullName>Tolerated play solicitations</fullName>
            </value>
            <value>
                <fullName>Tolerated rude behavior</fullName>
            </value>
            <value>
                <fullName>Appropriately corrected rude behavior</fullName>
            </value>
            <value>
                <fullName>Overcorrected rude approach</fullName>
            </value>
            <value>
                <fullName>Defensive</fullName>
            </value>
            <value>
                <fullName>Responded to handler correction</fullName>
            </value>
            <value>
                <fullName>Unresponsive to handler correction</fullName>
            </value>
            <value>
                <fullName>Requires drag for TO</fullName>
            </value>
            <value>
                <fullName>Requires Muzzle</fullName>
            </value>
            <value>
                <fullName>Requires handler to crate breaks in play</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Play_Rating__c.field-meta.xml
<CustomField>
    <fullName>Play_Rating__c</fullName>
    <label>Play Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Playgroup_Individual_Notes__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Individual_Notes__c</fullName>
    <label>PG Notes for this Dog</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Playgroup_Session__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Session</label>
    <referenceTo>Playgroup_Session__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Playgroup_Session_Notes__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Session_Notes__c</fullName>
    <label>Playgroup Session Notes</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+ Id ,  FirstName + &quot; &quot; + LastName )</formula>
    <label>Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Playgroup_Contact__c/Playgroup_Contact__c.object-meta.xml
<CustomObject>
    <label>Playgroup Contact</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroup Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Playgroup_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Contact__c/fields/Novel_Not_Novel__c.field-meta.xml
<CustomField>
    <fullName>Novel_Not_Novel__c</fullName>
    <label>Novel/Not Novel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novel</fullName>
            </value>
            <value>
                <fullName>Familiar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Playgroup_Contact__c/fields/Playgroup__c.field-meta.xml
<CustomField>
    <fullName>Playgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup</label>
    <referenceTo>Animal_Playgroup__c</referenceTo>
    <relationshipName>Playgroup_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/Playgroup_Session__c.object-meta.xml
<CustomObject>
    <label>Playgroup Session</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroup Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup_Session__c/fields/Animal_Playgroup__c.field-meta.xml
<CustomField>
    <fullName>Animal_Playgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Playgroup</label>
    <referenceTo>Animal_Playgroup__c</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/fields/Playgroup_Leader__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/fields/Playgroup_Notes__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Notes__c</fullName>
    <label>Playgroup Notes</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/test/test_PlaygroupSessionTriggerHandler.cls
@isTest
private class test_PlaygroupSessionTriggerHandler {
    @isTest 
    static void getAnimalPlaygroups(){
        Playgroup_Session__c pgs = TestDataFactory.createPlaygroupSessionWithAnimals();
        Set<Id> pgIds = new Set<Id>();
        pgIds.add(pgs.Id);
        
        test.startTest();
            Animal_Playgroup__c[] aPgs = PlaygroupSessionTriggerHandler.getAnimalPlaygroups(pgIds);
        test.stopTest();
        
        System.assert(!apgs.isEmpty(), 'Should have returned a list of animal playgroups, but was empty');
    }

    @isTest 
    static void getPlaygroupLeaderContacts(){
        Playgroup_Session__c pgs = TestDataFactory.createPlaygroupSessionWithAnimals();
        Set<Id> pgIds = new Set<Id>();
        pgIds.add(pgs.Id);
        
        test.startTest();
            Playgroup_Contact__c[] pgCs = PlaygroupSessionTriggerHandler.getPlaygroupLeaderContacts(pgIds);
        test.stopTest();
        
        System.assert(!pgCs.isEmpty(), 'Should have returned a list of animal playgroups, but was empty');
    }

    @isTest 
    static void getAnimalPlaygroupsNoIds(){
        test.startTest();
            Animal_Playgroup__c[] aPgs = PlaygroupSessionTriggerHandler.getAnimalPlaygroups(null);
        test.stopTest();
        
        System.assert(apgs.isEmpty(), 'Should have returned an empty list, but was: ' + aPgs);
    }

    @isTest 
    static void getPlaygroupLeaderContactsNoIds(){
        test.startTest();
            Playgroup_Contact__c[] pgCs = PlaygroupSessionTriggerHandler.getPlaygroupLeaderContacts(null);
        test.stopTest();
        
        System.assert(pgCs.isEmpty(), 'Should have returned an empty list, but was: ' + pgCs);
    }

    @iSTest 
    static void createPlaygroupContactsSuccess(){
        Playgroup_Session__c pgs = createPlaygroupSession();
        Animal__c dog = TestDataFactory.createAnimalWithName('testDog');
        Animal_Playgroup__c[] aPgs = createAnimalPlaygroups(pgs.Id, new Animal__c[]{dog});
        Map<Id, Playgroup_Session__c> sessionMap = new Map<Id, Playgroup_Session__c>();
        sessionMap.put(pgs.Id, pgs);

        test.startTest();
            PlaygroupSessionTriggerHandler.createPlaygroupContacts(sessionMap, aPgs);
        test.stopTest();

        System.assert(![SELECT Id FROM Playgroup_Contact__c WHERE Playgroup__r.Playgroup_Session__c =: pgs.Id].isEmpty(),
        'should have returned a list of Playgroup Contacts, but was empty');
    }

    @iSTest 
    static void createPlaygroupContactsNoContacts(){
        test.startTest();
            PlaygroupSessionTriggerHandler.createPlaygroupContacts(new Map<Id, Playgroup_Session__c>(), new Animal_Playgroup__c[0]) ;
        test.stopTest();

        Playgroup_Contact__c[] pgCs = [SELECT Id FROM Playgroup_Contact__c];

        System.assert(pgCs.isEmpty(),
        'should have returned an empty list of Playgroup Contacts, but was: ' + pgCs);
    }

    @isTest 
    static void updatePlaygroupContactsSuccess(){
        Playgroup_Session__c pgs = TestDataFactory.createPlaygroupSessionWithAnimals();
        Map<Id, Playgroup_Session__c> pgsMap = new Map<Id, Playgroup_Session__c>();
        pgsMap.put(pgs.Id, pgs);
        Playgroup_Contact__c[] pgCs = [SELECT Id, Contact__c, Playgroup__r.Playgroup_Session__c FROM Playgroup_Contact__c WHERE Playgroup__r.Playgroup_Session__c =: pgs.Id];
        Contact newCon = TestDataFactory.createContact();

        pgs.Playgroup_Leader__c =  newCon.Id;

        test.startTest();
            PlaygroupSessionTriggerHandler.updatePlaygroupContacts(pgsMap, pgCs);
        test.stopTest();

        Playgroup_Contact__c[] updatedPgCs = [SELECT Id FROM Playgroup_Contact__c WHERE Contact__c =: newCon.Id];
        System.assert(!updatedPgCs.isEmpty(), 'Should have returned the playgroup contact, but was empty');
    }

    @isTest 
    static void updatePlaygroupContactsEmptyParams(){
        test.startTest();
            PlaygroupSessionTriggerHandler.updatePlaygroupContacts(new Map<Id, Playgroup_Session__c>(), new Playgroup_Contact__c[0]);
        test.stopTest();

        Playgroup_Contact__c[] updatedPgCs = [SELECT Id FROM Playgroup_Contact__c];
        System.assert(updatedPgCs.isEmpty(), 'Should have returned an empty list, but was: ' + updatedPgCs);
    }

    @isTest 
    static void filterSessionsWithLeaders(){
        Playgroup_Session__c session1 = TestDataFactory.createPlaygroupSessionWithAnimals();
        Playgroup_Session__c session2 = createPlaygroupSession();
        session2.Playgroup_Leader__c = null;

        test.startTest();
            Map<Id, Playgroup_Session__c> sessionsWithLeaders = PlaygroupSessionTriggerHandler.filterSessionsWithLeaders(new Playgroup_Session__c[]{session1, session2});
        test.stopTest();

        System.assert(sessionsWithLeaders.containsKey(session1.Id), 'Map should have included session1 becuase it has a leader');
        System.assert(!sessionsWithLeaders.containsKey(session2.Id), 'Map should not have included session2 becuase it does not have a leader');
    }

    @isTest 
    static void prepUpdatedSessionMap(){
        Playgroup_Session__c sessionRemoveLeader = createPlaygroupSession();
        Playgroup_Session__c sessionAddLeader = createPlaygroupSession();
        sessionAddLeader.Playgroup_Leader__c = TestDataFactory.createContact().Id;
        Playgroup_Session__c sessionUpdateLeader = createPlaygroupSession();

        //set up the 'old' data
        Map<Id, Playgroup_Session__c> oldSessionMap = new Map<Id, Playgroup_Session__c>();
        oldSessionMap.put(sessionRemoveLeader.Id, new Playgroup_Session__c(
            Id = sessionRemoveLeader.Id,
            Playgroup_Leader__c = sessionRemoveLeader.Playgroup_Leader__c
            )
        );

        oldSessionMap.put(sessionAddLeader.Id, new Playgroup_Session__c(
            Id = sessionAddLeader.Id,
            Playgroup_Leader__c = null
            )
        );

        oldSessionMap.put(sessionUpdateLeader.Id, new Playgroup_Session__c(
            Id = sessionUpdateLeader.Id,
            Playgroup_Leader__c = TestDataFactory.createContact().Id
            )
        );

        sessionRemoveLeader.Playgroup_Leader__c = null;
        test.startTest();
            Map<String, Map<Id, Playgroup_Session__c>> updatedSessionMap = PlaygroupSessionTriggerHandler.prepUpdatedSessionMap(
                new Playgroup_Session__c[]{sessionRemoveLeader, sessionAddLeader, sessionUpdateLeader},
                oldSessionMap
            );
        test.stopTest();

        System.assert(updatedSessionMap.get('removed').containsKey(sessionRemoveLeader.Id));
        System.assert(updatedSessionMap.get('updated').containsKey(sessionUpdateLeader.Id));
        System.assert(updatedSessionMap.get('added').containsKey(sessionAddLeader.Id));
        
    }

    @isTest 
    static void handlePlaygroupLeaderUpdatedAddLeader(){
        Playgroup_Session__c pgs = TestDataFactory.createPlaygroupSessionWithAnimals();
        Playgroup_Session__c oldPgs = new Playgroup_Session__c(
            Id = pgs.Id,
            Playgroup_Leader__c = null
        );

        //need to delete the playgroup contacts created in the dataFactory
        delete [SELECT Id FROM Playgroup_Contact__c];

        test.startTest();
            PlaygroupSessionTriggerHandler.handlePlaygroupLeaderUpdated(new Playgroup_Session__c[]{pgs}, new Map<Id, Playgroup_Session__c>{pgs.Id => oldPgs});
        test.stopTest();

        Playgroup_Contact__c[] pgCList = [SELECT Id FROM Playgroup_Contact__c WHERE Playgroup__r.Playgroup_Session__c =: pgs.Id];
        System.assert(!pgCList.isEmpty(), 'should have returned newly created pg contacts, but was empty');
    }

    @isTest 
    static void handlePlaygroupLeaderUpdatedRemoveLeader(){
        Playgroup_Session__c oldPgs = TestDataFactory.createPlaygroupSessionWithAnimals();
        Playgroup_Session__c pgs = new Playgroup_Session__c(
            Id = oldPgs.Id,
            Playgroup_Leader__c = null
        );

        System.assert(![SELECT Id FROM Playgroup_Contact__c WHERE Playgroup__r.Playgroup_Session__c =: pgs.Id AND Novel_Not_Novel__c = 'PG Leader'].isEmpty());

        test.startTest();
            PlaygroupSessionTriggerHandler.handlePlaygroupLeaderUpdated(new Playgroup_Session__c[]{pgs}, new Map<Id, Playgroup_Session__c>{pgs.Id => oldPgs});
        test.stopTest();

        Playgroup_Contact__c[] pgCList = [SELECT Id FROM Playgroup_Contact__c WHERE Playgroup__r.Playgroup_Session__c =: pgs.Id AND Novel_Not_Novel__c = 'PG Leader'];
        System.assert(pgCList.isEmpty(), 'should have returned an empty list becuase the playgroupContacts should have been deleted, but was: ' + pgCList);
    }

    @isTest 
    static void handlePlaygroupLeaderUpdatedUpdateLeader(){
        Playgroup_Session__c oldPgs = TestDataFactory.createPlaygroupSessionWithAnimals();
        System.debug('oldPgs: ' + oldPgs);
        Contact con = TestDataFactory.createContact();
        Playgroup_Session__c pgs = new Playgroup_Session__c(
            Id = oldPgs.Id,
            Playgroup_Leader__c = con.Id
        );

        Playgroup_Contact__c[] pgCList = [SELECT Id, Contact__c FROM Playgroup_Contact__c WHERE Playgroup__r.Playgroup_Session__c =: pgs.Id AND Novel_Not_Novel__c = 'PG Leader'];
        System.debug('pgCList: ' + pgCList);
        System.assert(pgClist.size() == 1);
        System.assertEquals(oldPgs.Playgroup_Leader__c, pgClist[0].Contact__c);

        test.startTest();
            PlaygroupSessionTriggerHandler.handlePlaygroupLeaderUpdated(new Playgroup_Session__c[]{pgs}, new Map<Id, Playgroup_Session__c>{pgs.Id => oldPgs});
        test.stopTest();

        Playgroup_Contact__c[] pgCListUpdated = [SELECT Id, Contact__c FROM Playgroup_Contact__c WHERE Playgroup__r.Playgroup_Session__c =: pgs.Id AND Novel_Not_Novel__c = 'PG Leader'];
        System.assert(pgCListUpdated.size() == 1);
        System.assertEquals(con.Id, pgCListUpdated[0].Contact__c);
    }

    @isTest 
    static void getAnimalSessionNoteToPlaygroup(){
        Playgroup_Session__c pgs = TestDataFactory.createPlaygroupSessionWithAnimals();

        test.startTest();
        pgs.Playgroup_Notes__c = 'test';
        update pgs;
        test.stopTest();

        for(Animal_Playgroup__c ap : [SELECT Id, Playgroup_Session_Notes__c FROM Animal_Playgroup__c WHERE Playgroup_Session__c = :pgs.Id]){
            System.assertEquals(
                'test', 
                ap.Playgroup_Session_Notes__c, 
                'Playgroup_Session_Notes__c for each Animal_Playgroup__c should be test, but was: ' + ap.Playgroup_Session_Notes__c);
        }        
    }

    private static Playgroup_Session__c createPlaygroupSession(){
        Contact con = TestDataFactory.createContact();
        Playgroup_Session__c playgroup = new Playgroup_Session__c(
            Playgroup_Leader__c = con.Id
        );
        insert playgroup;
        return playgroup;
    }

    private static Animal_Playgroup__c[] createAnimalPlaygroups(Id sessionid, Animal__c[] animals){
        Animal_Playgroup__c[] aPgList = new Animal_Playgroup__c[0];
        for(Animal__c anim : animals){
            aPgList.add(new Animal_Playgroup__c(
                Playgroup_Session__c = sessionId,
                Animal__c = anim.Id,
                Common_Playgroup_Note_Sections__c = 'Greeting',
                Common_Playgroup_Notes__c = 'Airhorn',
                Play_Rating__c = 'Green',
                Playgroup_Individual_Notes__c = 'Individual note'
            ));
        }
        insert aPgList;
        return aPgList;
    }
}