force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/Behavior_Evaluation__c.object-meta.xml
<CustomObject>
    <label>Behavior Evaluation</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Behavior Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Behavior Evaluations</relationshipLabel>
    <relationshipName>Behavior_Evaluations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Comments_BIK__c.field-meta.xml
<CustomField>
    <fullName>Comments_BIK__c</fullName>
    <label>Comments BIK</label>
    <length>22768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Comments_BOL__c.field-meta.xml
<CustomField>
    <fullName>Comments_BOL__c</fullName>
    <label>Comments BOL</label>
    <length>22768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Evaluation_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Subtype__c</fullName>
    <label>Evaluations</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Puppy</fullName>
            </value>
            <value>
                <fullName>Dog Fighting</fullName>
            </value>
            <value>
                <fullName>Adult Animal</fullName>
            </value>
            <value>
                <fullName>Fighting Dog Case</fullName>
                <isActive>false</isActive>
                <label>Fighting Dog Case</label>
            </value>
            <value>
                <fullName>Play Test P1</fullName>
                <isActive>false</isActive>
                <label>Play Test P1</label>
            </value>
            <value>
                <fullName>Play Test P2</fullName>
                <isActive>false</isActive>
                <label>Play Test P2</label>
            </value>
            <value>
                <fullName>Pleasant Touch Test</fullName>
                <isActive>false</isActive>
                <label>Pleasant Touch Test</label>
            </value>
            <value>
                <fullName>Social Test P1</fullName>
                <isActive>false</isActive>
                <label>Social Test P1</label>
            </value>
            <value>
                <fullName>Social Test P2</fullName>
                <isActive>false</isActive>
                <label>Social Test P2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Handler_Initials__c.field-meta.xml
<CustomField>
    <fullName>Handler_Initials__c</fullName>
    <label>Handler Name</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Potential_Behavior_Issues__c.field-meta.xml
<CustomField>
    <fullName>Potential_Behavior_Issues__c</fullName>
    <label>Potential Behavior Issues</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aggression to People</fullName>
            </value>
            <value>
                <fullName>Aggression to Dogs</fullName>
            </value>
            <value>
                <fullName>Fear</fullName>
            </value>
            <value>
                <fullName>High Arousal</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Other:</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Puppy_Behavior_in_Kennel__c.field-meta.xml
<CustomField>
    <fullName>Puppy_Behavior_in_Kennel__c</fullName>
    <label>Puppy Behavior in Kennel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Not social</fullName>
            </value>
            <value>
                <fullName>Mildly fearful</fullName>
            </value>
            <value>
                <fullName>Excited</fullName>
            </value>
            <value>
                <fullName>Stereotypic behavior</fullName>
            </value>
            <value>
                <fullName>Hyperaroused</fullName>
            </value>
            <value>
                <fullName>Moderately Fearful</fullName>
            </value>
            <value>
                <fullName>Aggressive in cage only</fullName>
            </value>
            <value>
                <fullName>Extremely fearful</fullName>
            </value>
            <value>
                <fullName>Threatened tester</fullName>
            </value>
            <value>
                <fullName>Aggressive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Puppy_Behavior_on_Leash__c.field-meta.xml
<CustomField>
    <fullName>Puppy_Behavior_on_Leash__c</fullName>
    <label>Puppy Behavior on Leash</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Relaxed</fullName>
            </value>
            <value>
                <fullName>Excited</fullName>
            </value>
            <value>
                <fullName>Mildly fearful</fullName>
            </value>
            <value>
                <fullName>Moderately fearful</fullName>
            </value>
            <value>
                <fullName>Walked or balked-extremely fearful</fullName>
            </value>
            <value>
                <fullName>Panicked</fullName>
            </value>
            <value>
                <fullName>Showed aggressive behavior</fullName>
            </value>
            <value>
                <fullName>Too fearful-subtest was not done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Puppy_Skipped_DI_P1__c.field-meta.xml
<CustomField>
    <fullName>Puppy_Skipped_DI_P1__c</fullName>
    <label>Puppy Skipped DI P1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skip_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Puppy_Skipped_DI_P2__c.field-meta.xml
<CustomField>
    <fullName>Puppy_Skipped_DI_P2__c</fullName>
    <label>Puppy Skipped DI P2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skip_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Puppy_Skipped_DI_P3__c.field-meta.xml
<CustomField>
    <fullName>Puppy_Skipped_DI_P3__c</fullName>
    <label>Puppy Skipped DI P3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skip_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Scribe_Initials__c.field-meta.xml
<CustomField>
    <fullName>Scribe_Initials__c</fullName>
    <label>Scribe Name</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Tester_Initials__c.field-meta.xml
<CustomField>
    <fullName>Tester_Initials__c</fullName>
    <label>Tester Name</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bundle_Entry__c/Bundle_Entry__c.object-meta.xml
<CustomObject>
    <label>Bundle Entry</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Bundle Entries Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle_Entry__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Bundle Entries</relationshipLabel>
    <relationshipName>Bundle_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bundle_Entry__c/fields/Treatment_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Bundle__c</fullName>
    <label>Treatment Bundle</label>
    <referenceTo>Treatment_Bundle__c</referenceTo>
    <relationshipLabel>Bundle Entries</relationshipLabel>
    <relationshipName>Bundle_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Bundle__c/Treatment_Bundle__c.object-meta.xml
<CustomObject>
    <label>Treatment Bundle</label>
    <nameField>
        <label>Treatment Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Treatment Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/AssignedTreatmentBundleId__c.field-meta.xml
<CustomField>
    <fullName>AssignedTreatmentBundleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Treatment Bundle</label>
    <referenceTo>Treatment_Bundle__c</referenceTo>
    <relationshipLabel>Treatment Plans (Assigned Treatment Bundle)</relationshipLabel>
    <relationshipName>Assigned_Treatment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/MasterTreatmentBundleId__c.field-meta.xml
<CustomField>
    <fullName>MasterTreatmentBundleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Treatment Bundle</label>
    <referenceTo>Treatment_Bundle__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Preferred_Motivators__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Motivators__c</fullName>
    <label>Preferred Motivators</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Treatment_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Treatment Bundle</label>
    <referenceTo>Treatment_Bundle__c</referenceTo>
    <relationshipLabel>Treatment Plans (Assigned Treatment Bundle)</relationshipLabel>
    <relationshipName>Assigned_Treatment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Skip_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Skipped to safeguard welfare of the animal</fullName>
    </customValue>
    <customValue>
        <fullName>Skipped due to risk to the handler</fullName>
    </customValue>
    <customValue>
        <fullName>Skipped for medical reason</fullName>
    </customValue>
    <customValue>
        <fullName>Skipped due to not having an appropriate helper dog</fullName>
    </customValue>
    <customValue>
        <fullName>Skipped due to risk to the helper dog</fullName>
    </customValue>
    <customValue>
        <fullName>Skipped not necessary</fullName>
    </customValue>
    <masterLabel>Skip Reason</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/test_TreatmentPlanService.cls
/**
 * Created by CloudQnect on 9/20/2021.
 */

@IsTest
private class test_TreatmentPlanService {
    @IsTest
    static void treatmentPlanRegressionTest() {

        Treatment_Bundle__c master = TestDataFactory.createMasterBundle();
        Treatment_Bundle__c bundle = TestDataFactory.createTreatmentBundle();
        Treatment_Bundle__c bundleTwo = TestDataFactory.createTreatmentBundle();
        bundleTwo.Name = 'Bundle Two';
        update bundleTwo;

        List<Protocol__c> protocols = TestDataFactory.createProtocols(5);
        List<Protocol__c> protocolsTwo = TestDataFactory.createProtocols(8);

        List<Bundle_Entry__c> masterEntries = TestDataFactory.assignEntries(master, protocols);
        List<Bundle_Entry__c> masterEntriesTwo = TestDataFactory.assignEntries(master, protocolsTwo);

        List<Bundle_Entry__c> bundleEntries = TestDataFactory.assignEntries(bundle, protocols);
        List<Bundle_Entry__c> bundleTwoEntries = TestDataFactory.assignEntries(bundleTwo, protocolsTwo);

        Treatment_Plan__c plan = new Treatment_Plan__c();
        plan.MasterTreatmentBundleId__c = master.Id;
        insert plan;

        plan.Preferred_Motivators__c = 'Test';
        plan.AssignedTreatmentBundleId__c = bundle.Id;
        update plan;

        plan.AssignedTreatmentBundleId__c = bundleTwo.Id;
        update plan;

    }

    @IsTest
    static void assignNewBundleTest() {
        Treatment_Bundle__c master = TestDataFactory.createMasterBundle();
        Treatment_Bundle__c bundle = TestDataFactory.createTreatmentBundle();
        Treatment_Bundle__c bundleTwo = TestDataFactory.createTreatmentBundle();
        bundleTwo.Name = 'Bundle Two';
        update bundleTwo;

        List<Protocol__c> protocols = TestDataFactory.createProtocols(5);
        List<Protocol__c> protocolsTwo = TestDataFactory.createProtocols(8);

        List<Bundle_Entry__c> masterEntries = TestDataFactory.assignEntries(master, protocols);
        List<Bundle_Entry__c> masterEntriesTwo = TestDataFactory.assignEntries(master, protocolsTwo);

        List<Bundle_Entry__c> bundleEntries = TestDataFactory.assignEntries(bundle, protocols);
        List<Bundle_Entry__c> bundleTwoEntries = TestDataFactory.assignEntries(bundleTwo, protocolsTwo);

        Treatment_Plan__c plan = new Treatment_Plan__c();
        plan.MasterTreatmentBundleId__c = master.Id;
        insert plan;

        plan.Preferred_Motivators__c = 'Test';
        plan.AssignedTreatmentBundleId__c = bundle.Id;
        update plan;
    }

    @IsTest
    static void bundleReassignmentTest() {
        Treatment_Bundle__c master = TestDataFactory.createMasterBundle();
        Treatment_Bundle__c bundle = TestDataFactory.createTreatmentBundle();
        Treatment_Bundle__c bundleTwo = TestDataFactory.createTreatmentBundle();
        bundleTwo.Name = 'Bundle Two';
        update bundleTwo;

        List<Protocol__c> protocols = TestDataFactory.createProtocols(5);
        List<Protocol__c> protocolsTwo = TestDataFactory.createProtocols(8);

        List<Bundle_Entry__c> masterEntries = TestDataFactory.assignEntries(master, protocols);
        List<Bundle_Entry__c> masterEntriesTwo = TestDataFactory.assignEntries(master, protocolsTwo);

        List<Bundle_Entry__c> bundleEntries = TestDataFactory.assignEntries(bundle, protocols);
        List<Bundle_Entry__c> bundleTwoEntries = TestDataFactory.assignEntries(bundleTwo, protocolsTwo);

        Treatment_Plan__c plan = new Treatment_Plan__c();
        plan.MasterTreatmentBundleId__c = master.Id;
        insert plan;

        plan.Preferred_Motivators__c = 'Test';
        plan.AssignedTreatmentBundleId__c = bundle.Id;
        update plan;
        plan.AssignedTreatmentBundleId__c = bundleTwo.Id;
        update plan;

    }

    @isTest 
    static void assignPlanTest(){
        Treatment_Plan__c plan = TestDataFactory.createPlan();
        Behavior_Evaluation__c be = new Behavior_Evaluation__c(
            Puppy_Behavior_in_Kennel__c = 'Social;Excited',
            Puppy_Behavior_on_Leash__c = 'Mildly fearful;Panicked',
            Animal__c = plan.Animal__c,
            Scribe_Initials__c = 'SI',
            Tester_Initials__c = 'TI',
            Handler_Initials__c = 'HI',
            Comments_BIK__c = 'Test Comments for Unit Test',
            Comments_BOL__c = 'Other Test Comments for Unit Test',
            Puppy_Skipped_DI_P1__c = 'Skipped not necessary',
            Puppy_Skipped_DI_P2__c = 'Skipped not necessary',
            Puppy_Skipped_DI_P3__c = 'Skipped not necessary',
            Evaluation_Subtype__c = 'Puppy',
            Potential_Behavior_Issues__c = 'Aggression to People;Other'
        );
        insert be;

        ServiceRequest req = new ServiceRequest('test request','assignPlan',null);
        req.Parameters.put('recordId',(Object) be.Id);

        test.startTest();
            ServiceResponse response = TreatmentPlanService.process(req);
        test.stopTest();
        System.AssertEquals('SUCCESS', response.Data);

    }
}