force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Name_Id__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name_Id__c</fullName>
    <formula>Animal_Name__c + &apos; (&apos; +  Name + &apos;)&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animal Name/Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Behavior Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Behavior Case Worker)</relationshipLabel>
    <relationshipName>Beh_Case_Worker_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <label>Current Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Recent_Shelter_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Recent_Shelter_Location__c</fullName>
    <label>Current/Recent Shelter Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Calendar_Schedule_Config__mdt/Calendar_Schedule_Config__mdt.object-meta.xml
<CustomObject>
    <description>Used to auto schedule items</description>
    <label>Calendar Schedule Config</label>
    <pluralLabel>Calendar Schedule Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Calendar_Schedule_Config__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Custom_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Custom_Schedule__c</fullName>
    <inlineHelpText>If left blank, will use default schedule.</inlineHelpText>
    <label>Custom Schedule</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Scheduling_Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Treatment_Priority__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Priority__c</fullName>
    <label>Treatment Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Treatment</fullName>
                <default>true</default>
                <label>No Treatment</label>
            </value>
            <value>
                <fullName>Daily – 7 days</fullName>
            </value>
            <value>
                <fullName>High – 5 days</fullName>
            </value>
            <value>
                <fullName>Medium – 4 days</fullName>
            </value>
            <value>
                <fullName>Low – 3 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Scheduling_Days.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Monday</fullName>
    </customValue>
    <customValue>
        <fullName>Tuesday</fullName>
    </customValue>
    <customValue>
        <fullName>Wednesday</fullName>
    </customValue>
    <customValue>
        <fullName>Thursday</fullName>
    </customValue>
    <customValue>
        <fullName>Friday</fullName>
    </customValue>
    <customValue>
        <fullName>Saturday</fullName>
    </customValue>
    <customValue>
        <fullName>Sunday</fullName>
    </customValue>
    <masterLabel>Scheduling Days</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ScheduleAnimalTreatments.cls
public with sharing class ScheduleAnimalTreatments {
    public static Task[] scheduleTreatments() {
        Task[] treatmentTasks = new Task[0];
        Map<String, Calendar_Schedule_Config__mdt> calendarConfigMap = AutoScheduleTasksUtil.getCalendarConfig('Treatment');
        for(Treatment_Plan__c treatment : [
            SELECT Id, Custom_Schedule__c, Treatment_Priority__c, Animal__c,
            Animal__r.Animal_Name_Id__c, Animal__r.Current_Recent_Shelter_Location__c, Animal__r.Current_Location__c, Animal__r.Behavior_Case_Worker__c, Animal__r.Behavior_Case_Worker__r.Name
            FROM Treatment_Plan__c
            WHERE Animal__r.Current_Recent_Shelter_Location__c IN ('MRC', 'CRC') 
            AND IsActive__c = TRUE
            AND Treatment_Priority__c NOT IN ('No Treatment', '')
        ]){
            String configKey = treatment.Animal__r.Current_Recent_Shelter_Location__c + '-' + treatment.Treatment_Priority__c.split(' ')[0];
            if(treatment.Custom_Schedule__c != null || calendarConfigMap.containsKey(configKey)){
                treatmentTasks.addAll(prepTasks(treatment, calendarConfigMap.containsKey(configKey) ? calendarConfigMap.get(configKey) : null));
            }
        }
        return treatmentTasks;
    }

    private static Task[] prepTasks(Treatment_Plan__c treatment, Calendar_Schedule_Config__mdt config){
        Id taskRTId = [SELECT Id FROM RecordType WHERE SobjectType = 'Task' AND DeveloperName =: AutoScheduleTasksUtil.TREATMENT_TASK_RECORD_TYPE_NAME LIMIT 1].Id;
        Task[] newTasks = new Task[0];
        Map<String, Date> dateMap = new Map<String, Date>();
        
        if(config != null){
            dateMap = AutoScheduleTasksUtil.getDateMap(config);
        } else {
            dateMap = AutoScheduleTasksUtil.getDateMap(treatment.Custom_Schedule__c);
        }

        for(String day : dateMap.keySet()){
            Task newTask = new Task(
                WhatId = treatment.Id,
                Animal__c = treatment.Animal__c,
                RecordTypeId = taskRTId,
                ActivityDate = dateMap.get(day),
                Description = 'Treatment is needed for: ' + treatment.Animal__r.Animal_Name_Id__c + ' (' + treatment.Animal__r.Current_Recent_Shelter_Location__c + ')',
                IsReminderSet = true,
                Status = 'Not Started',
                WhoId = treatment.Animal__r.Behavior_Case_Worker__c != null ? treatment.Animal__r.Behavior_Case_Worker__c : '0030100000IdslhAAB',
                Subject = 'Treatment'
                // ,Assigned_Resources__c = treatment.Animal__r.Animal_Name_Id__c + ';' + AutoScheduleTasksUtil.NO_RESOURCE_DEFAULT

            );
            newTasks.add(newTask);
        }
        return newTasks;
    }
}