force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Designated_Handler_Reason__c.field-meta.xml
<CustomField>
    <fullName>Designated_Handler_Reason__c</fullName>
    <label>Designated Handler Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Handling_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Handling_Instructions__c</fullName>
    <label>Handling Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Play_Style_Notes__c.field-meta.xml
<CustomField>
    <fullName>Play_Style_Notes__c</fullName>
    <label>Play Style Notes</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Shelter_Color_Coding__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Color_Coding__c</fullName>
    <inlineHelpText>Shelter handling color code for the animal</inlineHelpText>
    <label>Shelter Color Coding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shelter_Color_Coding</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/Behavior_Evaluation__c.object-meta.xml
<CustomObject>
    <label>Behavior Evaluation</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Behavior Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Behavior Evaluations</relationshipLabel>
    <relationshipName>Behavior_Evaluations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Overall_Evaluation_Grade__c.field-meta.xml
<CustomField>
    <fullName>Overall_Evaluation_Grade__c</fullName>
    <label>Overall Evaluation Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A - No Concerns</fullName>
            </value>
            <value>
                <fullName>B - Mild Concern(s)</fullName>
            </value>
            <value>
                <fullName>C - Moderate Concern(s)</fullName>
            </value>
            <value>
                <fullName>D - Severe Concern(s)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EntityHistory__c/EntityHistory__c.object-meta.xml
<CustomObject>
    <label>Entity History</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Entity History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entity Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EntityHistory__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Entity Histories</relationshipLabel>
    <relationshipName>Entity_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EntityHistory__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>Field Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EntityHistory__c/fields/NewValue__c.field-meta.xml
<CustomField>
    <fullName>NewValue__c</fullName>
    <label>New Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EntityHistory__c/fields/ObjectId__c.field-meta.xml
<CustomField>
    <fullName>ObjectId__c</fullName>
    <label>Object Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EntityHistory__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EntityHistory__c/fields/OldValue__c.field-meta.xml
<CustomField>
    <fullName>OldValue__c</fullName>
    <label>Old Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EntityHistory__c/fields/RecordName__c.field-meta.xml
<CustomField>
    <fullName>RecordName__c</fullName>
    <label>Record Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogHistory.cls
public without sharing class LogHistory {
    public static void LogHistory(Map<Id, SObject> oldRecordMap, List<SObject> records){
        if(oldRecordMap == null || records == null){
            return;
        }
        
        List<SObject> histories = new List<SObject>();
        for(SObject obj : records){
            histories.addAll(LogHistory(obj, oldRecordMap));
        }
        if(histories.size() > 0){
            insert histories;
        }
    }
    
    public static List<SObject> LogHistory(Sobject record, Map<Id, SObject> oldRecord){
        List<EntityHistory__c> histories = new List<EntityHistory__c>();
        String objectApiName = (getObjectName(record.Id)).toLowerCase();
        if(objectFieldMap.containsKey(objectApiName)){
            for(String fieldName : objectFieldMap.get(objectApiName)){
                if(hasChanged(record, oldRecord, fieldName)){
                    EntityHistory__c history = new EntityHistory__c();
                    history.RecordName__c = String.valueof(record.get('name')); 
                    if(objectApiName == 'behavior_evaluation__c'){
                        history.ParentId__c = String.valueof(record.get('animal__c'));
                    }
                    history.FieldName__c = getFieldLabel(objectApiName, fieldName);
                    history.OldValue__c = String.valueOf(oldRecord.get(record.Id).get(fieldName));
                    history.NewValue__c = String.valueOf(record.get(fieldName));
                    history.ObjectId__c = record.Id;
                    history.ObjectName__c = getObjectLabel(record.Id);
                    histories.add(history);
                }
            }
        }
        return histories;
    }
    
    public static boolean hasChanged(SObject newRecord, Map<Id, SObject > oldRecordMap, String fieldName) {
        return ((newRecord.get(fieldName) != null && oldRecordMap == null)
                || oldRecordMap != null && oldRecordMap.get(newRecord.Id).get(fieldName) != newRecord.get(fieldName))
            ? true : false;
    }
    
    public static String getObjectName(Id sId){
        return sId.getSObjectType().getDescribe().getName();
    }
    
    public static String getObjectLabel(Id sId){
        return sId.getSObjectType().getDescribe().getLabel();
    }
    
    public static String getFieldLabel(String ObjectApi, String FieldApi){
        return (String)Schema.getGlobalDescribe().get(ObjectApi).getDescribe().fields.getMap().get(FieldApi).getDescribe().getLabel()+' \n';
    }
    
    private static Map<String, Set<String>> objectFieldMap = new Map<String, Set<String>>{
        'animal__c' => new Set<String> {'handling_instructions__c', 'shelter_color_coding__c', 'play_style_notes__c','	Designated_Handler_Reason__c'},  
        'behavior_evaluation__c' => new Set<String> {'overall_evaluation_grade__c'}
    };    
}