force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Age__c.field-meta.xml
<CustomField>
    <fullName>Animal_Age__c</fullName>
    <label>Animal Age</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Age_Units__c.field-meta.xml
<CustomField>
    <fullName>Animal_Age_Units__c</fullName>
    <label>Animal Age Units</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Weeks</fullName>
            </value>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Age_Units_Changed_Date__c.field-meta.xml
<CustomObject>
<fields>
    <fullName>Animal_Age_Units_Changed_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The last date the animal age fields that are based on units (rather than estimated DOB) have been updated.</description>
    <label>Animal Age Units Changed Date</label>
    <type>Date</type>
</fields>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name__c</fullName>
    <externalId>true</externalId>
    <label>ASPCA Animal Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;Unspecified&quot;</defaultValue>
    <label>Primary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Primary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Animal_Age_Formatted__c.field-meta.xml
<CustomField>
    <fullName>Current_Animal_Age_Formatted__c</fullName>
    <formula>IF( ISNULL( Today_Test__c ) ,
IF(NOT(ISBLANK(Estimated_Date_of_Birth__c)),
    TEXT(FLOOR(( (TODAY() - Estimated_Date_of_Birth__c) / 365)))
    &amp;&apos; Years&apos; &amp; &apos; &apos; &amp;
    TEXT(FLOOR( (MOD( (TODAY() - Estimated_Date_of_Birth__c),365)/30))) &amp;&apos; Months&apos;,
    IF(NOT(ISBLANK(Animal_Age__c)) &amp;&amp; NOT(ISBLANK(TEXT(Animal_Age_Units__c))),
        IF(TEXT(Animal_Age_Units__c) = &apos;Days&apos;,
            TEXT(FLOOR(( (TODAY() - (Animal_Age_Units_Changed_Date__c - Animal_Age__c))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (TODAY() - (Animal_Age_Units_Changed_Date__c - Animal_Age__c)),365)/30))) &amp;&apos; Months&apos;,
        IF(TEXT(Animal_Age_Units__c) = &apos;Weeks&apos;,
            TEXT(FLOOR(( (TODAY() - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (TODAY() - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c))),365)/30))) &amp;&apos; Months&apos; ,
        IF(TEXT(Animal_Age_Units__c) = &apos;Months&apos;,
            IF(Animal_Age__c &lt; 12,
                &apos;0 Years &apos; &amp; TEXT(Animal_Age__c) &amp; &apos; Months&apos;,
                TEXT(FLOOR( (TODAY()  - ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))/365))
                &amp;&apos; Years&apos; &amp; &apos; &apos;
                &amp; TEXT(FLOOR( MOD( (TODAY()  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))),365)/30)) &amp;&apos; Months&apos;),
        IF(TEXT(Animal_Age_Units__c) = &apos;Years&apos;,
            TEXT(FLOOR(( (TODAY() - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -12 * Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD(TODAY() - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, 12)),365)/30))) &amp;&apos; Months&apos;,
        &quot;&quot;)))) ,
    &quot;&quot;)
),

IF(NOT(ISBLANK(Estimated_Date_of_Birth__c)),
    TEXT(FLOOR(( (Today_Test__c  - Estimated_Date_of_Birth__c) / 365)))
    &amp;&apos; Years&apos; &amp; &apos; &apos; &amp;
    TEXT(FLOOR( (MOD( (Today_Test__c  - Estimated_Date_of_Birth__c),365)/30))) &amp;&apos; Months&apos;,
    IF(NOT(ISBLANK(Animal_Age__c)) &amp;&amp; NOT(ISBLANK(TEXT(Animal_Age_Units__c))),
        IF(TEXT(Animal_Age_Units__c) = &apos;Days&apos;,
            TEXT(FLOOR(( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - Animal_Age__c))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - Animal_Age__c)),365)/30))) &amp;&apos; Months&apos;,
        IF(TEXT(Animal_Age_Units__c) = &apos;Weeks&apos;,
            TEXT(FLOOR(( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c))),365)/30))) &amp;&apos; Months&apos; ,
        IF(TEXT(Animal_Age_Units__c) = &apos;Months&apos;,
            IF(Animal_Age__c &lt; 12,
                &apos;0 Years &apos; &amp; TEXT(Animal_Age__c) &amp; &apos; Months&apos;,
                TEXT(FLOOR( (Today_Test__c  - ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))/365))
                &amp;&apos; Years&apos; &amp; &apos; &apos;
                &amp; TEXT(FLOOR( MOD( (Today_Test__c  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))),365)/30)) &amp;&apos; Months&apos;),
        IF(TEXT(Animal_Age_Units__c) = &apos;Years&apos;,
            TEXT(FLOOR(( (Today_Test__c  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -12 * Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD(Today_Test__c  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, 12)),365)/30))) &amp;&apos; Months&apos;,
        &quot;&quot;)))) ,
    &quot;&quot;)
)

)</formula>
    <label>Current Animal Age</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Estimated_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Date_of_Birth__c</fullName>
    <label>Estimated Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Type_of_Animal__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Animal__c</fullName>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Species</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name__c</fullName>
    <label>Animal Name(s)</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Primary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Bay roan</fullName>
    </customValue>
    <customValue>
        <fullName>Beige</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Blue roan</fullName>
    </customValue>
    <customValue>
        <fullName>Brindle</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Buckskin</fullName>
    </customValue>
    <customValue>
        <fullName>Buff</fullName>
    </customValue>
    <customValue>
        <fullName>Calico</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut/Sorrel</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Dun</fullName>
    </customValue>
    <customValue>
        <fullName>Fawn</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Grulla</fullName>
    </customValue>
    <customValue>
        <fullName>Hairless</fullName>
    </customValue>
    <customValue>
        <fullName>Liver chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Palomino</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Red roan</fullName>
    </customValue>
    <customValue>
        <fullName>Roan</fullName>
    </customValue>
    <customValue>
        <fullName>Seal</fullName>
    </customValue>
    <masterLabel>Primary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Species.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avian</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Cow</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Equine</fullName>
    </customValue>
    <customValue>
        <fullName>Exotic</fullName>
    </customValue>
    <customValue>
        <fullName>Fowl</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <masterLabel>Species</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AnimalAgeTest.cls
@isTest public class AnimalAgeTest {
    public static final Date TESTDOB1 = Date.newInstance(2016, 1, 15);
    // public static FINAL Date testDOB2 = Date.newInstance(2020, 4, 15);
    // static FINAL Date testDOB3 = Date.newInstance(2020, 12, 15);
    // public static FINAL Date testCurrentDate1 = Date.newInstance(2021, 1, 15);

    @testSetup static void setup() {
        // Create case
        Case testCase = new Case();
        insert testCase;

        // Create animals
        Animal__c[] testAnimals = new List<Animal__c>();
        for(Integer i = 1; i <= 12; i++) {
            Animal__c animal = new Animal__c(Animal_Name__c = 'Train' + i);
            animal.Animal_Name__c = 'Train';
            animal.Animal_Age__c = 1;
            switch on Math.mod(i,3) {
                when 1 { animal.Animal_Age_Units__c = 'Months'; }
                when 2 { animal.Animal_Age_Units__c = 'Years'; }
                when 3 { animal.Animal_Age_Units__c = 'Days'; }
            }
            animal.Estimated_Date_of_Birth__c =  i > 6 ? TESTDOB1 : null;
            animal.Type_of_Animal__c = 'Dog';
            animal.Case__c = testCase.Id;
            testAnimals.add(animal);
        }
        insert testAnimals;      
    }

    @isTest static void testInitalLastAnimalUnitsUpdate() {
        Animal__c[] animals= new List<Animal__c>([SELECT Id, CreatedDate, Current_Animal_Age_Formatted__c, Animal_Age_Units_Changed_Date__c	 FROM Animal__c]);

        for (Animal__c a : animals) {
            system.debug(a.Current_Animal_Age_Formatted__c);
            system.debug(a.Animal_Age_Units_Changed_Date__c);
        }
        // system.debug(animal.CreatedDate);
        // system.assertEquals(test1expected, animal.Current_Animal_Age_Formatted__c, test1def);
        // system.debug(animal);
    }



    @isTest static void testAgeUnitsLastUpdated() {

        // test1
        String test1def = 'no Estimated DOB, units=months, currentdateyear=different from birth year';
        // test2
        String test2def = 'no Estimated DOB, units=years, currentdateyear=different from birth year';        
        // test3
        String test3def = 'no Estimated DOB, units=days, currentdateyear=different from birth year';
        // test4
        String test4def = 'no Estimated DOB, units=months, currentdateyear=same from birth year';
        // test5
        String test5def = 'no Estimated DOB, units=years, currentdateyear=same from birth year';        
        // test6
        String test6def = 'no Estimated DOB, units=days, currentdateyear=same from birth year';
        // test7
        String test7def = 'Estimated DOB, units=months, currentdateyear=different from birth year';
        // test8
        String test8def = 'Estimated DOB, units=years, currentdateyear=different from birth year';        
        // test9
        String test9def = 'Estimated DOB, units=days, currentdateyear=different from birth year';
        // test10
        String test10def = 'Estimated DOB, units=months, currentdateyear=same from birth year';
        // test11
        String test11def = 'Estimated DOB, units=years, currentdateyear=same from birth year';        
        // test12
        String test12def = 'Estimated DOB, units=days, currentdateyear=same from birth year';


        Integer test1number = 5;
        String test1units = 'Months';
        String test1expected = '0 Years and 5 Months';
        Datetime test1CreatedDate = Datetime.newInstance(2021, 12, 16);
        Datetime testEDOB = Datetime.newInstance(2021, 6, 1);

        // Case testCase = new Case();
        // insert testCase;



        Animal__c animal = new Animal__c();
        // animal.Animal_Name__c = 'Train';
        // animal.Type_of_Animal__c = 'Cat';
        // animal.Color__c = 'Black';
        // animal.Case__c = testCase.ID;
        // animal.Animal_Age__c = test1number;
        // animal.Animal_Age_Units__c = test1units;
        // animal.Estimated_Date_of_Birth__c = null;
        insert animal;
        Test.setCreatedDate(animal.Id, test1CreatedDate);

        animal = [SELECT Id, CreatedDate, Current_Animal_Age_Formatted__c FROM Animal__c WHERE Id = :animal.Id];
        system.debug(animal.CreatedDate);
        system.assertEquals(test1expected, animal.Current_Animal_Age_Formatted__c, test1def);
        system.debug(animal);
    }
}