force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Behavior_Evaluation__c/Behavior_Evaluation__c.object-meta.xml
<CustomObject>
    <label>Behavior Evaluation</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Behavior Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Behavior Evaluations</relationshipLabel>
    <relationshipName>Behavior_Evaluations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Behavior_in_Kennel__c.field-meta.xml
<CustomField>
    <fullName>Behavior_in_Kennel__c</fullName>
    <label>Behavior in Kennel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Not social</fullName>
            </value>
            <value>
                <fullName>Mildly fearful</fullName>
            </value>
            <value>
                <fullName>Excited</fullName>
            </value>
            <value>
                <fullName>Stereotypic behavior</fullName>
            </value>
            <value>
                <fullName>Hyperaroused</fullName>
            </value>
            <value>
                <fullName>Aggressive in cage only</fullName>
            </value>
            <value>
                <fullName>Extremely fearful</fullName>
            </value>
            <value>
                <fullName>Threatened</fullName>
            </value>
            <value>
                <fullName>Aggressive</fullName>
            </value>
            <value>
                <fullName>Moderately Fearful</fullName>
            </value>
            <value>
                <fullName>Did not approach the tester-Moderately fearful</fullName>
                <isActive>false</isActive>
                <label>Did not approach the tester-Moderately fearful</label>
            </value>
            <value>
                <fullName>Threatens</fullName>
                <isActive>false</isActive>
                <label>Threatens</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Caution__c.field-meta.xml
<CustomField>
    <fullName>Caution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Caution for Live Dog Testing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Comments_BIK__c.field-meta.xml
<CustomField>
    <fullName>Comments_BIK__c</fullName>
    <label>Comments BIK</label>
    <length>22768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Evaluation_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Subtype__c</fullName>
    <label>Evaluations</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Puppy</fullName>
            </value>
            <value>
                <fullName>Dog Fighting</fullName>
            </value>
            <value>
                <fullName>Adult Animal</fullName>
            </value>
            <value>
                <fullName>Fighting Dog Case</fullName>
                <isActive>false</isActive>
                <label>Fighting Dog Case</label>
            </value>
            <value>
                <fullName>Play Test P1</fullName>
                <isActive>false</isActive>
                <label>Play Test P1</label>
            </value>
            <value>
                <fullName>Play Test P2</fullName>
                <isActive>false</isActive>
                <label>Play Test P2</label>
            </value>
            <value>
                <fullName>Pleasant Touch Test</fullName>
                <isActive>false</isActive>
                <label>Pleasant Touch Test</label>
            </value>
            <value>
                <fullName>Social Test P1</fullName>
                <isActive>false</isActive>
                <label>Social Test P1</label>
            </value>
            <value>
                <fullName>Social Test P2</fullName>
                <isActive>false</isActive>
                <label>Social Test P2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Handler_Initials__c.field-meta.xml
<CustomField>
    <fullName>Handler_Initials__c</fullName>
    <label>Handler Name</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Scribe_Initials__c.field-meta.xml
<CustomField>
    <fullName>Scribe_Initials__c</fullName>
    <label>Scribe Name</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Tester_Initials__c.field-meta.xml
<CustomField>
    <fullName>Tester_Initials__c</fullName>
    <label>Tester Name</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/test/test_BehaviorEvaluationPageController.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

@IsTest
private class test_BehaviorEvaluationPageController {
    @IsTest
    static void regressionCoverage() {


        Test.startTest();
        //Animal__c A = [SELECT Id, name from Animal__c WHERE Id = 'a077j000001VVm6AAG'];
        String initials = 'LB';
        Behavior_Evaluation__c evaluation = new Behavior_Evaluation__c();
        evaluation.Behavior_in_Kennel__c = 'Social';
        evaluation.Animal__c = Id.valueOf('a077j000001VVm6AAG');
        evaluation.Scribe_Initials__c = initials;
        evaluation.Tester_Initials__c = initials;
        evaluation.Handler_Initials__c = initials;
        evaluation.Comments_BIK__c = 'AAAAAAAAAAAAAAAAAAA';
        evaluation.Evaluation_Subtype__c = 'Puppy';
        insert evaluation;
        BehaviorEvaluationPageController controller = new BehaviorEvaluationPageController();
        Behavior_Evaluation__c testGetter = BehaviorEvaluationPageController.getOne(evaluation.Id);
        List<EvaluationWrapper> allWrappers = new List<EvaluationWrapper>();
        allWrappers.add(BehaviorEvaluationPageController.getBehaviorInKennel(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getBehaviorOnLeash(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getSocialBehaviorTestOne(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getSocialBehaviorTestTwo(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPleasantTouchTest(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getUnpleasantTouchTestOne(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPlayTestPartOne(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPlayTestPartTwo(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getTagTest(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getResourceGuardingOnePF(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getResourceGuardingOneTF(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getResourceGuardingOneTN(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getResourceGuardingOneTB(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getResourceGuardingTwo(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getResourceGuardingTF(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getResourceGuardingTwoTB(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getResourceGuardingTwoTN(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getToddlerDollTestOne(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getToddlerDollTestTwo(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getScoldingPersonTestOne(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getScoldingPersonTestTwo(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getFakeDogTest(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getSameSexDogTestOne(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getSameSexDogTestTwo(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getSameSexDogTestThree(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getOppositeSexDogTestOne(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getOppositeSexDogTestTwo(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getOppositeSexDogTestThree(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppyBehaviorInKennel(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppyBehaviorOnLeash(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppyChildDollOne(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppyChildDollTwo(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppySocialBehaviorPart1(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppySocialBehaviorPart2(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppyPlayTestTugTug(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppyPlayTestTugP1(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppyPlayTestTugP2(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppyRestraint(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppyResourceGuardingPartOne(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppyResourceGuardingPartTwo(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppyChildDollTwo(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppyChildDollTwo(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppyDogInteractionOne(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppyDogInteractionTwo(evaluation.Id));
        allWrappers.add(BehaviorEvaluationPageController.getPuppyDogInteractionThree(evaluation.Id));

        evaluation.Caution__c = true;
        Boolean status = BehaviorEvaluationPageController.getCautionStatus(evaluation.Id);

        Map<String, Object> updateEvalTest = BehaviorEvaluationPageController.updateEval('Comments_BIK__c',
                'Social', String.valueOf(evaluation.Id));
        Map<String, Object> selectionsTest = BehaviorEvaluationPageController.putSelections('Behavior_In_Kennel__c',
                String.valueOf('Social, Not Social').split(','), String.valueOf(evaluation.Id));
        Map<String,Object> validityTest = BehaviorEvaluationPageController.handleValidity(String.valueOf(evaluation.Id));
        List<EvaluationWrapper.ListItems> items = BehaviorEvaluationPageController.getSkipReasons(1);
        System.assertNotEquals(items, null);
        System.assertNotEquals(allWrappers, null);
        System.assertNotEquals(updateEvalTest, null);
        System.assertNotEquals(selectionsTest, null);
        System.assertNotEquals(validityTest, null);
        Test.stopTest();
    }

    @IsTest
    static void adultCoverage() {
        Test.startTest();
        String initials = 'LB';
        Behavior_Evaluation__c evaluation = new Behavior_Evaluation__c();
        evaluation.Behavior_in_Kennel__c = 'Social';
        evaluation.Animal__c = Id.valueOf('a077j000001VVm6AAG');
        evaluation.Scribe_Initials__c = initials;
        evaluation.Tester_Initials__c = initials;
        evaluation.Handler_Initials__c = initials;
        evaluation.Comments_BIK__c = 'AAAAAAAAAAAAAAAAAAA';
        evaluation.Evaluation_Subtype__c = 'Adult Animal';
        insert evaluation;
        BehaviorEvaluationPageController controller = new BehaviorEvaluationPageController();
        Behavior_Evaluation__c testGetter = BehaviorEvaluationPageController.getOne(evaluation.Id);

        Map<String,Object> validityTest = BehaviorEvaluationPageController.handleValidity(String.valueOf(evaluation.Id));
        Test.stopTest();

    }
    @IsTest
    static void dogFightingCoverage() {
        Test.startTest();
        String initials = 'LB';
        Behavior_Evaluation__c evaluation = new Behavior_Evaluation__c();
        evaluation.Behavior_in_Kennel__c = 'Social';
        evaluation.Animal__c = Id.valueOf('a077j000001VVm6AAG');
        evaluation.Scribe_Initials__c = initials;
        evaluation.Tester_Initials__c = initials;
        evaluation.Handler_Initials__c = initials;
        evaluation.Comments_BIK__c = 'AAAAAAAAAAAAAAAAAAA';
        evaluation.Evaluation_Subtype__c = 'Dog Fighting';
        insert evaluation;
        BehaviorEvaluationPageController controller = new BehaviorEvaluationPageController();
        Behavior_Evaluation__c testGetter = BehaviorEvaluationPageController.getOne(evaluation.Id);

        Map<String,Object> validityTest = BehaviorEvaluationPageController.handleValidity(String.valueOf(evaluation.Id));
        Test.stopTest();

    }


}