force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Days_in_Treatment__c.field-meta.xml
<CustomField>
    <fullName>Days_in_Treatment__c</fullName>
    <description>calculate # of days in treatment</description>
    <formula>Final_Outcome_Date__c -  Treatment_Start_Date__c</formula>
    <label># of Days in Treatment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/Treatment_Session__c.object-meta.xml
<CustomObject>
    <label>Treatment Session</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Treatment Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Session__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Sessions</relationshipLabel>
    <relationshipName>Treatment_Sessions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/test_RollupCountHandler.cls
@isTest
private class test_RollupCountHandler {
    @isTest
    static void tesAnimalUpdatemethod(){
		Test.startTest();
        
		Animal__c animal = TestDataFactory.createAnimalWithName('TestDog');
		Animal__c animalData = [Select id,Days_in_Treatment__c from Animal__c where ID = :animal.id ];
        Treatment_Session__c session = TestDataFactory.createSessionWithAnimal(animal.Id);
        Treatment_Session__c session2 = TestDataFactory.createSessionWithAnimal(animal.Id);
        //Treatment_Session__c sessionData = [SELECT Id, Animal__c FROM Treatment_Session__c WHERE ID =: session.Id limit 1];	
		//sessionData.Animal__c =animalData.ID;	
        //update sessionData;
        Animal__c animalUpdatedData = [Select id,Days_in_Treatment__c from Animal__c where ID = :animal.id ];
        Test.stopTest();
        System.assertEquals(animalUpdatedData.Days_in_Treatment__c, 1);
    }	
    @isTest
    static void testDeleteTreatmentMethod(){
		Test.startTest();
        
		Animal__c animal = TestDataFactory.createAnimalWithName('TestDog3');
		Animal__c animalData = [Select id,Days_in_Treatment__c from Animal__c where ID = :animal.id ];
        Treatment_Session__c session = TestDataFactory.createSessionWithAnimal(animal.id);
         Treatment_Session__c session2 = TestDataFactory.createSessionWithAnimal(animal.id);
        //Treatment_Session__c session2 = TestDataFactory.createSession();
        Treatment_Session__c sessionData = [SELECT Id, Animal__c FROM Treatment_Session__c WHERE ID =: session.Id limit 1];	
		
        // Treatment_Session__c sessionData2 = [SELECT Id, Animal__c FROM Treatment_Session__c WHERE ID =: session2.Id limit 1];	
		// sessionData2.Animal__c =animalData.ID;	
        // update sessionData2;   
        Delete sessionData;
        Animal__c animalUpdatedData = [Select id,Days_in_Treatment__c from Animal__c where ID = :animal.id ];
        Test.stopTest();
        System.assertEquals(animalUpdatedData.Days_in_Treatment__c, 1);
    }	
      @isTest
    static void testUpdateTreatmentMethod(){
		Test.startTest();
        
		Animal__c animal = TestDataFactory.createAnimalWithName('TestDog'); 
        Animal__c animal2 = TestDataFactory.createAnimalWithName('TestDog2');
		
        Treatment_Session__c session = TestDataFactory.createSessionWithAnimal(animal.id);
        Treatment_Session__c sessionData = [SELECT Id, Animal__c FROM Treatment_Session__c WHERE ID =: session.Id limit 1];	
        Animal__c animalData = [Select id,Days_in_Treatment__c from Animal__c where ID = :animal2.id ];
		sessionData.Animal__c =animalData.ID;	
        update sessionData;
        // Animal__c animalData2 = [Select id,Days_in_Treatment__c from Animal__c where ID = :animal2.id ];
        // sessionData.Animal__c =animalData2.ID;	
        // update sessionData;
        
       
        Animal__c animalUpdatedData = [Select id,Days_in_Treatment__c from Animal__c where ID = :animal.id ];
        Test.stopTest();
        System.assertEquals(animalUpdatedData.Days_in_Treatment__c, 1);
    }	
}