force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age Estimate at Intake</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Age_Estimate_at_Intake</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Field_ID__c.field-meta.xml
<CustomField>
    <fullName>Animal_Field_ID__c</fullName>
    <label>Animal Field ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name__c</fullName>
    <externalId>true</externalId>
    <label>ASPCA Animal Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Concerns__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Concerns__c</fullName>
    <label>Behavior Concerns</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shy in Kennel</fullName>
            </value>
            <value>
                <fullName>Mouthy</fullName>
            </value>
            <value>
                <fullName>Dog Reactive</fullName>
            </value>
            <value>
                <fullName>Small Dogs</fullName>
            </value>
            <value>
                <fullName>Strangers</fullName>
            </value>
            <value>
                <fullName>Novelty</fullName>
            </value>
            <value>
                <fullName>Fearfull Outdoors</fullName>
            </value>
            <value>
                <fullName>Men</fullName>
            </value>
            <value>
                <fullName>Women</fullName>
            </value>
            <value>
                <fullName>Children</fullName>
            </value>
            <value>
                <fullName>RG Food/Objects</fullName>
            </value>
            <value>
                <fullName>Handling Issues</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>For EQUINE, see Help Text</description>
    <inlineHelpText>For EQUINE, choose one of the following: Horse, Donkey, Mule, Draft Horse, Mini Horse, Pony, Mini Mule, Mini Donkey</inlineHelpText>
    <label>Breed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;Unspecified&quot;</defaultValue>
    <label>Primary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Primary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Age_Estimate_at_Intake.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Juvenile w/dam</fullName>
    </customValue>
    <customValue>
        <fullName>&lt; 6 months</fullName>
    </customValue>
    <customValue>
        <fullName>0-4 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-8 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>8-12 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>12-16 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 1 year</fullName>
    </customValue>
    <customValue>
        <fullName>1 year - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>2-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>5-7 years</fullName>
    </customValue>
    <customValue>
        <fullName>7-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>greater than 10 yrs</fullName>
    </customValue>
    <customValue>
        <fullName>Egg</fullName>
    </customValue>
    <customValue>
        <fullName>Chick: Up To 8 Weeks</fullName>
    </customValue>
    <customValue>
        <fullName>Pullet: Female &lt; 2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Adult: &gt;2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Stag: Male &lt;2YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (with dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (without dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Weanling</fullName>
    </customValue>
    <customValue>
        <fullName>Yearling</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>4-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>6-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>11-15 years</fullName>
    </customValue>
    <customValue>
        <fullName>15-20 years</fullName>
    </customValue>
    <customValue>
        <fullName>20+ years</fullName>
    </customValue>
    <customValue>
        <fullName>Chick (0-10 wks.)</fullName>
    </customValue>
    <masterLabel>Age Estimate at Intake</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Primary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Bay roan</fullName>
    </customValue>
    <customValue>
        <fullName>Beige</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Blue roan</fullName>
    </customValue>
    <customValue>
        <fullName>Brindle</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Buckskin</fullName>
    </customValue>
    <customValue>
        <fullName>Buff</fullName>
    </customValue>
    <customValue>
        <fullName>Calico</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut/Sorrel</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Dun</fullName>
    </customValue>
    <customValue>
        <fullName>Fawn</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Grulla</fullName>
    </customValue>
    <customValue>
        <fullName>Hairless</fullName>
    </customValue>
    <customValue>
        <fullName>Liver chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Palomino</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Red roan</fullName>
    </customValue>
    <customValue>
        <fullName>Roan</fullName>
    </customValue>
    <customValue>
        <fullName>Seal</fullName>
    </customValue>
    <masterLabel>Primary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/controller/KennelSignageController.cls
/**
 * Created by barne on 4/6/2021.
 */
public with sharing class KennelSignageController {

    public Animal__c currentAnimal;
    public Animal__c animal { get; set; }
    public List<String> variables;

    /******************************************************************************************************************/
    /**************     PDF Generator and Basic Controller methods ****************************************************/
    /******************************************************************************************************************/

    public KennelSignageController()
    {
        dao_Animal daoAnimal = new dao_Animal();
        //PageReference page = new PageReference('/apex/KennelSignage');
        PageReference page = ApexPages.currentPage();
        System.debug('######Current Page   =' + page);

        currentAnimal = daoAnimal.findOne(page.getParameters().get('id'));
        System.debug('### Value of current animal  ' + currentAnimal);

        m_animalName();
        m_animalId();
        m_animalSex();
        m_animalColor();
        m_animalBreed();
        m_animalAge();
        iBehaviorConcernOptions();
        iBehaviorConcerns();

    }




    /****************************************************************************************************************/
    /************************ Basic Animal Info *********************************************************************/
    /****************************************************************************************************************/

    public String animalName {get; set; }
    public String animalId { get; set; }
    public String animalBreed { get; set;}
    public String animalAge {get; set; }
    public String animalSex { get; set; }
    public String animalColor { get; set; }

    public String m_animalName(){
        String defaultName = 'Default';

        animalName = currentAnimal.Animal_Name__c;

        if (animalName == null) {
            animalName = defaultName;
        }
        return animalName;
    }

    public String m_animalId() {
        String defaultId = '123456';

        animalId = currentAnimal.Animal_Field_ID__c;
        if (animalId == null) {
            animalId = defaultId;
        }
        return animalId;
    }

    public String m_animalBreed() {
         String defaultBreed = 'Dog';

        animalBreed = currentAnimal.Breed__c;
        if (animalBreed == null) {
            animalBreed = defaultBreed;
        }
        return animalBreed;
    }

    public String m_animalAge() {
        String defaultAge = 'Unkown';

        animalAge = currentAnimal.Age__c;
        if (animalAge == null) { animalAge = defaultAge ;}
        return animalAge;
    }

    public String m_animalSex() {
        String defaultSex = 'M';

        animalSex = currentAnimal.Gender__c;
        if (animalSex == null) { animalSex = defaultSex ;}
        return animalSex;
    }

    public String m_animalColor() {
        String defaultColor = 'Brown';

        animalColor = currentAnimal.Color__c;
        if (animalColor == null ) { animalColor = defaultColor ; }
        return animalColor;
    }



    /******************************************************************************************************************/
    /**********************  Body Properties **************************************************************************/
    /******************************************************************************************************************/

    public List<SelectOption> behaviorConcerns { get; set; }
    public List<String> behaviorConcernOptions { get; set; }

    public List<SelectOption> iBehaviorConcerns() {
        Schema.DescribeFieldResult fieldResult = Animal__c.Behavior_Concerns__c.getDescribe();
        List<PicklistEntry> options = fieldResult.getPicklistValues();

        ControllerHelper controllerHelper = new ControllerHelper();

        behaviorConcerns = controllerHelper.getPicklist(options);

        return behaviorConcerns;
    }

    public List<String> iBehaviorConcernOptions() {
        Schema.DescribeFieldResult fieldResult = Animal__c.Behavior_Concerns__c.getDescribe();
        List<PicklistEntry> options = fieldResult.getPicklistValues();

        ControllerHelper controllerHelper = new ControllerHelper();

        behaviorConcernOptions = controllerHelper.getOptions(options);

        return behaviorConcernOptions;
    }

    public List<SelectOption> iwalkingEquipment() {
        return null;
    }

    public List<SelectOption> iwalkingStatus() {
        return null;
    }

    public List<SelectOption> ivolunteerLevel() {
        return null;
    }

    public List<SelectOption> itrainingProtocols() {
        return null;
    }

    /******************************************************************************************************/
    /*******  Evaluation Property *************************************************************************/
    /******************************************************************************************************/

    public String evaluation() {
        return null;
    }

    /******************************************************************************************************************/
    /**************** PRIVATE METHODS *********************************************************************************/
    /******************************************************************************************************************/



}