force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Active_Animal__c.field-meta.xml
<CustomField>
    <fullName>Active_Animal__c</fullName>
    <formula>IF(AND(ISBLANK(Final_Outcome__c),Current_Location__c  &lt;&gt; &quot;NYPD Freezer&quot;,Current_Location__c &lt;&gt; &quot;NYPD Refrigerator&quot;),True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active Animal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name__c</fullName>
    <externalId>true</externalId>
    <label>ASPCA Animal Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Name_Id__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name_Id__c</fullName>
    <formula>Animal_Name__c + &apos; (&apos; +  Name + &apos;)&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animal Name/Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Behavior Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Behavior Case Worker)</relationshipLabel>
    <relationshipName>Beh_Case_Worker_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Behavior_Grade__c.field-meta.xml
<CustomField>
    <fullName>Current_Behavior_Grade__c</fullName>
    <label>Current Behavior Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>No Evaluation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Recent_Shelter_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Recent_Shelter_Location__c</fullName>
    <label>Current/Recent Shelter Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Email_Notification__c.field-meta.xml
<CustomField>
    <fullName>Email_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Automatic email sent to caseworker and manager when ownership is granted use the surrender field to trigger</description>
    <label>Email Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Play_Category__c.field-meta.xml
<CustomField>
    <fullName>Play_Category__c</fullName>
    <label>Play Category</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Seizure_Surrender_Date__c.field-meta.xml
<CustomField>
    <fullName>Seizure_Surrender_Date__c</fullName>
    <label>Seizure/Surrender Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Surrender_Type__c.field-meta.xml
<CustomField>
    <fullName>Surrender_Type__c</fullName>
    <label>Surrender Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Surrendered</fullName>
            </value>
            <value>
                <fullName>Forfeited</fullName>
            </value>
            <value>
                <fullName>Legally Abandoned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/recordTypes/Behavior.recordType-meta.xml
<RecordType>
    <fullName>Behavior</fullName>
    <active>true</active>
    <label>Behavior</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Treatment_Priority__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Priority__c</fullName>
    <label>Treatment Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Treatment</fullName>
                <default>true</default>
                <label>No Treatment</label>
            </value>
            <value>
                <fullName>Daily – 7 days</fullName>
            </value>
            <value>
                <fullName>High – 5 days</fullName>
            </value>
            <value>
                <fullName>Medium – 4 days</fullName>
            </value>
            <value>
                <fullName>Low – 3 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SeizureEmailNotificationController.cls
public class SeizureEmailNotificationController { 
    public static void handleSeizureEmailNotificationSchedular(){
        String[] locations = new String[]{'CRC','MRC','CRC/MRC'};
        Map<Id, List<Animal__c>> animalsRec = new  Map<Id, List<Animal__c>>();

        List<Animal__c> lstAnimals =[
            SELECT Id ,Name, Animal_Name_Id__c,Animal_Name__c,Gender__c,Current_Behavior_Grade__c,Surrender_Type__c, Email_Notification__c,
            Play_Category__c, Seizure_Surrender_Date__c,Current_Recent_Shelter_Location__c, Behavior_Case_Worker__c,
            (SELECT Id, Treatment_Priority__c FROM Treatment_Plan__r WHERE IsActive__c = true ORDER BY CreatedDate DESC LIMIT 1) 
            FROM Animal__c where Email_Notification__c =: true 
            AND Current_Recent_Shelter_Location__c IN :locations
            AND Active_Animal__c = true
        ];
        List<Animal__c> animalValues = null;   
        if(!lstAnimals.isEmpty()){
            for(Animal__c anm : lstAnimals){
                if(!animalsRec.containsKey(anm.Behavior_Case_Worker__c)){
                    animalValues = new  List<Animal__c>();
                }
                animalValues.add(anm);
                animalsRec.put(anm.Behavior_Case_Worker__c, animalValues);
            }
                    
            Map<Id, List<String>> contactByIdEmail  = new  Map<Id, List<String>> ();
            List<Contact> lstcontatcs = [Select Id,ReportsToId, ReportsTo.Email, Email from Contact where Id IN : animalsRec.keySet()];
            List<String> emails = new List<String>();
            for (Contact conn : lstcontatcs) {
                if(conn.ReportsToId != null && conn.ReportsTo.Email != null){
                    emails.add(conn.ReportsTo.Email);
                }
                if(conn.Email != null){
                    emails.add(conn.Email);
                }
                if(!emails.isEmpty()){
                    contactByIdEmail.put(conn.Id, emails);
                    emails = new List<String>();
                }
            }
            List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
            Date dtTodayDate = System.Today();
            Datetime dtTodayDateTime = datetime.newInstance(dtTodayDate.year(), dtTodayDate.month(),dtTodayDate.day());
            string strDate = dtTodayDateTime.format('MM/dd/yyyy');
            //for (Id conId : contactByIdEmail.keySet()) {
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(new List<String>{'scott.silvestro@aspca.org','Lauren.Zverina@aspca.org','katy.mahaley@aspca.org'});
                //mail.setToAddresses(contactByIdEmail.get(conId));
                //mail.setCcAddresses(new List<String> {'CRCBehaviorMgmt@aspca.org'});
                mail.setSubject('Animal surrender notification');
                String td1='"border:1px solid green; width=200px;"';
                String tdHead= '"border:1px solid green; width=200px; color:white; background-color:green; font-weight:bold;"';
                
                String htmlBody = 'Hello Manager! <br/>This is the ownership report for '+strDate+'.<br/><br/><center><table style="border:3px solid green; border-collapse:collapse;">';
                htmlBody  = htmlBody + '<thead>'
                            + '<tr>'
                                + '<th style='+ tdHead +'>Name</th>'
                                + '<th style='+ tdHead +'>Sex</th>'
                                + '<th style='+ tdHead +'>Current Behavior</th>'
                                + '<th style='+ tdHead +'>Treatment Priority</th>'
                                + '<th style='+ tdHead +'>Play Category</th>'
                                + '<th style='+ tdHead +'>Surrender Date</th>'
                                + '<th style='+ tdHead +'>Surrender Type</th>'
                            + '</tr>'
                            + '</thead><tbody>';
                //List<Animal__c> animals = animalsRec.get(conId);

                //for (Animal__c anm : animals) {
                List<Animal__c> animalList = new List<Animal__c>();
                for (Animal__c anm : lstAnimals) {
                    String animalName = anm.Animal_Name_Id__c == null ? '': anm.Animal_Name_Id__c;
                    String animalGender = anm.Gender__c == null ? '': anm.Gender__c;
                    String animalCurrBehvGrade = anm.Current_Behavior_Grade__c == null ? '': anm.Current_Behavior_Grade__c;
                        String animalPlayPriority = '';
                        if(anm.Treatment_Plan__r != null && anm.Treatment_Plan__r.size() > 0){
                            animalPlayPriority = anm.Treatment_Plan__r[0]. Treatment_Priority__c;
                        }
                        
                    String animalPlayCategory = anm.Play_Category__c == null ? '': anm.Play_Category__c;
                    Date animalSurrDate = anm.Seizure_Surrender_Date__c;
                    String animalsurrenderType = anm.Surrender_Type__c == null ? '': anm.Surrender_Type__c; 
                    htmlBody = htmlBody +   '<tr>'
                                        + '<td style='+ td1 +'>'+ animalName +'</td>'
                                        + '<td style='+ td1 +'>'+ animalGender +'</td>'
                                        + '<td style='+ td1 +'>'+ animalCurrBehvGrade +'</td>'
                                        + '<td style='+ td1 +'>'+ animalPlayPriority +'</td>'
                                        + '<td style='+ td1 +'>'+ animalPlayCategory +'</td>'
                                        + '<td style='+ td1 +'>'+ String.valueOf(animalSurrDate) +'</td>'
                                        + '<td style='+ td1 +'>'+ animalsurrenderType +'</td>'
                                        + '</tr>'; 
                    anm.Email_Notification__c = false;
                    // animalList.add(anm);
                }
                htmlBody = htmlBody + '</tbody></table></center>';
                
                mail.setHtmlBody(htmlBody);
                system.debug(htmlBody);
                mails.add(mail);
            //}
            if(test.isRunningTest()){
                if(!lstAnimals.isEmpty()){
                    update lstAnimals;
                }
            } else {
                if (mails.size() > 0){
                    try{
                        Messaging.sendEmail(mails);
                        if(!lstAnimals.isEmpty()){
                            update lstAnimals;
                        }
                    } catch(exception ex){
                        system.debug('error '+ ex );
                    }
                }
            }
        }
    }
}