force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Problem_Behavior__c.field-meta.xml
<CustomField>
    <fullName>Problem_Behavior__c</fullName>
    <label>Problem Behavior (see TEC)</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fear of People - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of People - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of People - Severe</fullName>
            </value>
            <value>
                <fullName>Fear of Handling - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of Handling - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of Handling - Severe</fullName>
            </value>
            <value>
                <fullName>Fear of Leashing, Leash Pressure, Walking on Leash - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of Leashing, Leash Pressure, Walking on Leash - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of Leashing, Leash Pressure, Walking on Leash - Severe</fullName>
            </value>
            <value>
                <fullName>Fear of Places, Objects, Novelty - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of Places, Objects, Novelty - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of Places, Objects, Novelty - Severe</fullName>
            </value>
            <value>
                <fullName>Fear of Noises - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of Noises - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of Noises - Severe</fullName>
            </value>
            <value>
                <fullName>Fear of Dogs - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of Dogs - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of Dogs - Severe</fullName>
            </value>
            <value>
                <fullName>Reactivity Toward People/Dogs (Specific to Kennel) - Mild</fullName>
            </value>
            <value>
                <fullName>Reactivity Toward People/Dogs (Specific to Kennel) - Moderate</fullName>
            </value>
            <value>
                <fullName>Reactivity Toward People/Dogs (Specific to Kennel) - Severe</fullName>
            </value>
            <value>
                <fullName>Arousal in Kennel/Shelter Stress - Mild</fullName>
            </value>
            <value>
                <fullName>Arousal in Kennel/Shelter Stress - Moderate</fullName>
            </value>
            <value>
                <fullName>Arousal in Kennel/Shelter Stress - Severe</fullName>
            </value>
            <value>
                <fullName>Arousal Out of Kennel/Jumping &amp; Mouthing - Mild</fullName>
            </value>
            <value>
                <fullName>Arousal Out of Kennel/Jumping &amp; Mouthing - Moderate</fullName>
            </value>
            <value>
                <fullName>Arousal Out of Kennel/Jumping &amp; Mouthing - Severe</fullName>
            </value>
            <value>
                <fullName>Reactivity on Leash (People) - Mild</fullName>
            </value>
            <value>
                <fullName>Reactivity on Leash (People) - Moderate</fullName>
            </value>
            <value>
                <fullName>Reactivity on Leash (People) - Severe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/Treatment_Session__c.object-meta.xml
<CustomObject>
    <label>Treatment Session</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Treatment Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Session__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Sessions</relationshipLabel>
    <relationshipName>Treatment_Sessions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/fields/Session_Contact__c.field-meta.xml
<CustomField>
    <fullName>Session_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Session Contacts</relationshipLabel>
    <relationshipName>Treatment_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/fields/Session_Notes__c.field-meta.xml
<CustomField>
    <fullName>Session_Notes__c</fullName>
    <label>Session Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <label>Treatment Plan</label>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Treatment Sessions</relationshipLabel>
    <relationshipName>Treatment_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RollUpCountHandlerTest.cls
@isTest
public class RollUpCountHandlerTest {

    @isTest
    static void testRollup(){
        Animal__c anm = TestDataFactory.createAnimal();
        Treatment_Plan__c plan = new Treatment_Plan__c(
            Problem_Behavior__c = 'Fear of People - Mild'
        );

        insert plan;

        Contact con = TestDataFactory.createContact();
		List<Treatment_Session__c> sessionList = new List<Treatment_Session__c>();
        Treatment_Session__c session = new Treatment_Session__c(
            Treatment_Plan__c = plan.Id,
            Session_Contact__c = con.Id,
            Session_Notes__c = 'Test',
            Animal__c = anm.Id
        );
        sessionList.add(session);
        
        Treatment_Session__c session2 = new Treatment_Session__c(
            Treatment_Plan__c = plan.Id,
            Session_Contact__c = con.Id,
            Session_Notes__c = 'Test',
            Animal__c = anm.Id
        );
        sessionList.add(session2);
        insert sessionList;
        
        update sessionList[0];
        
        delete sessionList[1];
        
        List<Treatment_Session__c> sList = [Select Id from Treatment_Session__c];
        System.assertEquals(sList.size(), 1);
    }
}