force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/AAH_ID__c.field-meta.xml
<CustomField>
    <fullName>AAH_ID__c</fullName>
    <label>AAH ID #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Active_Animal__c.field-meta.xml
<CustomField>
    <fullName>Active_Animal__c</fullName>
    <formula>IF(AND(ISBLANK(Final_Outcome__c),Current_Location__c  &lt;&gt; &quot;NYPD Freezer&quot;,Current_Location__c &lt;&gt; &quot;NYPD Refrigerator&quot;),True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active Animal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name__c</fullName>
    <externalId>true</externalId>
    <label>ASPCA Animal Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Name_Id__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name_Id__c</fullName>
    <formula>Animal_Name__c + &apos; (&apos; +  Name + &apos;)&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animal Name/Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Behavior Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Behavior Case Worker)</relationshipLabel>
    <relationshipName>Beh_Case_Worker_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <label>Current Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Evaluation_Status__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Status__c</fullName>
    <label>Evaluation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Hold_Status_ARC_CARE__c.field-meta.xml
<CustomField>
    <fullName>Hold_Status_ARC_CARE__c</fullName>
    <label>Hold Status ARC/CARE</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTA</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Behavior</fullName>
            </value>
            <value>
                <fullName>Forensic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Important_Notes_ARC_CARE__c.field-meta.xml
<CustomField>
    <fullName>Important_Notes_ARC_CARE__c</fullName>
    <label>Important Notes ARC/CARE</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Location_Filter__c.field-meta.xml
<CustomField>
    <fullName>Location_Filter__c</fullName>
    <formula>IF(User_Location__c = &quot;All&quot;, True, IF(ISBLANK(Current_Recent_Shelter_Location__c), False, IF(CONTAINS(User_Location__c, Current_Recent_Shelter_Location__c), True, False)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location Filter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Petpoint_ID__c.field-meta.xml
<CustomField>
    <fullName>Petpoint_ID__c</fullName>
    <label>Petpoint ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/PPE_DOH__c.field-meta.xml
<CustomField>
    <fullName>PPE_DOH__c</fullName>
    <label>PPE/DOH</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes – ACC/CIRDC</fullName>
            </value>
            <value>
                <fullName>Yes – Parasites</fullName>
            </value>
            <value>
                <fullName>Yes – Other</fullName>
            </value>
            <value>
                <fullName>DOH Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Walking_Notes__c.field-meta.xml
<CustomField>
    <fullName>Walking_Notes__c</fullName>
    <label>Walking Status Notes</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Walking_Status__c.field-meta.xml
<CustomField>
    <fullName>Walking_Status__c</fullName>
    <label>Walking Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Walks</fullName>
            </value>
            <value>
                <fullName>Terrace Walks</fullName>
            </value>
            <value>
                <fullName>Inside Walks</fullName>
            </value>
            <value>
                <fullName>Outside Walks</fullName>
            </value>
            <value>
                <fullName>2 person Walks</fullName>
            </value>
            <value>
                <fullName>Ok to take the Stairs</fullName>
            </value>
            <value>
                <fullName>None Specified</fullName>
                <default>true</default>
                <label>None Specified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/recordTypes/Behavior.recordType-meta.xml
<RecordType>
    <fullName>Behavior</fullName>
    <active>true</active>
    <label>Behavior</label>
</RecordType>

force-app/main/default/objects/BehaviorCaseWorker__c/BehaviorCaseWorker__c.object-meta.xml
<CustomObject>
    <label>Behavior Case Worker</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>BCW #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior Case Workers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BehaviorCaseWorker__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Behavior Case Workers</relationshipLabel>
    <relationshipName>Behavior_Case_Workers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BehaviorCaseWorker__c/fields/CaseWorker__c.field-meta.xml
<CustomField>
    <fullName>CaseWorker__c</fullName>
    <label>Case Worker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Contact_Type__c</field>
            <operation>equals</operation>
            <value>Behavior Case Worker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Behavior Case Workers</relationshipLabel>
    <relationshipName>Case_Workers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BehaviorCaseWorker__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name__c</fullName>
    <label>Animal Name(s)</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Citizen</fullName>
            </value>
            <value>
                <fullName>Agency Representative</fullName>
            </value>
            <value>
                <fullName>Animal Control Officer</fullName>
            </value>
            <value>
                <fullName>Animal Owner</fullName>
            </value>
            <value>
                <fullName>Animal Rescue</fullName>
            </value>
            <value>
                <fullName>Animal Welfare Professional</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Code Enforcement Officer</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>County/Civil Attorney</fullName>
            </value>
            <value>
                <fullName>Defense Attorney</fullName>
            </value>
            <value>
                <fullName>Law Enforcement Contact</fullName>
            </value>
            <value>
                <fullName>Law Enforcement Officer</fullName>
            </value>
            <value>
                <fullName>Local Elected Official</fullName>
            </value>
            <value>
                <fullName>Officer/Complainant</fullName>
            </value>
            <value>
                <fullName>Prosecuting Attorney</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
            <value>
                <fullName>Senator</fullName>
            </value>
            <value>
                <fullName>Shelter Contact</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>State Representative</fullName>
            </value>
            <value>
                <fullName>State Senator</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Suspect</fullName>
            </value>
            <value>
                <fullName>US Representative</fullName>
            </value>
            <value>
                <fullName>US Senator</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Relocation Driver</fullName>
            </value>
            <value>
                <fullName>Behavior Case Worker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ArcCareAnimalDogListController.cls
public class ArcCareAnimalDogListController {
    @AuraEnabled
    public static List<Animal__c> getRecords() {
        List<Animal__c> objs = [Select Id, Name, Animal_Name__c, Animal_Name_Id__c, Petpoint_ID__c,AAH_ID__c, Gender__c, Evaluation_Status__c, Current_Location__c, 
                Hold_Status_ARC_CARE__c, Behavior_Case_Worker__c, Behavior_Case_Worker__r.Name, Walking_Status__c, 
                Walking_Notes__c, PPE_DOH__c, Important_Notes_ARC_CARE__c FROM Animal__c 
                WHERE Active_Animal__c = true AND Location_Filter__c = true
                ORDER BY CreatedDate ];
        
        List<Animal__c> objList = new List<Animal__c>();
        for(Animal__c obj : objs){
            if(obj.Current_Location__c != null && (obj.Current_Location__c.equalsIgnoreCase('ARC') || 
              obj.Current_Location__c.equalsIgnoreCase('CARE'))){
                objList.add(obj);
            }
        }
        return objList;
    }
    
    @AuraEnabled
    public static List<Option> getPicklistValue(String fieldname){
        Schema.DescribeSObjectResult objSchema = Animal__c.sObjectType.getDescribe();
        Map<String, Schema.SObjectField> fieldMap = objSchema.fields.getmap();
        List<Schema.Picklistentry>fld =fieldmap.get(fieldname).getDescribe().getpicklistValues();
        List<Option> optionList = new List<Option>();
        for(Schema.Picklistentry pl : fld){
            Option op = new Option();
            op.value = pl.getValue();
            op.label = pl.getValue();
            optionList.add(op);
        }
        return optionList;
    }
    
    @AuraEnabled
    public static String saveRecords(String recsString) {
        System.debug(recsString);
        List<Animal__c> recs2Save = (List<Animal__c>) JSON.deserialize(recsString, List<Animal__c>.class);
        update recs2Save;

        Map<Id, Id> animalBehCaseWorkerMap = new Map<Id, Id>();
        for(Animal__c anm : recs2Save){
            if(anm.Behavior_Case_Worker__c != null){
                animalBehCaseWorkerMap.put(anm.Id, anm.Behavior_Case_Worker__c);
            }
        }

        List<BehaviorCaseWorker__c> behCaseWorkers =  [SELECT Id, Animal__c, CaseWorker__c, EndDate__c, StartDate__c FROM BehaviorCaseWorker__c where Animal__c IN : animalBehCaseWorkerMap.keySet()];
        Map<Id, Set<Id>> behAnmMap = new Map<Id, Set<Id>>();
        set<Id> caseWorkers = new Set<Id>();
        for(BehaviorCaseWorker__c b : behCaseWorkers){
            caseWorkers.add(b.CaseWorker__c);
            behAnmMap.put(b.Animal__c, caseWorkers);
        }
        List<BehaviorCaseWorker__c> newCaseWorkers = new List<BehaviorCaseWorker__c>();
        for(Id anmId : animalBehCaseWorkerMap.keySet()){
            if(!behAnmMap.containsKey(anmId) || (behAnmMap.containsKey(anmId) && !(behAnmMap.get(anmId).contains(animalBehCaseWorkerMap.get(anmId))))){
                BehaviorCaseWorker__c bcw = new BehaviorCaseWorker__c();
                bcw.Animal__c = anmId;
                bcw.StartDate__c = System.today();
                bcw.CaseWorker__c = animalBehCaseWorkerMap.get(anmId);
                newCaseWorkers.add(bcw);
            }
        }

        if(!newCaseWorkers.isEmpty()){
            insert newCaseWorkers;
        }

        return 'success';
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Contact> getBehCaseWorkers() {
        return [SELECT Id, Name FROM Contact WHERE Contact_Type__c = 'Behavior Case Worker'];
    }
    
    public class option{
        @AuraEnabled
        public String value;
        @AuraEnabled
        public String label;
    }
}