force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Playgroup__c/Animal_Playgroup__c.object-meta.xml
<CustomObject>
    <label>Animal Playgroup</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Animal Playgroup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Playgroups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Playgroup__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Playgroup_Session__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Session</label>
    <referenceTo>Playgroup_Session__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+ Id ,  FirstName + &quot; &quot; + LastName )</formula>
    <label>Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Playgroup__c/Playgroup__c.object-meta.xml
<CustomObject>
    <label>Playgroup</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Playgroups</relationshipLabel>
    <relationshipName>Playgroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup__c/fields/Playgroup_Location__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Location__c</fullName>
    <label>Playgroup Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indoor Play Yard</fullName>
            </value>
            <value>
                <fullName>Outdoor Play Yard</fullName>
            </value>
            <value>
                <fullName>MRC Indoor Play Yard</fullName>
            </value>
            <value>
                <fullName>MRC Outdoor Play Yard</fullName>
            </value>
            <value>
                <fullName>Monster Park</fullName>
            </value>
            <value>
                <fullName>ARC Terrace</fullName>
            </value>
            <value>
                <fullName>SBR</fullName>
            </value>
            <value>
                <fullName>Playroom 1</fullName>
            </value>
            <value>
                <fullName>Playroom 2</fullName>
            </value>
            <value>
                <fullName>Playroom 1 &amp; 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Playgroup_Contact__c/Playgroup_Contact__c.object-meta.xml
<CustomObject>
    <label>Playgroup Contact</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroup Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Playgroup_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Contact__c/fields/Playgroup__c.field-meta.xml
<CustomField>
    <fullName>Playgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup</label>
    <referenceTo>Animal_Playgroup__c</referenceTo>
    <relationshipName>Playgroup_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/Playgroup_Session__c.object-meta.xml
<CustomObject>
    <label>Playgroup Session</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroup Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup_Session__c/fields/Animal_Playgroup__c.field-meta.xml
<CustomField>
    <fullName>Animal_Playgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Playgroup</label>
    <referenceTo>Animal_Playgroup__c</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/fields/Contact_Ids__c.field-meta.xml
<CustomField>
    <fullName>Contact_Ids__c</fullName>
    <description>This field is used to hold the list of Contact Ids for this Session</description>
    <label>Contact Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/fields/Playgroup_Leader__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/fields/Playgroup_Location__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Location__c</fullName>
    <label>Playgroup Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indoor Play Yard</fullName>
            </value>
            <value>
                <fullName>Outdoor Play Yard</fullName>
            </value>
            <value>
                <fullName>MRC Indoor Play Yard</fullName>
            </value>
            <value>
                <fullName>MRC Outdoor Play Yard</fullName>
            </value>
            <value>
                <fullName>Monster Park</fullName>
            </value>
            <value>
                <fullName>ARC Terrace</fullName>
            </value>
            <value>
                <fullName>SBR</fullName>
            </value>
            <value>
                <fullName>Playroom 1</fullName>
            </value>
            <value>
                <fullName>Playroom 2</fullName>
            </value>
            <value>
                <fullName>Playroom 1 &amp; 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/test/test_playgroupSessionLWCController.cls
@isTest
private class test_playgroupSessionLWCController {
    @isTest 
    static void getPlaygroupSession_hasSession(){
        Playgroup_Session__c session = TestDataFactory.createPlaygroupSessionWithAnimals();

        test.startTest();
            Playgroup_Session__c returnedSession = playgroupSessionLWCController.getPlaygroupSession(session.Id);
        test.stopTest();

        System.assert(returnedSession != null, 'No session was returned');
    }

    @isTest 
    static void getPlaygroupSession_noSession(){
        test.startTest();
            Playgroup_Session__c returnedSession = playgroupSessionLWCController.getPlaygroupSession(null);
        test.stopTest();

        System.assert(returnedSession == null, 'Should have returned a null value');
    }

    @isTest 
    static void animalPlaygroups_hasPlaygroups(){
        Playgroup_Session__c session = TestDataFactory.createPlaygroupSessionWithAnimals();

        test.startTest();
            Animal_Playgroup__c[] returnedPlaygroups = playgroupSessionLWCController.animalPlaygroups(session.Id);
        test.stopTest();

        System.assert(!returnedPlaygroups.isEmpty(), 'Should have returned some animal playgroups, but was empty');
    }

    @isTest 
    static void animalPlaygroups_noPlaygroups(){
        Contact c = testDataFactory.createContact();

        Playgroup_Session__c session = new Playgroup_Session__c(
            Playgroup_Location__c = 'MRC Indoor Play Yard',
            Playgroup_Leader__c = c.Id
        );
        insert session;

        test.startTest();
            Animal_Playgroup__c[] returnedPlaygroups = playgroupSessionLWCController.animalPlaygroups(session.Id);
        test.stopTest();

        System.assert(returnedPlaygroups.isEmpty(), 'List of animal playgroups should be empty, but was: ' + returnedPlaygroups);
    }

    @isTest 
    static void getPlaygroupContacts_hasContacts(){
        Contact c1 = testDataFactory.createContact();
        Contact c2 = testDataFactory.createContact();
        String contactIds = c1.Id + ',' + c2.Id;

        test.startTest();
            Contact[] returnedContacts = playgroupSessionLWCController.getPlaygroupContacts(contactIds);
        test.stopTest();

        System.assertEquals(c1.Id, returnedContacts[0].Id);
        System.assertEquals(c2.Id, returnedContacts[1].Id);
    }

    @isTest 
    static void getPlaygroupContacts_noContacts(){
        test.startTest();
            Contact[] returnedContacts = playgroupSessionLWCController.getPlaygroupContacts(null);
        test.stopTest();

        System.assertEquals(null, returnedContacts);
    }

    // @isTest 
    // static void createNewPlaygroupAnimals_hasAnimalsToAdd(){
    //     Playgroup_Session__c session = TestDataFactory.createPlaygroupSessionWithAnimals();
    //     Contact c1 = testDataFactory.createContact();
    //     Contact c2 = testDataFactory.createContact();
    //     session.Contact_Ids__c = c1.Id + ',' + c2.Id;
    //     update session;
        
    //     playgroupSessionLWCController.playgroupSessionInfo sessionInfo = new playgroupSessionLWCController.playgroupSessionInfo();
    //     sessionInfo.playgroupSession = session;
    //     Animal__c newAnimal = TestDataFactory.createAnimalWithName('Doggo1');

    //     test.startTest();
    //         Animal_Playgroup__c[] returnedAnimalPlaygroup = playgroupSessionLWCController.createNewPlaygroupAnimals(sessionInfo, new Id[]{newAnimal.Id});
    //     test.stopTest();

    //     System.assert(!returnedAnimalPlaygroup.isEmpty(), 'Should have returned an animal playgroup, instead returned: ' + returnedAnimalPlaygroup);
    //     System.assertEquals(session.Id, returnedAnimalPlaygroup[0].Playgroup_Session__c);
    //     System.assertEquals(newAnimal.Id, returnedAnimalPlaygroup[0].Animal__c);

    //     Playgroup_Contact__c[] pgCons = [SELECT Id, Contact__c FROM Playgroup_Contact__c WHERE Playgroup__c =: returnedAnimalPlaygroup[0].Id];
    //     System.assertEquals(2, pgCons.Size());
    // }

    @isTest 
    static void getAnimalList_hasAnimals(){
        Playgroup_Session__c session = TestDataFactory.createPlaygroupSessionWithAnimals();

        test.startTest();
            Animal_Playgroup__c[] returnedAnimalPlaygroups = playgroupSessionLWCController.getAnimalList(session.Id);
        test.stopTest();

        System.assert(!returnedAnimalPlaygroups.isEmpty(), 'Returned animal playgroups should not be empty');
    }

    @isTest 
    static void getAnimalList_noAnimals(){
        Contact c = testDataFactory.createContact();

        Playgroup_Session__c session = new Playgroup_Session__c(
            Playgroup_Location__c = 'MRC Indoor Play Yard',
            Playgroup_Leader__c = c.Id
        );
        insert session;

        test.startTest();
            Animal_Playgroup__c[] returnedAnimalPlaygroups = playgroupSessionLWCController.getAnimalList(session.Id);
        test.stopTest();

        System.assert(!returnedAnimalPlaygroups.isEmpty(), 'Returned animal playgroups should not be empty');
    }

}