force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age Estimate at Intake</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Age_Estimate_at_Intake</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;Unspecified&quot;</defaultValue>
    <label>Primary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Primary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Discharged_to_Contact__c.field-meta.xml
<CustomField>
    <fullName>Discharged_to_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discharged to Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Discharged to Contact)</relationshipLabel>
    <relationshipName>Animals1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Formatted_Address__c.field-meta.xml
<CustomField>
    <fullName>Formatted_Address__c</fullName>
    <label>Formatted Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DG</fullName>
            </value>
            <value>
                <fullName>TP</fullName>
            </value>
            <value>
                <fullName>TR</fullName>
            </value>
            <value>
                <fullName>KH</fullName>
            </value>
            <value>
                <fullName>LG</fullName>
            </value>
            <value>
                <fullName>JR</fullName>
            </value>
            <value>
                <fullName>NR</fullName>
            </value>
            <value>
                <fullName>MW</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>LD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Config__c/Trigger_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger Config</label>
</CustomObject>

force-app/main/default/objects/Trigger_Config__c/fields/Animal_Trigger_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Animal_Trigger_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Animal Trigger Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Age_Estimate_at_Intake.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Juvenile w/dam</fullName>
    </customValue>
    <customValue>
        <fullName>&lt; 6 months</fullName>
    </customValue>
    <customValue>
        <fullName>0-4 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-8 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>8-12 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>12-16 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 1 year</fullName>
    </customValue>
    <customValue>
        <fullName>1 year - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>2-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>5-7 years</fullName>
    </customValue>
    <customValue>
        <fullName>7-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>greater than 10 yrs</fullName>
    </customValue>
    <customValue>
        <fullName>Egg</fullName>
    </customValue>
    <customValue>
        <fullName>Chick: Up To 8 Weeks</fullName>
    </customValue>
    <customValue>
        <fullName>Pullet: Female &lt; 2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Adult: &gt;2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Stag: Male &lt;2YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (with dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (without dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Weanling</fullName>
    </customValue>
    <customValue>
        <fullName>Yearling</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>4-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>6-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>11-15 years</fullName>
    </customValue>
    <customValue>
        <fullName>15-20 years</fullName>
    </customValue>
    <customValue>
        <fullName>20+ years</fullName>
    </customValue>
    <customValue>
        <fullName>Chick (0-10 wks.)</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown At Intake</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
        <isActive>false</isActive>
        <label>Unknown</label>
    </customValue>
    <masterLabel>Age Estimate at Intake</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Primary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Bay roan</fullName>
    </customValue>
    <customValue>
        <fullName>Beige</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Blue roan</fullName>
    </customValue>
    <customValue>
        <fullName>Brindle</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Buckskin</fullName>
    </customValue>
    <customValue>
        <fullName>Buff</fullName>
    </customValue>
    <customValue>
        <fullName>Calico</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut/Sorrel</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Dun</fullName>
    </customValue>
    <customValue>
        <fullName>Fawn</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Grulla</fullName>
    </customValue>
    <customValue>
        <fullName>Hairless</fullName>
    </customValue>
    <customValue>
        <fullName>Liver chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Palomino</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Red roan</fullName>
    </customValue>
    <customValue>
        <fullName>Roan</fullName>
    </customValue>
    <customValue>
        <fullName>Seal</fullName>
    </customValue>
    <customValue>
        <fullName>Unspecified</fullName>
    </customValue>
    <masterLabel>Primary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/domain/AnimalTriggerHandler.cls
public with sharing class AnimalTriggerHandler {

    public static void Execute() {
        if (!Trigger.isExecuting) { return; }
        Trigger_Config__c config = Trigger_Config__c.getInstance();
        if (config != null  && config.Animal_Trigger_Enabled__c == false) { return; }
        //System.debug('#### Running Animal Trigger');
        //trigger_Controller.getInstance().process(Animal__c.SObjectType);
        if (Trigger.isUpdate && Trigger.isBefore ) {
            beforeUpdateHandler();
        }
    }
    
    public static void insertHandler(){
        CaseContactRole conrole = new CaseContactRole();
        for (Animal__c a : (List<Animal__c>)Trigger.new){
            List<CaseContactRole> curroles = [SELECT Id from CaseContactRole WHERE CasesId =: a.Case__c AND ContactId =: a.Discharged_to_Contact__c AND Role = 'Animal Discharge Contact'];
            if (a.Discharged_to_Contact__c != null){
                conrole.CasesId = a.Case__c;
                conrole.ContactId = a.Discharged_to_Contact__c;
                conrole.Role = 'Animal Discharge Contact';   
                if (curroles.size() > 0){
                    break;
                } 
                else {
                insert conrole;
                }
            }
            
            if (a.Location__Latitude__s !=null){
                reverseGeoloc(a.Location__Latitude__s, a.Location__Longitude__s, a.Id);
                
            }

        }  
    }
    
    public static void insertHandlerBefore(){
        string initials = '';
        for (Animal__c a : (List<Animal__c>)Trigger.new){
            if (a.Gender__c == null){
                a.Gender__c = 'Unknown';
            }
            
//            if (a.Age__c == null){
//                a.Age__c = 'Unknown At Intake';
//            }
            
            if (a.Color__c == null){
                a.Color__c = 'Unspecified';
            }
            
            if (a.Name.contains('Form')){
                initials = UserInfo.getFirstName().substring(0,1) + UserInfo.getLastName().substring(0,1);
                a.Team__c = initials;
            }           
            
     
        }  
    }

    public static void beforeUpdateHandler() {
        Map<Id, SObject> toUpdate = Trigger.newMap;

    }

    
    public static void updateHandler(List<Animal__c> anms, Map<Id, Animal__c> oldAnms){
        CaseContactRole conrole = new CaseContactRole();
        for (Animal__c a : anms){
            List<CaseContactRole> curroles = [SELECT Id from CaseContactRole WHERE CasesId =: a.Case__c AND ContactId =: a.Discharged_to_Contact__c AND Role = 'Animal Discharge Contact'];
            Id oldCon = oldAnms.get(a.id).Discharged_to_Contact__c;
/*            System.debug(oldCon);
            if (oldCon != null){
                List<CaseContactRole> delConRoles = [SELECT Id from CaseContactRole WHERE CasesId =: a.Case__c AND ContactId =: oldCon AND Role = 'Animal Discharge Contact'];
                System.debug('CaseContactRole to be deleted: ' + delConRoles);
                delConRoles[0].Role = 'Receiving Shelter Contact';
                System.debug('CaseContactRole to be updated: ' + delConRoles);
                //delete delConRoles;
            }*/
			if (a.Discharged_to_Contact__c != oldCon && a.Discharged_to_Contact__c != null){
                conrole.CasesId = a.Case__c;
            	conrole.ContactId = a.Discharged_to_Contact__c;
            	conrole.Role = 'Animal Discharge Contact'; 
                if (curroles.size() > 0){
                    break;
                } 
                else {
                	insert conrole;
                }
                System.debug(conrole);
            }
            }
    }
    
	@future(callout=true)
	public static void reverseGeoloc(Decimal lat, Decimal longit, Id animalId) {
        
		String address = '';
        Http h = new Http();
		HttpRequest req = new HttpRequest();
        address = 'https://maps.googleapis.com/maps/api/geocode/json?latlng='+String.valueOf(lat)+','+String.valueOf(longit)+'&result_type=street_address&key=AIzaSyB_vRSHbde-6dByBFtnz-shb4CjuG8OPH0';
       	req.setMethod('GET');
        req.setEndpoint(address);
        HttpResponse res = h.send(req);
        
        system.debug(address);

        if (res.getStatusCode() == 200){
        	Map<String,Object> gr = (Map<String,Object>)JSON.deserializeUntyped(res.getBody());
			List<Object> results = (List<Object>)gr.get('results');
        	Map<String,Object> firstResult = (Map<String,Object>)results[0];  
        	if (firstResult != null){            
        		String fullAddress = (String)firstResult.get('formatted_address');
        		List<Animal__c> lstAnim = [SELECT Formatted_Address__c FROM Animal__c WHERE Id = :animalId];
            	if (!lstAnim.isEmpty()){
                	lstAnim[0].Formatted_Address__c = fullAddress;
                	system.debug(lstAnim[0].Formatted_Address__c);
            	}
        		update lstAnim;
        	}
        }
    }  
}