force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Days_in_Treatment__c.field-meta.xml
<CustomField>
    <fullName>Days_in_Treatment__c</fullName>
    <description>calculate # of days in treatment</description>
    <formula>Final_Outcome_Date__c -  Treatment_Start_Date__c</formula>
    <label># of Days in Treatment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Final_Outcome_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Outcome_Date__c</fullName>
    <label>Final Outcome Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Treatment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Start_Date__c</fullName>
    <label>Treatment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/Treatment_Session__c.object-meta.xml
<CustomObject>
    <label>Treatment Session</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Treatment Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Session__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Sessions</relationshipLabel>
    <relationshipName>Treatment_Sessions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RollUpCountHandler.cls
/**
 * 
 * Class Description
 *
 * @author Neha
 * @version 1.0.0
 */

public with sharing class RollUpCountHandler extends DomainActionBase {
    public override void ProcessAction(TriggerRequest request) {
        if (request.targetSObject == Treatment_Session__c.SObjectType) {
            String triggerAction = request.action + request.process;

            switch on triggerAction {
                when 'BeforeInsert' { beforeInsert(request); }
                when 'BeforeUpdate' { beforeUpdate(request); }
                when 'BeforeDelete' { beforeDelete(request);}
                when 'AfterInsert' { afterInsert(request);}
                when 'AfterUpdate' { afterUpdate(request);}
                when 'AfterDelete' { afterDelete(request);}
            }
        } 
        return;
    }

    @SuppressWarnings('ApexUnresolvableReference')
    public void beforeInsert(TriggerRequest request) {
        System.debug('TREATMENT SESSION ROLLUP BEFORE INSERT IS EXECUTING');
    }


    public void beforeUpdate (TriggerRequest request)  {System.debug('TREATMENT SESSION ROLLUP BEFORE INSERT IS EXECUTING'); }
    public void beforeDelete (TriggerRequest request)  {System.debug('TREATMENT SESSION ROLLUP BEFORE INSERT IS EXECUTING'); }
    public void afterInsert (TriggerRequest request) {
        System.debug('TREATMENT SESSION ROLLUP AFTER INSERT IS EXECUTING');
               
        List<Treatment_Session__c> newRecords =  request.newRecords;
        set<id> animalsIds = new Set<id>();
        List<Animal__c> listOfAnimals = new List<Animal__c>();
        
        for(Treatment_Session__c ts: newRecords){
            if(ts.Animal__c!=null){
                animalsIds.add(ts.Animal__c);
            }
        }
        if(!animalsIds.isEmpty()){
            List<Animal__c> listAnimals = [Select id, Name, Days_in_Treatment__c,Final_Outcome_Date__c, Treatment_Start_Date__c, (Select id, CreatedDate from Treatment_Sessions__r Order by CreatedDate ASC) FROM Animal__c WHERE ID IN: animalsIds];
            for(Animal__c animal: listAnimals){
                if(animal.Treatment_Sessions__r.size()>0){
                    animal.Treatment_Start_Date__c = Date.newinstance(animal.Treatment_Sessions__r[0].CreatedDate.year(), animal.Treatment_Sessions__r[0].CreatedDate.month(), animal.Treatment_Sessions__r[0].CreatedDate.day());
                    animal.Days_in_Treatment__c=animal.Treatment_Sessions__r.size();
                    listOfAnimals.add(animal);
                }
            }
            if(listOfAnimals.size()>0){
                update listOfAnimals;
            }
        }

       
        
    }

    //@SuppressWarnings('ApexUnresolvableReference')
    public void afterUpdate(TriggerRequest request) { 
    	System.debug('TREATMENT SESSION ROLLUP BEFORE INSERT IS EXECUTING'); 
 		List<Treatment_Session__c> oldRecords =  request.oldRecords;
        set<id> animalsIds = new Set<id>();
        List<Animal__c> listOfAnimals = new List<Animal__c>();
        
        for(Treatment_Session__c ts: oldRecords){
            if(ts.Animal__c!=null){
                animalsIds.add(ts.Animal__c);
            }
        }
        if(!animalsIds.isEmpty()){
            List<Animal__c> listAnimals = [Select id, Name, Days_in_Treatment__c,Final_Outcome_Date__c, Treatment_Start_Date__c, (Select id, CreatedDate from Treatment_Sessions__r Order by CreatedDate ASC) FROM Animal__c WHERE ID IN: animalsIds];
            for(Animal__c animal: listAnimals){
                if(animal.Treatment_Sessions__r.size()>0){
                    animal.Treatment_Start_Date__c = Date.newinstance(animal.Treatment_Sessions__r[0].CreatedDate.year(), animal.Treatment_Sessions__r[0].CreatedDate.month(), animal.Treatment_Sessions__r[0].CreatedDate.day());
                    animal.Days_in_Treatment__c=animal.Treatment_Sessions__r.size();
                    listOfAnimals.add(animal);
                }
            }
            if(listOfAnimals.size()>0){
                update listOfAnimals;
			  }
        }

    }
    public void afterDelete (TriggerRequest request)  {
        System.debug('TREATMENT SESSION ROLLUP BEFORE INSERT IS EXECUTING');
        List<Treatment_Session__c> newRecords =  request.newRecords;
        List<Treatment_Session__c> oldRecords =  request.oldRecords;
        set<id> animalsIds = new Set<id>();
        List<Animal__c> listOfAnimals = new List<Animal__c>();
        
        for(Treatment_Session__c ts: oldRecords){
            if(ts.Animal__c!=null){
                animalsIds.add(ts.Animal__c);
            }
           if(!animalsIds.isEmpty()){
            List<Animal__c> listAnimals = [Select id, Name, Days_in_Treatment__c, (Select id from Treatment_Sessions__r) FROM Animal__c WHERE ID IN: animalsIds];
            for(Animal__c animal: listAnimals){
                if(animal.Treatment_Sessions__r.size()>0){
                    Animal__c obj = new Animal__c();
                    obj.id=animal.id;
                    obj.Days_in_Treatment__c=animal.Treatment_Sessions__r.size();
                    listOfAnimals.add(obj);
                }
            }
            if(listOfAnimals.size()>0){
                update listOfAnimals;
			  }
        }
        }                                   
                                                      
                                                      
                                                      
                                                      
                                                      }

}