force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name__c</fullName>
    <externalId>true</externalId>
    <label>ASPCA Animal Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Name_Id__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name_Id__c</fullName>
    <formula>Animal_Name__c + &apos; (&apos; +  Name + &apos;)&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animal Name/Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Behavior Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Behavior Case Worker)</relationshipLabel>
    <relationshipName>Beh_Case_Worker_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Summary_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Summary_Change_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Placement Summary Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <label>Current Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Enrichment_Priority__c.field-meta.xml
<CustomField>
    <fullName>Enrichment_Priority__c</fullName>
    <formula>TEXT(Treatment_Plan__r.Enrichment_Priority__c)</formula>
    <label>Enrichment Priority</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Meets_Adoptability_Date__c.field-meta.xml
<CustomField>
    <fullName>Meets_Adoptability_Date__c</fullName>
    <label>Meets Adoptability Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Play_Pause__c.field-meta.xml
<CustomField>
    <fullName>Play_Pause__c</fullName>
    <label>Play-Pause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Playgroup_Priority_Level__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Priority_Level__c</fullName>
    <label>Playgroup Priority Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily – 7 days</fullName>
            </value>
            <value>
                <fullName>High – 4 days</fullName>
            </value>
            <value>
                <fullName>Low – 2 days</fullName>
            </value>
            <value>
                <fullName>No Priority</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Shelter_Color_Coding__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Color_Coding__c</fullName>
    <inlineHelpText>Shelter handling color code for the animal</inlineHelpText>
    <label>Shelter Color Coding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shelter_Color_Coding</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Play_Pause__c/Play_Pause__c.object-meta.xml
<CustomObject>
    <label>Play Pause</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Play Pause #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Play Pauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Play_Pause__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalshelters__Animal__c</referenceTo>
    <relationshipLabel>Play Pauses</relationshipLabel>
    <relationshipName>Play_Pauses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Play_Pause__c/fields/End_Play_Pause__c.field-meta.xml
<CustomField>
    <fullName>End_Play_Pause__c</fullName>
    <defaultValue>false</defaultValue>
    <label>End Play Pause</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Enrichment_Priority__c.field-meta.xml
<CustomField>
    <fullName>Enrichment_Priority__c</fullName>
    <label>Enrichment Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily – 7 days</fullName>
            </value>
            <value>
                <fullName>High – 5 days</fullName>
            </value>
            <value>
                <fullName>Low – 3 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Treatment_Priority__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Priority__c</fullName>
    <label>Treatment Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Treatment</fullName>
                <default>true</default>
                <label>No Treatment</label>
            </value>
            <value>
                <fullName>Daily – 7 days</fullName>
            </value>
            <value>
                <fullName>High – 5 days</fullName>
            </value>
            <value>
                <fullName>Medium – 4 days</fullName>
            </value>
            <value>
                <fullName>Low – 3 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CRCAnimalDogListController.cls
public class CRCAnimalDogListController {
	@AuraEnabled
    public static List<Treatment_Plan__c> getRecords() {
        List<Treatment_Plan__c> objs = [SELECT Animal__c, Treatment_Priority__c, Enrichment_Priority__c, 
                Animal__r.Shelter_Color_Coding__c, Animal__r.Behavior_Summary_Change_Date__c,
                Animal__r.Name, Animal__r.Animal_Name__c, Animal__r.Animal_Name_Id__c,
                Animal__r.Meets_Adoptability_Date__c, Animal__r.Playgroup_Priority_Level__c, Animal__r.Current_Location__c,
                Animal__r.Behavior_Case_Worker__c, Animal__r.Behavior_Case_Worker__r.Name from Treatment_Plan__c 
                WHERE IsActive__c = true 
                AND Animal__r.Current_Location__c like '%CRC%'
                AND Animal__c IN (Select Animal__c from Play_Pause__c where End_Play_Pause__c != true) ];
        
        List<Treatment_Plan__c> objList = new List<Treatment_Plan__c>();
        for(Treatment_Plan__c obj : objs){
            if(obj.Animal__r != null && obj.Animal__r.Current_Location__c.containsIgnoreCase('CRC')){
                objList.add(obj);
            }
        }
        return objList;
    }
    
    @AuraEnabled
    public static String saveRecords(String recsString) {
        System.debug(recsString);
        List<Treatment_Plan__c> treatmentPlanList = (List<Treatment_Plan__c>) JSON.deserialize(recsString, List<Treatment_Plan__c>.class);
        List<Animal__c> animalList = new List<Animal__c>();
        for(Treatment_Plan__c plan: treatmentPlanList){
            animalList.add(plan.Animal__r);
        }
        
        update treatmentPlanList;
        update animalList;
        return 'success';
    }
}