force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Enrichment__c/Daily_Enrichment__c.object-meta.xml
<CustomObject>
    <label>Daily Enrichment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Daily Enrichment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Enrichment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Enrichment__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Daily Enrichment</relationshipLabel>
    <relationshipName>Daily_Enrichment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Observation__c/Observation__c.object-meta.xml
<CustomObject>
    <label>Observation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Observation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Observations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Observation__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Observations</relationshipLabel>
    <relationshipName>Observations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Observation__c/fields/Daily_Enrichment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Enrichment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Enrichment</label>
    <referenceTo>Daily_Enrichment__c</referenceTo>
    <relationshipLabel>Observations</relationshipLabel>
    <relationshipName>Observations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Observation__c/fields/Observation_Date__c.field-meta.xml
<CustomField>
    <fullName>Observation_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Observation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Observation__c/fields/Observation_Notes__c.field-meta.xml
<CustomField>
    <fullName>Observation_Notes__c</fullName>
    <label>Observation Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Observation__c/fields/Observation_Reported_By__c.field-meta.xml
<CustomField>
    <fullName>Observation_Reported_By__c</fullName>
    <label>Observation Reported By</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Observation__c/fields/Observation_Type__c.field-meta.xml
<CustomField>
    <fullName>Observation_Type__c</fullName>
    <label>Observation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Observation</fullName>
            </value>
            <value>
                <fullName>Happy Tale</fullName>
            </value>
            <value>
                <fullName>Concern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ObservationController.cls
public with sharing class ObservationController {
    @AuraEnabled (cacheable=true)
    public static Observation__c[] getObservations(Id recordId, String observationType, Integer count){
        System.debug('in getObservations');
        System.debug('recordId: ' + recordId);
        System.debug('observationType: ' + observationType);
        try {
            String query = 'SELECT Id, Animal__c, Daily_Enrichment__c, Observation_Date__c, Observation_Notes__c, Observation_Reported_By__c, Observation_Type__c ' +
                'FROM Observation__c WHERE Animal__c =: recordId AND Observation_Type__c =: observationType ORDER BY CreatedDate DESC';
            if(count != null){
                query += ' LIMIT : count';
            }
            
            Observation__c[] observations = database.query(query);

            System.debug('observations: ' + observations);
            return !observations.isEmpty() ? observations : null;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}