force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Play_Category__c.field-meta.xml
<CustomField>
    <fullName>Play_Category__c</fullName>
    <label>Play Category</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/test/test_PlaygroupToDoPdfController.cls
@isTest
public class test_PlaygroupToDoPdfController {
    @isTest
    static void getToDoPdf() {
        Animal__c a = TestDataFactory.createAnimal();
        a.Play_Category__c = 'Small Mellow';
        update a;

        PageReference toDoPdf = Page.PlaygroupToDoPdf;
        toDoPdf.getParameters().put('location', 'MRC');
        Test.setCurrentPage(toDoPdf);

        Test.startTest();
        PlaygroupToDoPdfController controller = new PlaygroupToDoPdfController();
        List<Animal__c> animals = controller.getAnimals();
        Test.stopTest();
        
        System.assertEquals(1, animals.size());
    }
}