force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Behavior_Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Behavior Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Behavior Case Worker)</relationshipLabel>
    <relationshipName>Beh_Case_Worker_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Recent_Shelter_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Recent_Shelter_Location__c</fullName>
    <label>Current/Recent Shelter Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <scale>15</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Animal__c/recordTypes/Behavior.recordType-meta.xml
<RecordType>
    <fullName>Behavior</fullName>
    <active>true</active>
    <label>Behavior</label>
</RecordType>

force-app/main/default/objects/Calendar_Schedule_Config__mdt/Calendar_Schedule_Config__mdt.object-meta.xml
<CustomObject>
    <description>Used to auto schedule items</description>
    <label>Calendar Schedule Config</label>
    <pluralLabel>Calendar Schedule Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Calendar_Schedule_Config__mdt/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Foster - Weekly</fullName>
            </value>
            <value>
                <fullName>Foster - Every Other Week</fullName>
            </value>
            <value>
                <fullName>Foster - Every Three Weeks</fullName>
            </value>
            <value>
                <fullName>Foster - Monthly</fullName>
            </value>
            <value>
                <fullName>Foster - Every Other Month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Calendar_Schedule_Config__mdt/fields/Population__c.field-meta.xml
<CustomField>
    <fullName>Population__c</fullName>
    <label>Population</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CRC</fullName>
                <default>true</default>
                <label>CRC</label>
            </value>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>Foster - All</fullName>
            </value>
            <value>
                <fullName>Board And Train All</fullName>
            </value>
            <value>
                <fullName>CARE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Calendar_Schedule_Config__mdt/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <label>Task Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Treatment</fullName>
                <default>true</default>
                <label>Treatment</label>
            </value>
            <value>
                <fullName>Playgroup</fullName>
            </value>
            <value>
                <fullName>Foster</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Citizen</fullName>
            </value>
            <value>
                <fullName>Agency Representative</fullName>
            </value>
            <value>
                <fullName>Animal Control Officer</fullName>
            </value>
            <value>
                <fullName>Animal Owner</fullName>
            </value>
            <value>
                <fullName>Animal Rescue</fullName>
            </value>
            <value>
                <fullName>Animal Welfare Professional</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Code Enforcement Officer</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>County/Civil Attorney</fullName>
            </value>
            <value>
                <fullName>Defense Attorney</fullName>
            </value>
            <value>
                <fullName>Law Enforcement Contact</fullName>
            </value>
            <value>
                <fullName>Law Enforcement Officer</fullName>
            </value>
            <value>
                <fullName>Local Elected Official</fullName>
            </value>
            <value>
                <fullName>Officer/Complainant</fullName>
            </value>
            <value>
                <fullName>Prosecuting Attorney</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
            <value>
                <fullName>Senator</fullName>
            </value>
            <value>
                <fullName>Shelter Contact</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>State Representative</fullName>
            </value>
            <value>
                <fullName>State Senator</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Suspect</fullName>
            </value>
            <value>
                <fullName>US Representative</fullName>
            </value>
            <value>
                <fullName>US Senator</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Relocation Driver</fullName>
            </value>
            <value>
                <fullName>Behavior Case Worker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Generic_Contact__c.field-meta.xml
<CustomField>
    <fullName>Is_Generic_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Generic Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>What user will this Contact log into Salesforce ass</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/Facility_Outcome__c.object-meta.xml
<CustomObject>
    <label>Facility/Outcome</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>F/O #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facilities/Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility_Outcome__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipName>Animal_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Facility_or_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Facility_or_Outcome__c</fullName>
    <label>Facility or Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility</fullName>
            </value>
            <value>
                <fullName>Outcome</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Facility_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Facility_Outcome__c</fullName>
    <label>Facility/Outcome</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Facility_or_Outcome__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAH</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Adoption Center</fullName>
            </value>
            <value>
                <fullName>Adoption Center (Temp Boarding)</fullName>
            </value>
            <value>
                <fullName>Animal Hospital</fullName>
            </value>
            <value>
                <fullName>Animal Shelter</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>ASNA</fullName>
            </value>
            <value>
                <fullName>ASPCA Shelter</fullName>
            </value>
            <value>
                <fullName>Board and Train</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>BRC</fullName>
            </value>
            <value>
                <fullName>Bronx CVC</fullName>
            </value>
            <value>
                <fullName>Brooklyn CVC</fullName>
            </value>
            <value>
                <fullName>CARE</fullName>
            </value>
            <value>
                <fullName>Clinic</fullName>
            </value>
            <value>
                <fullName>Community Medicine</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
            <value>
                <fullName>CRC-MRC</fullName>
            </value>
            <value>
                <fullName>Cremation</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Euthanized</fullName>
            </value>
            <value>
                <fullName>Field Temp Shelter</fullName>
            </value>
            <value>
                <fullName>Foster-Based Rescue</fullName>
            </value>
            <value>
                <fullName>Foster Home</fullName>
            </value>
            <value>
                <fullName>Foster Home - Adoption Center</fullName>
            </value>
            <value>
                <fullName>Foster Home - ARC</fullName>
            </value>
            <value>
                <fullName>Foster Home - CARE</fullName>
            </value>
            <value>
                <fullName>Hound Hotel</fullName>
            </value>
            <value>
                <fullName>Kitten Nursery</fullName>
            </value>
            <value>
                <fullName>MRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Follow_Up_Days__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Days__c</fullName>
    <inlineHelpText>If left blank the default follow up schedule will apply</inlineHelpText>
    <label>Follow Up Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Scheduling_Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Follow_Up_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Frequency__c</fullName>
    <label>Follow Up Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every Other Week</fullName>
            </value>
            <value>
                <fullName>Every Three Weeks</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Every Other Month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ARC/CARE</fullName>
            </value>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Scheduling_Days.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Monday</fullName>
    </customValue>
    <customValue>
        <fullName>Tuesday</fullName>
    </customValue>
    <customValue>
        <fullName>Wednesday</fullName>
    </customValue>
    <customValue>
        <fullName>Thursday</fullName>
    </customValue>
    <customValue>
        <fullName>Friday</fullName>
    </customValue>
    <customValue>
        <fullName>Saturday</fullName>
    </customValue>
    <customValue>
        <fullName>Sunday</fullName>
    </customValue>
    <masterLabel>Scheduling Days</masterLabel>
</GlobalValueSet>

force-app/main/default/test/test_ScheduleBoardAndTrainTask.cls
@isTest
private class test_ScheduleBoardAndTrainTask {
    @TestSetup
    static void testSetup(){
        Animal__c animal1 = TestDataFactory.createAnimalWithName('test1');
        Animal__c animal2 = TestDataFactory.createAnimalWithName('test2');
        
        // User u = [SELECT Id FROM User Where Profile.Name = 'System Administrator' AND isActive = true LIMIT 1];
        // User u2 = [SELECT Id FROM User Where Division = 'MRC' AND isActive = true LIMIT 1];

        User[] userList = TestDataFactory.createUsersWithoutInserting(2);
        User u = userList[0];
        u.Location__c = 'All';

        User u2 = userList[1];
        u2.Location__c = 'CRC/MRC';

        insert userList;


        Contact con = TestDataFactory.createContact();
        con.User__c = u.Id;
        con.Contact_Type__c = 'Behavior Case Worker';
        con.Email = 'testEmail@testEmail.com';
        update con;

        Contact genericContact = new Contact(
            LastName = 'generic',
            Is_Generic_Contact__c = true,
            User__c = u2.Id
        );
        insert genericContact;

        animal1.Behavior_Case_Worker__c = con.Id;
        animal2.Behavior_Case_Worker__c = con.Id;
        update new Animal__c[]{animal1, animal2};

        Facility_Outcome__c loc1 = new Facility_Outcome__c(
            Animal__c = animal1.Id,
            Facility_or_Outcome__c = 'Facility',
            Facility_Outcome__c = 'Board and Train'
        );
        Facility_Outcome__c loc2 = new Facility_Outcome__c(
            Animal__c = animal2.Id,
            Facility_or_Outcome__c = 'Facility',
            Facility_Outcome__c = 'Board and Train'
        );
        insert new Facility_Outcome__c[]{loc1, loc2};
        
    }

    @isTest
    static void scheduleFollowups_success() {
        test.startTest();
            Task[] toInsert = ScheduleBoardAndTrainTask.scheduleFollowUps(null);
        test.stopTest();

        //one task for each animal should be created
        Map<Id, Task[]> taskMap = new Map<Id, Task[]>();
        for(Task t : toInsert){
            if(taskMap.containsKey(t.Animal__c)){
                taskMap.get(t.Animal__c).add(t);
            }
            else {
                taskMap.put(t.Animal__c, new Task[]{t});
            }
        }
        System.debug('taskMap = ' + taskMap);

        /*
        this assert loop takes into account the number of days on the custom meta data records may change.
        it also takes into account the day of the week the test is ran to make sure only those tasks need through the
        following tuesday are created
        */
        
        Facility_Outcome__c[] locs = [SELECT Id, Animal__c, Animal__r.Current_Recent_Shelter_Location__c, Follow_Up_Days__c, Follow_Up_Frequency__c FROM Facility_Outcome__c];
        for(Facility_Outcome__c loc : locs){
            Integer count = taskCount(loc);
            System.debug('count = ' + count);
            if(taskMap.containsKey(loc.Animal__c)){
                System.assertEquals(count, taskMap.get(loc.Animal__c).size());
            }
            else {
                System.assertEquals(0, count);
            }
        }
    }

    @isTest
    static void scheduleFollowups_withExistingTask() {
        Id recordTypeId = Util.getRecordTypeId('Task',AutoScheduleTasksUtil.BOARD_AND_TRAIN_RECORD_TYPE_NAME);
        Task[] existingTasks = new Task[0];
        for(Animal__c anim : [SELECT Id FROM Animal__c]){
            Task t = new Task(
                recordTypeId = recordTypeId,
                Animal__c = anim.Id,
                ActivityDate = date.today().addDays(-7)
            );
            existingTasks.add(t);
        }

        insert existingTasks;
        test.startTest();
            Task[] toInsert = ScheduleBoardAndTrainTask.scheduleFollowUps(null);
        test.stopTest();

        //with default frequency new tasks should still be created for each animal
        Map<Id, Task[]> taskMap = new Map<Id, Task[]>();
        for(Task t : toInsert){
            if(taskMap.containsKey(t.Animal__c)){
                taskMap.get(t.Animal__c).add(t);
            }
            else {
                taskMap.put(t.Animal__c, new Task[]{t});
            }
        }
        System.debug('taskMap = ' + taskMap);

        /*
        this assert loop takes into account the number of days on the custom meta data records may change.
        it also takes into account the day of the week the test is ran to make sure only those tasks need through the
        following tuesday are created
        */

        Facility_Outcome__c[] locs = [SELECT Id, Animal__c, Animal__r.Current_Recent_Shelter_Location__c, Follow_Up_Days__c, Follow_Up_Frequency__c FROM Facility_Outcome__c];
        for(Facility_Outcome__c loc : locs){
            Integer count = taskCount(loc);
            System.debug('count = ' + count);
            if(taskMap.containsKey(loc.Animal__c)){
                System.assertEquals(count, taskMap.get(loc.Animal__c).size());
            }
            else {
                System.assertEquals(0, count);
            }
        }
    }

    @isTest
    static void scheduleFollowups_customSchedule() {
        Facility_Outcome__c[] locs = [SELECT Id, Animal__c, Animal__r.Current_Recent_Shelter_Location__c, Follow_Up_Days__c, Follow_Up_Frequency__c FROM Facility_Outcome__c];
        locs[0].Follow_Up_Days__c = 'Wednesday;Friday';
        locs[1].Follow_Up_Frequency__c = 'Every Other Week';

        update locs;

        test.startTest();
            Task[] toInsert = ScheduleBoardAndTrainTask.scheduleFollowUps(null);
        test.stopTest();

        //two tasks for locs[0] and one task for locs[1]
        Map<Id, Task[]> taskMap = new Map<Id, Task[]>();
        for(Task t : toInsert){
            if(taskMap.containsKey(t.Animal__c)){
                taskMap.get(t.Animal__c).add(t);
            }
            else {
                taskMap.put(t.Animal__c, new Task[]{t});
            }
        }
        System.debug('taskMap = ' + taskMap);

        /*
        * the first check takes into account the number of days on the custom meta data records may change.
        * it also takes into account the day of the week the test is ran to make sure only those tasks needed through the
        * following tuesday are created
        */
        Integer count = taskCount(locs[0]);
        System.assertEquals(count, taskMap.get(locs[0].Animal__c).size());

        //because the follow up frequency for this loc is set to every other week a task should not be created at this time
        System.assert(!taskMap.containsKey(locs[1].Animal__c), 'taskMap should not have contained tasks for this animal, instead was: ' + taskMap.get(locs[1].Animal__c));
    }

    @isTest
    static void scheduleFollowups_customScheduleWithExistingTasks() {
        Facility_Outcome__c[] locs = [SELECT Id, Animal__c, Animal__r.Current_Recent_Shelter_Location__c, Follow_Up_Days__c, Follow_Up_Frequency__c FROM Facility_Outcome__c];
        locs[0].Follow_Up_Days__c = 'Wednesday;Friday';
        locs[0].Follow_Up_Frequency__c = 'Every Other Week';
        locs[1].Follow_Up_Days__c = 'Wednesday;Friday';
        locs[1].Follow_Up_Frequency__c = 'Every Other Week';
        update locs;

        Id recordTypeId = Util.getRecordTypeId('Task',AutoScheduleTasksUtil.BOARD_AND_TRAIN_RECORD_TYPE_NAME);
        Task[] existingTasks = new Task[0];
        Animal__c[] animals = [SELECT Id FROM Animal__c];

        Task t1 = new Task(
            recordTypeId = recordTypeId,
            Animal__c = animals[0].Id,
            WhatId = locs[0].Id,
            ActivityDate = date.today().addDays(-8),
            Subject = 'Board and Train Follow Up'
        );
        existingTasks.add(t1);

        Task t2 = new Task(
            recordTypeId = recordTypeId,
            Animal__c = animals[1].Id,
            WhatId = locs[1].Id,
            ActivityDate = date.today().addDays(2),
            Subject = 'Board and Train Follow Up'
        );
        existingTasks.add(t2);

        insert existingTasks;

        test.startTest();
            Task[] toInsert = ScheduleBoardAndTrainTask.scheduleFollowUps(null);
        test.stopTest();

        Map<Id, Task[]> taskMap = new Map<Id, Task[]>();
        for(Task t : toInsert){
            if(taskMap.containsKey(t.Animal__c)){
                taskMap.get(t.Animal__c).add(t);
            }
            else {
                taskMap.put(t.Animal__c, new Task[]{t});
            }
        }

        Integer count = taskCount(locs[0]);
        System.assertEquals(count, taskMap.get(locs[0].Animal__c).size());
        System.assert(!taskMap.containsKey(locs[1].Animal__c), 'Task should not have been created for this animal since the last task is less than a week old');
    }

    @isTest
    static void scheduleFollowupsSpecificDog_success() {
        Animal__c dog = [SELECT Id FROM Animal__c LIMIT 1];
        test.startTest();
            Task[] toInsert = ScheduleBoardAndTrainTask.scheduleFollowUps(new Id[]{dog.Id});
        test.stopTest();

        System.debug('toInsert: ' + toInsert);

        Map<Id, Task[]> taskMap = new Map<Id, Task[]>();
        for(Task t : toInsert){
            if(taskMap.containsKey(t.Animal__c)){
                taskMap.get(t.Animal__c).add(t);
            }
            else {
                taskMap.put(t.Animal__c, new Task[]{t});
            }
        }
        System.debug('taskMap = ' + taskMap);

        /*
        * this assert loop takes into account the number of days on the custom meta data records may change.
        * it also takes into account the day of the week the test is ran to make sure only those tasks need through the
        * following tuesday are created
        */
        
        Facility_Outcome__c[] locs = [SELECT Id, Animal__c, Animal__r.Current_Recent_Shelter_Location__c, Follow_Up_Days__c, Follow_Up_Frequency__c FROM Facility_Outcome__c];
        for(Facility_Outcome__c loc : locs){
            if(loc.Animal__c == dog.Id){
                system.debug('this is the dog');
                Integer count = taskCount(loc);
                System.assertEquals(count, taskMap.get(loc.Animal__c).size());
            }
            else {
                system.assert(!taskMap.containsKey(loc.Animal__c));
            }
        }
    }

    //need to calculate the number of tasks needed from today through tuesday
    private static Integer taskCount(Facility_Outcome__c loc){
        Date[] dateList = new Date[0];
        if(loc.Follow_Up_Days__c != null){
            dateList = AutoScheduleTasksUtil.getDateList(loc.Follow_Up_Days__c);
        } else {
            Calendar_Schedule_Config__mdt config = [
                SELECT Frequency__c, Population__c, Monday__c, Tuesday__c, Wednesday__c, Thursday__c, Friday__c, Saturday__c, Sunday__c
                FROM Calendar_Schedule_Config__mdt 
                WHERE Task_Type__c = 'Board And Train'
            ];

            dateList = AutoScheduleTasksUtil.getDateList(config);
        }

        return !dateList.isEmpty() ? dateList.size() : 0;
    }    
}