force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Discharged_to_Contact__c.field-meta.xml
<CustomField>
    <fullName>Discharged_to_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discharged to Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Discharged to Contact)</relationshipLabel>
    <relationshipName>Animals1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/test/AnimalTriggerTest.cls
@isTest
public class AnimalTriggerTest {

    static testMethod void validateAnimalTrigger(){
        
/*        Case cs = new Case();
        insert cs;
        
        Contact con = new Contact(LastName='Test', MailingCity='Test', MailingState='AK',County__c='Test');
        insert con;
        
        Contact con2 = new Contact(LastName='Test2', MailingCity='Test2', MailingState='AK',County__c='Test2');
        insert con2;
        
        Animal__c anim = new Animal__c(Name='Test', Case__c=cs.Id, Discharged_to_Contact__c=con.Id);
        
        insert anim;
      
        Test.setMock(HttpCalloutMock.class, new MockHttpCallout());
        Test.startTest();
        AnimalTriggerHandler.reverseGeoloc(40.75335663830957,-73.99213560828238, anim.Id);
        Test.stopTest();

        List<CaseContactRole> ccr = [SELECT Id, CasesId, ContactId, Role FROM CaseContactRole WHERE CasesId =: cs.Id AND ContactId =: con.Id AND Role='Animal Discharge Contact'];
        System.assertEquals(ccr.size(), 1);
        
        anim.Discharged_to_Contact__c=con2.Id;
        update anim;
        
        List<CaseContactRole> ccr2 = [SELECT Id, CasesId, ContactId, Role FROM CaseContactRole WHERE CasesId =: cs.Id AND ContactId =: con2.Id AND Role='Animal Discharge Contact'];
        System.assertEquals(ccr2.size(), 1);*/
        
    }
    

    
    
}