force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Name_Id__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name_Id__c</fullName>
    <formula>Animal_Name__c + &apos; (&apos; +  Name + &apos;)&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animal Name/Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Behavior Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Behavior Case Worker)</relationshipLabel>
    <relationshipName>Beh_Case_Worker_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <label>Current Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Recent_Shelter_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Recent_Shelter_Location__c</fullName>
    <label>Current/Recent Shelter Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Playgroup_Priority_Level__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Priority_Level__c</fullName>
    <label>Playgroup Priority Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily – 7 days</fullName>
            </value>
            <value>
                <fullName>High – 4 days</fullName>
            </value>
            <value>
                <fullName>Low – 2 days</fullName>
            </value>
            <value>
                <fullName>No Priority</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Shelter_Location2__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Location2__c</fullName>
    <label>Shelter Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ohio Shelter - 3900 Groves Rd</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
            <value>
                <fullName>ARC and CARE</fullName>
                <isActive>false</isActive>
                <label>ARC and CARE</label>
            </value>
            <value>
                <fullName>BRC</fullName>
                <isActive>false</isActive>
                <label>BRC</label>
            </value>
            <value>
                <fullName>Foster</fullName>
                <isActive>false</isActive>
                <label>Foster</label>
            </value>
            <value>
                <fullName>MRC</fullName>
                <isActive>false</isActive>
                <label>MRC</label>
            </value>
            <value>
                <fullName>MRC - CRC</fullName>
                <isActive>false</isActive>
                <label>MRC - CRC</label>
            </value>
            <value>
                <fullName>Marysville</fullName>
                <isActive>false</isActive>
                <label>Marysville</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Calendar_Schedule_Config__mdt/Calendar_Schedule_Config__mdt.object-meta.xml
<CustomObject>
    <description>Used to auto schedule items</description>
    <label>Calendar Schedule Config</label>
    <pluralLabel>Calendar Schedule Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Calendar_Schedule_Config__mdt/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Foster - Weekly</fullName>
            </value>
            <value>
                <fullName>Foster - Every Other Week</fullName>
            </value>
            <value>
                <fullName>Foster - Every Three Weeks</fullName>
            </value>
            <value>
                <fullName>Foster - Monthly</fullName>
            </value>
            <value>
                <fullName>Foster - Every Other Month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Calendar_Schedule_Config__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Calendar_Schedule_Config__mdt/fields/Population__c.field-meta.xml
<CustomField>
    <fullName>Population__c</fullName>
    <label>Population</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CRC</fullName>
                <default>true</default>
                <label>CRC</label>
            </value>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>Foster - All</fullName>
            </value>
            <value>
                <fullName>Board And Train All</fullName>
            </value>
            <value>
                <fullName>CARE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Calendar_Schedule_Config__mdt/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <label>Task Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Treatment</fullName>
                <default>true</default>
                <label>Treatment</label>
            </value>
            <value>
                <fullName>Playgroup</fullName>
            </value>
            <value>
                <fullName>Foster</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Playgroup.recordType-meta.xml
<RecordType>
    <fullName>Playgroup</fullName>
    <active>true</active>
    <description>Task created to show a playgroup is needed that day</description>
    <label>Playgroup</label>
</RecordType>

force-app/main/default/classes/AutoScheduleController.cls
public with sharing class AutoScheduleController {
    public static void handleScheduleTasks(){
        scheduleAnimalPlaygroups();
    }

    private static void scheduleAnimalPlaygroups(){
        Task[] tasksToInsert = new Task[0];
        Map<String, Calendar_Schedule_Config__mdt> calendarConfigMap = getCalendarConfig('Playgroup');
        for(Animal__c animal : [
            SELECT Id, Playgroup_Priority_Level__c, Shelter_Location2__c, Animal_Name_Id__c, Current_Recent_Shelter_Location__c, Current_Location__c, Behavior_Case_Worker__r.Name
            FROM Animal__c 
            WHERE Playgroup_Priority_Level__c != null 
            AND Current_Recent_Shelter_Location__c IN ('MRC', 'CRC')
        ]){
            String configKey = animal.Current_Recent_Shelter_Location__c + '-' + animal.Playgroup_Priority_Level__c.split(' ')[0];
            if(calendarConfigMap.containsKey(configKey)){
                tasksToInsert.addAll(prepTasks(animal, calendarConfigMap.get(configKey), 'Playgroup'));
            }
        }
        insert tasksToInsert;
    }

    private static Map<String, Calendar_Schedule_Config__mdt> getCalendarConfig(String taskType){
        Map<String, Calendar_Schedule_Config__mdt> configMap = new Map<String, Calendar_Schedule_Config__mdt>();
        for(Calendar_Schedule_Config__mdt config : [
            SELECT Frequency__c, Population__c, Monday__c, Tuesday__c, Wednesday__c, Thursday__c, Friday__c, Saturday__c, Sunday__c
            FROM Calendar_Schedule_Config__mdt 
            WHERE Task_Type__c =: taskType 
            AND IsActive__c = true
        ]){
            configMap.put(config.Population__c + '-' + config.Frequency__c, config);
        }

        return configMap;
    }

    private static Task[] prepTasks(Animal__c animal, Calendar_Schedule_Config__mdt config, String taskType){
        Id taskRTId = [SELECT Id FROM RecordType WHERE SobjectType = 'Task' AND DeveloperName =: taskType LIMIT 1].Id;
        Task[] newTasks = new Task[0];
        Map<String, Date> dateMap = getDateMap(config);
        for(String day : dateMap.keySet()){
            Task newTask = new Task(
                WhatId = animal.Id,
                Animal__c = animal.Id,
                RecordTypeId = taskRTId,
                ActivityDate = dateMap.get(day),
                Description = 'Playgroup is needed for: ' + animal.Animal_Name_Id__c + ' (' + animal.Current_Recent_Shelter_Location__c + ')',
                IsReminderSet = true,
                Status = 'Not Started',
                WhoId = animal.Behavior_Case_Worker__c != null ? animal.Behavior_Case_Worker__c : '0030100000IdslhAAB',
                Subject = 'Playgroup',
                Assigned_Resources__c = animal.Animal_Name_Id__c + ';' + (animal.Behavior_Case_Worker__r.Name != null ? animal.Behavior_Case_Worker__r.Name : 'Dwight Schrute')

            );
            newTasks.add(newTask);
        }

        return newTasks;
    }

    private static Map<String, Date> getDateMap(Calendar_Schedule_Config__mdt config){
        Map<String, Date> dateMap = new Map<String, Date>();
        Date myDate = Date.today();
        Date weekStart = myDate.toStartofWeek().addDays(2);
        System.debug('weekStart = ' + weekStart);
        Map<String, Integer> dayOfWeekMap = dayOfWeekMap();
        for(String day : dayOfWeekMap.keySet()){
            if(config.get(day) == true){
                System.Debug('has Day: ' + day);
                System.Debug('date: ' + dayOfWeekMap.get(day));
                dateMap.put(day, weekStart.addDays(dayOfWeekMap.get(day)));
            }
        }
        return dateMap;
    }

    private static Map<String, Integer> dayOfWeekMap(){
        return new Map<String, Integer>{
            'Tuesday__c' => 0,
            'Wednesday__c' => 1,
            'Thursday__c' => 2,
            'Friday__c' => 3,
            'Saturday__c' => 4,
            'Sunday__c' => 5,
            'Monday__c' => 6
        };
    }
}