force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <scale>15</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Play_Category__c.field-meta.xml
<CustomField>
    <fullName>Play_Category__c</fullName>
    <label>Play Category</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Play_Pause__c.field-meta.xml
<CustomField>
    <fullName>Play_Pause__c</fullName>
    <label>Play-Pause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Shelter_Location2__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Location2__c</fullName>
    <label>Shelter Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ohio Shelter - 3900 Groves Rd</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
            <value>
                <fullName>ARC and CARE</fullName>
                <isActive>false</isActive>
                <label>ARC and CARE</label>
            </value>
            <value>
                <fullName>BRC</fullName>
                <isActive>false</isActive>
                <label>BRC</label>
            </value>
            <value>
                <fullName>Foster</fullName>
                <isActive>false</isActive>
                <label>Foster</label>
            </value>
            <value>
                <fullName>MRC</fullName>
                <isActive>false</isActive>
                <label>MRC</label>
            </value>
            <value>
                <fullName>MRC - CRC</fullName>
                <isActive>false</isActive>
                <label>MRC - CRC</label>
            </value>
            <value>
                <fullName>Marysville</fullName>
                <isActive>false</isActive>
                <label>Marysville</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/Animal_Playgroup__c.object-meta.xml
<CustomObject>
    <label>Animal Playgroup</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Animal Playgroup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Playgroups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Playgroup__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Playgroup_Session__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Session</label>
    <referenceTo>Playgroup_Session__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Play_Pause__c/Play_Pause__c.object-meta.xml
<CustomObject>
    <label>Play Pause</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Play Pause #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Play Pauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Play_Pause__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalshelters__Animal__c</referenceTo>
    <relationshipLabel>Play Pauses</relationshipLabel>
    <relationshipName>Play_Pauses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/Playgroup_Session__c.object-meta.xml
<CustomObject>
    <label>Playgroup Session</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroup Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup_Session__c/fields/Animal_Playgroup__c.field-meta.xml
<CustomField>
    <fullName>Animal_Playgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Playgroup</label>
    <referenceTo>Animal_Playgroup__c</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/fields/Playgroup_Leader__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/fields/Playgroup_Location__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Location__c</fullName>
    <label>Playgroup Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indoor Play Yard</fullName>
            </value>
            <value>
                <fullName>Outdoor Play Yard</fullName>
            </value>
            <value>
                <fullName>MRC Indoor Play Yard</fullName>
            </value>
            <value>
                <fullName>MRC Outdoor Play Yard</fullName>
            </value>
            <value>
                <fullName>Monster Park</fullName>
            </value>
            <value>
                <fullName>ARC Terrace</fullName>
            </value>
            <value>
                <fullName>SBR</fullName>
            </value>
            <value>
                <fullName>Playroom 1</fullName>
            </value>
            <value>
                <fullName>Playroom 2</fullName>
            </value>
            <value>
                <fullName>Playroom 1 &amp; 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ARC/CARE</fullName>
            </value>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/test_PlaygroupToDoListController.cls
@isTest
public with sharing class test_PlaygroupToDoListController {
    @isTest
    static void getPlaygroupAnimalsSuccess() {
        Animal__c a = TestDataFactory.createAnimal();
        a.Play_Category__c = 'Small Mellow';
        update a;

        User u = [SELECT Id, Location__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        u.Location__c = 'All';
        update u;
        
        Test.startTest();
        List<Animal__c> playgroupAnimals = PlaygroupToDoListController.getPlaygroupAnimals('MRC');
        Test.stopTest();

        List<Animal__c> animals = [SELECT Id, Shelter_Location2__c, Play_Category__c FROM Animal__c WHERE Id = :a.Id];
        System.assertEquals(1, playgroupAnimals.size());
        System.assertEquals(a.Id, playgroupAnimals[0].Id);
    }
    
    @isTest
    static void getReportId() {
        Test.startTest();
        Id getReportId = PlaygroupToDoListController.getReportId();
        Test.stopTest();
    }

    @isTest
    static void getPlaygroupAnimalsBadCategory() {
        Animal__c a = TestDataFactory.createAnimal();
        Test.startTest();
        List<Animal__c> playgroupAnimals = PlaygroupToDoListController.getPlaygroupAnimals('MRC');
        Test.stopTest();
        System.assertEquals(0, playgroupAnimals.size());
    }

    @isTest
    static void getPlaygroupAnimalsBehaviorPause() {
        Animal__c a = TestDataFactory.createAnimal();
        List<Play_Pause__c> playPauses = TestDataFactory.createPlayPauses(a);
        Test.startTest();
        List<Animal__c> playgroupAnimals = PlaygroupToDoListController.getPlaygroupAnimals('MRC');
        Test.stopTest();
        System.assertEquals(0, playgroupAnimals.size());
    }

    @isTest
    static void getPlaygroupAnimalsBadLocation() {
        Animal__c a = TestDataFactory.createAnimal();
        Test.startTest();
        List<Animal__c> playgroupAnimals = PlaygroupToDoListController.getPlaygroupAnimals('Not MRC');
        Test.stopTest();
        System.assertEquals(0, playgroupAnimals.size());
    }

    @isTest
    static void getPlaygroupAnimalsNoPlayCategory() {
        Animal__c a = TestDataFactory.createAnimal();
        a.Play_Category__c = null;
        update a;
        Test.startTest();
        List<Animal__c> playgroupAnimals = PlaygroupToDoListController.getPlaygroupAnimals('MRC');
        Test.stopTest();
        System.assertEquals(0, playgroupAnimals.size());
    }

    @isTest
    static void createPlaygroupSuccess() {
        Animal__c a = TestDataFactory.createAnimal();
        Test.startTest();
        String sessionId = PlaygroupToDoListController.createPlaygroup(new List<String>{a.Id});
        Test.stopTest();
        List<Animal_Playgroup__c> animalPlaygroups = [SELECT Id, Animal__c, Playgroup_Session__c FROM Animal_Playgroup__c WHERE Animal__c = :a.Id];
        System.assertEquals(1, animalPlaygroups.size());
        System.assertEquals(a.Id, animalPlaygroups[0].Animal__c);
        System.assertEquals(sessionId, animalPlaygroups[0].Playgroup_Session__c);
    }

    @isTest
    static void createPlaygroupBadAnimals() {
        Animal__c a = TestDataFactory.createAnimal();
        List<String> animals = new List<String>{a.Id};
        delete a;
        Test.startTest();
        String sessionId = PlaygroupToDoListController.createPlaygroup(animals);
        Test.stopTest();
        System.assertEquals('Error creating animal playgroups', sessionId);
    }

    @isTest
    static void copyPlaygroupSessionSuccess() {
        Playgroup_Session__c playSession = TestDataFactory.createPlaygroupSessionWithAnimals();
        Animal__c a = [SELECT Id FROM Animal__c LIMIT 1];
        Test.startTest();
        Id sessionId = PlaygroupToDoListController.copyPlaygroupSession(playSession.Id, new List<Id>{a.Id});
        Test.stopTest();
        Playgroup_Session__c copiedSession = [SELECT Id, Playgroup_Location__c, Playgroup_Leader__c, (SELECT Id FROM Animal_Playgroups__r) FROM Playgroup_Session__c WHERE Id = :sessionId LIMIT 1];
        System.assertEquals(playSession.Playgroup_Location__c, copiedSession.Playgroup_Location__c);
        System.assertEquals(playSession.Playgroup_Leader__c, copiedSession.Playgroup_Leader__c);
        System.assertEquals(1, copiedSession.Animal_Playgroups__r.size());
    }

    @isTest
    static void copyPlaygroupSessionError() {
        Playgroup_Session__c playSession = TestDataFactory.createPlaygroupSessionWithAnimals();
        Animal__c a = [SELECT Id FROM Animal__c LIMIT 1];
        List<Id> animalIds = new List<Id>{a.Id};
        delete a;
        Test.startTest();
        String errorMsg;
        try {
            Id sessionId = PlaygroupToDoListController.copyPlaygroupSession(playSession.Id, animalIds);
        }
        catch (Exception ex) {
            errorMsg = ex.getMessage();
        }
        Test.stopTest();
        System.assert(!String.isEmpty(errorMsg));
    }

    @isTest
    static void editPlaygroupSessionSuccess() {
        Playgroup_Session__c playSession = TestDataFactory.createPlaygroupSessionWithAnimals();
        Animal__c a = [SELECT Id FROM Animal__c LIMIT 1];
        Animal__c b = TestDataFactory.createAnimalWithName('b');
        Test.startTest();
        Id sessionId = PlaygroupToDoListController.editPlaygroup(playSession.Id, new List<Id>{a.Id, b.Id});
        Test.stopTest();
        Playgroup_Session__c editSession = [SELECT Id, Playgroup_Location__c, Playgroup_Leader__c, (SELECT Id FROM Animal_Playgroups__r) FROM Playgroup_Session__c WHERE Id = :sessionId LIMIT 1];
        System.assertEquals(playSession.Playgroup_Location__c, editSession.Playgroup_Location__c);
        System.assertEquals(playSession.Playgroup_Leader__c, editSession.Playgroup_Leader__c);
        System.assertEquals(2, editSession.Animal_Playgroups__r.size());
    }
}