force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age Estimate at Intake</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Age_Estimate_at_Intake</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;Unspecified&quot;</defaultValue>
    <label>Primary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Primary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Type_of_Animal__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Animal__c</fullName>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Species</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/recordTypes/Behavior.recordType-meta.xml
<RecordType>
    <fullName>Behavior</fullName>
    <active>true</active>
    <label>Behavior</label>
</RecordType>

force-app/main/default/objects/Behavior_Evaluation__c/Behavior_Evaluation__c.object-meta.xml
<CustomObject>
    <label>Behavior Evaluation</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Behavior Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Behavior Evaluations</relationshipLabel>
    <relationshipName>Behavior_Evaluations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Behavior_in_Kennel__c.field-meta.xml
<CustomField>
    <fullName>Behavior_in_Kennel__c</fullName>
    <label>Behavior in Kennel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Not social</fullName>
            </value>
            <value>
                <fullName>Mildly fearful</fullName>
            </value>
            <value>
                <fullName>Excited</fullName>
            </value>
            <value>
                <fullName>Stereotypic behavior</fullName>
            </value>
            <value>
                <fullName>Hyperaroused</fullName>
            </value>
            <value>
                <fullName>Aggressive in cage only</fullName>
            </value>
            <value>
                <fullName>Extremely fearful</fullName>
            </value>
            <value>
                <fullName>Threatened</fullName>
            </value>
            <value>
                <fullName>Aggressive</fullName>
            </value>
            <value>
                <fullName>Moderately Fearful</fullName>
            </value>
            <value>
                <fullName>Did not approach the tester-Moderately fearful</fullName>
                <isActive>false</isActive>
                <label>Did not approach the tester-Moderately fearful</label>
            </value>
            <value>
                <fullName>Threatens</fullName>
                <isActive>false</isActive>
                <label>Threatens</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Comments_BOL__c.field-meta.xml
<CustomField>
    <fullName>Comments_BOL__c</fullName>
    <label>Comments BOL</label>
    <length>22768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Evaluation_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Subtype__c</fullName>
    <label>Evaluations</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Puppy</fullName>
            </value>
            <value>
                <fullName>Dog Fighting</fullName>
            </value>
            <value>
                <fullName>Adult Animal</fullName>
            </value>
            <value>
                <fullName>Fighting Dog Case</fullName>
                <isActive>false</isActive>
                <label>Fighting Dog Case</label>
            </value>
            <value>
                <fullName>Play Test P1</fullName>
                <isActive>false</isActive>
                <label>Play Test P1</label>
            </value>
            <value>
                <fullName>Play Test P2</fullName>
                <isActive>false</isActive>
                <label>Play Test P2</label>
            </value>
            <value>
                <fullName>Pleasant Touch Test</fullName>
                <isActive>false</isActive>
                <label>Pleasant Touch Test</label>
            </value>
            <value>
                <fullName>Social Test P1</fullName>
                <isActive>false</isActive>
                <label>Social Test P1</label>
            </value>
            <value>
                <fullName>Social Test P2</fullName>
                <isActive>false</isActive>
                <label>Social Test P2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Handler_Initials__c.field-meta.xml
<CustomField>
    <fullName>Handler_Initials__c</fullName>
    <label>Handler Name</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Puppy_Behavior_in_Kennel__c.field-meta.xml
<CustomField>
    <fullName>Puppy_Behavior_in_Kennel__c</fullName>
    <label>Puppy Behavior in Kennel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Not social</fullName>
            </value>
            <value>
                <fullName>Mildly fearful</fullName>
            </value>
            <value>
                <fullName>Excited</fullName>
            </value>
            <value>
                <fullName>Stereotypic behavior</fullName>
            </value>
            <value>
                <fullName>Hyperaroused</fullName>
            </value>
            <value>
                <fullName>Moderately Fearful</fullName>
            </value>
            <value>
                <fullName>Aggressive in cage only</fullName>
            </value>
            <value>
                <fullName>Extremely fearful</fullName>
            </value>
            <value>
                <fullName>Threatened tester</fullName>
            </value>
            <value>
                <fullName>Aggressive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Puppy_Resource_Guarding_P1_Push_Face__c.field-meta.xml
<CustomField>
    <fullName>Puppy_Resource_Guarding_P1_Push_Face__c</fullName>
    <label>Puppy Resource Guarding P1 - Push Face</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Puppy_Resource_Guarding_P1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Resource_Guarding_P1_Push_Face__c.field-meta.xml
<CustomField>
    <fullName>Resource_Guarding_P1_Push_Face__c</fullName>
    <label>Resource Guarding P1 - Push Face</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Resource_Guarding_P1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Scribe_Initials__c.field-meta.xml
<CustomField>
    <fullName>Scribe_Initials__c</fullName>
    <label>Scribe Name</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Skipped_BOL__c.field-meta.xml
<CustomField>
    <fullName>Skipped_BOL__c</fullName>
    <label>Skipped BOL</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skip_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Skipped_RG_P2_PF__c.field-meta.xml
<CustomField>
    <fullName>Skipped_RG_P2_PF__c</fullName>
    <label>Skipped RG P2 PF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skip_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Skipped_SB_P1__c.field-meta.xml
<CustomField>
    <fullName>Skipped_SB_P1__c</fullName>
    <label>Skipped SB P1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Skip_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Tag_Test__c.field-meta.xml
<CustomField>
    <fullName>Tag_Test__c</fullName>
    <label>Tag Test</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Played with tester</fullName>
            </value>
            <value>
                <fullName>Did not play but followed</fullName>
            </value>
            <value>
                <fullName>Watched tester-did not follow</fullName>
            </value>
            <value>
                <fullName>Unresponsive-distracted by environment</fullName>
            </value>
            <value>
                <fullName>Moderately fearful</fullName>
            </value>
            <value>
                <fullName>Highly aroused</fullName>
            </value>
            <value>
                <fullName>Extremely fearful</fullName>
            </value>
            <value>
                <fullName>Threatened</fullName>
            </value>
            <value>
                <fullName>Too fearful-subtest not done</fullName>
            </value>
            <value>
                <fullName>Became aggressive</fullName>
                <isActive>false</isActive>
                <label>Became aggressive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Tester_Initials__c.field-meta.xml
<CustomField>
    <fullName>Tester_Initials__c</fullName>
    <label>Tester Name</label>
    <length>55</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Age_Estimate_at_Intake.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Juvenile w/dam</fullName>
    </customValue>
    <customValue>
        <fullName>&lt; 6 months</fullName>
    </customValue>
    <customValue>
        <fullName>0-4 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-8 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>8-12 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>12-16 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 1 year</fullName>
    </customValue>
    <customValue>
        <fullName>1 year - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>2-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>5-7 years</fullName>
    </customValue>
    <customValue>
        <fullName>7-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>greater than 10 yrs</fullName>
    </customValue>
    <customValue>
        <fullName>Egg</fullName>
    </customValue>
    <customValue>
        <fullName>Chick: Up To 8 Weeks</fullName>
    </customValue>
    <customValue>
        <fullName>Pullet: Female &lt; 2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Adult: &gt;2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Stag: Male &lt;2YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (with dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (without dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Weanling</fullName>
    </customValue>
    <customValue>
        <fullName>Yearling</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>4-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>6-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>11-15 years</fullName>
    </customValue>
    <customValue>
        <fullName>15-20 years</fullName>
    </customValue>
    <customValue>
        <fullName>20+ years</fullName>
    </customValue>
    <customValue>
        <fullName>Chick (0-10 wks.)</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown At Intake</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
        <isActive>false</isActive>
        <label>Unknown</label>
    </customValue>
    <masterLabel>Age Estimate at Intake</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Primary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Bay roan</fullName>
    </customValue>
    <customValue>
        <fullName>Beige</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Blue roan</fullName>
    </customValue>
    <customValue>
        <fullName>Brindle</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Buckskin</fullName>
    </customValue>
    <customValue>
        <fullName>Buff</fullName>
    </customValue>
    <customValue>
        <fullName>Calico</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut/Sorrel</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Dun</fullName>
    </customValue>
    <customValue>
        <fullName>Fawn</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Grulla</fullName>
    </customValue>
    <customValue>
        <fullName>Hairless</fullName>
    </customValue>
    <customValue>
        <fullName>Liver chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Palomino</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Red roan</fullName>
    </customValue>
    <customValue>
        <fullName>Roan</fullName>
    </customValue>
    <customValue>
        <fullName>Seal</fullName>
    </customValue>
    <masterLabel>Primary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Puppy_Resource_Guarding_P1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Remained relaxed</fullName>
    </customValue>
    <customValue>
        <fullName>Left bowl to interact with tester</fullName>
    </customValue>
    <customValue>
        <fullName>Ate but seemed nervous</fullName>
    </customValue>
    <customValue>
        <fullName>Motivated to eat-not stiff/rigid</fullName>
    </customValue>
    <customValue>
        <fullName>Stopped eating-fearful</fullName>
    </customValue>
    <customValue>
        <fullName>Became stiff/rigid-no escalation</fullName>
    </customValue>
    <customValue>
        <fullName>Became stiff/rigid-threatened</fullName>
    </customValue>
    <customValue>
        <fullName>Became stiff/rigid—bit</fullName>
    </customValue>
    <customValue>
        <fullName>Too fearful</fullName>
    </customValue>
    <customValue>
        <fullName>Not interested</fullName>
    </customValue>
    <masterLabel>Puppy Resource Guarding P1</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Resource_Guarding_P1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Remained relaxed</fullName>
    </customValue>
    <customValue>
        <fullName>Left bowl to interact with tester</fullName>
    </customValue>
    <customValue>
        <fullName>Ate but seemed nervous</fullName>
    </customValue>
    <customValue>
        <fullName>Motivated to eat-not stiff/rigid</fullName>
    </customValue>
    <customValue>
        <fullName>Stopped eating-fearful</fullName>
    </customValue>
    <customValue>
        <fullName>Became stiff/rigid-no escalation</fullName>
    </customValue>
    <customValue>
        <fullName>Became stiff/rigid-threatened</fullName>
    </customValue>
    <customValue>
        <fullName>Became stiff/rigid—bit</fullName>
    </customValue>
    <customValue>
        <fullName>Too fearful</fullName>
    </customValue>
    <customValue>
        <fullName>Not interested</fullName>
    </customValue>
    <masterLabel>Resource Guarding P1</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Skip_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Skipped to safeguard welfare of the animal</fullName>
    </customValue>
    <customValue>
        <fullName>Skipped due to risk to the handler</fullName>
    </customValue>
    <customValue>
        <fullName>Skipped for medical reason</fullName>
    </customValue>
    <customValue>
        <fullName>Skipped due to not having an appropriate helper dog</fullName>
    </customValue>
    <customValue>
        <fullName>Skipped due to risk to the helper dog</fullName>
    </customValue>
    <customValue>
        <fullName>Skipped not necessary</fullName>
    </customValue>
    <masterLabel>Skip Reason</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Species.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avian</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Cow</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Equine</fullName>
    </customValue>
    <customValue>
        <fullName>Exotic</fullName>
    </customValue>
    <customValue>
        <fullName>Fowl</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <masterLabel>Species</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BehaviorEvaluationMatrixControllerTest.cls
@isTest
private class BehaviorEvaluationMatrixControllerTest{
    
    static testMethod void unitTest(){
        
        Case cs = new Case();
        insert cs;  
        
        Animal__c objAnimal = new Animal__c(Name='Test2846298359832', Case__c=cs.Id, Type_of_Animal__c = 'Dog', Gender__c = 'Unknown', Age__c = 'Unknown At Intake', Color__c = 'Black');
        insert objAnimal;
        
        Test.startTest();
        
        //Adult Animal Evaluation Test
        Behavior_Evaluation__c behEval = new Behavior_Evaluation__c(
            Animal__c = objAnimal.Id, 
            Evaluation_Subtype__c = 'Adult Animal', 
            Handler_Initials__c = 'TI', 
            Scribe_Initials__c = 'TI', 
            Tester_Initials__c = 'TI',
            Behavior_in_Kennel__c = 'Social;Hyperaroused', 
            Skipped_BOL__c = 'Skipped to safeguard welfare of the animal', 
            Skipped_SB_P1__c = 'Skipped not necessary', 
            Resource_Guarding_P1_Push_Face__c = 'Remained relaxed', 
            Comments_BOL__c='test test test', 
            Tag_Test__c='Too fearful-subtest not done', 
            Skipped_RG_P2_PF__c	= 'Skipped for medical reason'
        );
        insert behEval;
        
        PageReference pageRef = Page.BehaviorEvaluationMatrix;
        Test.setCurrentPage(pageRef);
        apexpages.currentpage().getparameters().put('Id' , behEval.id);
        
        
        
        BehaviorEvaluationMatrixController objBehMatrix  = new BehaviorEvaluationMatrixController (new ApexPages.StandardController(behEval));
        
		//Expected result:        
        //((Behavior in Kennel, ✔, ✔,  ,  ), (Behavior on Leash, ❌, ❌, ❌, ❌), (Social Behavior P1, ---, ---, ---, ---), (Resource Guarding P1 - PF, ✔,  ,  ,  ))
        
        System.assertEquals(5, objBehMatrix.finalTestAndDisplayValues.size());
        //system.debug(objBehMatrix.finalTestAndDisplayValues.size());
        
        //Dog Fighting Evaluation Test
        Behavior_Evaluation__c dogFightingBehEval = new Behavior_Evaluation__c(
            Animal__c = objAnimal.Id, 
            Evaluation_Subtype__c	= 'Dog Fighting', 
            Handler_Initials__c = 'TI', 
            Scribe_Initials__c = 'TI', 
            Tester_Initials__c = 'TI', 
            Behavior_in_Kennel__c = 'Social;Hyperaroused', 
            Skipped_BOL__c = 'Skipped to safeguard welfare of the animal', 
            Skipped_SB_P1__c = 'Skipped not necessary', 
            Resource_Guarding_P1_Push_Face__c = 'Remained relaxed', 
            Comments_BOL__c='test test test', 
            Tag_Test__c='Too fearful-subtest not done', 
            Skipped_RG_P2_PF__c	= 'Skipped for medical reason'
        );
        insert dogFightingBehEval;

        PageReference dogFightingPageRef = Page.BehaviorEvaluationMatrix;
        Test.setCurrentPage(dogFightingPageRef);
        apexpages.currentpage().getparameters().put('Id' , dogFightingBehEval.id);



        BehaviorEvaluationMatrixController dogFightingObjBehMatrix  = new BehaviorEvaluationMatrixController (new ApexPages.StandardController(dogFightingBehEval));

        //Expected result:        
        //((Behavior in Kennel, ✔, ✔,  ,  ), (Behavior on Leash, ❌, ❌, ❌, ❌), (Social Behavior P1, ---, ---, ---, ---), (Resource Guarding P1 - PF, ✔,  ,  ,  ))

        System.assertEquals(5, dogFightingObjBehMatrix.finalTestAndDisplayValues.size());
        
        //Puppy Evaluation Test
        Behavior_Evaluation__c puppyBehEval = new Behavior_Evaluation__c(
            Animal__c = objAnimal.Id, 
            Evaluation_Subtype__c = 'Puppy', 
            Handler_Initials__c = 'TI', 
            Scribe_Initials__c = 'TI', 
            Tester_Initials__c = 'TI', 
            Puppy_Behavior_in_Kennel__c = 'Social;Hyperaroused', 
            Skipped_BOL__c = 'Skipped to safeguard welfare of the animal', 
            Skipped_SB_P1__c = 'Skipped not necessary', 
            Puppy_Resource_Guarding_P1_Push_Face__c = 'Remained relaxed'
        );
        insert puppyBehEval;
        
        PageReference puppyPageRef = Page.BehaviorEvaluationMatrix;
        Test.setCurrentPage(puppyPageRef);
        apexpages.currentpage().getparameters().put('Id' , puppyBehEval.id);
        
        BehaviorEvaluationMatrixController puppyObjBehMatrix  = new BehaviorEvaluationMatrixController (new ApexPages.StandardController(puppyBehEval));
        
		//Expected result:        
        //((Behavior in Kennel, ✔, ✔,  ,  ), (Behavior on Leash, ❌, ❌, ❌, ❌), (Social Behavior P1, ---, ---, ---, ---), (Resource Guarding P1 - PF, ✔,  ,  ,  ))
        
        System.assertEquals(5, objBehMatrix.finalTestAndDisplayValues.size());
        //system.debug(objBehMatrix.finalTestAndDisplayValues.size());
        
        Test.stopTest();
        
        //system.debug(behEval);
        
        
    }
    
    //@isTest static void test
    
}