force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Observation__c/Observation__c.object-meta.xml
<CustomObject>
    <label>Observation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Observation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Observations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Observation__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Observations</relationshipLabel>
    <relationshipName>Observations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_ObservationController.cls
@isTest
private class Test_ObservationController {
    @isTest
    static void getObservations_hasObservations(){
        Observation__c[] observations = TestDataFactory.createObservations();

        test.startTest();
            Observation__c[] returnedObservations = ObservationController.getObservations(observations[0].Animal__c, 'Happy Tail');
        test.stopTest();

        System.assertEquals(1, returnedObservations.size());
    }

    @isTest
    static void getObservations_noObservations(){
        Animal__c animal = TestDataFactory.createAnimal();

        test.startTest();
            Observation__c[] returnedObservations = ObservationController.getObservations(animal.Id, 'Happy Tail');
        test.stopTest();

        System.assertEquals(null, returnedObservations);
    }
}