force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Name_Id__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name_Id__c</fullName>
    <formula>Animal_Name__c + &apos; (&apos; +  Name + &apos;)&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animal Name/Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Medication_Flag__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Medication_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Behavior Medication Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Feeding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Feeding_Amount__c</fullName>
    <label>Feeding Amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Handling_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Handling_Instructions__c</fullName>
    <label>Handling Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Shelter_Location__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Location__c</fullName>
    <label>Kennel Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/Animal_Daily_Care__c.object-meta.xml
<CustomObject>
    <label>Animal Daily Care</label>
    <nameField>
        <displayFormat>ADCN-{0000}</displayFormat>
        <label>Animal Daily Care Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals Daily Care</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animals Daily Care</relationshipLabel>
    <relationshipName>Animals_Daily_Care</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Daily_Care__c.field-meta.xml
<CustomField>
    <fullName>Daily_Care__c</fullName>
    <label>Daily Care</label>
    <referenceTo>Daily_Care__c</referenceTo>
    <relationshipLabel>Animals Daily Care</relationshipLabel>
    <relationshipName>Animals_Daily_Care</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Enrichment__c.field-meta.xml
<CustomField>
    <fullName>Enrichment__c</fullName>
    <description>Enrichment field on Animal care. We have one on Animal record aswell.</description>
    <label>Enrichment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Feeding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Feeding_Amount__c</fullName>
    <label>Feeding Amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Handling_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Handling_Instructions__c</fullName>
    <label>Handling Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Mvmt_Round_Notes_Cleaning_Destination__c.field-meta.xml
<CustomField>
    <fullName>Mvmt_Round_Notes_Cleaning_Destination__c</fullName>
    <label>Mvmt Round Notes &amp; Cleaning Destination</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <label>Round</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Special_Care_Other__c.field-meta.xml
<CustomField>
    <fullName>Special_Care_Other__c</fullName>
    <label>Special Care Other</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Special_Care_Outside_TX__c.field-meta.xml
<CustomField>
    <fullName>Special_Care_Outside_TX__c</fullName>
    <label>Special Care Outside TX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Special_Care_TX__c.field-meta.xml
<CustomField>
    <fullName>Special_Care_TX__c</fullName>
    <label>Special Care TX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Care__c/Daily_Care__c.object-meta.xml
<CustomObject>
    <label>Daily Care</label>
    <nameField>
        <displayFormat>DCN-{0000}</displayFormat>
        <label>Daily Care Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Care</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task/recordTypes/Treatments.recordType-meta.xml
<RecordType>
    <fullName>Treatments</fullName>
    <active>true</active>
    <description>Treatment tasks</description>
    <label>Treatments</label>
</RecordType>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Enrichment_Activities__c.field-meta.xml
<CustomField>
    <fullName>Enrichment_Activities__c</fullName>
    <label>Enrichment Activities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Enrichment_Activities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Enrichment_Activities.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 on 1</fullName>
    </customValue>
    <customValue>
        <fullName>Backyard</fullName>
    </customValue>
    <customValue>
        <fullName>Ball/rock pit (foraging)</fullName>
    </customValue>
    <customValue>
        <fullName>Basic Training</fullName>
    </customValue>
    <customValue>
        <fullName>Dig pit</fullName>
    </customValue>
    <customValue>
        <fullName>Fetch with rules</fullName>
    </customValue>
    <customValue>
        <fullName>Foster overnights</fullName>
    </customValue>
    <customValue>
        <fullName>Four on the Floor for Leash</fullName>
    </customValue>
    <customValue>
        <fullName>Gym</fullName>
    </customValue>
    <customValue>
        <fullName>IPY</fullName>
    </customValue>
    <customValue>
        <fullName>Kennel Presence</fullName>
    </customValue>
    <customValue>
        <fullName>LLW</fullName>
    </customValue>
    <customValue>
        <fullName>Nose Work</fullName>
    </customValue>
    <customValue>
        <fullName>Outside ExPen</fullName>
    </customValue>
    <customValue>
        <fullName>Office Time</fullName>
    </customValue>
    <customValue>
        <fullName>Offsite Trips</fullName>
    </customValue>
    <customValue>
        <fullName>OPY</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Outside Walks</fullName>
    </customValue>
    <customValue>
        <fullName>PC Tug</fullName>
    </customValue>
    <customValue>
        <fullName>Puppy Enrichment/Socialization</fullName>
    </customValue>
    <customValue>
        <fullName>Puppy Handling</fullName>
    </customValue>
    <customValue>
        <fullName>Quiet Time</fullName>
    </customValue>
    <customValue>
        <fullName>Real-Life Room</fullName>
    </customValue>
    <customValue>
        <fullName>Shelter Notes</fullName>
    </customValue>
    <customValue>
        <fullName>Snuffle mat</fullName>
    </customValue>
    <customValue>
        <fullName>Trick Training</fullName>
    </customValue>
    <customValue>
        <fullName>Tug pully</fullName>
    </customValue>
    <customValue>
        <fullName>Tug with rules</fullName>
    </customValue>
    <customValue>
        <fullName>Walk</fullName>
    </customValue>
    <masterLabel>Enrichment Activities</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DailyCareLWCController.cls
public with sharing class DailyCareLWCController {
    
    @AuraEnabled (cacheable=true)
    public static DailyCareInfo getDailyCare(Date careDate, String sortByField, String sortByValue){
        DailyCareInfo info = new DailyCareInfo();
        if(careDate != null){
            try{
                Daily_Care__c[] dcList = [SELECT Id FROM Daily_Care__c WHERE Date__c =: careDate LIMIT 1];
                if(!dcList.isEmpty()){
                    Id dcId = dcList[0].Id;
                    info.dailyCareId = dcId;
                    info.animalDailyCares = getAnimalDailyCares(dcId, sortByField, sortByValue);
                }
                return info;
            } catch (Exception e) {
                System.debug('stackTrace: ' + e.getStackTraceString());
                throw new AuraHandledException(e.getMessage());
            }
        } else {
            AuraHandledException e = new AuraHandledException('No date selected');
            e.setMessage('No date selected');
            throw e;
        }
    }

    private static Id[] getAnimalDailyCares(Id dailyCareId, String sortByField, String sortByValue){
        Id[] idList = new Id[0];
        String query = 'SELECT Id FROM Animal_Daily_Care__c WHERE Daily_Care__c = \'' +  dailyCareId + '\' ORDER BY ' + sortByField + ' ' + sortByValue;
        System.debug('query: ' + query);
        Animal_Daily_Care__c[] adcs = Database.query(query);
        for(Animal_Daily_Care__c adc : adcs){
            idList.add(adc.Id);
        }
        return idList;
    }

    @AuraEnabled (cacheable=true)
    public static AnimalInfo getAnimalDailyCareInfo(Id animalDailyCareId){
        try{
            AnimalInfo info = new AnimalInfo();

            Animal_Daily_Care__c[] adcs = [
                SELECT 
                    Id, 
                    Animal__c,
                    Animal__r.Animal_Name_Id__c, 
                    Animal__r.Behavior_Medication_Flag__c,
                    Animal__r.Feeding_Amount__c,
                    Animal__r.Shelter_Location__c,
                    Special_Care_TX__c,
                    Special_Care_Outside_TX__c,
                    Special_Care_Other__c,
                Enrichment__c,
                    Round__c,
                    Mvmt_Round_Notes_Cleaning_Destination__c,
                    Handling_Instructions__c
                FROM Animal_Daily_Care__c 
                WHERE Id =: animalDailyCareId
                LIMIT 1
            ];

            if(!adcs.isEmpty()){
                Animal_Daily_Care__c adc = adcs[0];
                info.animalCareId = adc.Id;
                info.animalName = adc.Animal__r.Animal_Name_Id__c;
                info.animalKennelLocation = adc.Animal__r.Shelter_Location__c;
                info.dailyRations = adc.Animal__r.Feeding_Amount__c;
                info.restDays = getAnimalRestDays(adc.animal__c);
                info.behaviorMeds = adc.Animal__r.Behavior_Medication_Flag__c;
                info.specialCareTreatment = adc.Special_Care_TX__c;
                info.specialCareOutside = adc.Special_Care_Outside_TX__c;
                info.specialCareOther = adc.Special_Care_Other__c;
                //info.enrichment = getAnimalEnrichments(adc.Animal__c);
                info.enrichment = adc.Enrichment__c;
                info.round = adc.Round__c;
                info.movemntAndCleaningDestinationField = adc.Mvmt_Round_Notes_Cleaning_Destination__c;
                info.handlingInstructions = adc.Handling_Instructions__c;
            }
            
            return info;
        
        } catch (Exception e) {
            System.debug('stackTrace: ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }

    public static String getAnimalRestDays(Id animalId){
        String restDays = null;
        Date today = date.today();
        Date startDate = AutoScheduleTasksUtil.startOfASPCAWeek(today);
        Date endDate = startDate.addDays(7);
        Id rtId = Util.getRecordTypeId('Task', AutoScheduleTasksUtil.BEH_TREATMENT_TASK_RECORD_TYPE_NAME);
        Set<String> restDaysSet = new Set<String>();
        Date[] treatmentDays = new Date[0];
        for(Task t : [SELECT Id, ActivityDate FROM Task WHERE Animal__c =: animalId AND RecordTypeId =: rtId AND ActivityDate >=: startDate AND ActivityDate <: endDate]){
            treatmentDays.add(t.ActivityDate);
        }

        System.debug('treatmentDays: ' + treatmentDays);

        if(treatmentDays.isEmpty()){
            restDays = 'No treatments assigned this week';
        }
        else{
            while(startDate < endDate){
                System.debug('startDate: ' + startDate);
                if(!treatmentDays.contains(startDate)){
                    restDaysSet.add(AutoScheduleTasksUtil.getDayOfWeek(startDate));
                }   
                startDate = startDate.addDays(1);
            }

            if(!restDaysSet.isEmpty()){
                restDays = String.join(new List<String>(restDaysSet), ',');
            }
        }
        return restDays;
    }

  /*private static String getAnimalEnrichments(Id animalId){
        String enrichments = null;
        Treatment_Plan__c[] plans = [SELECT Id, Enrichment_Activities__c FROM Treatment_Plan__c WHERE IsActive__c = true AND Animal__c =: animalId LIMIT 1];
        if(!plans.isEmpty() && plans[0].Enrichment_Activities__c != null){
            enrichments = plans[0].Enrichment_Activities__c.replace(';', ',');
        }
        return enrichments;

    }*/

    public class DailyCareInfo{
        @AuraEnabled public Id dailyCareId;
        @AuraEnabled public Id[] animalDailyCares;
    }

    public class AnimalInfo{
        @AuraEnabled public Id animalCareId;
        @AuraEnabled public String animalName;
        @AuraEnabled public String animalKennelLocation;
        @AuraEnabled public String dailyRations;
        @AuraEnabled public String restDays;
        @AuraEnabled public Boolean behaviorMeds;
        @AuraEnabled public String specialCareTreatment;
        @AuraEnabled public String specialCareOutside;
        @AuraEnabled public String specialCareOther;
        @AuraEnabled public String enrichment;
        @AuraEnabled public String round;
        @AuraEnabled public String movemntAndCleaningDestinationField;
        @AuraEnabled public String handlingInstructions;
    }
}