force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Sessions Quote</relationshipLabel>
    <relationshipName>Treatment_Sessions_Quote</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Session_Notes__c.field-meta.xml
<CustomField>
    <fullName>Session_Notes__c</fullName>
    <label>Session Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SObjectSelectors/TreatmentSessionSelector.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class TreatmentSessionSelector extends SObjectSelector {
    public TreatmentSessionSelector() {
        super(Quote.SObjectType);
    }

    public override Set<SObjectField> GetDefaultFields() {
        return new Set<SObjectField> {
                Quote.Name,
                Quote.Id,
                Quote.OpportunityId,
                Quote.Pricebook2Id,
                Quote.Animal__c,
                Quote.CreatedById,
                Quote.CreatedDate,
                Quote.LastModifiedById,
                Quote.LastModifiedDate,
                Quote.Session_Notes__c,
                Quote.Status
        };
    }

    public override List<iOrderBy> GetDefaultOrderBy() {
        return new List<iOrderBy> {
                OrderBy.Ascending(Quote.Name) ,
                OrderBy.Ascending(Quote.Id)
        };
    }

    public List<Quote> GetByIds(Set<Id> ids) {
        return queryById(ids);
    }

    public List<Quote> GetByName(String name) {
        return queryByName(name);
    }

}