force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name__c</fullName>
    <externalId>true</externalId>
    <label>ASPCA Animal Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Does_Not_Walk_on_a_Leash__c.field-meta.xml
<CustomField>
    <fullName>Does_Not_Walk_on_a_Leash__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Does Not Walk on a Leash</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Does_Not_Walk_on_a_Leash_Notes__c.field-meta.xml
<CustomField>
    <fullName>Does_Not_Walk_on_a_Leash_Notes__c</fullName>
    <label>Does Not Walk on a Leash Notes</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <scale>15</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Number_of_Playgroups__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Playgroups__c</fullName>
    <description>This information is populated using the Roll-up Helper tool.</description>
    <label># of Playgroups (last seven days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Play_Category__c.field-meta.xml
<CustomField>
    <fullName>Play_Category__c</fullName>
    <label>Play Category</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Play_Pause_Reason__c.field-meta.xml
<CustomField>
    <fullName>Play_Pause_Reason__c</fullName>
    <label>Play-Pause Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Play_Style_Notes__c.field-meta.xml
<CustomField>
    <fullName>Play_Style_Notes__c</fullName>
    <label>Play Style Notes</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Playgroup_Priority_Level__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Priority_Level__c</fullName>
    <label>Playgroup Priority Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily – 7 days</fullName>
            </value>
            <value>
                <fullName>High – 4 days</fullName>
            </value>
            <value>
                <fullName>Low – 2 days</fullName>
            </value>
            <value>
                <fullName>No Priority</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Shelter_Color_Coding__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Color_Coding__c</fullName>
    <inlineHelpText>Shelter handling color code for the animal</inlineHelpText>
    <label>Shelter Color Coding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shelter_Color_Coding</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Shelter_Location__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Location__c</fullName>
    <label>Kennel Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/Animal_Playgroup__c.object-meta.xml
<CustomObject>
    <label>Animal Playgroup</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Animal Playgroup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Playgroups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Playgroup__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Playgroup_Session__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Session</label>
    <referenceTo>Playgroup_Session__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Conditions__c/Medical_Conditions__c.object-meta.xml
<CustomObject>
    <label>Medical Condition</label>
    <nameField>
        <displayFormat>MC-{0}</displayFormat>
        <label>Medical Conditions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Conditions__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal ID</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Medical Conditions</relationshipLabel>
    <relationshipName>Medical_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Conditions__c/fields/Date_Diagnosed__c.field-meta.xml
<CustomField>
    <fullName>Date_Diagnosed__c</fullName>
    <label>Date Diagnosed</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Medical_Conditions__c/fields/Date_Resolved__c.field-meta.xml
<CustomField>
    <fullName>Date_Resolved__c</fullName>
    <label>Date Resolved</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Medical_Conditions__c/fields/Medical_Condition__c.field-meta.xml
<CustomField>
    <fullName>Medical_Condition__c</fullName>
    <label>Medical Condition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Allergy</fullName>
            </value>
            <value>
                <fullName>Anaplasma</fullName>
            </value>
            <value>
                <fullName>Anemia</fullName>
            </value>
            <value>
                <fullName>Angel Wing</fullName>
            </value>
            <value>
                <fullName>Appears Healthy on Forensic Exam</fullName>
            </value>
            <value>
                <fullName>Avian Influenza</fullName>
            </value>
            <value>
                <fullName>Avian Pox</fullName>
            </value>
            <value>
                <fullName>Babesia</fullName>
            </value>
            <value>
                <fullName>Beak (Clipped)</fullName>
            </value>
            <value>
                <fullName>Beak (Malformed)</fullName>
            </value>
            <value>
                <fullName>Beak (Overgrown)</fullName>
            </value>
            <value>
                <fullName>Behavior</fullName>
            </value>
            <value>
                <fullName>Blunt force trauma</fullName>
            </value>
            <value>
                <fullName>Bumblefoot (Pododermatitis)</fullName>
            </value>
            <value>
                <fullName>Canine Bordetella</fullName>
            </value>
            <value>
                <fullName>Canine Distemper</fullName>
            </value>
            <value>
                <fullName>Canine Mycoplasma</fullName>
            </value>
            <value>
                <fullName>Canine Parvo</fullName>
            </value>
            <value>
                <fullName>Cardiac disease</fullName>
            </value>
            <value>
                <fullName>Coccidia</fullName>
            </value>
            <value>
                <fullName>Crop Stasis</fullName>
            </value>
            <value>
                <fullName>Cryptorchid</fullName>
            </value>
            <value>
                <fullName>Dehydration</fullName>
            </value>
            <value>
                <fullName>Demodex</fullName>
            </value>
            <value>
                <fullName>Dental Disease</fullName>
            </value>
            <value>
                <fullName>Dental Fracture</fullName>
            </value>
            <value>
                <fullName>Dermatitis</fullName>
            </value>
            <value>
                <fullName>Dermatophyte</fullName>
            </value>
            <value>
                <fullName>Egg Bound</fullName>
            </value>
            <value>
                <fullName>Ehrlichia</fullName>
            </value>
            <value>
                <fullName>In Heat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Play_Pause__c/Play_Pause__c.object-meta.xml
<CustomObject>
    <label>Play Pause</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Play Pause #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Play Pauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Play_Pause__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalshelters__Animal__c</referenceTo>
    <relationshipLabel>Play Pauses</relationshipLabel>
    <relationshipName>Play_Pauses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Play_Pause__c/fields/Play_Pause_Reason__c.field-meta.xml
<CustomField>
    <fullName>Play_Pause_Reason__c</fullName>
    <label>Play Pause Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Heat</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Lameness</fullName>
            </value>
            <value>
                <fullName>Infectious Disease</fullName>
            </value>
            <value>
                <fullName>Spay/Neuter</fullName>
            </value>
            <value>
                <fullName>Bite Quarantine</fullName>
            </value>
            <value>
                <fullName>Medical Quarantine</fullName>
            </value>
            <value>
                <fullName>Cardiac Condition</fullName>
            </value>
            <value>
                <fullName>Nursing Dam</fullName>
            </value>
            <value>
                <fullName>Needs a Break</fullName>
            </value>
            <value>
                <fullName>Bad Session</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Play_Pause__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Behavioral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Playgroup__c/Playgroup__c.object-meta.xml
<CustomObject>
    <label>Playgroup</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Playgroups</relationshipLabel>
    <relationshipName>Playgroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ARC/CARE</fullName>
            </value>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PlaygroupToDoListController.cls
public with sharing class PlaygroupToDoListController {
    static String[] locationsToExclude = new String[]{
        'Board and Train',
        'Boarding',
        'Field Temp Shelter',
        'Foster Home',
        'Partner Hospital',
        'Response Partner'
    };
    @AuraEnabled(cacheable=true)
    public static List<Animal__c> getPlaygroupAnimals(String location) {
        List<Animal__c> animals = [
            SELECT Id, Name, Animal_Name__c, Gender__c, Shelter_Location__c, Playgroup_Priority_Level__c, Play_Style_Notes__c,
            Play_Category__c, Shelter_Color_Coding__c, Number_of_Playgroups__c, Does_Not_Walk_on_a_Leash__c, Does_Not_Walk_on_a_Leash_Notes__c,
            (SELECT Id FROM Medical_Conditions__r
                WHERE Medical_Condition__c = 'Babesia'
                AND Date_Diagnosed__c <= TODAY
                AND (Date_Resolved__c = null OR Date_Resolved__c > TODAY) LIMIT 1),
            (SELECT Id FROM Play_Pauses__r
                WHERE Type__c = 'Medical'
                AND Play_Pause_Reason__c = 'In Heat'
                AND Start_Date__c <= TODAY
                AND (End_Date__c = null OR End_Date__c > TODAY) LIMIT 1),
            (SELECT Id FROM Animal_Playgroups__r
                WHERE Playgroup_Session__r.Playgroup_Date_Time__c >= TODAY
                AND Playgroup_Session__r.Playgroup_Date_Time__c < TOMORROW LIMIT 1)
            FROM Animal__c
            WHERE Active_Animal__c = true
            AND Type_of_Animal__c = 'Dog'
            AND Current_Location__c NOT IN :locationsToExclude
            AND Play_Category__c NOT IN ('Unevaluated', 'DO NOT PLAY', '')
            AND Id NOT IN (SELECT Animal__c FROM Play_Pause__c WHERE Type__c = 'Behavioral' AND Start_Date__c <= TODAY AND (End_Date__c = null OR End_Date__c >= TODAY))
            AND Location_Filter__c = true
            ORDER BY Id
        ];
        return animals;
    }
    //Neha
    @AuraEnabled(cacheable=true)
    public static Id getReportId(){
        Report[] reports =  [SELECT Id FROM Report where DeveloperName ='Playgroups_Last_2_Days'];
        return reports != null && !reports.isEmpty() ? reports[0].Id : null;
    }

    @AuraEnabled
    public static String createPlaygroup(List<String> animals) {
        String sessionResult = '';
        Playgroup_Session__c session = new Playgroup_Session__c();
        Database.SaveResult sessionSR = Database.insert(session, false);
        if (sessionSR.isSuccess()) {
            sessionResult = sessionSR.getId();
            List<Animal_Playgroup__c> animalPlaygroups = new List<Animal_Playgroup__c>();
            for(String a : animals) {
                Animal_Playgroup__c animalPG = new Animal_Playgroup__c(
                    Animal__c = a,
                    Playgroup_Session__c = sessionResult
                );
                animalPlaygroups.add(animalPG);
            }
            List<Database.SaveResult> animalSR = Database.insert(animalPlaygroups, false);
            for(Database.SaveResult s : animalSR) {
                if (!s.isSuccess()) {
                    sessionResult = 'Error creating animal playgroups';
                    break;
                }
            }
        }
        else {
            sessionResult = 'Error creating playgroup session';
        }
        return sessionResult;
    }

    @AuraEnabled
    public static Id copyPlaygroupSession(Id sessionId, Id[] animalsToAdd){
        try {
            Id newSessionId = handleCopyPlaygroupSession(sessionId);
            createNewAnimalPlaygroupsFromCopy(sessionId, newSessionId, animalsToAdd);
            return newSessionId;

        } catch (Exception e) {
            System.debug('error: ' + e.getMessage());
            System.debug('line: ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Id editPlaygroup(Id sessionId, Id[] animalsToAdd){
        try {

            handleDeleteAnimalPlaygroups(sessionId, animalsToAdd);

            createNewAnimalPlaygroupsFromEdit(sessionId, animalsToAdd);
            return sessionId;

        } catch (Exception e) {
            System.debug('error: ' + e.getMessage());
            System.debug('line: ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled 
    public static String getUserLocation(){
        try {
            return [SELECT Location__c FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1].Location__c;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static void handleDeleteAnimalPlaygroups(Id sessionId, Id[] animalsToAdd){
        //first delete the playgroup contacts
        delete [SELECT Id FROM Playgroup_Contact__c WHERE Playgroup__r.Playgroup_Session__c =: sessionId AND Playgroup__r.Animal__c NOT IN: animalsToAdd ];
        //now delete the animal playgroups
        delete [SELECT Id FROM Animal_Playgroup__c WHERE Playgroup_Session__c =: sessionId AND Animal__c NOT IN : animalsToAdd];
    }

    private static Id handleCopyPlaygroupSession(Id SessionId){
        Playgroup_Session__c originalSession = getPlaygroupSession(sessionId);
        Playgroup_Session__c newSession = new Playgroup_Session__c(
            Playgroup_Leader__c = originalSession.Playgroup_Leader__c,
            Playgroup_Location__c = originalSession.Playgroup_Location__c,
            Playgroup_Date_Time__c = dateTime.now(),
            Population__c = originalSession.Population__c,
            Contact_Ids__c = originalSession.Contact_Ids__c
        );
        insert newSession;
        return newSession.Id;
    }

    private static Playgroup_Session__c getPlaygroupSession (Id sessionId){
        Playgroup_Session__c[] sessions = [
            SELECT Id, Playgroup_Location__c, Playgroup_Leader__c, Contact_Ids__c, Population__c
            FROM Playgroup_Session__c 
            WHERE Id =: sessionId 
            LIMIT 1
        ];
        return sessions.isEmpty() ? null : sessions[0];
    }

    private static void createNewAnimalPlaygroupsFromEdit(Id sessionId, Id[] animalsToAdd){
        Animal_Playgroup__c[] newAnimalPlaygroups = new Animal_Playgroup__c[0];
        Map<Id, Animal_Playgroup__c> existingAnimalPlaygroupMap = getAnimalPlaygroupsForCurrentSession(sessionId, animalsToAdd);
        for(Id animalToAdd : animalsToAdd){
            if(!existingAnimalPlaygroupMap.containsKey(animalToAdd)){
                Animal_Playgroup__c newAnimal = new Animal_Playgroup__c(
                    Animal__c = animalToAdd,
                    Playgroup_Session__c = sessionId
                );
                newAnimalPlaygroups.add(newAnimal);
            }
        }

        insert newAnimalPlaygroups;
        createPlaygroupContacts(newAnimalPlaygroups, null, sessionId);
    }

    private static void createNewAnimalPlaygroupsFromCopy(Id oldSessionId, Id newSessionId, Id[] animalsToAdd){
        Animal_Playgroup__c[] newAnimalPlaygroups = new Animal_Playgroup__c[0];

        Map<Id, Animal_Playgroup__c> oldAnimalPlaygroupMap = getAnimalPlaygroupsForCurrentSession(oldSessionId, animalsToAdd);

        for(Id animalToAdd : animalsToAdd){
            if(oldAnimalPlaygroupMap.containsKey(animalToAdd)){
                Animal_Playgroup__c oldAnimal = oldAnimalPlaygroupMap.get(animalToAdd);
                Animal_Playgroup__c newAnimal = new Animal_Playgroup__c(
                    Animal__c = oldAnimal.Animal__c, 
                    Play_Rating__c = 'Green', 
                    Playgroup_Individual_Notes__c = oldAnimal.Playgroup_Individual_Notes__c,
                    Playgroup_Session__c = newSessionId
                );
                newAnimalPlaygroups.add(newAnimal);
            }
            else {
                Animal_Playgroup__c newAnimal = new Animal_Playgroup__c(
                    Animal__c = animalToAdd,
                    Playgroup_Session__c = newSessionId
                );
                newAnimalPlaygroups.add(newAnimal);
            }
        }

        insert newAnimalPlaygroups;
        createPlaygroupContacts(newAnimalPlaygroups, oldAnimalPlaygroupMap, newSessionId);
    }

    private static Map<Id, Animal_Playgroup__c> getAnimalPlaygroupsForCurrentSession(Id sessionId, Id[] animalsToAdd){
        Animal_Playgroup__c[] animalPlaygroups = [
            SELECT Id, Animal__c, Common_Playgroup_Note_Sections__c, Common_Playgroup_Notes__c, Playgroup_Individual_Notes__c,
            (SELECT Id, Contact__c, Novel_Not_Novel__c, Playgroup__c FROM Playgroup_Contacts__r)
            FROM Animal_Playgroup__c 
            WHERE Playgroup_Session__c =: sessionId
            AND Animal__c IN: animalsToAdd
        ];

        Map<Id, Animal_Playgroup__c> animalPlaygroupMap = new Map<Id, Animal_Playgroup__c>();
        for(Animal_Playgroup__c animal : animalPlaygroups){
            animalPlaygroupMap.put(animal.Animal__c, animal);
        }

        return animalPlaygroupMap;
    }

    private static void createPlaygroupContacts(Animal_Playgroup__c[] animalPlaygroups, Map<Id, Animal_Playgroup__c> oldAnimalPlaygroupMap, Id newSessionId){
        Playgroup_Session__c session = [SELECT Id, Contact_Ids__c FROM Playgroup_Session__c WHERE Id =: newSessionId LIMIT 1];
        if(session.Contact_Ids__c != null){
            String[] contactList = session.Contact_Ids__c.split(',');
            Playgroup_Contact__c[] pgContacts = new Playgroup_Contact__c[0];
            for(Animal_Playgroup__c animal : animalPlaygroups){
                if(oldAnimalPlaygroupMap != null && oldAnimalPlaygroupMap.containsKey(animal.Animal__c)){
                    for(Playgroup_Contact__c pgContact : oldAnimalPlaygroupMap.get(animal.Animal__c).Playgroup_Contacts__r){
                        pgContacts.add(
                            new Playgroup_Contact__c(
                                Contact__c = pgContact.Contact__c,
                                Novel_Not_Novel__c = pgContact.Novel_Not_Novel__c,
                                Playgroup__c = animal.Id
                            )
                        );
                    }
                }
                else {
                    for(String con : contactList){
                        pgContacts.add(
                            new Playgroup_Contact__c(
                                Contact__c = con,
                                Novel_Not_Novel__c = 'Familiar',
                                Playgroup__c = animal.Id
                            )
                        );
                    }
                }
            }
            insert pgContacts;
        }
    }
}