force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Daily_Care__c/Animal_Daily_Care__c.object-meta.xml
<CustomObject>
    <label>Animal Daily Care</label>
    <nameField>
        <displayFormat>ADCN-{0000}</displayFormat>
        <label>Animal Daily Care Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals Daily Care</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animals Daily Care</relationshipLabel>
    <relationshipName>Animals_Daily_Care</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Daily_Care__c.field-meta.xml
<CustomField>
    <fullName>Daily_Care__c</fullName>
    <label>Daily Care</label>
    <referenceTo>Daily_Care__c</referenceTo>
    <relationshipLabel>Animals Daily Care</relationshipLabel>
    <relationshipName>Animals_Daily_Care</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Movement_Method_For_Cleaning__c.field-meta.xml
<CustomField>
    <fullName>Movement_Method_For_Cleaning__c</fullName>
    <label>Movement Method For Cleaning</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Movements_For_Cleaning__c.field-meta.xml
<CustomField>
    <fullName>Movements_For_Cleaning__c</fullName>
    <label>Movements For Cleaning</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <label>Round</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Special_Care_Other__c.field-meta.xml
<CustomField>
    <fullName>Special_Care_Other__c</fullName>
    <label>Special Care Other</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Special_Care_Outside_TX__c.field-meta.xml
<CustomField>
    <fullName>Special_Care_Outside_TX__c</fullName>
    <label>Special Care Outside TX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Special_Care_TX__c.field-meta.xml
<CustomField>
    <fullName>Special_Care_TX__c</fullName>
    <label>Special Care TX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Care__c/Daily_Care__c.object-meta.xml
<CustomObject>
    <label>Daily Care</label>
    <nameField>
        <displayFormat>DCN-{0000}</displayFormat>
        <label>Daily Care Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Care</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Care__c/fields/AM_Reminders__c.field-meta.xml
<CustomField>
    <fullName>AM_Reminders__c</fullName>
    <label>AM Reminders</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Care__c/fields/General_Reminders__c.field-meta.xml
<CustomField>
    <fullName>General_Reminders__c</fullName>
    <label>General Reminders</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Care__c/fields/PM_Reminders__c.field-meta.xml
<CustomField>
    <fullName>PM_Reminders__c</fullName>
    <label>PM Reminders</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Care__c/fields/Scent_of_the_Week__c.field-meta.xml
<CustomField>
    <fullName>Scent_of_the_Week__c</fullName>
    <label>Scent of the Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deer</fullName>
            </value>
            <value>
                <fullName>Skunk</fullName>
            </value>
            <value>
                <fullName>Bear</fullName>
            </value>
            <value>
                <fullName>Squirrel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Care__c/fields/Special_Projects__c.field-meta.xml
<CustomField>
    <fullName>Special_Projects__c</fullName>
    <label>Special Projects</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DailyCarePDFController.cls
public class DailyCarePDFController {
    public String dailyCareId {get; set;}
    
    public DailyCarePDFController(){
        this.dailyCareId = ApexPages.currentPage().getParameters().get('dailyCareId');
    }
    
    public Daily_Care__c dailyCare {
        public get {
            if (dailyCare == null){
                dailyCare = [SELECT AM_Reminders__c, Date__c, General_Reminders__c, PM_Reminders__c, 
                             Scent_of_the_Week__c, Special_Projects__c, Id, Name 
                             FROM Daily_Care__c WHERE Id =: dailyCareId];
            }
            return dailyCare;
        }
        private set;
    }
    
    public List<Animal_Daily_Care__c> animalDailyCares {
        public get {
            if (animalDailyCares == null){
                animalDailyCares = [SELECT Id, Name, Animal__c, Daily_Care__c, Movement_Method_For_Cleaning__c, 
                             Movements_For_Cleaning__c, Round__c, Special_Care_Other__c, 
                             Special_Care_Outside_TX__c, Special_Care_TX__c FROM Animal_Daily_Care__c WHERE Daily_Care__c =: dailyCareId];
            }
            return animalDailyCares;
        }
        private set;
    }
    
    

}