force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Name_Id__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name_Id__c</fullName>
    <formula>Animal_Name__c + &apos; (&apos; +  Name + &apos;)&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animal Name/Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Behavior Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Behavior Case Worker)</relationshipLabel>
    <relationshipName>Beh_Case_Worker_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Recent_Shelter_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Recent_Shelter_Location__c</fullName>
    <label>Current/Recent Shelter Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Evaluation_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Due_Date__c</fullName>
    <label>Evaluation Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Type_of_Animal__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Animal__c</fullName>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Species</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/recordTypes/Behavior.recordType-meta.xml
<RecordType>
    <fullName>Behavior</fullName>
    <active>true</active>
    <label>Behavior</label>
</RecordType>

force-app/main/default/objects/Facility_Outcome__c/Facility_Outcome__c.object-meta.xml
<CustomObject>
    <label>Facility/Outcome</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>F/O #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facilities/Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility_Outcome__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipName>Animal_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Facility_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Facility_Outcome__c</fullName>
    <label>Facility/Outcome</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Facility_or_Outcome__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAH</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Adoption Center</fullName>
            </value>
            <value>
                <fullName>Adoption Center (Temp Boarding)</fullName>
            </value>
            <value>
                <fullName>Animal Hospital</fullName>
            </value>
            <value>
                <fullName>Animal Shelter</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>ASNA</fullName>
            </value>
            <value>
                <fullName>ASPCA Shelter</fullName>
            </value>
            <value>
                <fullName>Board and Train</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>BRC</fullName>
            </value>
            <value>
                <fullName>Bronx CVC</fullName>
            </value>
            <value>
                <fullName>Brooklyn CVC</fullName>
            </value>
            <value>
                <fullName>CARE</fullName>
            </value>
            <value>
                <fullName>Clinic</fullName>
            </value>
            <value>
                <fullName>Community Medicine</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
            <value>
                <fullName>CRC-MRC</fullName>
            </value>
            <value>
                <fullName>Cremation</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Euthanized</fullName>
            </value>
            <value>
                <fullName>Field Temp Shelter</fullName>
            </value>
            <value>
                <fullName>Foster-Based Rescue</fullName>
            </value>
            <value>
                <fullName>Foster Home</fullName>
            </value>
            <value>
                <fullName>Foster Home - Adoption Center</fullName>
            </value>
            <value>
                <fullName>Foster Home - ARC</fullName>
            </value>
            <value>
                <fullName>Foster Home - CARE</fullName>
            </value>
            <value>
                <fullName>Hound Hotel</fullName>
            </value>
            <value>
                <fullName>Kitten Nursery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Point_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Point_of_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Point of Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Facilities/Outcomes</relationshipLabel>
    <relationshipName>Facilities_Outcomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Previous_Facility_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Previous_Facility_Outcome__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Facility/Outcome</label>
    <referenceTo>Facility_Outcome__c</referenceTo>
    <relationshipLabel>Facilities/Outcomes</relationshipLabel>
    <relationshipName>Facilities_Outcomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Evaluation.recordType-meta.xml
<RecordType>
    <fullName>Evaluation</fullName>
    <active>true</active>
    <label>Evaluation</label>
</RecordType>

force-app/main/default/globalValueSets/Species.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avian</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Cow</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Equine</fullName>
    </customValue>
    <customValue>
        <fullName>Exotic</fullName>
    </customValue>
    <customValue>
        <fullName>Fowl</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <masterLabel>Species</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/util/FacilityOutcomeUtil.cls
public class FacilityOutcomeUtil {
    public static final String[] EVAL_PROCESS_OUTCOME_OPTIONS = new String[]{'ARC','CARE'};
    public static void sendFosterSurveyEmail(List<Id> fosterIdList) {
        List<Messaging.SingleEmailMessage> fosterEmailList = new List<Messaging.SingleEmailMessage>();
        Id templateId = Util.getEmailTemplateId('Foster_Home_Survey');
        OrgWideEmailAddress orgWide = Util.getOrgWideEmailAddress('CRC Behavior Mgmt');
        Id orgWideId = orgWide == null ? null : orgWide.Id;
        for (Facility_Outcome__c foster : [SELECT Id, Point_of_Contact__c FROM Facility_Outcome__c WHERE Id IN :fosterIdList AND Point_of_Contact__r.Email != null]) {
            fosterEmailList.add(Util.createContactEmail(templateId, foster.Point_of_Contact__c, foster.Id, true, orgWideId));
        }
        //do not send emails if tests are running because it will fail if emails are turned off (typical in sandboxes)
        if(!test.isRunningTest()){
            Messaging.sendEmail(fosterEmailList);
        }
    }

    public static void handleEvaluationProcess(Set<Id> animalIds, Set<Id> foIds){
        //query the animals and their child facility/outcome records
        Animal__c[] toUpdate = new Animal__c[0];
        Task[] tasksToInsert = new Task[0];
        Date evalDueDate = Date.today().addDays(4);
        Id taskRecordTypeId = Util.getRecordTypeId('Task',AutoScheduleTasksUtil.EVALUATION_RECORD_TYPE_NAME);
        for(Animal__c dog : [
            SELECT Id, Evaluation_Due_Date__c, Behavior_Case_Worker__c,
            Animal_Name_Id__c, Current_Recent_Shelter_Location__c,
            (
                SELECT Id
                FROM Facilities_Outcomes__r
                WHERE Facility_Outcome__c IN :EVAL_PROCESS_OUTCOME_OPTIONS
                AND Id NOT IN :foIds
            )
            FROM Animal__c
            WHERE Id IN :animalIds
            AND Type_of_Animal__c = 'Dog'
        ]){
            //if there is only one facility outcome, we know we need to update the evalu due date and create a follow up task
            if(dog.Facilities_Outcomes__r.isEmpty()){
                dog.Evaluation_Due_Date__c = evalDueDate;
                toUpdate.add(dog);
            
                Task evalTask = new Task(
                    ActivityDate = evalDueDate,
                    Animal__c = dog.Id,
                    Description = 'Evaluation Due for: ' + dog.Animal_Name_Id__c + '(' + dog.Current_Recent_Shelter_Location__c + ')',
                    Priority = 'Normal',
                    RecordTypeId = taskRecordTypeId,
                    Species__c = 'Dog',
                    Status = 'Not Started',
                    Subject = 'Evaluation Due',
                    WhatId = dog.Id,
                    WhoId = dog.Behavior_Case_Worker__c
                );
                tasksToInsert.add(evalTask);
            }
        }

        update toUpdate;
        insert tasksToInsert;
    }
}