force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age Estimate at Intake</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Age_Estimate_at_Intake</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Behavior Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Behavior Case Worker)</relationshipLabel>
    <relationshipName>Beh_Case_Worker_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Discharged_to_Contact__c.field-meta.xml
<CustomField>
    <fullName>Discharged_to_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discharged to Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Discharged to Contact)</relationshipLabel>
    <relationshipName>Animals1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <scale>15</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Animal__c/recordTypes/Behavior.recordType-meta.xml
<RecordType>
    <fullName>Behavior</fullName>
    <active>true</active>
    <label>Behavior</label>
</RecordType>

force-app/main/default/objects/Animal_Exam_Sheet__c/Animal_Exam_Sheet__c.object-meta.xml
<CustomObject>
    <label>Animal Exam Sheet</label>
    <nameField>
        <displayFormat>EX-{0}</displayFormat>
        <label>Exam Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Exam Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animal Exam Sheets</relationshipLabel>
    <relationshipName>Animal_Exam_Sheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Animal_Exam_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Animal_Exam_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Exam Sheet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Animal_Exam_Sheet__c.Animal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Animal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Animal_Exam_Sheet__c</referenceTo>
    <relationshipLabel>Animal Exam Sheets</relationshipLabel>
    <relationshipName>Animal_Exam_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Babesia__c.field-meta.xml
<CustomField>
    <fullName>Babesia__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Babesia (INACTIVE)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Babesia_Results__c.field-meta.xml
<CustomField>
    <fullName>Babesia_Results__c</fullName>
    <label>Babesia Results (INACTIVE)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Editor__c.field-meta.xml
<CustomField>
    <fullName>Editor__c</fullName>
    <inlineHelpText>Please enter your initials, today&apos;s date, and time.</inlineHelpText>
    <label>Editor</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Felv_FIV_Results__c.field-meta.xml
<CustomField>
    <fullName>Felv_FIV_Results__c</fullName>
    <label>FeLV Results (INACTIVE)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Abnormal</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/FIV__c.field-meta.xml
<CustomField>
    <fullName>FIV__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FIV (INACTIVE)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/FIV_Results__c.field-meta.xml
<CustomField>
    <fullName>FIV_Results__c</fullName>
    <label>FIV Results (INACTIVE)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Abnormal</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Heartworm__c.field-meta.xml
<CustomField>
    <fullName>Heartworm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Heartworm</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Heartworm_Results__c.field-meta.xml
<CustomField>
    <fullName>Heartworm_Results__c</fullName>
    <label>Heartworm Results (INACTIVE)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Include_in_discharge__c.field-meta.xml
<CustomField>
    <fullName>Include_in_discharge__c</fullName>
    <inlineHelpText>Please select if this exam sheet needs to be included in the discharge form.</inlineHelpText>
    <label>Include in discharge?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Medication_Drug__c.field-meta.xml
<CustomField>
    <fullName>Medication_Drug__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medication/Drug</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Medication_Drug__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Medication</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Medication_Drug__c</referenceTo>
    <relationshipLabel>Animal Exam Sheets</relationshipLabel>
    <relationshipName>Animal_Exam_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Citizen</fullName>
            </value>
            <value>
                <fullName>Agency Representative</fullName>
            </value>
            <value>
                <fullName>Animal Control Officer</fullName>
            </value>
            <value>
                <fullName>Animal Owner</fullName>
            </value>
            <value>
                <fullName>Animal Rescue</fullName>
            </value>
            <value>
                <fullName>Animal Welfare Professional</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Code Enforcement Officer</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>County/Civil Attorney</fullName>
            </value>
            <value>
                <fullName>Defense Attorney</fullName>
            </value>
            <value>
                <fullName>Law Enforcement Contact</fullName>
            </value>
            <value>
                <fullName>Law Enforcement Officer</fullName>
            </value>
            <value>
                <fullName>Local Elected Official</fullName>
            </value>
            <value>
                <fullName>Officer/Complainant</fullName>
            </value>
            <value>
                <fullName>Prosecuting Attorney</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
            <value>
                <fullName>Senator</fullName>
            </value>
            <value>
                <fullName>Shelter Contact</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>State Representative</fullName>
            </value>
            <value>
                <fullName>State Senator</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Suspect</fullName>
            </value>
            <value>
                <fullName>US Representative</fullName>
            </value>
            <value>
                <fullName>US Senator</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Relocation Driver</fullName>
            </value>
            <value>
                <fullName>Behavior Case Worker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medication_Drug__c/Medication_Drug__c.object-meta.xml
<CustomObject>
    <label>Medication/Drug</label>
    <nameField>
        <label>Medication/Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medications/Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medication_Drug__c/fields/Behavior_Medication__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Medication__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Behavior Medication</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Treatment_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Treatment Bundle</label>
    <referenceTo>Treatment_Bundle__c</referenceTo>
    <relationshipLabel>Treatment Plans (Assigned Treatment Bundle)</relationshipLabel>
    <relationshipName>Assigned_Treatment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ARC/CARE</fullName>
            </value>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Age_Estimate_at_Intake.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Juvenile w/dam</fullName>
    </customValue>
    <customValue>
        <fullName>&lt; 6 months</fullName>
    </customValue>
    <customValue>
        <fullName>0-4 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-8 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>8-12 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>12-16 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 1 year</fullName>
    </customValue>
    <customValue>
        <fullName>1 year - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>2-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>5-7 years</fullName>
    </customValue>
    <customValue>
        <fullName>7-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>greater than 10 yrs</fullName>
    </customValue>
    <customValue>
        <fullName>Egg</fullName>
    </customValue>
    <customValue>
        <fullName>Chick: Up To 8 Weeks</fullName>
    </customValue>
    <customValue>
        <fullName>Pullet: Female &lt; 2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Adult: &gt;2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Stag: Male &lt;2YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (with dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (without dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Weanling</fullName>
    </customValue>
    <customValue>
        <fullName>Yearling</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>4-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>6-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>11-15 years</fullName>
    </customValue>
    <customValue>
        <fullName>15-20 years</fullName>
    </customValue>
    <customValue>
        <fullName>20+ years</fullName>
    </customValue>
    <customValue>
        <fullName>Chick (0-10 wks.)</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown At Intake</fullName>
    </customValue>
    <masterLabel>Age Estimate at Intake</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HomePageControllerTest.cls
@isTest
public class HomePageControllerTest {

    @testSetup
    static void setupData(){
        User cU = [SELECT Id, Location__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        cU.Location__c = 'All';
        update cU;
        
        User u = new User(firstname= 'Test',
                          lastname='XXXX',
                          Alias='Test',
                          Location__c = 'All',
                          email = 'test1234@example.com',
                          username= 'test1234xxx@test.com', 
                          profileId= [SELECT id, Name FROM Profile where name = 'System Administrator' ].id, 
                          emailencodingkey='UTF-8',
                          languagelocalekey='en_US',
                          localesidkey='en_US',
                          timezonesidkey='America/Los_Angeles');
        insert u;
        
        Case cs = new Case();
        insert cs;
        
        Contact con = new Contact(LastName='Test', MailingCity='Test', MailingState='AK',MailingCountry='United States');
        insert con;
        
        Contact con2 = new Contact(LastName='Test2', MailingCity='Test2', MailingState='AK',MailingCountry='United States', Contact_Type__c='Behavior Case Worker', Email='test5@domain.com');
        insert con2;
        
        System.runAs(u) {
            
        
        Animal__c anim = TestDataFactory.createAnimalWithName('Test');
        anim.Behavior_Case_Worker__c = con2.Id;
        anim.Discharged_to_Contact__c = con.Id;
        anim.Age__c = 'Unknown At Intake';

        update anim;
        
        Medication_Drug__c drug = new Medication_Drug__c(Name='drug1', Behavior_Medication__c=true);
        insert drug;
        
   		Animal_Exam_Sheet__c objAnimalExam = new Animal_Exam_Sheet__c (Animal__c =anim.id,Heartworm__c=true,FIV__c=true,FIV_Results__c='FIVResult',Heartworm_Results__c='heartwormResult',Babesia__c=true,Babesia_Results__c='babesiaResult',Felv_FIV_Results__c='FelvFIV',Include_in_discharge__c ='Yes',Editor__c='AS');
        insert objAnimalExam;
        
                
        Treatment_Bundle__c bundle = new Treatment_Bundle__c();
        bundle.Name = 'Master';
        bundle.IsActive__c = true;
        bundle.IsMaster__c = true;
        insert bundle;
        
        Treatment_Plan__c plan = new Treatment_Plan__c(
          IsActive__c = true, 
          Description__c = 'Test', 
          Animal__c = anim.Id, 
          Problem_Behavior__c = 'Fear of People - Mild',
            Treatment_Priority__c = 'Daily – 7 days'
        );
        
        insert plan;
        
        Protocol__c protocol = new Protocol__c();
        protocol.Name = 'Test';
        protocol.IsActive__c = true;
        protocol.Description__c = 'This is a Test Protocol';
        insert protocol;
        
        Plan_Protocol__c newProtocol = new Plan_Protocol__c(Treatment_Plan__c = plan.Id, Protocol__c = protocol.Id, IsRemoved__c = Math.mod(1, 2) != 0);
        insert newProtocol;
            
        }

        Animal__c anim2 = TestDataFactory.createAnimalWithName('Test2');
        anim2.Behavior_Case_Worker__c = con2.Id;
        anim2.Discharged_to_Contact__c = con.Id;
        anim2.Age__c = 'Unknown At Intake';

        update anim2;
        
        Task treatmentTask = new Task();
        treatmentTask.Subject = 'Animal Treatment';
        treatmentTask.ActivityDate = System.today();
        treatmentTask.Editor__c = 'Test';
        treatmentTask.Animal_Exam_Sheet_Lookup__c = [select id from Animal_Exam_Sheet__c LIMIT 1].Id;
        treatmentTask.Frequency_Of_Treatment__c = 'BID';
        treatmentTask.Priority = 'Low';
        treatmentTask.Status = 'Not Started';
        treatmentTask.WhatId = anim2.Id;
        treatmentTask.Animal__c = treatmentTask.WhatId;
        treatmentTask.Medication__c = [select id from Medication_Drug__c LIMIT 1].Id;
        treatmentTask.RecordTypeId = Util.getRecordTypeId('Task','Treatments');
		treatmentTask.Species__c = 'Dog';
        insert treatmentTask;

    }
    
    @isTest
    static void testTasks(){
        List<HomePageController.animalTaskRec> recs = HomePageController.getAnmialTasks(10, 0);
        System.assertNotEquals(null, recs);
    }
    
    @isTest
    static void testTreatments(){
        List<HomePageController.animalTreatmentRec> recs = HomePageController.getAnmialTreatement();
        System.assertNotEquals(null, recs);
    }
}