force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Enrichment__c/Daily_Enrichment__c.object-meta.xml
<CustomObject>
    <label>Daily Enrichment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Daily Enrichment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Enrichment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Enrichment__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Daily Enrichment</relationshipLabel>
    <relationshipName>Daily_Enrichment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Enrichment__c/fields/DE_Date__c.field-meta.xml
<CustomField>
    <fullName>DE_Date__c</fullName>
    <label>DE Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Enrichment__c/fields/Enrichment_Activities__c.field-meta.xml
<CustomField>
    <fullName>Enrichment_Activities__c</fullName>
    <label>Enrichment Activities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Enrichment_Activities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Enrichment__c/fields/Enrichment_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Enrichment_Coordinator__c</fullName>
    <label>Enrichment Coordinator</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hailey Kohl</fullName>
            </value>
            <value>
                <fullName>Carrie Bretz</fullName>
            </value>
            <value>
                <fullName>Tony Rankin</fullName>
            </value>
            <value>
                <fullName>Courtney Leigh</fullName>
            </value>
            <value>
                <fullName>Kay Duffy Taylor</fullName>
            </value>
            <value>
                <fullName>Bill Duvall</fullName>
            </value>
            <value>
                <fullName>Jess Drew</fullName>
            </value>
            <value>
                <fullName>Joanne Smith</fullName>
            </value>
            <value>
                <fullName>Vicky Watkins</fullName>
            </value>
            <value>
                <fullName>Heather Boothe</fullName>
            </value>
            <value>
                <fullName>Scott Sherlock</fullName>
            </value>
            <value>
                <fullName>Tom Griswold</fullName>
            </value>
            <value>
                <fullName>EG Aguilar</fullName>
            </value>
            <value>
                <fullName>Adam Gebauer</fullName>
            </value>
            <value>
                <fullName>Cindy Walden</fullName>
            </value>
            <value>
                <fullName>Andrea Stout</fullName>
            </value>
            <value>
                <fullName>Catherine Adair</fullName>
            </value>
            <value>
                <fullName>Jacqui Moreland</fullName>
            </value>
            <value>
                <fullName>Tiffany Van Hook</fullName>
            </value>
            <value>
                <fullName>Lois Michael</fullName>
            </value>
            <value>
                <fullName>Jeremy Robichaud</fullName>
            </value>
            <value>
                <fullName>Jeannie Pittman</fullName>
            </value>
            <value>
                <fullName>Joe Gordon</fullName>
            </value>
            <value>
                <fullName>Sarah Getman</fullName>
            </value>
            <value>
                <fullName>Lacie Davis</fullName>
            </value>
            <value>
                <fullName>Joe Hinkle</fullName>
            </value>
            <value>
                <fullName>Lindsey Cooke</fullName>
            </value>
            <value>
                <fullName>Raymond Willis</fullName>
            </value>
            <value>
                <fullName>Salina Wenzel</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Enrichment__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Enrichment__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Treatment Plan</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Daily Enrichment</relationshipLabel>
    <relationshipName>Enrichments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/AssignedTreatmentBundleId__c.field-meta.xml
<CustomField>
    <fullName>AssignedTreatmentBundleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Treatment Bundle</label>
    <referenceTo>Treatment_Bundle__c</referenceTo>
    <relationshipLabel>Treatment Plans (Assigned Treatment Bundle)</relationshipLabel>
    <relationshipName>Assigned_Treatment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Enrichment_Activities__c.field-meta.xml
<CustomField>
    <fullName>Enrichment_Activities__c</fullName>
    <label>Enrichment Activities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Enrichment_Activities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Shelter_Color_Code__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Color_Code__c</fullName>
    <label>Shelter Color Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Enrichment_Activities.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 on 1</fullName>
    </customValue>
    <customValue>
        <fullName>Backyard</fullName>
    </customValue>
    <customValue>
        <fullName>Ball/rock pit (foraging)</fullName>
    </customValue>
    <customValue>
        <fullName>Basic Training</fullName>
    </customValue>
    <customValue>
        <fullName>Dig pit</fullName>
    </customValue>
    <customValue>
        <fullName>Fetch with rules</fullName>
    </customValue>
    <customValue>
        <fullName>Foster overnights</fullName>
    </customValue>
    <customValue>
        <fullName>Four on the Floor for Leash</fullName>
    </customValue>
    <customValue>
        <fullName>Gym</fullName>
    </customValue>
    <customValue>
        <fullName>IPY</fullName>
    </customValue>
    <customValue>
        <fullName>Kennel Presence</fullName>
    </customValue>
    <customValue>
        <fullName>LLW</fullName>
    </customValue>
    <customValue>
        <fullName>Nose Work</fullName>
    </customValue>
    <customValue>
        <fullName>Outside ExPen</fullName>
    </customValue>
    <customValue>
        <fullName>Office Time</fullName>
    </customValue>
    <customValue>
        <fullName>Offsite Trips</fullName>
    </customValue>
    <customValue>
        <fullName>OPY</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Outside Walks</fullName>
    </customValue>
    <customValue>
        <fullName>PC Tug</fullName>
    </customValue>
    <customValue>
        <fullName>Puppy Enrichment/Socialization</fullName>
    </customValue>
    <customValue>
        <fullName>Puppy Handling</fullName>
    </customValue>
    <customValue>
        <fullName>Quiet Time</fullName>
    </customValue>
    <customValue>
        <fullName>Real-Life Room</fullName>
    </customValue>
    <customValue>
        <fullName>Shelter Notes</fullName>
    </customValue>
    <customValue>
        <fullName>Snuffle mat</fullName>
    </customValue>
    <customValue>
        <fullName>Trick Training</fullName>
    </customValue>
    <customValue>
        <fullName>Tug pully</fullName>
    </customValue>
    <customValue>
        <fullName>Tug with rules</fullName>
    </customValue>
    <customValue>
        <fullName>Walk</fullName>
    </customValue>
    <masterLabel>Enrichment Activities</masterLabel>
</GlobalValueSet>

force-app/main/default/test/test_EnrichmentQuickCreateController.cls
@isTest
public with sharing class test_EnrichmentQuickCreateController {
    @isTest
    static void getTreatmentPlanSuccess() {
        Treatment_Plan__c plan = TestDataFactory.createPlan();
        Test.startTest();
        Treatment_Plan__c controllerPlan = EnrichmentQuickCreateController.getTreatmentPlan(plan.Animal__c);
        Test.stopTest();
        Treatment_Plan__c planFields = [SELECT Id, AssignedTreatmentBundleId__c, Enrichment_Activities__c, Shelter_Color_Code__c FROM Treatment_Plan__c WHERE Id = :plan.Id LIMIT 1];
        System.assertEquals(planFields.Id, controllerPlan.Id);
        System.assertEquals(planFields.AssignedTreatmentBundleId__c, controllerPlan.AssignedTreatmentBundleId__c);
        System.assertEquals(planFields.Enrichment_Activities__c, controllerPlan.Enrichment_Activities__c);
        System.assertEquals(planFields.Shelter_Color_Code__c, controllerPlan.Shelter_Color_Code__c);
    }

    @isTest
    static void getTreatmentPlanWrongId() {
        Animal__c a = TestDataFactory.createAnimal();
        Test.startTest();
        Treatment_Plan__c controllerPlan = EnrichmentQuickCreateController.getTreatmentPlan(a.Id);
        Test.stopTest();
        System.assertEquals(null, controllerPlan);
    }

    @isTest
    static void getTreatmentPlanBadId() {
        Treatment_Plan__c plan = TestDataFactory.createPlan();
        String idDeleted = plan.Animal__c;
        delete plan;
        Test.startTest();
        Treatment_Plan__c controllerPlan = EnrichmentQuickCreateController.getTreatmentPlan(idDeleted);
        Test.stopTest();
        System.assertEquals(null, controllerPlan);
    }

    @isTest
    static void createDailyEnrichment() {
        Treatment_Plan__c plan = TestDataFactory.createPlan();
        Daily_Enrichment__c enrichment = new Daily_Enrichment__c(
            Animal__c = plan.Animal__c,
            Notes__c = 'Test notes for test data factory',
            DE_Date__c = System.today(),
            Enrichment_Coordinator__c = 'Hailey Kohl'
        );
        Test.startTest();
        Daily_Enrichment__c created = EnrichmentQuickCreateController.createQuickEnrichment(enrichment);
        Test.stopTest();
        System.assertEquals('Test notes for test data factory', created.Notes__c);
        System.assertEquals(plan.Animal__c, created.Animal__c);
        System.assertEquals(System.today(), created.DE_Date__c);
        System.assertEquals('Hailey Kohl', created.Enrichment_Coordinator__c);
    }

    @isTest
    static void createDailyEnrichmentBadRecord() {
        Daily_Enrichment__c enrichment = new Daily_Enrichment__c();
        Test.startTest();
        Daily_Enrichment__c created = EnrichmentQuickCreateController.createQuickEnrichment(enrichment);
        Test.stopTest();
        System.assertEquals(null, created);
    }
}