force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Enrichment__c/Daily_Enrichment__c.object-meta.xml
<CustomObject>
    <label>Daily Enrichment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Daily Enrichment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Enrichment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Enrichment__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Daily Enrichment</relationshipLabel>
    <relationshipName>Daily_Enrichment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Enrichment__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Observation__c/Observation__c.object-meta.xml
<CustomObject>
    <label>Observation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Observation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Observations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Observation__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Observations</relationshipLabel>
    <relationshipName>Observations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Observation__c/fields/Daily_Enrichment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Enrichment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Enrichment</label>
    <referenceTo>Daily_Enrichment__c</referenceTo>
    <relationshipLabel>Observations</relationshipLabel>
    <relationshipName>Observations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Observation__c/fields/Observation_Notes__c.field-meta.xml
<CustomField>
    <fullName>Observation_Notes__c</fullName>
    <label>Observation Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Observation__c/fields/Observation_Reported_By__c.field-meta.xml
<CustomField>
    <fullName>Observation_Reported_By__c</fullName>
    <label>Observation Reported By</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Observation__c/fields/Observation_Type__c.field-meta.xml
<CustomField>
    <fullName>Observation_Type__c</fullName>
    <label>Observation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Observation</fullName>
            </value>
            <value>
                <fullName>Happy Tale</fullName>
            </value>
            <value>
                <fullName>Concern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/test/test_ObservationQuickCreateController.cls
@isTest
public with sharing class test_ObservationQuickCreateController {
    @isTest
    static void getEnrichmentNotesSuccess() {
        Daily_Enrichment__c enrichment = TestDataFactory.createEnrichment();
        Test.startTest();
        Daily_Enrichment__c enrichmentNotes = ObservationQuickCreateController.getEnrichmentNotes(enrichment.Id);
        Test.stopTest();
        System.assertEquals(enrichment.Notes__c, enrichmentNotes.Notes__c);
        System.assertEquals(enrichment.Animal__c, enrichmentNotes.Animal__c);
    }

    @isTest
    static void getEnrichmentNotesWrongId() {
        Animal__c a = TestDataFactory.createAnimal();
        Test.startTest();
        Daily_Enrichment__c enrichmentNotes = ObservationQuickCreateController.getEnrichmentNotes(a.Id);
        Test.stopTest();
        System.assertEquals(null, enrichmentNotes);
    }

    @isTest
    static void getEnrichmentNotesBadId() {
        Daily_Enrichment__c enrichment = TestDataFactory.createEnrichment();
        String idDeleted = enrichment.Id;
        delete enrichment;
        Test.startTest();
        Daily_Enrichment__c enrichmentNotes = ObservationQuickCreateController.getEnrichmentNotes(idDeleted);
        Test.stopTest();
        System.assertEquals(null, enrichmentNotes);
    }

    @isTest
    static void createObservationHappyTail() {
        Daily_Enrichment__c enrichment = TestDataFactory.createEnrichment();
        Observation__c observation = new Observation__c(
            Observation_Reported_By__c = 'Reporter',
            Observation_Notes__c = enrichment.Notes__c,
            Animal__c = enrichment.Animal__c,
            Daily_Enrichment__c = enrichment.Id,
            Observation_Type__c = 'Happy Tail'
        );
        Test.startTest();
        Observation__c created = ObservationQuickCreateController.createQuickObservation(observation);
        Test.stopTest();
        System.assertEquals(enrichment.Id, created.Daily_Enrichment__c);
        System.assertEquals(enrichment.Notes__c, created.Observation_Notes__c);
        System.assertEquals(enrichment.Animal__c, created.Animal__c);
        System.assertEquals('Reporter', created.Observation_Reported_By__c);
        System.assertEquals('Happy Tail', created.Observation_Type__c);
    }

    @isTest
    static void createObservationConcern() {
        Daily_Enrichment__c enrichment = TestDataFactory.createEnrichment();
        Observation__c observation = new Observation__c(
            Observation_Reported_By__c = 'Reporter',
            Observation_Notes__c = enrichment.Notes__c,
            Animal__c = enrichment.Animal__c,
            Daily_Enrichment__c = enrichment.Id,
            Observation_Type__c = 'Concern'
        );
        Test.startTest();
        Observation__c created = ObservationQuickCreateController.createQuickObservation(observation);
        Test.stopTest();
        System.assertEquals(enrichment.Id, created.Daily_Enrichment__c);
        System.assertEquals(enrichment.Notes__c, created.Observation_Notes__c);
        System.assertEquals(enrichment.Animal__c, created.Animal__c);
        System.assertEquals('Reporter', created.Observation_Reported_By__c);
        System.assertEquals('Concern', created.Observation_Type__c);
    }

    @isTest
    static void createObservationBadRecord() {
        Observation__c observation = new Observation__c();
        Test.startTest();
        Observation__c created = ObservationQuickCreateController.createQuickObservation(observation);
        Test.stopTest();
        System.assertEquals(null, created);
    }
}