force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Name_Id__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name_Id__c</fullName>
    <formula>Animal_Name__c + &apos; (&apos; +  Name + &apos;)&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animal Name/Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>For EQUINE, see Help Text</description>
    <inlineHelpText>For EQUINE, choose one of the following: Horse, Donkey, Mule, Draft Horse, Mini Horse, Pony, Mini Mule, Mini Donkey</inlineHelpText>
    <label>Breed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Animal_Age_Formatted__c.field-meta.xml
<CustomField>
    <fullName>Current_Animal_Age_Formatted__c</fullName>
    <formula>IF( ISNULL( Today_Test__c ) ,
IF(NOT(ISBLANK(Estimated_Date_of_Birth__c)),
    TEXT(FLOOR(( (TODAY() - Estimated_Date_of_Birth__c) / 365)))
    &amp;&apos; Years&apos; &amp; &apos; &apos; &amp;
    TEXT(FLOOR( (MOD( (TODAY() - Estimated_Date_of_Birth__c),365)/30))) &amp;&apos; Months&apos;,
    IF(NOT(ISBLANK(Animal_Age__c)) &amp;&amp; NOT(ISBLANK(TEXT(Animal_Age_Units__c))),
        IF(TEXT(Animal_Age_Units__c) = &apos;Days&apos;,
            TEXT(FLOOR(( (TODAY() - (Animal_Age_Units_Changed_Date__c - Animal_Age__c))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (TODAY() - (Animal_Age_Units_Changed_Date__c - Animal_Age__c)),365)/30))) &amp;&apos; Months&apos;,
        IF(TEXT(Animal_Age_Units__c) = &apos;Weeks&apos;,
            TEXT(FLOOR(( (TODAY() - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (TODAY() - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c))),365)/30))) &amp;&apos; Months&apos; ,
        IF(TEXT(Animal_Age_Units__c) = &apos;Months&apos;,
            IF(Animal_Age__c &lt; 12,
                &apos;0 Years &apos; &amp; TEXT(Animal_Age__c) &amp; &apos; Months&apos;,
                TEXT(FLOOR( (TODAY()  - ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))/365))
                &amp;&apos; Years&apos; &amp; &apos; &apos;
                &amp; TEXT(FLOOR( MOD( (TODAY()  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))),365)/30)) &amp;&apos; Months&apos;),
        IF(TEXT(Animal_Age_Units__c) = &apos;Years&apos;,
            TEXT(FLOOR(( (TODAY() - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -12 * Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD(TODAY() - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, 12)),365)/30))) &amp;&apos; Months&apos;,
        &quot;&quot;)))) ,
    &quot;&quot;)
),

IF(NOT(ISBLANK(Estimated_Date_of_Birth__c)),
    TEXT(FLOOR(( (Today_Test__c  - Estimated_Date_of_Birth__c) / 365)))
    &amp;&apos; Years&apos; &amp; &apos; &apos; &amp;
    TEXT(FLOOR( (MOD( (Today_Test__c  - Estimated_Date_of_Birth__c),365)/30))) &amp;&apos; Months&apos;,
    IF(NOT(ISBLANK(Animal_Age__c)) &amp;&amp; NOT(ISBLANK(TEXT(Animal_Age_Units__c))),
        IF(TEXT(Animal_Age_Units__c) = &apos;Days&apos;,
            TEXT(FLOOR(( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - Animal_Age__c))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - Animal_Age__c)),365)/30))) &amp;&apos; Months&apos;,
        IF(TEXT(Animal_Age_Units__c) = &apos;Weeks&apos;,
            TEXT(FLOOR(( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c))),365)/30))) &amp;&apos; Months&apos; ,
        IF(TEXT(Animal_Age_Units__c) = &apos;Months&apos;,
            IF(Animal_Age__c &lt; 12,
                &apos;0 Years &apos; &amp; TEXT(Animal_Age__c) &amp; &apos; Months&apos;,
                TEXT(FLOOR( (Today_Test__c  - ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))/365))
                &amp;&apos; Years&apos; &amp; &apos; &apos;
                &amp; TEXT(FLOOR( MOD( (Today_Test__c  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))),365)/30)) &amp;&apos; Months&apos;),
        IF(TEXT(Animal_Age_Units__c) = &apos;Years&apos;,
            TEXT(FLOOR(( (Today_Test__c  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -12 * Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD(Today_Test__c  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, 12)),365)/30))) &amp;&apos; Months&apos;,
        &quot;&quot;)))) ,
    &quot;&quot;)
)

)</formula>
    <label>Current Animal Age</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Behavior_Grade__c.field-meta.xml
<CustomField>
    <fullName>Current_Behavior_Grade__c</fullName>
    <label>Current Behavior Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>No Evaluation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <label>Current Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <scale>15</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/Session_Protocol__c.object-meta.xml
<CustomObject>
    <label>Session Protocol</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Session Protocol Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocols</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/fields/IsRemoved__c.field-meta.xml
<CustomField>
    <fullName>IsRemoved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Removed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Overall_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score__c</fullName>
    <label>Overall Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Beginning/Acquisition</fullName>
            </value>
            <value>
                <fullName>2. Catching On/ Fluency</fullName>
            </value>
            <value>
                <fullName>3. Almost There/ Generalization</fullName>
            </value>
            <value>
                <fullName>4. Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Overall_Score_Number__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score_Number__c</fullName>
    <formula>VALUE(LEFT(TEXT(Overall_Score__c),1))</formula>
    <label>Overall Score (Number)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Protocol_Name__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Name__c</fullName>
    <formula>ProtocolId__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Protocol Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/TreatmentSessionId__c.field-meta.xml
<CustomField>
    <fullName>TreatmentSessionId__c</fullName>
    <label>Treatment Session</label>
    <referenceTo>Treatment_Session__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/Session_Protocol_Scale__c.object-meta.xml
<CustomObject>
    <label>Session Protocol Scale</label>
    <nameField>
        <displayFormat>SPSN-{00000}</displayFormat>
        <label>Session Protocol Scale Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocol Scales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Session_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Session_Protocol__c</fullName>
    <label>Session Protocol</label>
    <referenceTo>Session_Protocol__c</referenceTo>
    <relationshipLabel>Session Protocol Scales</relationshipLabel>
    <relationshipName>Session_Protocol_Scales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Treatment_Priority__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Priority__c</fullName>
    <label>Treatment Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Treatment</fullName>
                <default>true</default>
                <label>No Treatment</label>
            </value>
            <value>
                <fullName>Daily – 7 days</fullName>
            </value>
            <value>
                <fullName>High – 5 days</fullName>
            </value>
            <value>
                <fullName>Medium – 4 days</fullName>
            </value>
            <value>
                <fullName>Low – 3 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/Treatment_Session__c.object-meta.xml
<CustomObject>
    <label>Treatment Session</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Treatment Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Session__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Sessions</relationshipLabel>
    <relationshipName>Treatment_Sessions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <label>Treatment Plan</label>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Treatment Sessions</relationshipLabel>
    <relationshipName>Treatment_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ARC/CARE</fullName>
            </value>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TreatmentsByDogPDFController.cls
public with sharing class TreatmentsByDogPDFController {
    public DogInfoWrapper[] dogInfoWrapperList {get; set;}
    public String dogList{get;set;}
    public Boolean isCRCApp{get;set;}

    public TreatmentsByDogPDFController(){        
        dogList = apexpages.currentpage().getparameters().get('dogList');
        isCRCApp = apexpages.currentpage().getparameters().get('appName') == 'CRC Dog Database';
        Id[] dogList = dogList.split(',');
        System.debug('dogList: ' + dogList);
        dogInfoWrapperList = getDogInfo(dogList, isCRCApp);
    }

    @testVisible
    private static DogInfoWrapper[] getDogInfo(Id[] dogIds, Boolean isCRCApp){
        //if is not CRC no need to get medications
        Map<Id, Set<String>>  medicationsByDogMap = new Map<Id, Set<String>>();
        if(isCRCApp){
            medicationsByDogMap = getDogMedications(dogIds);
        }

        DogInfoWrapper[] dogInfos = new DogInfoWrapper[0];
        Map<Id, Map<String, TxProtocolWrapper>> treatmentsByDogMap = getDogTreatments(dogIds);

        for(Animal__c dog : [
            SELECT Id, Animal_Name_Id__c, Gender__c, Breed__c, Current_Animal_Age_Formatted__c, Current_Location__c, 
            Current_Behavior_Grade__c,
            (SELECT Id, Treatment_Priority__c FROM Treatment_Plan__r WHERE IsActive__c = true LIMIT 1)
            FROM Animal__c 
            WHERE Id IN: dogIds 
        ]){
            DogInfoWrapper dogInfo = new DogInfoWrapper(dog);

            if(medicationsByDogMap.containsKey(dog.Id)){
                dogInfo.medications = string.join(new List<String>(medicationsByDogMap.get(dog.Id)), '; ');
            }

            if(treatmentsByDogMap.containsKey(dog.Id)){
                Map<String, TxProtocolWrapper> dogTreatments = treatmentsByDogMap.get(dog.Id);
                dogInfo.txProtocols = dogTreatments.values();
            }            
            dogInfos.add(dogInfo);
        }
        return dogInfos;
    }    

    @testVisible
    private static Map<Id, Set<String>> getDogMedications(Id[] dogIds){
        Map<Id, Set<String>> dogToMedicationMap = new Map<Id, Set<String>>();
        Id recordTypeId = Util.getRecordTypeId('Task',AutoScheduleTasksUtil.TREATMENT_TASK_RECORD_TYPE_NAME);

        for(Task t : [
            SELECT Id, Medication__r.Name, Animal__c 
            FROM Task 
            WHERE RecordTypeId =: recordTypeId
            AND Animal__c IN: dogIds
            AND Medication__r.Behavior_Medication__c = true
            AND Status != 'Completed'
            AND ((IsRecurrence = true AND RecurrenceEndDateOnly >= TODAY)
            OR (RecurrenceActivityId = null AND ActivityDate >= TODAY))

        ]){
            if(dogToMedicationMap.containsKey(t.Animal__c)){
                dogToMedicationMap.get(t.Animal__c).add(t.Medication__r.Name);
            } else {
                dogToMedicationMap.put(t.Animal__c, new Set<String>{t.Medication__r.Name});
            }
        }

        return dogToMedicationMap;
    }

    @testVisible
    private static Map<Id, Map<String, TxProtocolWrapper>> getDogTreatments(Id[] dogIds){
        Map<Id, Map<String, TxProtocolWrapper>> m_dogToProtocols = new Map<Id, Map<String, TxProtocolWrapper>>();
               
        Session_Protocol__c[] sessionProtocols = getSessionProtocols (dogIds);
        for(Session_Protocol__c sp : sessionProtocols){
            Map<String, TxProtocolWrapper> m_protocols = new Map<String, TxProtocolWrapper>();
            if(m_dogToProtocols.containsKey(sp.TreatmentSessionId__r.Animal__c)){
                m_protocols = m_dogToProtocols.get(sp.TreatmentSessionId__r.Animal__c);
            }

            TreatmentWrapper treatment = new TreatmentWrapper(sp);

            if(m_protocols.containsKey(sp.Protocol_Name__c)){
                m_protocols.get(sp.Protocol_Name__c).sessionProtocols.add(treatment);
            }
            else{
                TxProtocolWrapper protoWrapper = new TxProtocolWrapper(sp);
                protowrapper.sessionProtocols.add(treatment);
                m_protocols.put(sp.Protocol_Name__c, protoWrapper);
            }
            m_dogToProtocols.put(sp.TreatmentSessionId__r.Animal__c, m_protocols);
        }
        return m_dogToProtocols;
    }

     private static Session_Protocol__c[] getSessionProtocols(Id[] dogIds){
        return [
            SELECT Id, Protocol_Name__c, isRemoved__c, Overall_Score__c, Overall_Score_Number__c, Overall_Score_Color__c, TreatmentSessionId__r.Treatment_Plan__c,
            TreatmentSessionId__c, TreatmentSessionId__r.Session_Date__c, ProtocolId__c, ProtocolId__r.Protocol_Categories__c, TreatmentSessionId__r.Animal__c,
            TreatmentSessionId__r.Treatment_Plan__r.IsActive__c,Protocol_Notes__c,
            (SELECT Id, Protocol_Scale_Name__c,Protocol_Score__c FROM Session_Protocol_Scales__r)
            FROM Session_Protocol__c
            WHERE TreatmentSessionId__r.Animal__c IN :dogIds
            AND Overall_Score__c != null
            ORDER BY ProtocolId__r.Protocol_Categories__c ASC, Protocol_Name__c ASC, TreatmentSessionId__r.Session_Date__c DESC
        ];
    }

    public class DogInfoWrapper{
        @AuraEnabled public Id id {get;set;}
        @AuraEnabled public String name {get;set;}
        @AuraEnabled public String gender {get;set;}
        @AuraEnabled public String breed {get;set;}
        @AuraEnabled public String age {get;set;}
        @AuraEnabled public String location {get;set;}
        @AuraEnabled public String evalGrade {get;set;}
        @AuraEnabled public String txPriority {get;set;}
        @AuraEnabled public String medications {get;set;}
        @AuraEnabled public Boolean hideMedications {get;set;}

        @AuraEnabled public TxProtocolWrapper[] txProtocols {get;set;}
        
        public DogInfoWrapper(Animal__c dog){
            User u = [SELECT Id, Location__c FROM User WHERE Id = :userInfo.getUserId() LIMIT 1];
            
            this.id = dog.Id;
            this.name = dog.Animal_Name_Id__c;
            this.gender = dog.Gender__c;
            this.breed = dog.Breed__c;
            this.age = dog.Current_Animal_Age_Formatted__c;
            this.location = dog.Current_Location__c;
            this.evalGrade = dog.Current_Behavior_Grade__c;
            this.txPriority = !dog.Treatment_Plan__r.isEmpty() ? dog.Treatment_Plan__r[0].Treatment_Priority__c : null;
            this.hideMedications = u.Location__c == 'ARC/CARE';
        }
    }

    public class TxProtocolWrapper{
        @AuraEnabled public String name {get;set;}
        @AuraEnabled public String category {get;set;}
        @AuraEnabled public TreatmentWrapper[] sessionProtocols {get; set;}

        public TxProtocolWrapper(Session_Protocol__c sp){
            this.name = sp.Protocol_Name__c;
            this.category = sp.ProtocolId__r.Protocol_Categories__c;
            this.sessionProtocols = new TreatmentWrapper[0];
        }    
    }

    public class TreatmentWrapper{
        @AuraEnabled public Id id {get;set;}
        @AuraEnabled public String score {get;set;}
        @AuraEnabled public String colorText {get;set;}
        @AuraEnabled public String txDateFormatted {get;set;}
        @AuraEnabled public String protocolNotes {get;set;}
        @AuraEnabled public String fearBest {get;set;}
        @AuraEnabled public String fearWorst {get;set;}
        @AuraEnabled public String arousalBest {get;set;}
        @AuraEnabled public String arousalWorst {get;set;}
        @AuraEnabled public String agressiveBest {get;set;}
        @AuraEnabled public String agressionMovement {get;set;}

        public TreatmentWrapper(Session_Protocol__c sp){
            this.id = sp.Id;
            this.score = sp.Overall_Score__c;
            this.colorText = sp.Overall_Score_Number__c == 1 ? 'Red' :
                sp.Overall_Score_Number__c == 2 ? 'Orange' :
                sp.Overall_Score_Number__c == 3 ? 'Yellow' :
                sp.Overall_Score_Number__c == 4 ? 'Green' : null;

            if(sp.TreatmentSessionId__r.Session_Date__c != null){
                this.txDateFormatted = (String) sp.TreatmentSessionId__r.Session_Date__c.format();
            }
            this.protocolNotes = sp.Protocol_Notes__c;

            for(Session_Protocol_Scale__c scale : sp.Session_Protocol_Scales__r){
                System.debug('scale.Protocol_Scale_Name__c: ' + scale);
                switch on scale.Protocol_Scale_Name__c {
                    when 'Fear - Best' {
                        this.fearBest = scale.Protocol_Score__c;
                    }
                    when 'Fear - Worst' {
                        this.fearWorst = scale.Protocol_Score__c;
                    }
                    when 'Arousal - Best' {
                        this.arousalBest = scale.Protocol_Score__c;
                    }
                    when 'Arousal - Worst' {
                        this.arousalWorst = scale.Protocol_Score__c;
                    }
                    when 'Aggression - Movement' {
                        this.agressiveBest = scale.Protocol_Score__c;
                    }
                    when 'Aggressive - Worst' {
                        this.agressionMovement = scale.Protocol_Score__c;
                    }
                }
            }
        }
    }
}