force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Play_Rating__c.field-meta.xml
<CustomField>
    <fullName>Play_Rating__c</fullName>
    <label>Play Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Playgroup_Individual_Notes__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Individual_Notes__c</fullName>
    <label>Playgroup Individual Notes</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/Animal_Playgroup__c.object-meta.xml
<CustomObject>
    <label>Animal Playgroup</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Animal Playgroup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Playgroups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Playgroup__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Common_Playgroup_Note_Sections__c.field-meta.xml
<CustomField>
    <fullName>Common_Playgroup_Note_Sections__c</fullName>
    <label>Common Playgroup Note Sections</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Greeting</fullName>
            </value>
            <value>
                <fullName>After Greeting</fullName>
            </value>
            <value>
                <fullName>Approached by another dog</fullName>
            </value>
            <value>
                <fullName>Handler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Common_Playgroup_Notes__c.field-meta.xml
<CustomField>
    <fullName>Common_Playgroup_Notes__c</fullName>
    <label>Common Playgroup Notes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Greeted – tense</fullName>
            </value>
            <value>
                <fullName>Greeted – politely</fullName>
            </value>
            <value>
                <fullName>Greeted – rude but playful</fullName>
            </value>
            <value>
                <fullName>Greeted – playful</fullName>
            </value>
            <value>
                <fullName>Greeted – no greeting</fullName>
            </value>
            <value>
                <fullName>Greeted – rude, aroused, not social</fullName>
            </value>
            <value>
                <fullName>Disengaged - remained tense</fullName>
            </value>
            <value>
                <fullName>Disengaged – relaxed some</fullName>
            </value>
            <value>
                <fullName>Disengaged – relaxed and milled</fullName>
            </value>
            <value>
                <fullName>Played – chase</fullName>
            </value>
            <value>
                <fullName>Played – wrestle</fullName>
            </value>
            <value>
                <fullName>Played – rude</fullName>
            </value>
            <value>
                <fullName>Played – roughly</fullName>
            </value>
            <value>
                <fullName>Played – boxed</fullName>
            </value>
            <value>
                <fullName>Played – arousal escalated</fullName>
            </value>
            <value>
                <fullName>Aggressed</fullName>
            </value>
            <value>
                <fullName>Took breaks</fullName>
            </value>
            <value>
                <fullName>Unresponsive to dogs’ correction</fullName>
            </value>
            <value>
                <fullName>Tolerated play solicitations</fullName>
            </value>
            <value>
                <fullName>Tolerated rude behavior</fullName>
            </value>
            <value>
                <fullName>Appropriately corrected rude behavior</fullName>
            </value>
            <value>
                <fullName>Overcorrected rude approach</fullName>
            </value>
            <value>
                <fullName>Defensive</fullName>
            </value>
            <value>
                <fullName>Responded to handler correction</fullName>
            </value>
            <value>
                <fullName>Unresponsive to handler correction</fullName>
            </value>
            <value>
                <fullName>Requires drag for TO</fullName>
            </value>
            <value>
                <fullName>Requires Muzzle</fullName>
            </value>
            <value>
                <fullName>Requires handler to crate breaks in play</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Play_Rating__c.field-meta.xml
<CustomField>
    <fullName>Play_Rating__c</fullName>
    <label>Play Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Playgroup_Individual_Notes__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Individual_Notes__c</fullName>
    <label>PG Notes for this Dog</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Playgroup_Session__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Session</label>
    <referenceTo>Playgroup_Session__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/Playgroup_Session__c.object-meta.xml
<CustomObject>
    <label>Playgroup Session</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroup Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup_Session__c/fields/Animal_Playgroup__c.field-meta.xml
<CustomField>
    <fullName>Animal_Playgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Playgroup</label>
    <referenceTo>Animal_Playgroup__c</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/fields/Playgroup_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Date_Time__c</fullName>
    <defaultValue>NOW ()</defaultValue>
    <label>Playgroup Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/fields/Playgroup_Leader__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/fields/Playgroup_Location__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Location__c</fullName>
    <label>Playgroup Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indoor Play Yard</fullName>
            </value>
            <value>
                <fullName>Outdoor Play Yard</fullName>
            </value>
            <value>
                <fullName>MRC Indoor Play Yard</fullName>
            </value>
            <value>
                <fullName>MRC Outdoor Play Yard</fullName>
            </value>
            <value>
                <fullName>Monster Park</fullName>
            </value>
            <value>
                <fullName>ARC Terrace</fullName>
            </value>
            <value>
                <fullName>SBR</fullName>
            </value>
            <value>
                <fullName>Playroom 1</fullName>
            </value>
            <value>
                <fullName>Playroom 2</fullName>
            </value>
            <value>
                <fullName>Playroom 1 &amp; 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/playgroupSessionLWCController.cls
public with sharing class playgroupSessionLWCController {
    @AuraEnabled (cacheable=true)
    public static playgroupSessionInfo getPlaygroupSessionInfo(){
        try {
            return null;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    // @AuraEnabled
    // public static playgroupSessionInfo copyPlaygroup(Id sessionId){
    //     try {            
    //         return handleCopyPlaygroup(sessionId);
    //     } catch (Exception e) {
    //         throw new AuraHandledException(e.getMessage());
    //     }
    // }

    @AuraEnabled
    public static playgroupSessionInfo startPlaygroupSession(Id sessionId, Id[] animalIdsToIgnore, Id[] animalIdsToAdd){
        try {
            playgroupSessionInfo info = handleCopyPlaygroup(sessionId, animalIdsToIgnore);
            if(!animalIdsToAdd.isEmpty()){
                info.animalPlaygroups.addAll(createNewPlaygroupAnimals(info.sessionId, animalIdsToAdd));
            }
            return info;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static string endPlaygroup(){
        try {
            return null;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static playgroupSessionInfo handleCopyPlaygroup(Id sessionId, Id[] animalIdstoIgnore){
        playgroupSessionInfo info = new playgroupSessionInfo();
        info.sessionId = createNewPlaygroupSession(sessionId).Id;
        info.animalPlaygroups = copyAnimalPlaygroups(sessionId, info.sessionId, animalIdstoIgnore);
        return info;
    }

    private static Animal_Playgroup__c[] copyAnimalPlaygroups(Id oldSessionId, Id newSessionId, Id[] animalIdstoIgnore){
        Animal_Playgroup__c[] copiedAnimals = new Animal_Playgroup__c[0];
        for(Animal_Playgroup__c oldAnimal : [
            SELECT Id, Animal__c, Common_Playgroup_Note_Sections__c, Common_Playgroup_Notes__c, Play_Rating__c, Playgroup_Individual_Notes__c
            FROM Animal_Playgroup__c 
            WHERE Playgroup_Session__c =: oldSessionId
        ]){
            if(animalIdstoIgnore.contains(oldAnimal.Animal__c)) continue;

            Animal_Playgroup__c newAnimal = new Animal_Playgroup__c(
                Animal__c = oldAnimal.Animal__c, 
                Common_Playgroup_Note_Sections__c = oldAnimal.Common_Playgroup_Note_Sections__c, 
                Common_Playgroup_Notes__c = oldAnimal.Common_Playgroup_Notes__c, 
                Play_Rating__c = oldAnimal.Play_Rating__c, 
                Playgroup_Individual_Notes__c = oldAnimal.Playgroup_Individual_Notes__c
            );
            copiedAnimals.add(newAnimal);
        }
        insert copiedAnimals;
        return copiedAnimals;
    }

    private static Animal_Playgroup__c[] createNewPlaygroupAnimals(Id sessionId, Id[] animalIdsToAdd){
        Animal_Playgroup__c[] newAnimals = new Animal_Playgroup__c[0];
        for(Id animalId : animalIdsToAdd){
            Animal_Playgroup__c newAnimal = new Animal_Playgroup__c(
                Animal__c = animalId
            );
            newAnimals.add(newAnimal);
        }
        insert newAnimals;
        return newAnimals;
    }

    private static void createNewPlaygroupContacts(){
            // (SELECT Id, Contact__c, Novel_Not_Novel__c FROM Playgroup_Contacts)
    }

    private static Playgroup_Session__c createNewPlaygroupSession(Id SessionId){
        Playgroup_Session__c originalSession = getPlaygroupSession(sessionId);
        Playgroup_Session__c newSession = new Playgroup_Session__c(
            Playgroup_Leader__c = originalSession.Playgroup_Leader__c,
            Playgroup_Location__c = originalSession.Playgroup_Location__c,
            Playgroup_Date_Time__c = dateTime.now()
        );
        insert newSession;
        return newSession;
    }

    private static Playgroup_Session__c getPlaygroupSession (Id sessionId){
        Playgroup_Session__c[] sessions = [
            SELECT Id, Playgroup_Location__c, Playgroup_Leader__c
            FROM Playgroup_Session__c 
            WHERE Id =: sessionId 
            LIMIT 1
        ];
        return sessions.isEmpty() ? null : sessions[0];
    }    

    public class playgroupSessionInfo{
        @AuraEnabled public Id sessionId {get; set;}
        @AuraEnabled public Animal_Playgroup__c[] animalPlaygroups {get; set;}
    }
}