force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Age__c.field-meta.xml
<CustomField>
    <fullName>Animal_Age__c</fullName>
    <label>Animal Age</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>For EQUINE, see Help Text</description>
    <inlineHelpText>For EQUINE, choose one of the following: Horse, Donkey, Mule, Draft Horse, Mini Horse, Pony, Mini Mule, Mini Donkey</inlineHelpText>
    <label>Breed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;Unspecified&quot;</defaultValue>
    <label>Primary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Primary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Handling_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Handling_Instructions__c</fullName>
    <label>Handling Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Intake_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Intake_Date_Time__c</fullName>
    <label>Intake Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Type_of_Animal__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Animal__c</fullName>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Species</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/Animal_Daily_Care__c.object-meta.xml
<CustomObject>
    <label>Animal Daily Care</label>
    <nameField>
        <displayFormat>ADCN-{0000}</displayFormat>
        <label>Animal Daily Care Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals Daily Care</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animals Daily Care</relationshipLabel>
    <relationshipName>Animals_Daily_Care</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Daily_Care__c.field-meta.xml
<CustomField>
    <fullName>Daily_Care__c</fullName>
    <label>Daily Care</label>
    <referenceTo>Daily_Care__c</referenceTo>
    <relationshipLabel>Animals Daily Care</relationshipLabel>
    <relationshipName>Animals_Daily_Care</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Enrichment__c.field-meta.xml
<CustomField>
    <fullName>Enrichment__c</fullName>
    <description>Enrichment field on Animal care. We have one on Animal record aswell.</description>
    <label>Enrichment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Handling_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Handling_Instructions__c</fullName>
    <label>Handling Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Movement_Method_For_Cleaning__c.field-meta.xml
<CustomField>
    <fullName>Movement_Method_For_Cleaning__c</fullName>
    <label>Movement Method For Cleaning</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Movements_For_Cleaning__c.field-meta.xml
<CustomField>
    <fullName>Movements_For_Cleaning__c</fullName>
    <label>Movements For Cleaning</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Mvmt_Round_Notes_Cleaning_Destination__c.field-meta.xml
<CustomField>
    <fullName>Mvmt_Round_Notes_Cleaning_Destination__c</fullName>
    <label>Mvmt Round Notes &amp; Cleaning Destination</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <label>Round</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Special_Care_Other__c.field-meta.xml
<CustomField>
    <fullName>Special_Care_Other__c</fullName>
    <label>Special Care Other</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Special_Care_Outside_TX__c.field-meta.xml
<CustomField>
    <fullName>Special_Care_Outside_TX__c</fullName>
    <label>Special Care Outside TX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Special_Care_TX__c.field-meta.xml
<CustomField>
    <fullName>Special_Care_TX__c</fullName>
    <label>Special Care TX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Agency_Case__c.field-meta.xml
<CustomField>
    <fullName>Agency_Case__c</fullName>
    <label>Agency Case #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Care__c/Daily_Care__c.object-meta.xml
<CustomObject>
    <label>Daily Care</label>
    <nameField>
        <displayFormat>DCN-{0000}</displayFormat>
        <label>Daily Care Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Care</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Care__c/fields/AM_Reminders__c.field-meta.xml
<CustomField>
    <fullName>AM_Reminders__c</fullName>
    <label>AM Reminders</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Care__c/fields/General_Reminders__c.field-meta.xml
<CustomField>
    <fullName>General_Reminders__c</fullName>
    <label>General Reminders</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Care__c/fields/PM_Reminders__c.field-meta.xml
<CustomField>
    <fullName>PM_Reminders__c</fullName>
    <label>PM Reminders</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Care__c/fields/Scent_of_the_Week__c.field-meta.xml
<CustomField>
    <fullName>Scent_of_the_Week__c</fullName>
    <label>Scent of the Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deer</fullName>
            </value>
            <value>
                <fullName>Skunk</fullName>
            </value>
            <value>
                <fullName>Bear</fullName>
            </value>
            <value>
                <fullName>Squirrel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Care__c/fields/Special_Projects__c.field-meta.xml
<CustomField>
    <fullName>Special_Projects__c</fullName>
    <label>Special Projects</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Primary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Bay roan</fullName>
    </customValue>
    <customValue>
        <fullName>Beige</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Blue roan</fullName>
    </customValue>
    <customValue>
        <fullName>Brindle</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Buckskin</fullName>
    </customValue>
    <customValue>
        <fullName>Buff</fullName>
    </customValue>
    <customValue>
        <fullName>Calico</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut/Sorrel</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Dun</fullName>
    </customValue>
    <customValue>
        <fullName>Fawn</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Grulla</fullName>
    </customValue>
    <customValue>
        <fullName>Hairless</fullName>
    </customValue>
    <customValue>
        <fullName>Liver chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Palomino</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Red roan</fullName>
    </customValue>
    <customValue>
        <fullName>Roan</fullName>
    </customValue>
    <customValue>
        <fullName>Seal</fullName>
    </customValue>
    <masterLabel>Primary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Species.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avian</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Cow</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Equine</fullName>
    </customValue>
    <customValue>
        <fullName>Exotic</fullName>
    </customValue>
    <customValue>
        <fullName>Fowl</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <masterLabel>Species</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DailyCarePDFControllerTest.cls
@isTest
public class DailyCarePDFControllerTest {

    @testSetup
    static void setupData(){
        
        case objCase = new Case(Status = 'On hold',Origin='Email',Agency_Case__c = 'test');
        insert objCase ;
        
        Animal__c objAnimal = new Animal__c(Case__c =objCase.id, Name='A-001-West',type_of_animal__c='Cat',breed__c='Coonhound',gender__c='MI',Animal_Age__c=12,Color__c='Brown',Intake_Date_Time__c= DateTime.now());
        insert objAnimal;
        
        Daily_Care__c dc = new Daily_Care__c(AM_Reminders__c = 'Refill DBT buckets w/hot dog/cheese each AM and ice pack!2.', 
                                             Date__c = System.today(), 
                                             General_Reminders__c = 'Test General Reminder', 
                                             PM_Reminders__c = 'Test PM Reminder', 
                                             Scent_of_the_Week__c = 'Skunk', 
                                             Special_Projects__c = 'Its Special');
        insert dc;
        
        Animal_Daily_Care__c adc = new Animal_Daily_Care__c(Daily_Care__c = dc.id,
                                                            Animal__c = objAnimal.Id, 
                                                            Handling_Instructions__c = 'Walks really well!', 
                                                            Movement_Method_For_Cleaning__c = 'Test', 
                                                            Movements_For_Cleaning__c = 'Test', 
                                                            Mvmt_Round_Notes_Cleaning_Destination__c = 'Test', 
                                                            Round__c = '1', 
                                                            Special_Care_Other__c = 'Test', 
                                                            Special_Care_Outside_TX__c = 'Test', 
                                                            Special_Care_TX__c = 'Test', 
                                                            Enrichment__c = 'Test');
        insert adc;
        
        Task t = new Task(ActivityDate = system.today(),
                          RecordTypeId = Util.getRecordTypeId('Task', AutoScheduleTasksUtil.BEH_TREATMENT_TASK_RECORD_TYPE_NAME),
                          Animal__c = objAnimal.Id,
                          OwnerId = UserInfo.getUserId(),
                          Subject = 'Test',
                          Editor__c = 'Test');

        insert t;
    }
    
    @isTest
    static void testPdf(){
        Daily_Care__c dc = [SELECT AM_Reminders__c, Date__c, General_Reminders__c, PM_Reminders__c, Scent_of_the_Week__c, Special_Projects__c, Name, Id FROM Daily_Care__c];
        ApexPages.StandardController sc = new ApexPages.StandardController(dc);
        ApexPages.currentPage().getParameters().put('dailyCareId',dc.Id);
        PageReference pageRef = sc.view();
        Test.setCurrentPage(pageRef);
      
        DailyCarePDFController controller = new DailyCarePDFController();
        Daily_Care__c ddc = controller.dailyCare;
        List<DailyCarePDFController.AnimalDailyCare> adcList = controller.animalDailyCares;
        System.assertNotEquals(null, controller);
    }
    
    @isTest
    static void testPdf2(){
        PageReference pageRef = Page.DailyCarePDF;
        Test.setCurrentPage(pageRef);
      	Daily_Care__c dc = [SELECT AM_Reminders__c, Date__c, General_Reminders__c, PM_Reminders__c, Scent_of_the_Week__c, Special_Projects__c, Name, Id FROM Daily_Care__c];
        ApexPages.currentPage().getParameters().put('dailyCareId',dc.Id);
        DailyCarePDFController controller = new DailyCarePDFController();
        Daily_Care__c ddc = controller.dailyCare;
        List<DailyCarePDFController.AnimalDailyCare> adcList = controller.animalDailyCares;
        System.assertNotEquals(null, controller);
    }
}