force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/AAH_ID__c.field-meta.xml
<CustomField>
    <fullName>AAH_ID__c</fullName>
    <label>AAH ID #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name__c</fullName>
    <externalId>true</externalId>
    <label>ASPCA Animal Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Approved_for_bath__c.field-meta.xml
<CustomField>
    <fullName>Approved_for_bath__c</fullName>
    <label>Approved for bath?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Approved_for_Revolution__c.field-meta.xml
<CustomField>
    <fullName>Approved_for_Revolution__c</fullName>
    <label>Approved for Revolution?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Placement_Status__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Placement_Status__c</fullName>
    <label>Current Behavior Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Behavior Hold</fullName>
            </value>
            <value>
                <fullName>Needs Evaluation</fullName>
            </value>
            <value>
                <fullName>Behavior Reassessment</fullName>
            </value>
            <value>
                <fullName>Cleared – Placement Summary Complete</fullName>
            </value>
            <value>
                <fullName>Cleared – Placement Summary Needed</fullName>
            </value>
            <value>
                <fullName>Placement Partner OK - Foster</fullName>
                <isActive>false</isActive>
                <label>Placement Partner OK - Foster</label>
            </value>
            <value>
                <fullName>Placement Partner OK - Foster-based Rescue</fullName>
                <isActive>false</isActive>
                <label>Placement Partner OK - Foster-based Rescue</label>
            </value>
            <value>
                <fullName>Placement Partner OK - Shelter with Behavior Dept.</fullName>
                <isActive>false</isActive>
                <label>Placement Partner OK - Shelter with Behavior Dept.</label>
            </value>
            <value>
                <fullName>Ready for Placement</fullName>
                <isActive>false</isActive>
                <label>Ready for Placement</label>
            </value>
            <value>
                <fullName>Rehab Candidate</fullName>
                <isActive>false</isActive>
                <label>Rehab Candidate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>For EQUINE, see Help Text</description>
    <inlineHelpText>For EQUINE, choose one of the following: Horse, Donkey, Mule, Draft Horse, Mini Horse, Pony, Mini Mule, Mini Donkey</inlineHelpText>
    <label>Breed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;Unspecified&quot;</defaultValue>
    <label>Primary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Primary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Animal_Age_Formatted__c.field-meta.xml
<CustomField>
    <fullName>Current_Animal_Age_Formatted__c</fullName>
    <formula>IF( ISNULL( Today_Test__c ) ,
IF(NOT(ISBLANK(Estimated_Date_of_Birth__c)),
    TEXT(FLOOR(( (TODAY() - Estimated_Date_of_Birth__c) / 365)))
    &amp;&apos; Years&apos; &amp; &apos; &apos; &amp;
    TEXT(FLOOR( (MOD( (TODAY() - Estimated_Date_of_Birth__c),365)/30))) &amp;&apos; Months&apos;,
    IF(NOT(ISBLANK(Animal_Age__c)) &amp;&amp; NOT(ISBLANK(TEXT(Animal_Age_Units__c))),
        IF(TEXT(Animal_Age_Units__c) = &apos;Days&apos;,
            TEXT(FLOOR(( (TODAY() - (Animal_Age_Units_Changed_Date__c - Animal_Age__c))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (TODAY() - (Animal_Age_Units_Changed_Date__c - Animal_Age__c)),365)/30))) &amp;&apos; Months&apos;,
        IF(TEXT(Animal_Age_Units__c) = &apos;Weeks&apos;,
            TEXT(FLOOR(( (TODAY() - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (TODAY() - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c))),365)/30))) &amp;&apos; Months&apos; ,
        IF(TEXT(Animal_Age_Units__c) = &apos;Months&apos;,
            IF(Animal_Age__c &lt; 12,
                &apos;0 Years &apos; &amp; TEXT(Animal_Age__c) &amp; &apos; Months&apos;,
                TEXT(FLOOR( (TODAY()  - ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))/365))
                &amp;&apos; Years&apos; &amp; &apos; &apos;
                &amp; TEXT(FLOOR( MOD( (TODAY()  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))),365)/30)) &amp;&apos; Months&apos;),
        IF(TEXT(Animal_Age_Units__c) = &apos;Years&apos;,
            TEXT(FLOOR(( (TODAY() - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -12 * Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD(TODAY() - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, 12)),365)/30))) &amp;&apos; Months&apos;,
        &quot;&quot;)))) ,
    &quot;&quot;)
),

IF(NOT(ISBLANK(Estimated_Date_of_Birth__c)),
    TEXT(FLOOR(( (Today_Test__c  - Estimated_Date_of_Birth__c) / 365)))
    &amp;&apos; Years&apos; &amp; &apos; &apos; &amp;
    TEXT(FLOOR( (MOD( (Today_Test__c  - Estimated_Date_of_Birth__c),365)/30))) &amp;&apos; Months&apos;,
    IF(NOT(ISBLANK(Animal_Age__c)) &amp;&amp; NOT(ISBLANK(TEXT(Animal_Age_Units__c))),
        IF(TEXT(Animal_Age_Units__c) = &apos;Days&apos;,
            TEXT(FLOOR(( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - Animal_Age__c))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - Animal_Age__c)),365)/30))) &amp;&apos; Months&apos;,
        IF(TEXT(Animal_Age_Units__c) = &apos;Weeks&apos;,
            TEXT(FLOOR(( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD( (Today_Test__c  - (Animal_Age_Units_Changed_Date__c - ( 7* Animal_Age__c))),365)/30))) &amp;&apos; Months&apos; ,
        IF(TEXT(Animal_Age_Units__c) = &apos;Months&apos;,
            IF(Animal_Age__c &lt; 12,
                &apos;0 Years &apos; &amp; TEXT(Animal_Age__c) &amp; &apos; Months&apos;,
                TEXT(FLOOR( (Today_Test__c  - ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))/365))
                &amp;&apos; Years&apos; &amp; &apos; &apos;
                &amp; TEXT(FLOOR( MOD( (Today_Test__c  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -1 * Animal_Age__c))),365)/30)) &amp;&apos; Months&apos;),
        IF(TEXT(Animal_Age_Units__c) = &apos;Years&apos;,
            TEXT(FLOOR(( (Today_Test__c  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, -12 * Animal_Age__c)))/365)))
            &amp;&apos; Years&apos; &amp; &apos; &apos;
            &amp; TEXT(FLOOR((MOD(Today_Test__c  - (ADDMONTHS(Animal_Age_Units_Changed_Date__c, 12)),365)/30))) &amp;&apos; Months&apos;,
        &quot;&quot;)))) ,
    &quot;&quot;)
)

)</formula>
    <label>Current Animal Age</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Behavior_Grade__c.field-meta.xml
<CustomField>
    <fullName>Current_Behavior_Grade__c</fullName>
    <label>Current Behavior Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>No Evaluation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Forensic_Behavior_Eval_Grade__c.field-meta.xml
<CustomField>
    <fullName>Forensic_Behavior_Eval_Grade__c</fullName>
    <label>Forensic Behavior Eval Grade</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Meets_Adoptability_Date__c.field-meta.xml
<CustomField>
    <fullName>Meets_Adoptability_Date__c</fullName>
    <label>Meets Adoptability Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Muzzle_needed_for_bath__c.field-meta.xml
<CustomField>
    <fullName>Muzzle_needed_for_bath__c</fullName>
    <label>Muzzle needed for bath?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/NYPD_Complaint__c.field-meta.xml
<CustomField>
    <fullName>NYPD_Complaint__c</fullName>
    <formula>Case__r.NYPD_Complaint_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NYPD Complaint #</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Original_Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Original_Animal_Name__c</fullName>
    <label>Original Animal Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Petpoint_ID__c.field-meta.xml
<CustomField>
    <fullName>Petpoint_ID__c</fullName>
    <label>Petpoint ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Placement_Recommendations__c.field-meta.xml
<CustomField>
    <fullName>Placement_Recommendations__c</fullName>
    <label>Placement Recommendations</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Special_instructions_for_bath__c.field-meta.xml
<CustomField>
    <fullName>Special_instructions_for_bath__c</fullName>
    <label>Special instructions for bath</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Special_instructions_for_Revolution__c.field-meta.xml
<CustomField>
    <fullName>Special_instructions_for_Revolution__c</fullName>
    <label>Special instructions for Revolution</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/recordTypes/Behavior.recordType-meta.xml
<RecordType>
    <fullName>Behavior</fullName>
    <active>true</active>
    <label>Behavior</label>
</RecordType>

force-app/main/default/objects/Behavior_Evaluation__c/Behavior_Evaluation__c.object-meta.xml
<CustomObject>
    <label>Behavior Evaluation</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Behavior Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Behavior Evaluations</relationshipLabel>
    <relationshipName>Behavior_Evaluations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name__c</fullName>
    <formula>Animal__r.Animal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Behavior_Evaluation_Summary__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Evaluation_Summary__c</fullName>
    <label>Behavior Evaluation Summary</label>
    <length>7232</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation_Summary__c/Behavior_Evaluation_Summary__c.object-meta.xml
<CustomObject>
    <label>Behavior Evaluation Summary</label>
    <nameField>
        <displayFormat>BES-{0000}</displayFormat>
        <label>Behavior Evaluation Summary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior Evaluation Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Behavior_Evaluation_Summary__c/fields/Behavior_Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Evaluation__c</fullName>
    <label>Behavior Evaluation</label>
    <referenceTo>Behavior_Evaluation__c</referenceTo>
    <relationshipLabel>Behavior Evaluation Summaries</relationshipLabel>
    <relationshipName>Behavior_Evaluation_Summaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Primary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Bay roan</fullName>
    </customValue>
    <customValue>
        <fullName>Beige</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Blue roan</fullName>
    </customValue>
    <customValue>
        <fullName>Brindle</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Buckskin</fullName>
    </customValue>
    <customValue>
        <fullName>Buff</fullName>
    </customValue>
    <customValue>
        <fullName>Calico</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut/Sorrel</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Dun</fullName>
    </customValue>
    <customValue>
        <fullName>Fawn</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Grulla</fullName>
    </customValue>
    <customValue>
        <fullName>Hairless</fullName>
    </customValue>
    <customValue>
        <fullName>Liver chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Palomino</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Red roan</fullName>
    </customValue>
    <customValue>
        <fullName>Roan</fullName>
    </customValue>
    <customValue>
        <fullName>Seal</fullName>
    </customValue>
    <masterLabel>Primary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BehaviorProfileSendEmail.cls
public class BehaviorProfileSendEmail {

@InvocableMethod(label='Send Behavior Email Alert' description='Behavior Profile Send Email')
    public static void sendEmail(List<EmailRequest> requestList) {
        if(requestList.size() > 0 && requestList[0].behEvaluations != null){
            Behavior_Evaluation__c inputCollection = requestList[0].behEvaluations;
            List<Behavior_Evaluation__c> behEvaluations = [SELECT Animal__r.Gender__c, Animal__r.Current_Animal_Age_Formatted__c, Animal__r.Name, Animal__r.Animal_Name__c,
                                                           Animal__r.Color__c, Animal__r.Breed__c, Animal__r.Case__c, Animal__r.Petpoint_ID__c, 
                                                           Animal__r.AAH_ID__c, Animal__r.LastModifiedDate, Behavior_Evaluation_Summary__c, Animal__r.Placement_Recommendations__c,
                                                           Animal__r.Current_Behavior_Grade__c, Animal__r.Forensic_Behavior_Eval_Grade__c, Animal__r.Original_Animal_Name__c,
                                                           Animal__r.Behavior_Placement_Status__c, Animal__r.Approved_for_bath__c, Animal__r.Muzzle_needed_for_bath__c, 
                                                           Animal__r.Special_instructions_for_bath__c, Animal__r.Approved_for_Revolution__c, Animal__r.NYPD_Complaint__c,
                                                           Animal__r.Special_instructions_for_Revolution__c,Animal__r.Meets_Adoptability_Date__c
                                                           FROM Behavior_Evaluation__c
                                                           WHERE Id = : inputCollection.id];
            
            for(Behavior_Evaluation__c behEval: behEvaluations){
                sendEmailAlert(behEval);
            }
        }
    }
    
    private static void sendEmailAlert(Behavior_Evaluation__c behEval){
        List<String> emails = System.Label.BehaviorProfileEmailsSendOut.replaceAll('\\s+','-').split(',');
        List<User> users = [Select Id from user where email IN : emails];
        EmailTemplate et =[Select Id, Subject, Body, HtmlValue from EmailTemplate where DeveloperName= 'Behavior_Profile_Send_Emails'];
        if(emails.size() > 0 && users.size() > 0){
            
            String animalName = '';
            if(String.isNotBlank(behEval.Animal__r.Animal_Name__c) || String.isNotBlank(behEval.Animal__r.Original_Animal_Name__c)){
                if(String.isNotBlank(behEval.Animal__r.Animal_Name__c)){
                    animalName = behEval.Animal__r.Animal_Name__c;
                }
                if(String.isNotBlank(behEval.Animal__r.Original_Animal_Name__c)){
                    animalName = animalName + ' ' + behEval.Animal__r.Original_Animal_Name__c;
                }
            }
            
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            String textBody = et.HtmlValue.replace('{!</font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.Name}', animalName);
            textBody = textBody.replace('{!</font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.Gender__c}', String.isNotBlank(behEval.Animal__r.Gender__c) ? behEval.Animal__r.Gender__c : '');
            textBody = textBody.replace('{!</span></font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.</span><span style="font-size: 12pt;">Current_Animal_Age_Formatted__c</span><span style="font-size: 12pt;">}', String.isNotBlank(behEval.Animal__r.Current_Animal_Age_Formatted__c) ? behEval.Animal__r.Current_Animal_Age_Formatted__c : '');
            textBody = textBody.replace('{!</font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.Color__c}', String.isNotBlank(behEval.Animal__r.Color__c) ? behEval.Animal__r.Color__c : '');
            textBody = textBody.replace('{!</font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.Breed__c}', String.isNotBlank(behEval.Animal__r.Breed__c) ? behEval.Animal__r.Breed__c : '');
            textBody = textBody.replace('{!</font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.Case__c}', String.isNotBlank(behEval.Animal__r.NYPD_Complaint__c) ? behEval.Animal__r.NYPD_Complaint__c : '');
            textBody = textBody.replace('{!</span></font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.</span><span style="font-size: 12pt;">Petpoint_ID__c</span><span style="font-size: 12pt;">}', String.isNotBlank(behEval.Animal__r.Petpoint_ID__c) ? behEval.Animal__r.Petpoint_ID__c : '');
            textBody = textBody.replace('{!</font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.AAH_ID__c}', String.isNotBlank(behEval.Animal__r.AAH_ID__c) ? behEval.Animal__r.AAH_ID__c : '');
            textBody = textBody.replace('{!</font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.LastModifiedDate}', String.isNotBlank(String.valueOf(behEval.Animal__r.LastModifiedDate)) ? String.valueOf(behEval.Animal__r.LastModifiedDate) : '');
            textBody = textBody.replace('{!</span>Behavior_Evaluation__c<span style="font-size: 12pt;">.</span>Behavior_Evaluation_Summary__c<span style="font-size: 12pt;">}', String.isNotBlank(behEval.Behavior_Evaluation_Summary__c) ? behEval.Behavior_Evaluation_Summary__c.replace('General Comments:', '') : '');
            textBody = textBody.replace('{!</font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.Placement_Recommendations__c}', String.isNotBlank(behEval.Animal__r.Placement_Recommendations__c) ? behEval.Animal__r.Placement_Recommendations__c : '');
            textBody = textBody.replace('{!</font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><font face="arial" style="font-size: 12pt;">Animal__c.</font><span style="font-size: 12pt;">Current_Behavior_Grade__c</span><font face="arial" style="font-size: 12pt;">}', String.isNotBlank(behEval.Animal__r.Current_Behavior_Grade__c) ? behEval.Animal__r.Current_Behavior_Grade__c : '');
            textBody = textBody.replace('{!</span></font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.</span><span style="font-size: 12pt;">Forensic_Behavior_Eval_Grade__c</span><span style="font-size: 12pt;">}', String.isNotBlank(behEval.Animal__r.Forensic_Behavior_Eval_Grade__c) ? behEval.Animal__r.Forensic_Behavior_Eval_Grade__c : '');
            textBody = textBody.replace('{!</font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.Behavior_Placement_Status__c}', String.isNotBlank(behEval.Animal__r.Behavior_Placement_Status__c) ? behEval.Animal__r.Behavior_Placement_Status__c : '');
            textBody = textBody.replace('{!</span></font><span style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">Behavior_Evaluation__c</span><span style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">.</span><span style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">Animal__c.</span><font face="arial">Meets_Adoptability_Date__c<span style="font-size: 12pt;">}', String.isNotBlank(String.valueOf(behEval.Animal__r.Meets_Adoptability_Date__c)) ? String.valueOf(behEval.Animal__r.Meets_Adoptability_Date__c) : '');
            textBody = textBody.replace('{!</font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.Approved_for_bath__c}', String.isNotBlank(behEval.Animal__r.Approved_for_bath__c) ? behEval.Animal__r.Approved_for_bath__c : '');
            textBody = textBody.replace('{!</font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.Muzzle_needed_for_bath__c}', String.isNotBlank(behEval.Animal__r.Muzzle_needed_for_bath__c) ? behEval.Animal__r.Muzzle_needed_for_bath__c : '');
            textBody = textBody.replace('{!</span><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.Special_instructions_for_bath__c}', String.isNotBlank(behEval.Animal__r.Special_instructions_for_bath__c) ? behEval.Animal__r.Special_instructions_for_bath__c : '');
            textBody = textBody.replace('{!</font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.Approved_for_Revolution__c}', String.isNotBlank(behEval.Animal__r.Approved_for_Revolution__c) ? behEval.Animal__r.Approved_for_Revolution__c : '');
            textBody = textBody.replace('{!</font><span style="font-size: 12pt;">Behavior_Evaluation__c</span><span style="font-size: 12pt;">.</span><span style="font-size: 12pt;">Animal__c.Special_instructions_for_Revolution}', String.isNotBlank(behEval.Animal__r.Special_instructions_for_Revolution__c) ? behEval.Animal__r.Special_instructions_for_Revolution__c : '');
            textBody = textBody.replace('<![CDATA[', '').replace(']]>','');
            message.setToAddresses(emails);
            message.setTemplateId(et.id);
            message.setSubject(et.Subject.replace('{!Behavior_Evaluation__c.Animal__c.Animal_Name__c}',behEval.Animal__r.Animal_Name__c));
            
            message.setHtmlBody(textBody);
            message.saveAsActivity = false;
            message.setTargetobjectid(users[0].Id);
            Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
            Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        }
    }  
    
    public class EmailRequest {
        @InvocableVariable(required=true)
        public Behavior_Evaluation__c behEvaluations;
    }
}