force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <scale>15</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ARC/CARE</fullName>
            </value>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/test/test_TreatmentToDoPDFController.cls
@isTest
private  class test_TreatmentToDoPDFController {
    @isTest 
    static void TreatmentToDoPDFController_hasData(){
        User u = [SELECT Id, Location__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        u.Location__c = 'All';
        update u;

        //create treatment plan, pan protocols, animal, etc
        TestDataFactory.createPlanProtocols(2);

        PageReference toDoPdf = Page.TreatmentToDoPDF;
        toDoPdf.getParameters().put('locations', 'CRC,CRC-MRC,ARC,CARE,ARC-CARE');
        toDoPdf.getParameters().put('useFilter', 'true');
        Test.setCurrentPage(toDoPdf);

        Animal__c[] anims = [SELECT Id, Name FROM Animal__c];

        test.startTest();
        TreatmentToDoPDFController pdfController = new TreatmentToDoPDFController();
        TreatmentToDoPDFController.TreatmentPlanWithProtocols[] plansWithProtocols = pdfController.treatmentPlansWithProtocols;
        test.stopTest();

        System.assert(!plansWithProtocols.isEmpty(), 'Should not have returned an empty list');
        System.assert(plansWithProtocols[0].treatmentPlan != null, 'Should have returned a treatment plan for the first itme in the list');
        System.assert(plansWithProtocols[0].protocols != null, 'Should have returned protocols for the first itme in the list');
    }

    @isTest
    static void TreatmentToDoPDFController_noData(){
        PageReference toDoPdf = Page.TreatmentToDoPDF;
        toDoPdf.getParameters().put('locations', 'CRC,CRC-MRC');
        toDoPdf.getParameters().put('useFilter', 'true');
        Test.setCurrentPage(toDoPdf);

        test.startTest();
        TreatmentToDoPDFController pdfController = new TreatmentToDoPDFController();
        TreatmentToDoPDFController.TreatmentPlanWithProtocols[] plansWithProtocols = pdfController.treatmentPlansWithProtocols;
        test.stopTest();

        System.assert(plansWithProtocols.isEmpty(), 'Should have returned an empty list, instead was: ' + plansWithProtocols);
    }
}