force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Additional_Comments__c.field-meta.xml
<CustomField>
    <fullName>Additional_Comments__c</fullName>
    <label>Additional Comments</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name__c</fullName>
    <externalId>true</externalId>
    <label>ASPCA Animal Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Incidents__c/Incidents__c.object-meta.xml
<CustomObject>
    <label>Incidents</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Incident Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Incidents__c/fields/Additional_Comments__c.field-meta.xml
<CustomField>
    <fullName>Additional_Comments__c</fullName>
    <label>Additional Comments</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Incidents</relationshipLabel>
    <relationshipName>Incidents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Behaviors_Exhibited_by_the_Dog__c.field-meta.xml
<CustomField>
    <fullName>Behaviors_Exhibited_by_the_Dog__c</fullName>
    <label>Behaviors Exhibited by the Dog</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Repetitive behavior (pacing - licking - drooling)</fullName>
            </value>
            <value>
                <fullName>Staring at wall or corner of kennel</fullName>
            </value>
            <value>
                <fullName>High arousal/excitement (intense - energetic activity)</fullName>
            </value>
            <value>
                <fullName>Tugging or climbing the leash</fullName>
            </value>
            <value>
                <fullName>Hard mouthing</fullName>
            </value>
            <value>
                <fullName>Climbing or high jumping up kennel walls or fence</fullName>
            </value>
            <value>
                <fullName>Escaping from kennel</fullName>
            </value>
            <value>
                <fullName>Trying to get away</fullName>
            </value>
            <value>
                <fullName>Trying to get at another dog</fullName>
            </value>
            <value>
                <fullName>Fighting with another dog</fullName>
            </value>
            <value>
                <fullName>Guarding food or chewy from person</fullName>
            </value>
            <value>
                <fullName>Guarding non-food item from person</fullName>
            </value>
            <value>
                <fullName>Resisting medical restraint</fullName>
            </value>
            <value>
                <fullName>Stiffening or freezing</fullName>
            </value>
            <value>
                <fullName>Whipping head toward person - unsure if dog would bite</fullName>
            </value>
            <value>
                <fullName>Lunging toward a person</fullName>
            </value>
            <value>
                <fullName>Muzzle punching (forceful jab with nose)</fullName>
            </value>
            <value>
                <fullName>Growling</fullName>
            </value>
            <value>
                <fullName>Showing teeth</fullName>
            </value>
            <value>
                <fullName>Snapping</fullName>
            </value>
            <value>
                <fullName>Biting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Clothing_Worn_at_Bite_Site__c.field-meta.xml
<CustomField>
    <fullName>Clothing_Worn_at_Bite_Site__c</fullName>
    <label>Clothing Worn at Bite Site</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Damage_Done_by_the_Dog__c.field-meta.xml
<CustomField>
    <fullName>Damage_Done_by_the_Dog__c</fullName>
    <label>Damage Done by the Dog</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A - there was NO bite or damage</fullName>
            </value>
            <value>
                <fullName>Bruising</fullName>
            </value>
            <value>
                <fullName>Broken skin</fullName>
            </value>
            <value>
                <fullName>Shallow scratch or abrasion</fullName>
            </value>
            <value>
                <fullName>Deep scratch or abrasion</fullName>
            </value>
            <value>
                <fullName>Puncture</fullName>
            </value>
            <value>
                <fullName>Puncture with tearing</fullName>
            </value>
            <value>
                <fullName>Torn material (leash - clothing)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/If_dog_did_not_bite__c.field-meta.xml
<CustomField>
    <fullName>If_dog_did_not_bite__c</fullName>
    <description>If dog did not bite, do you think it would have done so if you hadn&apos;t taken evasive action or used defensive handling?</description>
    <label>If dog did not bite</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Incident_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Incident_Date_Time__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Incident Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Incident_Description__c.field-meta.xml
<CustomField>
    <fullName>Incident_Description__c</fullName>
    <label>Incident Description</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Number_of_bites__c.field-meta.xml
<CustomField>
    <fullName>Number_of_bites__c</fullName>
    <label>Number of bites</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Other_Damage_Done_by_the_Dog__c.field-meta.xml
<CustomField>
    <fullName>Other_Damage_Done_by_the_Dog__c</fullName>
    <label>Other Damage Done by the Dog</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Person_Involved__c.field-meta.xml
<CustomField>
    <fullName>Person_Involved__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person Involved</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Incidents</relationshipLabel>
    <relationshipName>Incidents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Please_explain_why_you_think_so__c.field-meta.xml
<CustomField>
    <fullName>Please_explain_why_you_think_so__c</fullName>
    <label>Please explain why you think so</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Specific_Target_of_Dog_s_Behavior__c.field-meta.xml
<CustomField>
    <fullName>Specific_Target_of_Dog_s_Behavior__c</fullName>
    <label>Specific Target of Dog&apos;s Behavior</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Type_of_Bite__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Bite__c</fullName>
    <label>Type of Bite</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A - there was NO bite</fullName>
            </value>
            <value>
                <fullName>Single bite</fullName>
            </value>
            <value>
                <fullName>Bite and hold</fullName>
            </value>
            <value>
                <fullName>Bite, hold and shake</fullName>
            </value>
            <value>
                <fullName>Multiple bites</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Was_Bitten_Area_Covered_with_Clothing__c.field-meta.xml
<CustomField>
    <fullName>Was_Bitten_Area_Covered_with_Clothing__c</fullName>
    <label>Was Bitten Area Covered with Clothing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A - Not applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incidents__c/fields/Witnesses__c.field-meta.xml
<CustomField>
    <fullName>Witnesses__c</fullName>
    <label>Witnesses</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/Behavior_Incident_Report_Controller.cls
public class Behavior_Incident_Report_Controller {

    public Incidents__c incident {get;set;}
    public Incidents__c MultiselectPicklist {get;set;}
    public Animal__c anim {get;set;}
    public Contact contact {get;set;}
    
    public Behavior_Incident_Report_Controller(ApexPages.StandardController controller){
        
        incident = [SELECT Id
                    , Additional_Comments__c
                    , Animal__c
                    , Behaviors_Exhibited_by_the_Dog__c
                    , Clothing_Worn_at_Bite_Site__c
                    , Damage_Done_by_the_Dog__c
                    , If_dog_did_not_bite__c
                    , Incident_Date_Time__c
                    , Incident_Description__c
                    , Name
                    , Number_of_bites__c
                    , Other_Damage_Done_by_the_Dog__c
                    , Person_Involved__c
                    , Please_explain_why_you_think_so__c
                    , Report_Date__c
                    , Specific_Target_of_Dog_s_Behavior__c
                    , Type_of_Bite__c
                    , Was_Bitten_Area_Covered_with_Clothing__c
                    , Witnesses__c
                    , Animal__r.Name
                    , Animal__r.Animal_Name__c
        FROM Incidents__c
        WHERE Name = '2022/01/20-0'];

        MultiselectPicklist = (Incidents__c)controller.getRecord();
    }
    public List<SelectOption> getPicklistValue {
        get {
            List<SelectOption> options = new List<SelectOption>();
            for( Schema.PicklistEntry obj : Incidents__c.Behaviors_Exhibited_by_the_Dog__c.getDescribe().getPicklistValues()) {
                options.add(new SelectOption(obj.getValue(), obj.getLabel()));
            } 
            return options;
        }  
        set;
    }

    // public String[] getPicklistValue {
    //     get {
    //         String[] options = new String[0];
    //         for( Schema.PicklistEntry obj : Incidents__c.Behaviors_Exhibited_by_the_Dog__c.getDescribe().getPicklistValues()) {
    //             options.add(obj.getLabel());
    //         } 
    //         return options;
    //     }  
    //     set;
    // }    

    // public String[] Items { 
    //     get {
    //         List<String> selected = new List<String>();
    //         List<SelectOption> options = this.getPicklistValue;
    //         for(SelectOption obj : options) {
    //             if (this.incident.Behaviors_Exhibited_by_the_Dog__c !=null && this.incident.Behaviors_Exhibited_by_the_Dog__c.contains(obj.getValue()))
    //                 selected.add(obj.getValue());
    //         }
    //         return selected;
    //     }public set {
    //         String selectedCheckBox = '';
    //         for(String s : value) {
    //             if (selectedCheckBox == '') 
    //                 selectedCheckBox += s;
    //             else selectedCheckBox += ';' + s;
    //         }
    //         incident.Behaviors_Exhibited_by_the_Dog__c = selectedCheckBox;
    //     }
    // } 

    Option[] behaviorsExhibited { get; set; }
    public Option[] getbehaviorsExhibited(){
        behaviorsExhibited = new Option[0];
        String objectAPI = 'Incidents__c';
        String fieldAPI = 'Behaviors_Exhibited_by_the_Dog__c';
        String name = String.valueOf(Schema.getGlobalDescribe().get(objectAPI).getDescribe().fields.getMap().get(fieldAPI).getDescribe().getLabel());
        Schema.SObjectField fieldInfo = SchemaHelper.DetermineSObjectFieldByLabel(objectAPI, name);  

        String[] picklistValues = SchemaHelper.GetPicklistValues(fieldInfo);

        DescribeFieldResult fieldResult = Incidents__c.Behaviors_Exhibited_by_the_Dog__c.getDescribe();
        PicklistEntry[] entries = fieldResult.getPicklistValues();


        String value = '';
        if(!String.isEmpty(incident.Behaviors_Exhibited_by_the_Dog__c)) {
            value = incident.Behaviors_Exhibited_by_the_Dog__c;
        }
        String[] values = (String[]) value.split(';');

        for (PicklistEntry entry : entries) {
            String label = entry.label;

            Boolean isSelected = (!values.isEmpty() && values.contains(label)) ? true : false;
            Option opt = new Option();
            opt.label = label;
            opt.selected = isSelected;
            behaviorsExhibited.add(opt);
        }

        return behaviorsExhibited;
    }

    public class Option{
        public String label {get;set;}
        public Boolean selected {get;set;}
     }
}