force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility_Outcome__c/Facility_Outcome__c.object-meta.xml
<CustomObject>
    <label>Facility/Outcome</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>F/O #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facilities/Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility_Outcome__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipName>Animal_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Facility_or_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Facility_or_Outcome__c</fullName>
    <label>Facility or Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility</fullName>
            </value>
            <value>
                <fullName>Outcome</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Facility_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Facility_Outcome__c</fullName>
    <label>Facility/Outcome</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Facility_or_Outcome__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAH</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Adoption Center</fullName>
            </value>
            <value>
                <fullName>Adoption Center (Temp Boarding)</fullName>
            </value>
            <value>
                <fullName>Animal Hospital</fullName>
            </value>
            <value>
                <fullName>Animal Shelter</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>ASNA</fullName>
            </value>
            <value>
                <fullName>ASPCA Shelter</fullName>
            </value>
            <value>
                <fullName>Board and Train</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>BRC</fullName>
            </value>
            <value>
                <fullName>Bronx CVC</fullName>
            </value>
            <value>
                <fullName>Brooklyn CVC</fullName>
            </value>
            <value>
                <fullName>CARE</fullName>
            </value>
            <value>
                <fullName>Clinic</fullName>
            </value>
            <value>
                <fullName>Community Medicine</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
            <value>
                <fullName>CRC-MRC</fullName>
            </value>
            <value>
                <fullName>Cremation</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Euthanized</fullName>
            </value>
            <value>
                <fullName>Field Temp Shelter</fullName>
            </value>
            <value>
                <fullName>Foster-Based Rescue</fullName>
            </value>
            <value>
                <fullName>Foster Home</fullName>
            </value>
            <value>
                <fullName>Foster Home - Adoption Center</fullName>
            </value>
            <value>
                <fullName>Foster Home - ARC</fullName>
            </value>
            <value>
                <fullName>Foster Home - CARE</fullName>
            </value>
            <value>
                <fullName>Hound Hotel</fullName>
            </value>
            <value>
                <fullName>Kitten Nursery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Point_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Point_of_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Point of Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Facilities/Outcomes</relationshipLabel>
    <relationshipName>Facilities_Outcomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FacilityOutcomeTriggerHandler.cls
public with sharing class FacilityOutcomeTriggerHandler {
    private static List<Id> fosterIdList = new List<Id>();
    private static Set<Id> animalIdsForEvalProcess = new Set<Id>();
    private static Set<Id> foIdsForEvalProcess = new Set<Id>();

    public static void afterInsert(Facility_Outcome__c[] newRecords){
        for (Facility_Outcome__c foInsert : newRecords) {
            //Need to send survey for new Foster Home records
            //This checks for the Point of Contact since that's who would get the email
            if (foInsert.Facility_or_Outcome__c == 'Facility'
                && foInsert.Facility_Outcome__c == 'Foster Home'
                && foInsert.Point_of_Contact__c != null) {
                fosterIdList.add(foInsert.Id);
            }

            //if is ARC/CARE facility outcome add to animalIdsForEvalProcess            
            if(FacilityOutcomeUtil.EVAL_PROCESS_OUTCOME_OPTIONS.contains(foInsert.Facility_Outcome__c)){
                animalIdsForEvalProcess.add(foInsert.Animal__c);
                foIdsForEvalProcess.add(foInsert.Id);
            }
        }
    }

    public static void afterUpdate(Facility_Outcome__c[] newRecords, Map<Id, Facility_Outcome__c> oldMap){
        for (Facility_Outcome__c foUpdate : newRecords) {
            //Need to send survey for Foster Home records
            //when the Point of Contact gets either changed to another contact OR filled in from unassigned
            if(
                foUpdate.Facility_or_Outcome__c == 'Facility' &&
                foUpdate.Facility_Outcome__c ==  'Foster Home' &&
                (
                    (oldMap.get(foUpdate.Id).Point_of_Contact__c == null &&foUpdate.Point_of_Contact__c != null) ||
                    (oldMap.get(foUpdate.Id).Point_of_Contact__c != foUpdate.Point_of_Contact__c && foUpdate.Point_of_Contact__c != null)
                )
            ) {
                fosterIdList.add(foUpdate.Id);
            }
        }
    }

    public static void andFinally(){
        if(!fosterIdList.isEmpty()){
            FacilityOutcomeUtil.sendFosterSurveyEmail(fosterIdList);
        }

        if(!animalIdsForEvalProcess.isEmpty()){
            FacilityOutcomeUtil.handleEvaluationProcess(animalIdsForEvalProcess, foIdsForEvalProcess);
        }
    }
}