force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Behavior_Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Behavior Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Behavior Case Worker)</relationshipLabel>
    <relationshipName>Beh_Case_Worker_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/recordTypes/Behavior.recordType-meta.xml
<RecordType>
    <fullName>Behavior</fullName>
    <active>true</active>
    <label>Behavior</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Citizen</fullName>
            </value>
            <value>
                <fullName>Agency Representative</fullName>
            </value>
            <value>
                <fullName>Animal Control Officer</fullName>
            </value>
            <value>
                <fullName>Animal Owner</fullName>
            </value>
            <value>
                <fullName>Animal Rescue</fullName>
            </value>
            <value>
                <fullName>Animal Welfare Professional</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Code Enforcement Officer</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>County/Civil Attorney</fullName>
            </value>
            <value>
                <fullName>Defense Attorney</fullName>
            </value>
            <value>
                <fullName>Law Enforcement Contact</fullName>
            </value>
            <value>
                <fullName>Law Enforcement Officer</fullName>
            </value>
            <value>
                <fullName>Local Elected Official</fullName>
            </value>
            <value>
                <fullName>Officer/Complainant</fullName>
            </value>
            <value>
                <fullName>Prosecuting Attorney</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
            <value>
                <fullName>Senator</fullName>
            </value>
            <value>
                <fullName>Shelter Contact</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>State Representative</fullName>
            </value>
            <value>
                <fullName>State Senator</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Suspect</fullName>
            </value>
            <value>
                <fullName>US Representative</fullName>
            </value>
            <value>
                <fullName>US Senator</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Relocation Driver</fullName>
            </value>
            <value>
                <fullName>Behavior Case Worker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Generic_Contact__c.field-meta.xml
<CustomField>
    <fullName>Is_Generic_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Generic Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>What user will this Contact log into Salesforce ass</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/Facility_Outcome__c.object-meta.xml
<CustomObject>
    <label>Facility/Outcome</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>F/O #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facilities/Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility_Outcome__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipName>Animal_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Facility_or_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Facility_or_Outcome__c</fullName>
    <label>Facility or Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility</fullName>
            </value>
            <value>
                <fullName>Outcome</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Facility_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Facility_Outcome__c</fullName>
    <label>Facility/Outcome</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Facility_or_Outcome__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAH</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Adoption Center</fullName>
            </value>
            <value>
                <fullName>Adoption Center (Temp Boarding)</fullName>
            </value>
            <value>
                <fullName>Animal Hospital</fullName>
            </value>
            <value>
                <fullName>Animal Shelter</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>ASNA</fullName>
            </value>
            <value>
                <fullName>ASPCA Shelter</fullName>
            </value>
            <value>
                <fullName>Board and Train</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>BRC</fullName>
            </value>
            <value>
                <fullName>Bronx CVC</fullName>
            </value>
            <value>
                <fullName>Brooklyn CVC</fullName>
            </value>
            <value>
                <fullName>CARE</fullName>
            </value>
            <value>
                <fullName>Clinic</fullName>
            </value>
            <value>
                <fullName>Community Medicine</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
            <value>
                <fullName>CRC-MRC</fullName>
            </value>
            <value>
                <fullName>Cremation</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Euthanized</fullName>
            </value>
            <value>
                <fullName>Field Temp Shelter</fullName>
            </value>
            <value>
                <fullName>Foster-Based Rescue</fullName>
            </value>
            <value>
                <fullName>Foster Home</fullName>
            </value>
            <value>
                <fullName>Foster Home - Adoption Center</fullName>
            </value>
            <value>
                <fullName>Foster Home - ARC</fullName>
            </value>
            <value>
                <fullName>Foster Home - CARE</fullName>
            </value>
            <value>
                <fullName>Hound Hotel</fullName>
            </value>
            <value>
                <fullName>Kitten Nursery</fullName>
            </value>
            <value>
                <fullName>MRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Follow_Up_Days__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Days__c</fullName>
    <inlineHelpText>If left blank the default follow up schedule will apply</inlineHelpText>
    <label>Follow Up Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Scheduling_Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Follow_Up_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Frequency__c</fullName>
    <label>Follow Up Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every Other Week</fullName>
            </value>
            <value>
                <fullName>Every Three Weeks</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Every Other Month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Scheduling_Days.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Monday</fullName>
    </customValue>
    <customValue>
        <fullName>Tuesday</fullName>
    </customValue>
    <customValue>
        <fullName>Wednesday</fullName>
    </customValue>
    <customValue>
        <fullName>Thursday</fullName>
    </customValue>
    <customValue>
        <fullName>Friday</fullName>
    </customValue>
    <customValue>
        <fullName>Saturday</fullName>
    </customValue>
    <customValue>
        <fullName>Sunday</fullName>
    </customValue>
    <masterLabel>Scheduling Days</masterLabel>
</GlobalValueSet>

force-app/main/default/test/test_ScheduleAnimalFoster.cls
@isTest
private class test_ScheduleAnimalFoster {
    @TestSetUp
    static void testSetup(){
        Animal__c animal1 = TestDataFactory.createAnimalWithName('test1');
        Animal__c animal2 = TestDataFactory.createAnimalWithName('test2');
        Facility_Outcome__c loc1 = new Facility_Outcome__c(
            Animal__c = animal1.Id,
            Facility_or_Outcome__c = 'Facility',
            Facility_Outcome__c = 'Foster Home'
        );
        Facility_Outcome__c loc2 = new Facility_Outcome__c(
            Animal__c = animal2.Id,
            Facility_or_Outcome__c = 'Facility',
            Facility_Outcome__c = 'Foster Home'
        );
        insert new Facility_Outcome__c[]{loc1, loc2};
        
        User u = [SELECT Id FROM User Where Profile.Name = 'System Administrator' AND isActive = true LIMIT 1];
        User u2 = [SELECT Id FROM User Where Division = 'MRC' AND isActive = true LIMIT 1];
        Contact con = TestDataFactory.createContact();
        con.User__c = u.Id;
        con.Contact_Type__c = 'Behavior Case Worker';
        con.Email = 'testEmail@testEmail.com';
        update con;

        Contact genericContact = new Contact(
            LastName = 'generic',
            Is_Generic_Contact__c = true,
            User__c = u2.Id
        );
        insert genericContact;

        animal1.Behavior_Case_Worker__c = con.Id;
        animal2.Behavior_Case_Worker__c = con.Id;
        update new Animal__c[]{animal1, animal2};
    }

    @isTest
    static void scheduleFollowups_success() {
        test.startTest();
            Task[] toInsert = ScheduleAnimalFoster.scheduleFollowUps();
        test.stopTest();

        //one task for each animal should be created
        System.assertEquals(2, toInsert.size());
    }

    @isTest
    static void scheduleFollowups_withExistingTask() {
        Id recordTypeId = Util.getRecordTypeId('Task',AutoScheduleTasksUtil.FOSTER_TASK_RECORD_TYPE_NAME);
        Task[] existingTasks = new Task[0];
        for(Animal__c anim : [SELECT Id FROM Animal__c]){
            Task t = new Task(
                recordTypeId = recordTypeId,
                Animal__c = anim.Id,
                ActivityDate = date.today().addDays(-7)
            );
            existingTasks.add(t);
        }

        insert existingTasks;
        test.startTest();
            Task[] toInsert = ScheduleAnimalFoster.scheduleFollowUps();
        test.stopTest();

        //with default frequency new tasks should still be created for each animal
        System.assertEquals(2, toInsert.size());
    }

    @isTest
    static void scheduleFollowups_customSchedule() {
        Facility_Outcome__c[] locs = [SELECT Id, Follow_Up_Days__c, Follow_Up_Frequency__c FROM Facility_Outcome__c];
        locs[0].Follow_Up_Days__c = 'Wednesday;Friday';
        locs[1].Follow_Up_Frequency__c = 'Every Other Week';

        update locs;

        test.startTest();
            Task[] toInsert = ScheduleAnimalFoster.scheduleFollowUps();
        test.stopTest();

        //two tasks for locs[0] and one task for locs[1]
        System.assertEquals(3, toInsert.size());
    }

    @isTest
    static void scheduleFollowups_customScheduleWithExistingTasks() {
        Facility_Outcome__c[] locs = [SELECT Id, Follow_Up_Days__c, Follow_Up_Frequency__c FROM Facility_Outcome__c];
        locs[0].Follow_Up_Days__c = 'Wednesday;Friday';
        locs[0].Follow_Up_Frequency__c = 'Every Other Week';
        locs[1].Follow_Up_Days__c = 'Wednesday;Friday';
        locs[1].Follow_Up_Frequency__c = 'Every Other Week';
        update locs;

        Id recordTypeId = Util.getRecordTypeId('Task',AutoScheduleTasksUtil.FOSTER_TASK_RECORD_TYPE_NAME);
        Task[] existingTasks = new Task[0];
        Animal__c[] animals = [SELECT Id FROM Animal__c];

        Task t1 = new Task(
            recordTypeId = recordTypeId,
            Animal__c = animals[0].Id,
            WhatId = locs[0].Id,
            ActivityDate = date.today().addDays(-8),
            Subject = 'Foster Follow Up'
        );
        existingTasks.add(t1);

        Task t2 = new Task(
            recordTypeId = recordTypeId,
            Animal__c = animals[1].Id,
            WhatId = locs[1].Id,
            ActivityDate = date.today().addDays(-5),
            Subject = 'Foster Follow Up'
        );
        existingTasks.add(t2);

        insert existingTasks;

        test.startTest();
            Task[] toInsert = ScheduleAnimalFoster.scheduleFollowUps();
        test.stopTest();

        //two tasks for locs[0] and no tasks for locs[1]
        System.assertEquals(2, toInsert.size());
    }
}