force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Age__c.field-meta.xml
<CustomField>
    <fullName>Animal_Age__c</fullName>
    <label>Animal Age</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>For EQUINE, see Help Text</description>
    <inlineHelpText>For EQUINE, choose one of the following: Horse, Donkey, Mule, Draft Horse, Mini Horse, Pony, Mini Mule, Mini Donkey</inlineHelpText>
    <label>Breed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;Unspecified&quot;</defaultValue>
    <label>Primary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Primary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Intake_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Intake_Date_Time__c</fullName>
    <label>Intake Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Type_of_Animal__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Animal__c</fullName>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Species</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Agency_Case__c.field-meta.xml
<CustomField>
    <fullName>Agency_Case__c</fullName>
    <label>Agency Case #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/Plan_Protocol__c.object-meta.xml
<CustomObject>
    <label>Plan Protocol</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Plan Protocol Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Protocol__c/fields/Protocol_Description__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Description__c</fullName>
    <label>Protocol Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Plan Protocols</relationshipLabel>
    <relationshipName>Plan_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Treatment_Priority__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Priority__c</fullName>
    <label>Treatment Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Treatment</fullName>
                <default>true</default>
                <label>No Treatment</label>
            </value>
            <value>
                <fullName>Daily – 7 days</fullName>
            </value>
            <value>
                <fullName>High – 5 days</fullName>
            </value>
            <value>
                <fullName>Medium – 4 days</fullName>
            </value>
            <value>
                <fullName>Low – 3 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Primary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Bay roan</fullName>
    </customValue>
    <customValue>
        <fullName>Beige</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Blue roan</fullName>
    </customValue>
    <customValue>
        <fullName>Brindle</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Buckskin</fullName>
    </customValue>
    <customValue>
        <fullName>Buff</fullName>
    </customValue>
    <customValue>
        <fullName>Calico</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut/Sorrel</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Dun</fullName>
    </customValue>
    <customValue>
        <fullName>Fawn</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Grulla</fullName>
    </customValue>
    <customValue>
        <fullName>Hairless</fullName>
    </customValue>
    <customValue>
        <fullName>Liver chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Palomino</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Red roan</fullName>
    </customValue>
    <customValue>
        <fullName>Roan</fullName>
    </customValue>
    <customValue>
        <fullName>Seal</fullName>
    </customValue>
    <masterLabel>Primary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Species.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avian</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Cow</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Equine</fullName>
    </customValue>
    <customValue>
        <fullName>Exotic</fullName>
    </customValue>
    <customValue>
        <fullName>Fowl</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <masterLabel>Species</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PlanProtocolSelectorTest.cls
@isTest
public class PlanProtocolSelectorTest {

    @isTest
    static void testplanprotocol(){
        case objCase = new Case(Status = 'On hold',Origin='Email',Agency_Case__c = 'test');
        insert objCase ;
        
        Animal__c objAnimal = new Animal__c(Case__c =objCase.id, Name='A-001-West',type_of_animal__c='Cat',breed__c='Coonhound',gender__c='MI',Animal_Age__c=12,Color__c='Brown',Intake_Date_Time__c= DateTime.now());
        insert objAnimal;
        
        Plan_Protocol__c[] planProtocols = TestDataFactory.createPlanProtocols(4);
        
        Treatment_Plan__c arcPlan = new Treatment_Plan__c(
            Animal__c = objAnimal.Id,
            Treatment_Priority__c = 'Low – 3 days'
        );
        PlanProtocolSelector pps = new PlanProtocolSelector();
        Set<SObjectField> fields = pps.GetDefaultFields();
        
        List<Plan_Protocol__c> results1 = pps.GetById(new Set<Id>{planProtocols[0].Id});
        List<Plan_Protocol__c> results2 = pps.GetByName(planProtocols[0].Name);
        List<Plan_Protocol__c> results3 = pps.GetByOpp(arcPlan.Id);
        
        System.assertNotEquals(null, results3);
        
        planProtocols[0].Protocol_Description__c = 'test';
        update planProtocols[0];
        
        delete planProtocols[0];
        
    }
}