force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Photo_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Photo_Document_Id__c</fullName>
    <label>Photo Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AnimalPictureUploaderController.cls
public with sharing class AnimalPictureUploaderController {
    private Id animalId;
 
    public AnimalPictureUploaderController(){
        animalId = ApexPages.currentPage().getParameters().get('cid');
        system.debug('animalId ----'+animalId);
    }
 
    public PageReference initialise(){
        List<Attachment> listA = [select a.Id from Attachment a
                                    where // a.createdById =:UserInfo.getUserId() and
                                    a.parentId=:animalId order by a.createdDate desc limit 1];                                                    
        if (listA.size()>0){
            Id attachmentId = listA[0].Id;
             
            Animal__c animalObj = [select Id from Animal__c where Id=:animalId];
            animalObj.Photo_Document_Id__c = attachmentId;
            update animalObj;
        }
        return new PageReference('/'+animalId);       
    }
}