force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/Behavior_Evaluation__c.object-meta.xml
<CustomObject>
    <label>Behavior Evaluation</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Behavior Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Behavior Evaluations</relationshipLabel>
    <relationshipName>Behavior_Evaluations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Sessions Quote</relationshipLabel>
    <relationshipName>Treatment_Sessions_Quote</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/Session_Protocol__c.object-meta.xml
<CustomObject>
    <label>Session Protocol</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Session Protocol Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocols</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/fields/TreatmentSessionId__c.field-meta.xml
<CustomField>
    <fullName>TreatmentSessionId__c</fullName>
    <label>Treatment Session</label>
    <referenceTo>Treatment_Session__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Treatment_Bundle__c/Treatment_Bundle__c.object-meta.xml
<CustomObject>
    <label>Treatment Bundle</label>
    <nameField>
        <label>Treatment Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Treatment Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Treatment_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Treatment Bundle</label>
    <referenceTo>Treatment_Bundle__c</referenceTo>
    <relationshipLabel>Treatment Plans (Assigned Treatment Bundle)</relationshipLabel>
    <relationshipName>Assigned_Treatment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/Treatment_Session__c.object-meta.xml
<CustomObject>
    <label>Treatment Session</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Treatment Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Session__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Sessions</relationshipLabel>
    <relationshipName>Treatment_Sessions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <label>Treatment Plan</label>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Treatment Sessions</relationshipLabel>
    <relationshipName>Treatment_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/test/test_TreatmentSessionSelector.cls
@isTest 
private class test_TreatmentSessionSelector {
    @IsTest
    static void validateSessionCoverage() {
        InvocableActionHandler.InvocableActionRequest request = new InvocableActionHandler.InvocableActionRequest();

        List<Session_Protocol__c> sessionProtocols = TestDataFactory.createSessionProtocols();
        Treatment_Session__c session = new Treatment_Session__c();
        Session_Protocol__c protocol = sessionProtocols[0];
        session.Id = protocol.TreatmentSessionId__c;

        request.recordId = session.Id;
        request.targetSObject = 'Quote';
        request.action = 'validateSession';
        request.name = 'Test';

        List<InvocableActionHandler.InvocableActionRequest> requests = new List<InvocableActionHandler.InvocableActionRequest>();
        requests.add(request);

        List<InvocableActionHandler.InvocableActionResponse> responses = InvocableActionHandler.invocableAction
                (requests);

    }

    @IsTest
    static void validateSessionCoverageRegressionTest() {
        InvocableActionHandler.InvocableActionRequest request = new InvocableActionHandler.InvocableActionRequest();

        Treatment_Session__c session = TestDataFactory.createSession();

        request.recordId = session.Id;
        request.targetSObject = 'Quote';
        request.action = 'validateSession';
        request.name = 'Test';

        List<InvocableActionHandler.InvocableActionRequest> requests = new List<InvocableActionHandler.InvocableActionRequest>();
        requests.add(request);

        List<InvocableActionHandler.InvocableActionResponse> responses = InvocableActionHandler.invocableAction
                (requests);

        Test.startTest();

        System.debug(responses);

        Test.stopTest();
    }
    // @IsTest
    // static void validateAssignPlanActionWithNoPlan() {
    //     Behavior_Evaluation__c evaluation = TestDataFactory.createAdultBehaviorEvaluation(false);


    //     InvocableActionHandler.InvocableActionRequest actionRequest = new InvocableActionHandler.InvocableActionRequest();
    //     actionRequest.recordId = evaluation.Id;
    //     actionRequest.targetSObject = 'Treatment_Plan__c';
    //     actionRequest.name = 'assignPlanFromEval';
    //     actionRequest.action = 'assignPlan';
    //     InvocableActionHandler.InvocableActionResponse actionResponse = InvocableActionHandler.process(actionRequest);
    //     Test.startTest();
    //     System.assertEquals('NO PLAN FOUND', actionResponse.ResponseValue);
    //     System.debug(actionResponse);
    //     Test.stopTest();
    // }
    @IsTest
    static void validateAssignPlanActionWithPlan() {
        Behavior_Evaluation__c evaluation = TestDataFactory.createAdultBehaviorEvaluation(false);
        Treatment_Bundle__c masterbundle = TestDataFactory.createMasterBundle();
        Treatment_Plan__c plan = new Treatment_Plan__c();
        plan.Animal__c = evaluation.Animal__c;
        plan.IsActive__c = true;
        insert plan;

        InvocableActionHandler.InvocableActionRequest actionRequest = new InvocableActionHandler.InvocableActionRequest();
        actionRequest.recordId = evaluation.Id;
        actionRequest.targetSObject = 'Treatment_Plan__c';
        actionRequest.name = 'assignPlanFromEval';
        actionRequest.action = 'assignPlan';
        InvocableActionHandler.InvocableActionResponse actionResponse = InvocableActionHandler.process(actionRequest);

        Test.startTest();
        System.debug(actionResponse);

        Test.stopTest();
    }
}