force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Name_Id__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name_Id__c</fullName>
    <formula>Animal_Name__c + &apos; (&apos; +  Name + &apos;)&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animal Name/Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Behavior Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Behavior Case Worker)</relationshipLabel>
    <relationshipName>Beh_Case_Worker_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <label>Current Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Recent_Shelter_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Recent_Shelter_Location__c</fullName>
    <label>Current/Recent Shelter Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Type_of_Animal__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Animal__c</fullName>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Species</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Calendar_Schedule_Config__mdt/Calendar_Schedule_Config__mdt.object-meta.xml
<CustomObject>
    <description>Used to auto schedule items</description>
    <label>Calendar Schedule Config</label>
    <pluralLabel>Calendar Schedule Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Is_Generic_Contact__c.field-meta.xml
<CustomField>
    <fullName>Is_Generic_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Generic Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>What user will this Contact log into Salesforce ass</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/Facility_Outcome__c.object-meta.xml
<CustomObject>
    <label>Facility/Outcome</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>F/O #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facilities/Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility_Outcome__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipName>Animal_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Facility_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Facility_Outcome__c</fullName>
    <label>Facility/Outcome</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Facility_or_Outcome__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAH</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Adoption Center</fullName>
            </value>
            <value>
                <fullName>Adoption Center (Temp Boarding)</fullName>
            </value>
            <value>
                <fullName>Animal Hospital</fullName>
            </value>
            <value>
                <fullName>Animal Shelter</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>ASNA</fullName>
            </value>
            <value>
                <fullName>ASPCA Shelter</fullName>
            </value>
            <value>
                <fullName>Board and Train</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>BRC</fullName>
            </value>
            <value>
                <fullName>Bronx CVC</fullName>
            </value>
            <value>
                <fullName>Brooklyn CVC</fullName>
            </value>
            <value>
                <fullName>CARE</fullName>
            </value>
            <value>
                <fullName>Clinic</fullName>
            </value>
            <value>
                <fullName>Community Medicine</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
            <value>
                <fullName>CRC-MRC</fullName>
            </value>
            <value>
                <fullName>Cremation</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Euthanized</fullName>
            </value>
            <value>
                <fullName>Field Temp Shelter</fullName>
            </value>
            <value>
                <fullName>Foster-Based Rescue</fullName>
            </value>
            <value>
                <fullName>Foster Home</fullName>
            </value>
            <value>
                <fullName>Foster Home - Adoption Center</fullName>
            </value>
            <value>
                <fullName>Foster Home - ARC</fullName>
            </value>
            <value>
                <fullName>Foster Home - CARE</fullName>
            </value>
            <value>
                <fullName>Hound Hotel</fullName>
            </value>
            <value>
                <fullName>Kitten Nursery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Follow_Up_Days__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Days__c</fullName>
    <inlineHelpText>If left blank the default follow up schedule will apply</inlineHelpText>
    <label>Follow Up Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Scheduling_Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Follow_Up_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Frequency__c</fullName>
    <label>Follow Up Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every Other Week</fullName>
            </value>
            <value>
                <fullName>Every Three Weeks</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Every Other Month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Scheduling_Days.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Monday</fullName>
    </customValue>
    <customValue>
        <fullName>Tuesday</fullName>
    </customValue>
    <customValue>
        <fullName>Wednesday</fullName>
    </customValue>
    <customValue>
        <fullName>Thursday</fullName>
    </customValue>
    <customValue>
        <fullName>Friday</fullName>
    </customValue>
    <customValue>
        <fullName>Saturday</fullName>
    </customValue>
    <customValue>
        <fullName>Sunday</fullName>
    </customValue>
    <masterLabel>Scheduling Days</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Species.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avian</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Cow</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Equine</fullName>
    </customValue>
    <customValue>
        <fullName>Exotic</fullName>
    </customValue>
    <customValue>
        <fullName>Fowl</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <masterLabel>Species</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ScheduleAnimalFoster.cls
public with sharing class ScheduleAnimalFoster {
    public static Id recordTypeId = Util.getRecordTypeId('Task',AutoScheduleTasksUtil.FOSTER_TASK_RECORD_TYPE_NAME);
    public static Task[] scheduleFollowUps() {
        Task[] fosterTasks = new Task[0];
        Map<String, Calendar_Schedule_Config__mdt> calendarConfigMap = AutoScheduleTasksUtil.getCalendarConfig('Foster');
        Calendar_Schedule_Config__mdt defaultConfig = calendarConfigMap.get('Foster - All-Foster - Weekly');
        Animal__c[] animals = getAnimals();
        Map<Id, Task> animalToTaskMap = getTasks(animals);
        for(Animal__c animal : animals){
            if(needTasksThisWeek(animal, animalToTaskMap)){
                fosterTasks.addAll(prepTasks(animal, defaultConfig));
            }
        }
        return fosterTasks;
    }

    public static Animal__c[] getAnimals(){
        return [
            SELECT Id, Animal_Name_Id__c, Current_Recent_Shelter_Location__c, Current_Location__c, 
            Behavior_Case_Worker__c, Behavior_Case_Worker__r.Name, Behavior_Case_Worker__r.Is_Generic_Contact__c,
            (
                SELECT Id, Follow_Up_Days__c, Follow_Up_Frequency__c, CreatedDate
                FROM Animal_Locations__r
                WHERE Facility_Outcome__c = 'Foster Home'
                AND (End_Date__c = null OR End_Date__c >= TODAY)
                ORDER BY CreatedDate DESC
                LIMIT 1
            )
            FROM Animal__c
            WHERE Current_Location__c = 'Foster Home'
            AND Type_of_Animal__c = 'Dog'
            AND Id IN
            (
                SELECT Animal__c
                FROM Facility_Outcome__c
                WHERE Facility_Outcome__c = 'Foster Home'
                AND (End_Date__c = null OR End_Date__c >= TODAY)
            )
        ];
    }

    public static Map<Id,Task> getTasks(Animal__c[] animals){
        Map<Id,Task> taskMap = new Map<Id,Task>();
        Set<Id> animalIds = new Set<Id>();
        for(Animal__c anim : animals){
            animalIds.add(anim.Id);
        }

        for(Task t : [SELECT Id, ActivityDate, Animal__c FROM Task WHERE RecordTypeId =: recordTypeId AND Animal__c IN: animalIds ORDER BY ActivityDate DESC]){
            if(!taskMap.containsKey(t.Animal__c)){
                taskMap.put(t.Animal__c, t);
            }
        }

        return taskMap;
    }

    public static Boolean needTasksThisWeek(Animal__c animal, Map<Id, Task> taskMap){
        Boolean needsTasks = true;
        Facility_Outcome__c location = animal.Animal_Locations__r[0];
        if(location.Follow_Up_Frequency__c != null && location.Follow_Up_Frequency__c != 'Weekly' && taskMap.containsKey(animal.Id)){
            Task t = taskMap.get(animal.Id);
            if(t.ActivityDate.daysBetween(Date.Today()) < translateFrequency(location.Follow_Up_Frequency__c)){
                needsTasks = false;
            }
        }
        return needsTasks;
    }

    public static Integer translateFrequency(String frequency){
        Integer minDays = 0;
        switch on frequency {
            when 'Every Other Week' {
                minDays = 7;
            }	
            when 'Every Three Weeks' {
                minDays = 14;
            }
            when 'Monthly' {
                minDays = 23;
            }
            when 'Every Other Month' {
                minDays = 54;
            }
        }
        return minDays;
    }

    public static Task[] prepTasks(Animal__c animal, Calendar_Schedule_Config__mdt config){
        Contact genericCon = AutoScheduleTasksUtil.genericContactMap.get(animal.Current_Recent_Shelter_Location__c);
        Task[] newTasks = new Task[0];
        Map<String, Date> dateMap = new Map<String, Date>();

        Facility_Outcome__c location = animal.Animal_Locations__r[0];

        if(location.Follow_Up_Days__c == null){
            dateMap = AutoScheduleTasksUtil.getDateMap(config);
        } else {
            dateMap = AutoScheduleTasksUtil.getDateMap(location.Follow_Up_Days__c);
        }

        for(String day : dateMap.keySet()){
            Task newTask = new Task(
                WhatId = location.Id,
                Animal__c = animal.Id,
                RecordTypeId = recordTypeId,
                ActivityDate = dateMap.get(day),
                Description = 'Foster Follow Up for: ' + animal.Animal_Name_Id__c + ' (' + animal.Current_Recent_Shelter_Location__c + ')',
                IsReminderSet = true,
                Status = 'Not Started',
                WhoId = animal.Behavior_Case_Worker__c != null ? animal.Behavior_Case_Worker__c : genericCon.Id,
                OwnerId = genericCon.User__c,
                Subject = 'Foster Follow Up',
                Species__c = 'Dog'
            );
            newTasks.add(newTask);
        }
        return newTasks;
    }
}