force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age Estimate at Intake</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Age_Estimate_at_Intake</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Field_ID__c.field-meta.xml
<CustomField>
    <fullName>Animal_Field_ID__c</fullName>
    <label>Animal Field ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name__c</fullName>
    <externalId>true</externalId>
    <label>ASPCA Animal Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Concerns__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Concerns__c</fullName>
    <label>Behavior Concerns</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shy in Kennel</fullName>
            </value>
            <value>
                <fullName>Mouthy</fullName>
            </value>
            <value>
                <fullName>Dog Reactive</fullName>
            </value>
            <value>
                <fullName>Small Dogs</fullName>
            </value>
            <value>
                <fullName>Strangers</fullName>
            </value>
            <value>
                <fullName>Novelty</fullName>
            </value>
            <value>
                <fullName>Fearfull Outdoors</fullName>
            </value>
            <value>
                <fullName>Men</fullName>
            </value>
            <value>
                <fullName>Women</fullName>
            </value>
            <value>
                <fullName>Children</fullName>
            </value>
            <value>
                <fullName>RG Food/Objects</fullName>
            </value>
            <value>
                <fullName>Handling Issues</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>For EQUINE, see Help Text</description>
    <inlineHelpText>For EQUINE, choose one of the following: Horse, Donkey, Mule, Draft Horse, Mini Horse, Pony, Mini Mule, Mini Donkey</inlineHelpText>
    <label>Breed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;Unspecified&quot;</defaultValue>
    <label>Primary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Primary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Walking_Equipment__c.field-meta.xml
<CustomField>
    <fullName>Walking_Equipment__c</fullName>
    <label>Walking Equipment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Easy Walk Harness</fullName>
            </value>
            <value>
                <fullName>Gentle Leader</fullName>
            </value>
            <value>
                <fullName>Prong</fullName>
            </value>
            <value>
                <fullName>Regular Harness</fullName>
            </value>
            <value>
                <fullName>Regular Collar</fullName>
            </value>
            <value>
                <fullName>Chain Leash</fullName>
            </value>
            <value>
                <fullName>Walk with Toy</fullName>
            </value>
            <value>
                <fullName>Walk with Muzzle</fullName>
            </value>
            <value>
                <fullName>None Specified</fullName>
                <default>true</default>
                <label>None Specified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Walking_Status__c.field-meta.xml
<CustomField>
    <fullName>Walking_Status__c</fullName>
    <label>Walking Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Walks</fullName>
            </value>
            <value>
                <fullName>Terrace Walks</fullName>
            </value>
            <value>
                <fullName>Inside Walks</fullName>
            </value>
            <value>
                <fullName>Outside Walks</fullName>
            </value>
            <value>
                <fullName>2 person Walks</fullName>
            </value>
            <value>
                <fullName>Ok to take the Stairs</fullName>
            </value>
            <value>
                <fullName>None Specified</fullName>
                <default>true</default>
                <label>None Specified</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Age_Estimate_at_Intake.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Juvenile w/dam</fullName>
    </customValue>
    <customValue>
        <fullName>&lt; 6 months</fullName>
    </customValue>
    <customValue>
        <fullName>0-4 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-8 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>8-12 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>12-16 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 1 year</fullName>
    </customValue>
    <customValue>
        <fullName>1 year - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>2-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>5-7 years</fullName>
    </customValue>
    <customValue>
        <fullName>7-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>greater than 10 yrs</fullName>
    </customValue>
    <customValue>
        <fullName>Egg</fullName>
    </customValue>
    <customValue>
        <fullName>Chick: Up To 8 Weeks</fullName>
    </customValue>
    <customValue>
        <fullName>Pullet: Female &lt; 2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Adult: &gt;2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Stag: Male &lt;2YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (with dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (without dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Weanling</fullName>
    </customValue>
    <customValue>
        <fullName>Yearling</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>4-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>6-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>11-15 years</fullName>
    </customValue>
    <customValue>
        <fullName>15-20 years</fullName>
    </customValue>
    <customValue>
        <fullName>20+ years</fullName>
    </customValue>
    <customValue>
        <fullName>Chick (0-10 wks.)</fullName>
    </customValue>
    <masterLabel>Age Estimate at Intake</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Primary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Bay roan</fullName>
    </customValue>
    <customValue>
        <fullName>Beige</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Blue roan</fullName>
    </customValue>
    <customValue>
        <fullName>Brindle</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Buckskin</fullName>
    </customValue>
    <customValue>
        <fullName>Buff</fullName>
    </customValue>
    <customValue>
        <fullName>Calico</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut/Sorrel</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Dun</fullName>
    </customValue>
    <customValue>
        <fullName>Fawn</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Grulla</fullName>
    </customValue>
    <customValue>
        <fullName>Hairless</fullName>
    </customValue>
    <customValue>
        <fullName>Liver chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Palomino</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Red roan</fullName>
    </customValue>
    <customValue>
        <fullName>Roan</fullName>
    </customValue>
    <customValue>
        <fullName>Seal</fullName>
    </customValue>
    <masterLabel>Primary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/test/KennelSignageControllerTest.cls
@isTest
private class KennelSignageControllerTest {
    @isTest
    static void KennelSignageController_animalName() {
        Animal__c a = TestDataFactory.createAnimal();
        a.Animal_Field_ID__c = a.Id;
        update a;

        test.startTest();
            PageReference kennelSignage = Page.KennelSignage;
            kennelSignage.getParameters().put('id', a.Id);

            KennelSignageController cont = new KennelSignageController();
            cont.currentAnimal = a;

            system.assertEquals(a.Animal_Name__c, cont.m_animalName());
            system.assertEquals(a.Animal_Field_ID__c, cont.m_animalId());
            system.assertEquals(a.Breed__c, cont.m_animalBreed());
            system.assertEquals(a.Age__c, cont.m_animalAge());
            system.assertEquals(a.Gender__c, cont.m_animalSex());
            system.assertEquals(a.Color__c, cont.m_animalColor());
        test.stopTest();        
    }

    @isTest
    static void KennelSignageController_behaviorConcern() {
        Animal__c a = TestDataFactory.createAnimal();
        KennelSignageController cont = new KennelSignageController();
        cont.currentAnimal = a;

        test.startTest();
        KennelSignageController.behaviorConcern concern = new KennelSignageController.behaviorConcern('test', true);
        test.stopTest();

        System.assertEquals('test', concern.value);
        System.assertEquals(true, concern.isSelected);
    }

    @isTest
    static void KennelSignageController_getBehaviorConcerns() {
        Animal__c a = TestDataFactory.createAnimal();
        a.Behavior_Concerns__c = 'Shy in Kennel;Mouthy';
        KennelSignageController cont = new KennelSignageController();
        cont.currentAnimal = a;

        test.startTest();
        KennelSignageController.behaviorConcern[] concerns = new KennelSignageController.behaviorConcern[0];
        concerns = cont.getBehaviorConcerns();
        test.stopTest();

        System.assertEquals(false, concerns.isEmpty());
    }

    @isTest
    static void walkingEquipment() {
        test.startTest();
        KennelSignageController.walkingEquipment equip = new KennelSignageController.walkingEquipment('test', true);
        test.stopTest();

        System.assertEquals('test', equip.value);
        System.assertEquals(true, equip.isSelected);
    }

    @isTest
    static void KennelSignageController_getWalkingEquipment() {
        Animal__c a = TestDataFactory.createAnimal();
        a.Walking_Equipment__c = 'Easy Walk Harness;Prong';
        KennelSignageController cont = new KennelSignageController();
        cont.currentAnimal = a;

        test.startTest();
        KennelSignageController.walkingEquipment[] equipments = new KennelSignageController.walkingEquipment[0];
        equipments = cont.getWalkingEquipment();
        test.stopTest();

        System.assertEquals(false, equipments.isEmpty());
    }

    @isTest
    static void walkingStatus() {
        test.startTest();
        KennelSignageController.walkingStatus walking = new KennelSignageController.walkingStatus('test', true);
        test.stopTest();

        System.assertEquals('test', walking.value);
        System.assertEquals(true, walking.isSelected);
    }

    @isTest
    static void KennelSignageController_getWalkingStatus() {
        Animal__c a = TestDataFactory.createAnimal();
        a.Walking_Status__c = 'Terrace Walks;Inside Walks';
        KennelSignageController cont = new KennelSignageController();
        cont.currentAnimal = a;

        test.startTest();
        KennelSignageController.walkingStatus[] walkingStatuses = new KennelSignageController.walkingStatus[0];
        walkingStatuses = cont.getWalkingStatus();
        test.stopTest();

        System.assertEquals(false, walkingStatuses.isEmpty());
    }
}