force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <scale>15</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/Session_Protocol__c.object-meta.xml
<CustomObject>
    <label>Session Protocol</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Session Protocol Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocols</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/fields/Overall_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score__c</fullName>
    <label>Overall Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Beginning/Acquisition</fullName>
            </value>
            <value>
                <fullName>2. Catching On/ Fluency</fullName>
            </value>
            <value>
                <fullName>3. Almost There/ Generalization</fullName>
            </value>
            <value>
                <fullName>4. Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ARC/CARE</fullName>
            </value>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/test/Test_TreatmentsByDogPDFController.cls
@isTest private class Test_TreatmentsByDogPDFController {
    @isTest 
    static void getDogList_Success(){
        User u = [SELECT Id, Location__c FROM User WHERE Id =: userInfo.getUserId()];
        u.Location__c = 'CRC/MRC';
        update u;

        Animal__c willow = TestDataFactory.createAnimalWithName('willow');
        Animal__c fido = TestDataFactory.createAnimalWithName('fido');
        TestDataFactory.createBehaviorMedicationTask(willow.Id);

        test.startTest();
        TreatmentsByDogPDFController.DogInfoWrapper[] dogs = TreatmentsByDogPDFController.getDogInfo(
            new Id[]{willow.Id, fido.Id}, 
            true
        );
        test.stopTest();

        System.assertEquals(2, dogs.size());
    }

    @isTest 
    static void getDogTreatmentsByIds_Success(){
        Session_Protocol__c[] protocols = TestDataFactory.createSessionProtocols();
        for(Session_Protocol__c protocol : protocols){
            protocol.Overall_Score__c = '1. Beginning/Acquisition';
        }

        update protocols;

        Animal__c dog = [SELECT Id FROM Animal__c LIMIT 1];

        test.startTest();
            Map<Id, Map<String, TreatmentsByDogPDFController.TxProtocolWrapper>> dogTreatmentsMap = TreatmentsByDogPDFController.getDogTreatments(new Id[]{dog.Id});
        test.stopTest();

        System.assert(!dogTreatmentsMap.isEmpty(), 'Should have returned a map, but was empty');
    }

    @isTest 
    static void getDogTreatmentsByIds_NoDogs(){
        Session_Protocol__c[] protocols = TestDataFactory.createSessionProtocols();
        for(Session_Protocol__c protocol : protocols){
            protocol.Overall_Score__c = '1. Beginning/Acquisition';
        }

        update protocols;

        Animal__c dog = [SELECT Id FROM Animal__c LIMIT 1];

        test.startTest();
            Map<Id, Map<String, TreatmentsByDogPDFController.TxProtocolWrapper>> dogTreatmentsMap = TreatmentsByDogPDFController.getDogTreatments(new Id[0]);
        test.stopTest();

        System.assert(dogTreatmentsMap.isEmpty(), 'Should have returned an empty map, but was: ' + dogTreatmentsMap);
    }
}