force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age Estimate at Intake</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Age_Estimate_at_Intake</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;Unspecified&quot;</defaultValue>
    <label>Primary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Primary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Type_of_Animal__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Animal__c</fullName>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Species</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/Animal_Exam_Sheet__c.object-meta.xml
<CustomObject>
    <label>Animal Exam Sheet</label>
    <nameField>
        <displayFormat>EX-{0}</displayFormat>
        <label>Exam Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Exam Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animal Exam Sheets</relationshipLabel>
    <relationshipName>Animal_Exam_Sheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Animal_Exam_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Animal_Exam_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Exam Sheet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Animal_Exam_Sheet__c.Animal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Animal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Animal_Exam_Sheet__c</referenceTo>
    <relationshipLabel>Animal Exam Sheets</relationshipLabel>
    <relationshipName>Animal_Exam_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Babesia__c.field-meta.xml
<CustomField>
    <fullName>Babesia__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Babesia (INACTIVE)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Babesia_Results__c.field-meta.xml
<CustomField>
    <fullName>Babesia_Results__c</fullName>
    <label>Babesia Results (INACTIVE)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <formula>Animal__r.Case__r.CaseNumber</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case #</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <formula>Text(Animal__r.Color__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Color</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Editor__c.field-meta.xml
<CustomField>
    <fullName>Editor__c</fullName>
    <inlineHelpText>Please enter your initials, today&apos;s date, and time.</inlineHelpText>
    <label>Editor</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Felv_FIV_Results__c.field-meta.xml
<CustomField>
    <fullName>Felv_FIV_Results__c</fullName>
    <label>FeLV Results (INACTIVE)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Abnormal</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/FIV__c.field-meta.xml
<CustomField>
    <fullName>FIV__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FIV (INACTIVE)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/FIV_Results__c.field-meta.xml
<CustomField>
    <fullName>FIV_Results__c</fullName>
    <label>FIV Results (INACTIVE)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Abnormal</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <formula>Text(Animal__r.Gender__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sex</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Heartworm__c.field-meta.xml
<CustomField>
    <fullName>Heartworm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Heartworm</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Heartworm_Results__c.field-meta.xml
<CustomField>
    <fullName>Heartworm_Results__c</fullName>
    <label>Heartworm Results (INACTIVE)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Exam_Sheet__c/fields/Include_in_discharge__c.field-meta.xml
<CustomField>
    <fullName>Include_in_discharge__c</fullName>
    <inlineHelpText>Please select if this exam sheet needs to be included in the discharge form.</inlineHelpText>
    <label>Include in discharge?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Diagnostic__c/Diagnostic__c.object-meta.xml
<CustomObject>
    <label>Diagnostic</label>
    <nameField>
        <displayFormat>DI-{00000}</displayFormat>
        <label>Diagnostic Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Diagnostics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Diagnostic__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Diagnostics</relationshipLabel>
    <relationshipName>Diagnostics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Diagnostic__c/fields/Animal_Exam_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Animal_Exam_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Exam Sheet</label>
    <referenceTo>Animal_Exam_Sheet__c</referenceTo>
    <relationshipLabel>Diagnostics</relationshipLabel>
    <relationshipName>Diagnostics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Diagnostic__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Diagnostic__c/fields/Include_in_discharge__c.field-meta.xml
<CustomField>
    <fullName>Include_in_discharge__c</fullName>
    <defaultValue>&apos;Yes&apos;</defaultValue>
    <inlineHelpText>All but &quot;Anabolic steroid testing&quot; included by default.</inlineHelpText>
    <label>Include in discharge?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Diagnostic__c/fields/Test_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Name__c</fullName>
    <label>Test Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fecal OP</fullName>
            </value>
            <value>
                <fullName>CBC</fullName>
            </value>
            <value>
                <fullName>Chem</fullName>
            </value>
            <value>
                <fullName>Witness Pregnancy</fullName>
            </value>
            <value>
                <fullName>Heartworm</fullName>
            </value>
            <value>
                <fullName>Anaplasma</fullName>
            </value>
            <value>
                <fullName>Lyme</fullName>
            </value>
            <value>
                <fullName>Ehrlichia</fullName>
            </value>
            <value>
                <fullName>Microfilaria</fullName>
            </value>
            <value>
                <fullName>Ear Cytology</fullName>
            </value>
            <value>
                <fullName>ACTH Stim</fullName>
            </value>
            <value>
                <fullName>Anabolic Steroid Testing</fullName>
            </value>
            <value>
                <fullName>Avian Influenza PCR</fullName>
            </value>
            <value>
                <fullName>Babesia</fullName>
            </value>
            <value>
                <fullName>Blood Glucose</fullName>
            </value>
            <value>
                <fullName>Blood Pressure</fullName>
            </value>
            <value>
                <fullName>Bronchitis PCR</fullName>
            </value>
            <value>
                <fullName>Canine GI Panel</fullName>
            </value>
            <value>
                <fullName>Coggins (EIA)</fullName>
            </value>
            <value>
                <fullName>Cortisol/Creatinine Ratio</fullName>
            </value>
            <value>
                <fullName>Culture &amp; Sensitivity</fullName>
            </value>
            <value>
                <fullName>Diarrhea PCR</fullName>
            </value>
            <value>
                <fullName>Ear Swab for Mites</fullName>
            </value>
            <value>
                <fullName>FeLV</fullName>
            </value>
            <value>
                <fullName>FIV</fullName>
            </value>
            <value>
                <fullName>Fluorescein Stain</fullName>
            </value>
            <value>
                <fullName>FNA</fullName>
            </value>
            <value>
                <fullName>Fructosamine</fullName>
            </value>
            <value>
                <fullName>Fungal Culture</fullName>
            </value>
            <value>
                <fullName>Giardia SNAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medical_Conditions__c/Medical_Conditions__c.object-meta.xml
<CustomObject>
    <label>Medical Condition</label>
    <nameField>
        <displayFormat>MC-{0}</displayFormat>
        <label>Medical Conditions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Conditions__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal ID</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Medical Conditions</relationshipLabel>
    <relationshipName>Medical_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Conditions__c/fields/Date_Diagnosed__c.field-meta.xml
<CustomField>
    <fullName>Date_Diagnosed__c</fullName>
    <label>Date Diagnosed</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Medical_Conditions__c/fields/Include_in_discharge__c.field-meta.xml
<CustomField>
    <fullName>Include_in_discharge__c</fullName>
    <label>Include in discharge?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Treatments.recordType-meta.xml
<RecordType>
    <fullName>Treatments</fullName>
    <active>true</active>
    <description>Treatment tasks</description>
    <label>Treatments</label>
</RecordType>

force-app/main/default/globalValueSets/Age_Estimate_at_Intake.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Juvenile w/dam</fullName>
    </customValue>
    <customValue>
        <fullName>&lt; 6 months</fullName>
    </customValue>
    <customValue>
        <fullName>0-4 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-8 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>8-12 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>12-16 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 1 year</fullName>
    </customValue>
    <customValue>
        <fullName>1 year - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>2-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>5-7 years</fullName>
    </customValue>
    <customValue>
        <fullName>7-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>greater than 10 yrs</fullName>
    </customValue>
    <customValue>
        <fullName>Egg</fullName>
    </customValue>
    <customValue>
        <fullName>Chick: Up To 8 Weeks</fullName>
    </customValue>
    <customValue>
        <fullName>Pullet: Female &lt; 2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Adult: &gt;2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Stag: Male &lt;2YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (with dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (without dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Weanling</fullName>
    </customValue>
    <customValue>
        <fullName>Yearling</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>4-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>6-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>11-15 years</fullName>
    </customValue>
    <customValue>
        <fullName>15-20 years</fullName>
    </customValue>
    <customValue>
        <fullName>20+ years</fullName>
    </customValue>
    <customValue>
        <fullName>Chick (0-10 wks.)</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown At Intake</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
        <isActive>false</isActive>
        <label>Unknown</label>
    </customValue>
    <masterLabel>Age Estimate at Intake</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Primary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Bay roan</fullName>
    </customValue>
    <customValue>
        <fullName>Beige</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Blue roan</fullName>
    </customValue>
    <customValue>
        <fullName>Brindle</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Buckskin</fullName>
    </customValue>
    <customValue>
        <fullName>Buff</fullName>
    </customValue>
    <customValue>
        <fullName>Calico</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut/Sorrel</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Dun</fullName>
    </customValue>
    <customValue>
        <fullName>Fawn</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Grulla</fullName>
    </customValue>
    <customValue>
        <fullName>Hairless</fullName>
    </customValue>
    <customValue>
        <fullName>Liver chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Palomino</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Red roan</fullName>
    </customValue>
    <customValue>
        <fullName>Roan</fullName>
    </customValue>
    <customValue>
        <fullName>Seal</fullName>
    </customValue>
    <masterLabel>Primary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Species.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avian</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Cow</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Equine</fullName>
    </customValue>
    <customValue>
        <fullName>Exotic</fullName>
    </customValue>
    <customValue>
        <fullName>Fowl</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <masterLabel>Species</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DischargeTest.cls
@isTest
private class DischargeTest {

    static testMethod void unitTest(){
        
        Case cs = new Case();
        insert cs;  
        
        Discharge objDischarge  = new Discharge (new ApexPages.StandardController(cs));
        
        Animal__c objAnimal = new Animal__c(Name='Test', Case__c=cs.Id, Type_of_Animal__c = 'Dog', Gender__c = 'Unknown', Age__c = 'Unknown At Intake', Color__c = 'Black');
        insert objAnimal;
        
        PageReference pageRef = Page.Animal_Discharge;
        Test.setCurrentPage(pageRef);
        apexpages.currentpage().getparameters().put('Id' , objAnimal.id);
        
        RecordType treatmentType = [SELECT ID FROM RecordType WHERE Name = 'Treatments' AND SObjectType = 'Task' LIMIT 1];
       	ID treatmentID = treatmentType.ID;
        
        Animal_Exam_Sheet__c objAnimalExam = new Animal_Exam_Sheet__c (Animal__c =objAnimal.id,Heartworm__c=true,FIV__c=true,FIV_Results__c='FIVResult',Heartworm_Results__c='heartwormResult',Babesia__c=true,Babesia_Results__c='babesiaResult',Felv_FIV_Results__c='FelvFIV',Include_in_discharge__c ='Yes',Editor__c='AS');
        insert objAnimalExam;
        
        Task objTask1 = new Task (WhatId = objAnimal.id, RecordTypeId = treatmentID, Animal_Exam_Sheet_Lookup__c=objAnimalExam.id, Editor__c='AS', Include_in_discharge__c='Yes', ActivityDate=Date.newInstance(2021, 10, 8), Subject='Treatment Dread', Status='In Progress');
        insert objTask1;
        
        Task objTask2 = new Task (WhatId = objAnimal.id, RecordTypeId = treatmentID, Animal_Exam_Sheet_Lookup__c=objAnimalExam.id, Editor__c='AS', Include_in_discharge__c='Yes', ActivityDate=Date.newInstance(2021, 10, 17), Subject='Treatment Wedding', Status='Completed', Completed_By_Text__c='AH');
        insert objTask2;
        
        Task objTask3 = new Task (WhatId = objAnimal.id, RecordTypeId = treatmentID, Animal_Exam_Sheet_Lookup__c=objAnimalExam.id, Editor__c='AS', Include_in_discharge__c='Yes', ActivityDate=Date.newInstance(2021, 10, 20), Subject='Treatment Honeymoon', Status='In Progress');
        insert objTask3;
        
        Task objTask4 = new Task (WhatId = objAnimal.id, RecordTypeId = treatmentID, Animal_Exam_Sheet_Lookup__c=objAnimalExam.id, Editor__c='AS', Include_in_discharge__c='Yes', ActivityDate=Date.newInstance(2021, 10, 21), Subject='Treatment Honeymoon', Status='In Progress');
        insert objTask4;
        
        Task objTask5 = new Task (WhatId = objAnimal.id, RecordTypeId = treatmentID, Animal_Exam_Sheet_Lookup__c=objAnimalExam.id, Editor__c='AS', Include_in_discharge__c='Yes', ActivityDate=Date.newInstance(2021, 10, 27), Subject='Treatment Honeymoon', Status='Completed', Completed_By_Text__c='AH');
        insert objTask5;
        
        Task objTask6 = new Task (WhatId = objAnimal.id, RecordTypeId = treatmentID, Animal_Exam_Sheet_Lookup__c=objAnimalExam.id, Editor__c='AS', Include_in_discharge__c='Yes', ActivityDate=Date.newInstance(2021, 10, 28), Subject='Treatment Honeymoon', Status='Completed', Completed_By_Text__c='AH');
        insert objTask6;
        
        Medical_Conditions__c objMedCon = new Medical_Conditions__c(Animal__c=objAnimal.Id, Date_Diagnosed__c = System.Today(), Include_in_discharge__c = 'Yes');
        insert objMedCon;
        
        Diagnostic__c diag = new Diagnostic__c(Animal__c=objAnimal.Id, Animal_Exam_Sheet__c=objAnimalExam.Id, Include_in_discharge__c = 'Yes', Date__c = System.Today(), Test_Name__c = 'CBC');
        insert diag;
        
                
        System.assertEquals(1, objDischarge.examSheets.size());
		System.assertEquals(6, objDischarge.tsks.size());
		System.assertEquals(1, objDischarge.medCons.size());
        System.assertEquals(1, objDischarge.diags.size());
        System.assertEquals(3, objDischarge.currentTasks.size());
        System.assertEquals(3, objDischarge.pastTasks.size());

    }
    
}