force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <label>Current Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Final_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Final_Outcome__c</fullName>
    <label>Final Outcome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Type_of_Animal__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Animal__c</fullName>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Species</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/Plan_Protocol__c.object-meta.xml
<CustomObject>
    <label>Plan Protocol</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Plan Protocol Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Protocol__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Plan Protocols</relationshipLabel>
    <relationshipName>Plan_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Plan Protocols</relationshipLabel>
    <relationshipName>Plan_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Protocol__c/fields/Protocol_Categories__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Categories__c</fullName>
    <label>Protocol Categories</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fear Containment</fullName>
            </value>
            <value>
                <fullName>Fear Handling</fullName>
            </value>
            <value>
                <fullName>Fear Leashing</fullName>
            </value>
            <value>
                <fullName>Fear Socialization</fullName>
            </value>
            <value>
                <fullName>Fear Walking</fullName>
            </value>
            <value>
                <fullName>Non Fear Protocols</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Species.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avian</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Cow</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Equine</fullName>
    </customValue>
    <customValue>
        <fullName>Exotic</fullName>
    </customValue>
    <customValue>
        <fullName>Fowl</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <masterLabel>Species</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MRCTreatmentPlansReportLWCController.cls
public with sharing class MRCTreatmentPlansReportLWCController {
    @AuraEnabled
    public static Animal__c[] getMRCDogs(){
        try {
            return [
                SELECT Id 
                FROM Animal__c 
                WHERE Type_of_Animal__c = 'Dog'
                AND Current_Location__c IN ('MRC','CRC')
                AND Final_Outcome__c = null

            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static AnimalInfo getAnimalInfo(Id recordId){
        try {
            AnimalInfo info = new AnimalInfo();
            info.restDays = DailyCareLWCController.getAnimalRestDays(recordId);
            info.categoryToProtocolIdMap = getProtocolIdMap(recordId);

            return info;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static Map<String, Id[]> getProtocolIdMap(Id animalId){
        Map<String, Id[]> protocolMap = new Map<String, Id[]>();
        for(Plan_Protocol__c protocol : [
            SELECT Id, Protocol__r.Protocol_Categories__c 
            FROM Plan_Protocol__c 
            WHERE Treatment_Plan__r.IsActive__c = TRUE
            AND Treatment_Plan__r.Animal__c =: animalId
        ]){
            String category = protocol.Protocol__r.Protocol_Categories__c == null ? 'Non Fear Protocols' : protocol.Protocol__r.Protocol_Categories__c;
            
            if(protocolMap.containsKey(category)){
                protocolMap.get(category).add(protocol.Id);
            }else{
                protocolMap.put(category, new Id[]{protocol.Id});
            }
        }
        return protocolMap;
    }

    // private static List<Plan_Protocol__c[]> getProtocolIdLists(Id animalId){
    //     Plan_Protocol__c[] protocols = [SELECT Id, Protocol__r.Protocol_Categories__c FROM Plan_Protocol__c WHERE Protocol__r.Protocol_Categories__c = 'Fear Walking'];
    //     List<Plan_Protocol__c[]> mainList = new List<Plan_Protocol__c[]>();
    //     mainList.add(protocols);
    //     return mainList;
    // }

    public class AnimalInfo{
        @AuraEnabled public String restDays;
        @AuraEnabled public Map<String, Id[]> categoryToProtocolIdMap;
    }
}