force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Name_Id__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name_Id__c</fullName>
    <formula>Animal_Name__c + &apos; (&apos; +  Name + &apos;)&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animal Name/Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>For EQUINE, see Help Text</description>
    <inlineHelpText>For EQUINE, choose one of the following: Horse, Donkey, Mule, Draft Horse, Mini Horse, Pony, Mini Mule, Mini Donkey</inlineHelpText>
    <label>Breed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <label>Current Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Helper_Dogs__c.field-meta.xml
<CustomField>
    <fullName>Helper_Dogs__c</fullName>
    <inlineHelpText>The dogs favorite helper dogs</inlineHelpText>
    <label>Helper Dogs</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <scale>15</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Play_Pause__c.field-meta.xml
<CustomField>
    <fullName>Play_Pause__c</fullName>
    <label>Play-Pause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Shelter_Color_Coding__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Color_Coding__c</fullName>
    <inlineHelpText>Shelter handling color code for the animal</inlineHelpText>
    <label>Shelter Color Coding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shelter_Color_Coding</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Shelter_Location__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Location__c</fullName>
    <label>Kennel Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Generic_Data__c/Generic_Data__c.object-meta.xml
<CustomObject>
    <description>This object is to hold generic data that does not have an object to live on</description>
    <label>Generic Data</label>
    <nameField>
        <label>Generic Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Generic Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Generic_Data__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Description of what this generic data is used for</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Generic_Data__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <inlineHelpText>What location is this data for</inlineHelpText>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>CARE</fullName>
            </value>
            <value>
                <fullName>ARC/CARE</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
            <value>
                <fullName>CRC-MRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Generic_Data__c/fields/Species__c.field-meta.xml
<CustomField>
    <fullName>Species__c</fullName>
    <inlineHelpText>What Species is this generic data for?</inlineHelpText>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Species</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Generic_Data__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <inlineHelpText>This is the generic data - text format</inlineHelpText>
    <label>Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/Plan_Protocol__c.object-meta.xml
<CustomObject>
    <label>Plan Protocol</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Plan Protocol Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Protocol__c/fields/Protocol_Notes__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Notes__c</fullName>
    <label>Protocol Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Plan Protocols</relationshipLabel>
    <relationshipName>Plan_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Play_Pause__c/Play_Pause__c.object-meta.xml
<CustomObject>
    <label>Play Pause</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Play Pause #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Play Pauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Play_Pause__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalshelters__Animal__c</referenceTo>
    <relationshipLabel>Play Pauses</relationshipLabel>
    <relationshipName>Play_Pauses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/AssignedTreatmentBundleId__c.field-meta.xml
<CustomField>
    <fullName>AssignedTreatmentBundleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Treatment Bundle</label>
    <referenceTo>Treatment_Bundle__c</referenceTo>
    <relationshipLabel>Treatment Plans (Assigned Treatment Bundle)</relationshipLabel>
    <relationshipName>Assigned_Treatment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Preferred_Motivators__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Motivators__c</fullName>
    <label>Preferred Motivators</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Problem_Behavior__c.field-meta.xml
<CustomField>
    <fullName>Problem_Behavior__c</fullName>
    <label>Problem Behavior (see TEC)</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fear of People - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of People - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of People - Severe</fullName>
            </value>
            <value>
                <fullName>Fear of Handling - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of Handling - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of Handling - Severe</fullName>
            </value>
            <value>
                <fullName>Fear of Leashing, Leash Pressure, Walking on Leash - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of Leashing, Leash Pressure, Walking on Leash - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of Leashing, Leash Pressure, Walking on Leash - Severe</fullName>
            </value>
            <value>
                <fullName>Fear of Places, Objects, Novelty - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of Places, Objects, Novelty - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of Places, Objects, Novelty - Severe</fullName>
            </value>
            <value>
                <fullName>Fear of Noises - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of Noises - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of Noises - Severe</fullName>
            </value>
            <value>
                <fullName>Fear of Dogs - Mild</fullName>
            </value>
            <value>
                <fullName>Fear of Dogs - Moderate</fullName>
            </value>
            <value>
                <fullName>Fear of Dogs - Severe</fullName>
            </value>
            <value>
                <fullName>Reactivity Toward People/Dogs (Specific to Kennel) - Mild</fullName>
            </value>
            <value>
                <fullName>Reactivity Toward People/Dogs (Specific to Kennel) - Moderate</fullName>
            </value>
            <value>
                <fullName>Reactivity Toward People/Dogs (Specific to Kennel) - Severe</fullName>
            </value>
            <value>
                <fullName>Arousal in Kennel/Shelter Stress - Mild</fullName>
            </value>
            <value>
                <fullName>Arousal in Kennel/Shelter Stress - Moderate</fullName>
            </value>
            <value>
                <fullName>Arousal in Kennel/Shelter Stress - Severe</fullName>
            </value>
            <value>
                <fullName>Arousal Out of Kennel/Jumping &amp; Mouthing - Mild</fullName>
            </value>
            <value>
                <fullName>Arousal Out of Kennel/Jumping &amp; Mouthing - Moderate</fullName>
            </value>
            <value>
                <fullName>Arousal Out of Kennel/Jumping &amp; Mouthing - Severe</fullName>
            </value>
            <value>
                <fullName>Reactivity on Leash (People) - Mild</fullName>
            </value>
            <value>
                <fullName>Reactivity on Leash (People) - Moderate</fullName>
            </value>
            <value>
                <fullName>Reactivity on Leash (People) - Severe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Species.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avian</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Cow</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Equine</fullName>
    </customValue>
    <customValue>
        <fullName>Exotic</fullName>
    </customValue>
    <customValue>
        <fullName>Fowl</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <masterLabel>Species</masterLabel>
</GlobalValueSet>

force-app/main/default/test/Test_MRCTxPlansReportLWCController.cls
@isTest
private class Test_MRCTxPlansReportLWCController {
    @isTest
    static void getMotivators_Success() {
        Treatment_Plan__c tp = TestDataFactory.createPlan();
        tp.Preferred_Motivators__c = 'toys;treats';
        update tp;

        Treatment_Plan__c tp2 = new Treatment_Plan__c(
          IsActive__c = false, 
          Description__c = 'Test', 
          Animal__c = tp.Animal__c, 
          AssignedTreatmentBundleId__c = tp.AssignedTreatmentBundleId__c,
          Problem_Behavior__c = 'Fear of People - Mild',
          Preferred_Motivators__c = 'Treats;newspaper'

        );

        insert tp2;

        Animal__c dog = [SELECT Id, (SELECT Id, Preferred_Motivators__c FROM Treatment_Plan__r) FROM Animal__c WHERE Id =: tp.Animal__c LIMIT 1];

        test.startTest();
            String motivators = MRCTreatmentPlansReportLWCController.getMotivators(dog);
        test.stopTest();

        System.assert(motivators.contains('toys'), 'Should have included toys');
        System.assert(motivators.contains('treats'), 'Should have included treats');
        System.assert(motivators.contains('Treats'), 'Should have included Treats');
        System.assert(motivators.contains('newspaper'), 'Should have included newspaper');
    }

    @isTest
    static void getMotivators_NoMotivators() {
        Treatment_Plan__c tp = TestDataFactory.createPlan();

        Treatment_Plan__c tp2 = new Treatment_Plan__c(
          IsActive__c = false, 
          Description__c = 'Test', 
          Animal__c = tp.Animal__c, 
          AssignedTreatmentBundleId__c = tp.AssignedTreatmentBundleId__c,
          Problem_Behavior__c = 'Fear of People - Mild'
        );

        insert tp2;

        Animal__c dog = [SELECT Id, (SELECT Id, Preferred_Motivators__c FROM Treatment_Plan__r) FROM Animal__c WHERE Id =: tp.Animal__c LIMIT 1];

        test.startTest();
            String motivators = MRCTreatmentPlansReportLWCController.getMotivators(dog);
        test.stopTest();

        System.assertEquals('', motivators, 'Should have returned a blank string, but was: ' + motivators);
    }

    @isTest
    static void getProtocolCategoryMap_Success() {
        Treatment_Plan__c tp = TestDataFactory.createPlan();

        test.startTest();
            Map<Id, Map<String, Plan_Protocol__c[]>> protocolIdMap = MRCTreatmentPlansReportLWCController.getProtocolCategoryMap(new Id[]{tp.Animal__c});
        test.stopTest();

        System.assert(!protocolIdMap.isEmpty(), 'Should have returned a map, instead was empty');
    }

    @isTest
    static void getProtocolCategoryMap_NoProtocols() {
        Animal__c dog = TestDataFactory.createAnimal();

        test.startTest();
            Map<Id, Map<String, Plan_Protocol__c[]>> protocolIdMap = MRCTreatmentPlansReportLWCController.getProtocolCategoryMap(new Id[]{dog.Id});
        test.stopTest();

        System.assert(protocolIdMap.isEmpty(), 'Should have returned an empty map, instead was: ' + protocolIdMap);
    }

    @isTest 
    static void getHelperDogs_Success(){
        Animal__c dog = TestDataFactory.createAnimal();
        dog.Helper_Dogs__c = 'fido;willow';
        update dog;

        test.startTest();
            dog = MRCTreatmentPlansReportLWCController.getHelperDogs(dog.Id);
        test.stopTest();

        System.assertEquals('fido;willow', dog.Helper_Dogs__c);
    }

    @isTest 
    static void getHelperDogs_NoDogs(){
        Animal__c dog = TestDataFactory.createAnimal();
        update dog;

        test.startTest();
            dog = MRCTreatmentPlansReportLWCController.getHelperDogs(dog.Id);
        test.stopTest();

        System.assertEquals(null, dog.Helper_Dogs__c);
    }

    @isTest 
    static void getPlanProtocolInfo_Success(){
        Plan_Protocol__c[] protocols = TestDataFactory.createPlanProtocols(1);
        protocols[0].Protocol_Notes__c = 'test notes';
        update protocols;

        test.startTest();
            Plan_Protocol__c protocol = MRCTreatmentPlansReportLWCController.getPlanProtocolInfo(protocols[0].Id);
        test.stopTest();

        System.assertEquals('test notes', protocol.Protocol_Notes__c);
    }

    @isTest 
    static void getPlanProtocolInfo_NoNotes(){
        Plan_Protocol__c[] protocols = TestDataFactory.createPlanProtocols(1);

        test.startTest();
            Plan_Protocol__c protocol = MRCTreatmentPlansReportLWCController.getPlanProtocolInfo(protocols[0].Id);
        test.stopTest();

        System.assertEquals(null, protocol.Protocol_Notes__c);
    }

    @isTest
    static void getAnimalInfos_Success(){
        Treatment_Plan__c tp = TestDataFactory.createPlan();
        tp.Preferred_Motivators__c = 'test;toys';
        update tp;


        Play_Pause__c[] pps = TestDataFactory.createPlayPauses(new Animal__c(Id = tp.Animal__c));

        Animal__c dog = [
            SELECT Id, Animal_Name_Id__c, Gender__c, Breed__c, Current_Location__c, Shelter_Color_Coding__c, Shelter_Location__c,Helper_Dogs__c,
            (SELECT Id, Preferred_Motivators__c FROM Treatment_Plan__r),
            (SELECT Id FROM Play_Pauses__r WHERE (End_Date__c = null OR End_Date__c >= TODAY) LIMIT 1)
            FROM Animal__c 
            WHERE Id =: tp.Animal__c
        ];

        test.startTest();
            MRCTreatmentPlansReportLWCController.AnimalInfo[] infos = MRCTreatmentPlansReportLWCController.getAnimalInfos(new Animal__c[]{dog});
        test.stopTest();

        System.assert(!infos.isEmpty(), 'Should have returned an animalInfo, but was empty');
        MRCTreatmentPlansReportLWCController.AnimalInfo info = infos[0];
        System.assertEquals('test; toys', info.motivators);
        System.assertEquals(true, info.isPlayPause);
        System.assert(!info.categoryToProtocolMap.isEmpty(), 'Should have returned a map of protocols, but was empty');
    }

    @isTest
    static void getAnimalInfos_NoAnimal(){
        test.startTest();
            MRCTreatmentPlansReportLWCController.AnimalInfo[] infos = MRCTreatmentPlansReportLWCController.getAnimalInfos(new Animal__c[0]);
        test.stopTest();

        System.assert(infos.isEmpty(), 'Should have returned an empty infos, but was: ' + infos);
    }

    @isTest
    static void getMRCDogs_Success(){
        String[] dogNames = new String[]{'fido','willow','mika'};
        for(String name : dogNames){
            Animal__c dog = TestDataFactory.createAnimalWithName(name);
        }

        test.startTest();
            Animal__c[] dogs = MRCTreatmentPlansReportLWCController.getMRCDogs();
        test.stopTest();

        System.assert(!dogs.isEmpty(), 'Should have returned a list of dogs, but was empty');
        System.assertEquals(3, dogs.size());
    }

    @isTest
    static void getMRCDogs_NoMRCDog(){
        String[] dogNames = new String[]{'fido','willow','mika'};
        Animal__c[] dogs = new Animal__c[0];
        for(String name : dogNames){
            Animal__c dog = TestDataFactory.createAnimalWithName(name);
            dog.Current_Location__c = 'ARC';
            dogs.add(dog);
        }

        update dogs;

        test.startTest();
            Animal__c[] mrcDogs = MRCTreatmentPlansReportLWCController.getMRCDogs();
        test.stopTest();

        System.assert(mrcDogs.isEmpty(), 'Should have returned an empty list of dogs, but was: ' + mrcDogs);
    }

    @isTest
    static void getMRCDogsForPDF_Success(){
        Treatment_Plan__c tp = TestDataFactory.createPlan();

        test.startTest();
        MRCTreatmentPlansReportLWCController.AnimalInfo[] infos = MRCTreatmentPlansReportLWCController.getMRCDogsForPDF();
        test.stopTest();

        System.assert(!infos.isEmpty(), 'Should have returned a list of infos, but was empty');
    }

    @isTest
    static void getMRCDogsForPDF_NoMRCDog(){
        Treatment_Plan__c tp = TestDataFactory.createPlan();

        Animal__c dog = new Animal__c(
            Id = tp.Animal__c,
            Current_Location__c = 'ARC'
        );

        update dog;

        test.startTest();
        MRCTreatmentPlansReportLWCController.AnimalInfo[] infos = MRCTreatmentPlansReportLWCController.getMRCDogsForPDF();
        test.stopTest();

        System.assert(infos.isEmpty(), 'Should have returned an empty list of infos, but was: ' + infos);
    }

    @isTest 
    static void getTipOfMonth_Success(){
        Generic_Data__c gd = new Generic_Data__c(
            Species__c = 'Dog',
            Location__c = 'MRC',
            Name = 'MRC TOM',
            Text__c = 'tip of month'
        );
        insert gd;

        test.startTest();
        Generic_Data__c returnedGd = MRCTreatmentPlansReportLWCController.getTipOfMonth();
        test.stopTest();

        System.assert(returnedGd != null, 'Should have returned a generic data for tip of month, but was null');
        System.assertEquals(gd.Id, returnedGd.Id);
    }

    @isTest 
    static void getTipOfMonth_NoGenericData(){
        test.startTest();
        Generic_Data__c returnedGd = MRCTreatmentPlansReportLWCController.getTipOfMonth();
        test.stopTest();

        System.assert(returnedGd == null, 'Should have returned a null value, but was: ' + returnedGd);
    }

    @isTest 
    static void instantiate_MRCTreatmentPlansReportLWCController(){
        Treatment_Plan__c tp = TestDataFactory.createPlan();        
        
        test.startTest();
            MRCTreatmentPlansReportLWCController cont = new MRCTreatmentPlansReportLWCController();
            MRCTreatmentPlansReportLWCController.AnimalInfo[] infos = MRCTreatmentPlansReportLWCController.getMRCDogsForPDF();
            cont.infoWrapper = infos;
        test.stopTest();

        System.assertEquals(false, infos.isEmpty());
    }
}