force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Enrichment__c/Daily_Enrichment__c.object-meta.xml
<CustomObject>
    <label>Daily Enrichment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Daily Enrichment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Enrichment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Enrichment__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Daily Enrichment</relationshipLabel>
    <relationshipName>Daily_Enrichment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Enrichment__c/fields/Enrichment_Activities__c.field-meta.xml
<CustomField>
    <fullName>Enrichment_Activities__c</fullName>
    <label>Enrichment Activities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Enrichment_Activities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Enrichment__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Treatment Plan</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Daily Enrichment</relationshipLabel>
    <relationshipName>Enrichments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/AssignedTreatmentBundleId__c.field-meta.xml
<CustomField>
    <fullName>AssignedTreatmentBundleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Treatment Bundle</label>
    <referenceTo>Treatment_Bundle__c</referenceTo>
    <relationshipLabel>Treatment Plans (Assigned Treatment Bundle)</relationshipLabel>
    <relationshipName>Assigned_Treatment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Enrichment_Activities__c.field-meta.xml
<CustomField>
    <fullName>Enrichment_Activities__c</fullName>
    <label>Enrichment Activities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Enrichment_Activities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Shelter_Color_Code__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Color_Code__c</fullName>
    <label>Shelter Color Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Enrichment_Activities.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 on 1</fullName>
    </customValue>
    <customValue>
        <fullName>Backyard</fullName>
    </customValue>
    <customValue>
        <fullName>Ball/rock pit (foraging)</fullName>
    </customValue>
    <customValue>
        <fullName>Basic Training</fullName>
    </customValue>
    <customValue>
        <fullName>Dig pit</fullName>
    </customValue>
    <customValue>
        <fullName>Fetch with rules</fullName>
    </customValue>
    <customValue>
        <fullName>Foster overnights</fullName>
    </customValue>
    <customValue>
        <fullName>Four on the Floor for Leash</fullName>
    </customValue>
    <customValue>
        <fullName>Gym</fullName>
    </customValue>
    <customValue>
        <fullName>IPY</fullName>
    </customValue>
    <customValue>
        <fullName>Kennel Presence</fullName>
    </customValue>
    <customValue>
        <fullName>LLW</fullName>
    </customValue>
    <customValue>
        <fullName>Nose Work</fullName>
    </customValue>
    <customValue>
        <fullName>Outside ExPen</fullName>
    </customValue>
    <customValue>
        <fullName>Office Time</fullName>
    </customValue>
    <customValue>
        <fullName>Offsite Trips</fullName>
    </customValue>
    <customValue>
        <fullName>OPY</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Outside Walks</fullName>
    </customValue>
    <customValue>
        <fullName>PC Tug</fullName>
    </customValue>
    <customValue>
        <fullName>Puppy Enrichment/Socialization</fullName>
    </customValue>
    <customValue>
        <fullName>Puppy Handling</fullName>
    </customValue>
    <customValue>
        <fullName>Quiet Time</fullName>
    </customValue>
    <customValue>
        <fullName>Real-Life Room</fullName>
    </customValue>
    <customValue>
        <fullName>Shelter Notes</fullName>
    </customValue>
    <customValue>
        <fullName>Snuffle mat</fullName>
    </customValue>
    <customValue>
        <fullName>Trick Training</fullName>
    </customValue>
    <customValue>
        <fullName>Tug pully</fullName>
    </customValue>
    <customValue>
        <fullName>Tug with rules</fullName>
    </customValue>
    <customValue>
        <fullName>Walk</fullName>
    </customValue>
    <masterLabel>Enrichment Activities</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/controller/EnrichmentQuickCreateController.cls
public with sharing class EnrichmentQuickCreateController {
    @AuraEnabled
    public static Treatment_Plan__c getTreatmentPlan(Id animalId) {
        List<Treatment_Plan__c> treatmentPlan = [SELECT Id, AssignedTreatmentBundleId__c, Enrichment_Activities__c, Shelter_Color_Code__c FROM Treatment_Plan__c WHERE Animal__c = :animalId AND IsActive__c = true LIMIT 1];
        if (treatmentPlan.size() > 0) {
            return treatmentPlan[0];
        }
        else {
            return null;
        }
    }
    
    @AuraEnabled
    public static Daily_Enrichment__c createQuickEnrichment(Daily_Enrichment__c enrichment) {
        try {
            insert enrichment;
            return enrichment;
        }
        catch (DMLException ex) {
            System.debug('Error creating record: ' + ex.getMessage());
            return null;
        }
    }
}