force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/recordTypes/Behavior.recordType-meta.xml
<RecordType>
    <fullName>Behavior</fullName>
    <active>true</active>
    <label>Behavior</label>
</RecordType>

force-app/main/default/objects/Behavior_Evaluation__c/Behavior_Evaluation__c.object-meta.xml
<CustomObject>
    <label>Behavior Evaluation</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Behavior Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Behavior Evaluations</relationshipLabel>
    <relationshipName>Behavior_Evaluations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Behavior_in_Kennel__c.field-meta.xml
<CustomField>
    <fullName>Behavior_in_Kennel__c</fullName>
    <label>Behavior in Kennel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Not social</fullName>
            </value>
            <value>
                <fullName>Mildly fearful</fullName>
            </value>
            <value>
                <fullName>Excited</fullName>
            </value>
            <value>
                <fullName>Stereotypic behavior</fullName>
            </value>
            <value>
                <fullName>Hyperaroused</fullName>
            </value>
            <value>
                <fullName>Aggressive in cage only</fullName>
            </value>
            <value>
                <fullName>Extremely fearful</fullName>
            </value>
            <value>
                <fullName>Threatened</fullName>
            </value>
            <value>
                <fullName>Aggressive</fullName>
            </value>
            <value>
                <fullName>Moderately Fearful</fullName>
            </value>
            <value>
                <fullName>Did not approach the tester-Moderately fearful</fullName>
                <isActive>false</isActive>
                <label>Did not approach the tester-Moderately fearful</label>
            </value>
            <value>
                <fullName>Threatens</fullName>
                <isActive>false</isActive>
                <label>Threatens</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Picklist_Description_Config__mdt/Picklist_Description_Config__mdt.object-meta.xml
<CustomObject>
    <label>Picklist Description Config</label>
    <pluralLabel>Picklist Description Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Picklist_Description_Config__mdt/fields/Field_Description__c.field-meta.xml
<CustomField>
    <fullName>Field_Description__c</fullName>
    <description>Descriptive text for Field</description>
    <label>Field Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Description_Config__mdt/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <label>Field Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Description_Config__mdt/fields/Value_Category__c.field-meta.xml
<CustomField>
    <fullName>Value_Category__c</fullName>
    <description>Category of Picklist Value. 1= Not Concerning, 2 = Red Flag, 3 = Alert, 4 = Skipped/Inconclusive</description>
    <inlineHelpText>1= Not Concerning, 2 = Red Flag, 3 = Alert, 4 = Skipped/Inconclusive</inlineHelpText>
    <label>Value Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/controller/BehaviorEvalPDFController.cls
/**
 * Created by barne on 6/7/2021.
 */

public with sharing class BehaviorEvalPDFController {
    public Behavior_Evaluation__c behaviorEvaluation;
    public Animal__c animal;
    public BehaviorEvalPDFController()
    {
        dao_Animal daoAnimal = new dao_Animal();
        dao_BehaviorEvaluations daoBehaviorEvaluations = new dao_BehaviorEvaluations();
        //PageReference page = new PageReference('/apex/KennelSignage');
        PageReference page = ApexPages.currentPage();
        System.debug('######Current Page   =' + page);

        behaviorEvaluation = daoBehaviorEvaluations.findOne(page.getParameters().get('id'));
        System.debug('### Value of current animal  ' + behaviorEvaluation);

        animal = daoAnimal.findOne(String.valueOf(behaviorEvaluation.Animal__c));
        getBik_NotConcOptions();
    }

    /*******************************************************************************************************************/
    /************************* Behavior In Kennel Properties    *******************************************************/
    /*******************************************************************************************************************/

    //REFACTOR - MAKE PRIVATE METHOD
    public class PDFSelection {
        public String label { get; set; }
        public String longDesc { get; set; }
        public Boolean isSelected { get; set; }

        public PDFSelection(String label, String longDesc, Boolean isSelected) {
            this.label = label;
            this.longDesc = longDesc;
            this.isSelected = isSelected;
        }
        public PDFSelection () { }
    }
    public List<PDFSelection> bik_NotConcOptions { get; set; }
    public List<PDFSelection> bik_RedFlagOptions { get; set; }
    public  List<PDFSelection> bik_AlertOptions { get; set; }
    public  List<PDFSelection> getBik_NotConcOptions() {
        DescribeFieldResult fieldResult = Behavior_Evaluation__c.Behavior_in_Kennel__c.getDescribe();
        ControllerHelper.Properties prop = ControllerHelper.getFieldProperties(Behavior_Evaluation__c.Behavior_in_Kennel__c);
        List<Picklist_Description_Config__mdt>sConfigs = MetadataUtil.getFieldValues(prop.id);
        List<String> entries = String.isEmpty(behaviorEvaluation.Behavior_in_Kennel__c) ? null : behaviorEvaluation.Behavior_in_Kennel__c.split(';');
        List<PDFSelection> selections = new List<PDFSelection>();
        for (Picklist_Description_Config__mdt config : sConfigs) {
            PDFSelection options = new PDFSelection();
            options.label = config.Field_Value__c;
            options.longDesc = config.Field_Description__c;
            System.debug('$$$$ NOT BIK OPTIIONS ===> ' + config);
            if (config.Value_Category__c.equals('1')) {
                bik_NotConcOptions.add(options);
            }
            if (!entries.isEmpty()) {
                if (entries.contains(config.Field_Value__c)) {
                    options.isSelected = true;
                } else {
                    options.isSelected = false;
                }
            }
            selections.add(options);


    }
        return selections;
    }
    public  List<PDFSelection> getBik_RedFlagOptions() {
        DescribeFieldResult fieldResult = Behavior_Evaluation__c.Behavior_in_Kennel__c.getDescribe();
        ControllerHelper.Properties prop = ControllerHelper.getFieldProperties(Behavior_Evaluation__c.Behavior_in_Kennel__c);
        List<Picklist_Description_Config__mdt>sConfigs = MetadataUtil.getFieldValues(prop.id);
        List<String> entries = String.isEmpty(behaviorEvaluation.Behavior_in_Kennel__c) ? null : behaviorEvaluation.Behavior_in_Kennel__c.split(';');
        List<PDFSelection> selections = new List<PDFSelection>();
        for (Picklist_Description_Config__mdt config : sConfigs) {
            PDFSelection options = new PDFSelection();
            options.label = config.Field_Value__c;
            options.longDesc = config.Field_Description__c;
            System.debug('$$$$ NOT BIK OPTIIONS ===> ' + config);
            if (config.Value_Category__c.equals('2')) {
                bik_NotConcOptions.add(options);
            }
            if (!entries.isEmpty()) {
                if (entries.contains(config.Field_Value__c)) {
                    options.isSelected = true;
                } else {
                    options.isSelected = false;
                }
            }
            selections.add(options);


        }
        return selections;
    }
    public  List<PDFSelection> getBik_AlertOptions() {
        DescribeFieldResult fieldResult = Behavior_Evaluation__c.Behavior_in_Kennel__c.getDescribe();
        ControllerHelper.Properties prop = ControllerHelper.getFieldProperties(Behavior_Evaluation__c.Behavior_in_Kennel__c);
        List<Picklist_Description_Config__mdt>sConfigs = MetadataUtil.getFieldValues(prop.id);
        List<String> entries = String.isEmpty(behaviorEvaluation.Behavior_in_Kennel__c) ? null : behaviorEvaluation.Behavior_in_Kennel__c.split(';');
        List<PDFSelection> selections = new List<PDFSelection>();
        for (Picklist_Description_Config__mdt config : sConfigs) {
            PDFSelection options = new PDFSelection();
            options.label = config.Field_Value__c;
            options.longDesc = config.Field_Description__c;
            System.debug('$$$$ NOT BIK OPTIIONS ===> ' + config);
            if (config.Value_Category__c.equals('3')) {
                bik_NotConcOptions.add(options);
            }
            if (!entries.isEmpty()) {
                if (entries.contains(config.Field_Value__c)) {
                    options.isSelected = true;
                } else {
                    options.isSelected = false;
                }
            }
            selections.add(options);


        }
        return selections;
    }
    public PageReference showBikNc() {
        for (PDFSelection selection : bik_NotConcOptions) {
            System.debug(selection.label + '=====>' + selection.longDesc );
        }
        return null;
    }
    public PageReference showBikRf() {
        for (PDFSelection selection : bik_RedFlagOptions) {
            System.debug(selection.label + '=====>' + selection.longDesc );
        }
        return null;
    }
    public PageReference showBikAo() {
        for (PDFSelection selection : bik_AlertOptions) {
            System.debug(selection.label + '=====>' + selection.longDesc );
        }
        return null;
    }



}