force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name__c</fullName>
    <externalId>true</externalId>
    <label>ASPCA Animal Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Does_Not_Walk_on_a_Leash__c.field-meta.xml
<CustomField>
    <fullName>Does_Not_Walk_on_a_Leash__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Does Not Walk on a Leash</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <label>Handler</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red (designated)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Number_of_Playgroups__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Playgroups__c</fullName>
    <description>This information is populated using the Roll-up Helper tool.</description>
    <label># of Playgroups (last seven days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Play_Category__c.field-meta.xml
<CustomField>
    <fullName>Play_Category__c</fullName>
    <label>Play Category</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Play_Pause__c.field-meta.xml
<CustomField>
    <fullName>Play_Pause__c</fullName>
    <label>Play-Pause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Playgroup_Priority_Level__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Priority_Level__c</fullName>
    <label>Playgroup Priority Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily – 7 days</fullName>
            </value>
            <value>
                <fullName>High – 4 days</fullName>
            </value>
            <value>
                <fullName>Low – 2 days</fullName>
            </value>
            <value>
                <fullName>No Priority</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Shelter_Location2__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Location2__c</fullName>
    <label>Shelter Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ohio Shelter - 3900 Groves Rd</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
            <value>
                <fullName>ARC and CARE</fullName>
                <isActive>false</isActive>
                <label>ARC and CARE</label>
            </value>
            <value>
                <fullName>BRC</fullName>
                <isActive>false</isActive>
                <label>BRC</label>
            </value>
            <value>
                <fullName>Foster</fullName>
                <isActive>false</isActive>
                <label>Foster</label>
            </value>
            <value>
                <fullName>MRC</fullName>
                <isActive>false</isActive>
                <label>MRC</label>
            </value>
            <value>
                <fullName>MRC - CRC</fullName>
                <isActive>false</isActive>
                <label>MRC - CRC</label>
            </value>
            <value>
                <fullName>Marysville</fullName>
                <isActive>false</isActive>
                <label>Marysville</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Shelter_Location__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Location__c</fullName>
    <label>Kennel Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/Animal_Playgroup__c.object-meta.xml
<CustomObject>
    <label>Animal Playgroup</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Animal Playgroup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Playgroups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Playgroup__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Playgroup_Session__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Session</label>
    <referenceTo>Playgroup_Session__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Play_Pause__c/Play_Pause__c.object-meta.xml
<CustomObject>
    <label>Play Pause</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Play Pause #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Play Pauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Play_Pause__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>animalshelters__Animal__c</referenceTo>
    <relationshipLabel>Play Pauses</relationshipLabel>
    <relationshipName>Play_Pauses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/Playgroup_Session__c.object-meta.xml
<CustomObject>
    <label>Playgroup Session</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroup Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup_Session__c/fields/Animal_Playgroup__c.field-meta.xml
<CustomField>
    <fullName>Animal_Playgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Playgroup</label>
    <referenceTo>Animal_Playgroup__c</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/fields/Playgroup_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Date_Time__c</fullName>
    <defaultValue>NOW ()</defaultValue>
    <label>Playgroup Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/controller/PlaygroupToDoListController.cls
public with sharing class PlaygroupToDoListController {
    @AuraEnabled(cacheable=true)
    public static List<Animal__c> getPlaygroupAnimals(String location) {
        List<Animal__c> animals = [SELECT Id, Name, Animal_Name__c, Gender__c, Shelter_Location__c, Shelter_Location2__c, Playgroup_Priority_Level__c,
                                        Play_Category__c, Handler__c, Number_of_Playgroups__c, Play_Pause__c, Does_Not_Walk_on_a_Leash__c,
                                        (SELECT Id FROM Animal_Playgroups__r
                                        WHERE Playgroup_Session__r.Playgroup_Date_Time__c >= TODAY
                                            AND Playgroup_Session__r.Playgroup_Date_Time__c < TOMORROW LIMIT 1)
                                    FROM Animal__c
                                    WHERE Play_Category__c NOT IN ('Unevaluated', 'DO NOT PLAY') AND Shelter_Location2__c =: location];
        return animals;
    }

    @AuraEnabled
    public static String createPlaygroup(List<String> animals) {
        String sessionResult = '';
        Playgroup_Session__c session = new Playgroup_Session__c();
        Database.SaveResult sessionSR = Database.insert(session);
        if (sessionSR.isSuccess()) {
            sessionResult = sessionSR.getId();
            List<Animal_Playgroup__c> animalPlaygroups = new List<Animal_Playgroup__c>();
            for(String a : animals) {
                Animal_Playgroup__c animalPG = new Animal_Playgroup__c(
                    Animal__c = a,
                    Playgroup_Session__c = sessionResult
                );
                animalPlaygroups.add(animalPG);
            }
            List<Database.SaveResult> animalSR = Database.insert(animalPlaygroups);
            for(Database.SaveResult s : animalSR) {
                if (!s.isSuccess()) {
                    sessionResult = 'Error creating animal playgroups';
                    break;
                }
            }
        }
        else {
            sessionResult = 'Error creating playgroup session';
        }
        return sessionResult;
    }
}