force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Grade_Change_Reason__c.field-meta.xml
<CustomField>
    <fullName>Grade_Change_Reason__c</fullName>
    <description>This is required field when Current Behavior Grade field is changed on the animal record.</description>
    <label>Grade Change Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Handling_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Handling_Instructions__c</fullName>
    <label>Handling Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/Behavior_Evaluation__c.object-meta.xml
<CustomObject>
    <label>Behavior Evaluation</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Behavior Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Behavior Evaluations</relationshipLabel>
    <relationshipName>Behavior_Evaluations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Grade_Change_Reason__c.field-meta.xml
<CustomField>
    <fullName>Grade_Change_Reason__c</fullName>
    <description>This is required field when Overall Evaluation Grade field is modified on the behavior eval.</description>
    <label>Grade Change Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Overall_Evaluation_Grade__c.field-meta.xml
<CustomField>
    <fullName>Overall_Evaluation_Grade__c</fullName>
    <label>Overall Evaluation Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A - No Concerns</fullName>
            </value>
            <value>
                <fullName>B - Mild Concern(s)</fullName>
            </value>
            <value>
                <fullName>C - Moderate Concern(s)</fullName>
            </value>
            <value>
                <fullName>D - Severe Concern(s)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EntityHistory__c/EntityHistory__c.object-meta.xml
<CustomObject>
    <label>Entity History</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Entity History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entity Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EntityHistory__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Entity Histories</relationshipLabel>
    <relationshipName>Entity_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/test/LogHistoryTest.cls
@isTest 
private class LogHistoryTest {
    @isTest
    static void  getAnimalHistory() {
        Animal__c anim = TestDataFactory.createAnimal();

        test.startTest();
        anim.handling_instructions__c = 'update instructions';
        update anim;

        EntityHistory__c[] hisotryList = LogHistory.getAnimalHistory(
            anim.Id, 
            'Name', 
            '', 
            'Name', 
            'DESC'
        );

        test.stopTest();

        System.assertEquals(true, hisotryList.isEmpty());
    }

    @isTest
    static void  getBehaviorEvaluationHistory() {
        Behavior_Evaluation__c eval = TestDataFactory.createPuppyBehaviorEvaluation();


        test.startTest();
        eval.overall_evaluation_grade__c = 'A - No Concerns';
        eval.grade_change_reason__c = 'TO';
        update eval;

        EntityHistory__c[] hisotryList = LogHistory.getBehaviorEvaluationHistory(
            eval.Id, 
            'overall_evaluation_grade__c', 
            '', 
            'Name', 
            'DESC'
        );

        test.stopTest();

        System.assertEquals(true, hisotryList.isEmpty());
    }
}