force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name__c</fullName>
    <externalId>true</externalId>
    <label>ASPCA Animal Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Owner__c.field-meta.xml
<CustomField>
    <fullName>Animal_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Animal Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Behavior_Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Behavior Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Behavior Case Worker)</relationshipLabel>
    <relationshipName>Beh_Case_Worker_Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>For EQUINE, see Help Text</description>
    <inlineHelpText>For EQUINE, choose one of the following: Horse, Donkey, Mule, Draft Horse, Mini Horse, Pony, Mini Mule, Mini Donkey</inlineHelpText>
    <label>Breed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/dao/dao_Animal.cls
/**
 * Class description
 *
 * @author Lamar Barnett
 * @version 1.0.0
 */

public with sharing class dao_Animal extends sql_Dao{
    public dao_Animal() {
        setSObject(Animal__c.SObjectType);

        addField(Animal__c.Id);
        addField(Animal__c.Name);
        addField(Animal__c.Breed__c);
        addField(Animal__c.Behavior_Case_Worker__c);//returns CaseWorker Id = sObjectType = Contact
        addField(Animal__c.Animal_Name__c);
        addField(Animal__c.Animal_Owner__c);//Returns OwnerId - sObjectType = User
    }

    public List<Animal__c> findAll() {
        return (List<Animal__c>)getAll();
    }

}