force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Behavior_Evaluation__c/Behavior_Evaluation__c.object-meta.xml
<CustomObject>
    <label>Behavior Evaluation</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Behavior Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Behavior Evaluations</relationshipLabel>
    <relationshipName>Behavior_Evaluations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/test_BehaviorEvaluationsSelector.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

@IsTest
private class test_BehaviorEvaluationsSelector {
    @IsTest
    static void testGetAll() {

        Test.startTest();
        List<Behavior_Evaluation__c> evaluations = new BehaviorEvaluationsSelector().GetAll();
        Test.stopTest();

        System.assertEquals(true, evaluations.isEmpty());
    }

    @IsTest
    static void testGetById() {
        Behavior_Evaluation__c eval = TestDataFactory.createPuppyBehaviorEvaluation();
        Animal__c dog = [SELECT Id FROM Animal__c LIMIT 1];
        
        Test.startTest();
        List<Behavior_Evaluation__c> evaluations = new BehaviorEvaluationsSelector().GetById(new Set<Id>{eval.Id});
        Test.stopTest();

        System.assertEquals(false, evaluations.isEmpty());
    }

    @IsTest
    static void testGetSome() {
        Behavior_Evaluation__c eval = TestDataFactory.createPuppyBehaviorEvaluation();
        Animal__c dog = [SELECT Id FROM Animal__c LIMIT 1];
        
        Test.startTest();
        List<Behavior_Evaluation__c> evaluations = new BehaviorEvaluationsSelector().GetSome(1);
        Test.stopTest();

        System.assertEquals(false, evaluations.isEmpty());
    }
}