force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Active_Animal__c.field-meta.xml
<CustomField>
    <fullName>Active_Animal__c</fullName>
    <formula>IF(AND(ISBLANK(Final_Outcome__c),Current_Location__c  &lt;&gt; &quot;NYPD Freezer&quot;,Current_Location__c &lt;&gt; &quot;NYPD Refrigerator&quot;),True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active Animal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Animal_Name_Id__c.field-meta.xml
<CustomField>
    <fullName>Animal_Name_Id__c</fullName>
    <formula>Animal_Name__c + &apos; (&apos; +  Name + &apos;)&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animal Name/Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <label>Current Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Location_Filter__c.field-meta.xml
<CustomField>
    <fullName>Location_Filter__c</fullName>
    <formula>IF(User_Location__c = &quot;All&quot;, True, IF(ISBLANK(Current_Recent_Shelter_Location__c), False, IF(CONTAINS(User_Location__c, Current_Recent_Shelter_Location__c), True, False)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location Filter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Shelter_Location__c.field-meta.xml
<CustomField>
    <fullName>Shelter_Location__c</fullName>
    <label>Kennel Location</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Treatment_Plan__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/Plan_Protocol__c.object-meta.xml
<CustomObject>
    <label>Plan Protocol</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Plan Protocol Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Protocol__c/fields/Protocol_Description__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Description__c</fullName>
    <label>Protocol Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/fields/Protocol_Name__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Name__c</fullName>
    <formula>Protocol__r.Name</formula>
    <label>Protocol Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Plan Protocols</relationshipLabel>
    <relationshipName>Plan_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Treatment_Priority__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Priority__c</fullName>
    <label>Treatment Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Treatment</fullName>
                <default>true</default>
                <label>No Treatment</label>
            </value>
            <value>
                <fullName>Daily – 7 days</fullName>
            </value>
            <value>
                <fullName>High – 5 days</fullName>
            </value>
            <value>
                <fullName>Medium – 4 days</fullName>
            </value>
            <value>
                <fullName>Low – 3 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HomePageController.cls
public with sharing class HomePageController {
	@AuraEnabled(cacheable=true)
    public static List<animalTaskRec> getAnmialTasks(Integer limitSize, Integer offset){
        List<Task> tasks = [SELECT Id,Record_Type__c, Animal__c,Animal__r.Animal_Name_Id__c, animal__r.Current_Location__c,subject   
                from Task where Animal__C != null AND Animal__r.Active_Animal__c  = true AND Animal__r.Location_Filter__c = true
                           and CreatedDate = today 
                      LIMIT :limitSize  OFFSET :offset  ];
        //LIMIT :limitSize  OFFSET :offset     and CreatedDate = today
        List<animalTaskRec> aTaskRecds = new List<animalTaskRec>();
        for(Task tsk : tasks){
            animalTaskRec atr = new animalTaskRec();
            atr.TaskId = tsk.Id;
            atr.recordType = tsk.Record_Type__c;
            atr.subject = tsk.subject;
            atr.Name= tsk.Animal__r.Animal_Name_Id__c;
            atr.location = tsk.animal__r.Current_Location__c;
            atr.taskUrl = '/lightning/r/Task/' + tsk.Id + '/view';
            aTaskRecds.add(atr);
        }
        return aTaskRecds;
    }

    
    @AuraEnabled(cacheable=true)
    public static List<animalTreatmentRec> getAnmialTreatement(){
        List<Treatment_Plan__c> treatmentPlans = [Select Id, Animal__r.Name, Animal__r.Animal_Name_Id__c, Animal__r.Shelter_Location__c,Treatment_Priority__c,(Select Id,Name, Protocol_Name__c,Protocol_Description__c from Plan_Protocols__r)  FROM Treatment_Plan__c
                WHERE IsActive__c = true AND Treatment_Priority__c != 'No Treatment' AND Animal__c != null];
       	List<animalTreatmentRec> aRecds = new List<animalTreatmentRec>();
        for(Treatment_Plan__c tp: treatmentPlans){
            animalTreatmentRec ar = new animalTreatmentRec();
            ar.TreatmentId = tp.Id;
            ar.Name = tp.Animal__r.Animal_Name_Id__c;
            ar.location = tp.Animal__r.Shelter_Location__c;
            ar.treatmentPriority = tp.Treatment_Priority__c;
            List<planProtocol> ptcRecds = new List<planProtocol>();
            for(Plan_Protocol__c pp: tp.Plan_Protocols__r){
                planProtocol ptc = new planProtocol();
                ptc.PlanId = pp.Id;
                ptc.ProtocolName = pp.Name ;
                ptc.Protocol = pp.Protocol_Name__c;
                ptcRecds.add(ptc);
            }
            ar.children = ptcRecds;
            aRecds.add(ar);
        }
        return aRecds;
    }
    
    public class animalTaskRec{
        @AuraEnabled
        public Id TaskId {get;set;}
        @AuraEnabled
        public String recordType {get;set;}
        @AuraEnabled
        public String taskUrl {get;set;}
        @AuraEnabled
        public String Name {get;set;}
        @AuraEnabled
        public String location {get;set;}
        @AuraEnabled
        public String subject {get;set;}
    }
    
    public class animalTreatmentRec{

        @AuraEnabled
        public Id TreatmentId {get;set;}
        
        @AuraEnabled
        public String treatmentPriority {get;set;}
        
        @AuraEnabled
        public List<planProtocol> children {get;set;}
                
        @AuraEnabled
        public String Name {get;set;}
        @AuraEnabled
        public String location {get;set;}
    }
    
    public class planProtocol{
        @AuraEnabled
        public Id PlanId {get;set;}
        @AuraEnabled
        public String ProtocolName {get;set;}
        @AuraEnabled
        public String Protocol {get;set;}
        
    }
}