force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Evaluation_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Due_Date__c</fullName>
    <label>Evaluation Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/Facility_Outcome__c.object-meta.xml
<CustomObject>
    <label>Facility/Outcome</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>F/O #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facilities/Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility_Outcome__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipName>Animal_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Facility_or_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Facility_or_Outcome__c</fullName>
    <label>Facility or Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility</fullName>
            </value>
            <value>
                <fullName>Outcome</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Facility_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Facility_Outcome__c</fullName>
    <label>Facility/Outcome</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Facility_or_Outcome__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAH</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Adoption Center</fullName>
            </value>
            <value>
                <fullName>Adoption Center (Temp Boarding)</fullName>
            </value>
            <value>
                <fullName>Animal Hospital</fullName>
            </value>
            <value>
                <fullName>Animal Shelter</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>ASNA</fullName>
            </value>
            <value>
                <fullName>ASPCA Shelter</fullName>
            </value>
            <value>
                <fullName>Board and Train</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>BRC</fullName>
            </value>
            <value>
                <fullName>Bronx CVC</fullName>
            </value>
            <value>
                <fullName>Brooklyn CVC</fullName>
            </value>
            <value>
                <fullName>CARE</fullName>
            </value>
            <value>
                <fullName>Clinic</fullName>
            </value>
            <value>
                <fullName>Community Medicine</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
            <value>
                <fullName>CRC-MRC</fullName>
            </value>
            <value>
                <fullName>Cremation</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Euthanized</fullName>
            </value>
            <value>
                <fullName>Field Temp Shelter</fullName>
            </value>
            <value>
                <fullName>Foster-Based Rescue</fullName>
            </value>
            <value>
                <fullName>Foster Home</fullName>
            </value>
            <value>
                <fullName>Foster Home - Adoption Center</fullName>
            </value>
            <value>
                <fullName>Foster Home - ARC</fullName>
            </value>
            <value>
                <fullName>Foster Home - CARE</fullName>
            </value>
            <value>
                <fullName>Hound Hotel</fullName>
            </value>
            <value>
                <fullName>Kitten Nursery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Point_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Point_of_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Point of Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Facilities/Outcomes</relationshipLabel>
    <relationshipName>Facilities_Outcomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Evaluation.recordType-meta.xml
<RecordType>
    <fullName>Evaluation</fullName>
    <active>true</active>
    <label>Evaluation</label>
</RecordType>

force-app/main/default/test/test_FacilityOutcomeTrigger.cls
@isTest
public class test_FacilityOutcomeTrigger {
    @isTest
    static void sendInsertUpdateEmailTest() {
        Contact c = new Contact(FirstName = 'Second', LastName = 'Contact', Email = 'second@contact.com');
        insert c;
        Test.startTest();
        //First email invocation occurs here on the insert
        Facility_Outcome__c fosterFacility = TestDataFactory.createFacilityOutcome();
        //Second email invocation occurs here on the update from one contact to another
        fosterFacility.Point_of_Contact__c = c.Id;
        update fosterFacility;
        //No email occurs here
        fosterFacility.Point_of_Contact__c = null;
        update fosterFacility;
        //Third email invocation occurs here on the update from having no contact to having a contact
        fosterFacility.Point_of_Contact__c = c.Id;
        update fosterFacility;
        Integer emailInvocations = Limits.getEmailInvocations();
        Test.stopTest();
        
        //do not send emails if tests are running because it will fail if emails are turned off (typical in sandboxes) so, this should be 0
        System.assertEquals(0, emailInvocations);
    }

    @isTest
    static void sendNoEmailAddressTest() {
        Contact c = new Contact(FirstName = 'No', LastName = 'Email');
        insert c;
        Facility_Outcome__c fosterFacility = TestDataFactory.createFacilityOutcome();
        Test.startTest();
        fosterFacility.Point_of_Contact__c = c.Id;
        Integer emailInvocations = Limits.getEmailInvocations();
        Test.stopTest();
        System.assertEquals(0, emailInvocations);
    }

    @isTest 
    static void handleEvaluationProcessTest(){
        Animal__c dog = TestDataFactory.createAnimalWithName('Willow');
        Contact c = TestDataFactory.createContact();
        Facility_Outcome__c arcFO = new Facility_Outcome__c(
            Animal__c = dog.Id,
            Facility_or_Outcome__c = 'Facility',
            Facility_Outcome__c = 'ARC',
            Point_of_Contact__c = c.Id,
            Start_Date__c = System.today()
        );        

        Test.startTest();
        insert arcFO;
        Test.stopTest();

        dog = [SELECT Id, Evaluation_Due_Date__c FROM Animal__c WHERE Id = :dog.Id LIMIT 1];
        System.assertEquals(true, dog.Evaluation_Due_Date__c != null, 'Should have an evaluation due date, but was null');

        Task[] evalTasks = [SELECT Id FROM Task WHERE Animal__c = :dog.Id AND RecordTypeId = :Util.getRecordTypeId('Task',AutoScheduleTasksUtil.EVALUATION_RECORD_TYPE_NAME)];
        System.assertEquals(1, evalTasks.size(), 'Should have returned one evaluation task, instead was: ' + evalTasks);
    }
}