force-app/main/default/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/Session_Protocol__c.object-meta.xml
<CustomObject>
    <label>Session Protocol</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Session Protocol Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocols</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/fields/ProtocolId__c.field-meta.xml
<CustomField>
    <fullName>ProtocolId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/TreatmentSessionId__c.field-meta.xml
<CustomField>
    <fullName>TreatmentSessionId__c</fullName>
    <label>Treatment Session</label>
    <referenceTo>Treatment_Session__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/Treatment_Session__c.object-meta.xml
<CustomObject>
    <label>Treatment Session</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Treatment Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/test_SessionProtocolService.cls
@isTest
private class test_SessionProtocolService {
    @isTest 
    static void handleValidty_Test(){
        Session_Protocol__c[] sProtocols = TestDataFactory.createSessionProtocols();
        Session_Protocol__c[] sProtocolsWithNames = [SELECT Id, ProtocolId__r.Name FROM Session_Protocol__c WHERE Id =: sProtocols];
        ServiceRequest request = new ServiceRequest();
        request.withParams('treatmentSession', new Treatment_Session__c(Id = sProtocols[0].TreatmentSessionId__c));

        test.startTest();
            ServiceResponse response = SessionProtocolService.handleValidity(request);
        test.stopTest();

        System.debug('response: ' + response);
        Map<String,Map<String,String>> responseMap = (Map<String,Map<String,String>>)response.data;
        
        System.debug('sProtocol.Name: ' + sProtocolsWithNames[0].ProtocolId__r.Name);
        System.debug('response: ' + responseMap.keySet());
        System.debug('response: ' + responseMap.get(sProtocolsWithNames[0].ProtocolId__r.Name));

        for(String protocolName : responseMap.keySet()){
            Map<String, String> resultMap = responseMap.get(protocolName);
            for(String field : resultMap.keySet()){
                System.assertEquals('INVALID', resultMap.get(field));
                System.debug('response: ' + resultMap.get(field));

            }
        }
    }

    // @isTest 
    // static void handleSession_Test(){
    //     Session_Protocol__c[] sProtocols = TestDataFactory.createSessionProtocols();
    //     Session_Protocol__c[] sProtocolsWithNames = [SELECT Id, ProtocolId__r.Name FROM Session_Protocol__c WHERE Id =: sProtocols];
    //     ServiceRequest request = new ServiceRequest();
    //     request.withParams('treatmentSession', new Treatment_Session__c(Id = sProtocols[0].TreatmentSessionId__c));

    //     test.startTest();
    //         ServiceResponse response = SessionProtocolService.handleSession(request);
    //     test.stopTest();

    //     System.debug('response: ' + response);
    // }
}