force-app/main/default/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Protocol_Scale__c/Protocol_Scale__c.object-meta.xml
<CustomObject>
    <label>Protocol Scale</label>
    <nameField>
        <label>Protocol Scale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocol Scales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Protocol_Scale_Junction__c/Protocol_Scale_Junction__c.object-meta.xml
<CustomObject>
    <label>Protocol Scale Junction</label>
    <nameField>
        <displayFormat>PSJN-{00000}</displayFormat>
        <label>Protocol Scale Junction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Protocol Scale Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Protocol_Scale_Junction__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Protocol Scale Junctions</relationshipLabel>
    <relationshipName>Protocol_Scale_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Protocol_Scale_Junction__c/fields/Protocol_Scale__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Scale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol Scale</label>
    <referenceTo>Protocol_Scale__c</referenceTo>
    <relationshipLabel>Protocol Scale Junctions</relationshipLabel>
    <relationshipName>Protocol_Scale_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/test/Test_ProtocolDomain.cls
@isTest 
private class Test_ProtocolDomain {
    @isTest 
    static void Test_InsertProtocolsSuccess() {
        Integer pScaleCount = 3;
        Protocol_Scale__c[] pScales = TestDataFactory.createProtocolScales(pScaleCount);

        test.startTest();
        Protocol__c[] protocols = TestDataFactory.createProtocols();
        test.stopTest();

        Protocol_Scale_Junction__c[] scaleJunctions = [SELECT Id FROM Protocol_Scale_Junction__c];
        System.assertEquals(pScaleCount * protocols.size(), scaleJunctions.size());
    }

    @isTest 
    static void Test_InsertProtocolsNoScales(){
        test.startTest();
        Protocol__c[] protocols = TestDataFactory.createProtocols();
        test.stopTest();

        Protocol_Scale_Junction__c[] scaleJunctions = [SELECT Id FROM Protocol_Scale_Junction__c];
        System.assert(scaleJunctions.isEmpty(), 'No scale junctions should have been created, but query returned: ' + scaleJunctions);
    }
}