force-app/main/default/objects/Case/fields/Agency_Case_2__c.field-meta.xml
<CustomField>
    <fullName>Agency_Case_2__c</fullName>
    <label>Agency Case #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Agency_Case__c.field-meta.xml
<CustomField>
    <fullName>Agency_Case__c</fullName>
    <label>Agency Case #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Animal_Breed_from_TIP_details__c.field-meta.xml
<CustomField>
    <fullName>Animal_Breed_from_TIP_details__c</fullName>
    <label>Animal Breed (from Intel details)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ASPCA_Liaison__c.field-meta.xml
<CustomField>
    <fullName>ASPCA_Liaison__c</fullName>
    <label>ASPCA Liaison</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Borough__c.field-meta.xml
<CustomField>
    <fullName>Borough__c</fullName>
    <formula>IF(Precinct__c &lt; 40, &apos;Manhattan&apos;,
IF(Precinct__c &lt; 60, &apos;Bronx&apos;,
IF(Precinct__c &lt; 100, &apos;Brooklyn&apos;,
IF(Precinct__c &lt; 120, &apos;Queens&apos;,
IF(Precinct__c &lt;=123, &apos;Staten Island&apos;,&apos;&apos;)))))</formula>
    <label>Borough</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Call_Center__c.field-meta.xml
<CustomField>
    <fullName>Call_Center__c</fullName>
    <label>Call Center #</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Origin_2__c.field-meta.xml
<CustomField>
    <fullName>Case_Origin_2__c</fullName>
    <label>Case Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Case_Subtype__c</fullName>
    <label>Case Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Case_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Inadequate Nutrition</fullName>
            </value>
            <value>
                <fullName>Lack of Vet Care</fullName>
            </value>
            <value>
                <fullName>Environmental Conditions</fullName>
            </value>
            <value>
                <fullName>Pet Store</fullName>
            </value>
            <value>
                <fullName>Puppy Mill</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
            </value>
            <value>
                <fullName>Blunt Force Trauma</fullName>
            </value>
            <value>
                <fullName>Penetrating Trauma</fullName>
            </value>
            <value>
                <fullName>Burn Injuries</fullName>
            </value>
            <value>
                <fullName>Asphyxia</fullName>
            </value>
            <value>
                <fullName>Drowning</fullName>
            </value>
            <value>
                <fullName>Poisoning</fullName>
            </value>
            <value>
                <fullName>Sexual Abuse</fullName>
            </value>
            <value>
                <fullName>Cockfighting</fullName>
            </value>
            <value>
                <fullName>Dogfighting</fullName>
            </value>
            <value>
                <fullName>Dog and Chicken Fighting</fullName>
            </value>
            <value>
                <fullName>Ritual Abuse</fullName>
            </value>
            <value>
                <fullName>Breeder</fullName>
            </value>
            <value>
                <fullName>Farm</fullName>
            </value>
            <value>
                <fullName>Private Citizen</fullName>
            </value>
            <value>
                <fullName>Rescue/Sanctuary</fullName>
            </value>
            <value>
                <fullName>Shelter</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Earthquake</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Flooding</fullName>
            </value>
            <value>
                <fullName>Hurricane</fullName>
            </value>
            <value>
                <fullName>Tornado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investigations - Consultation</fullName>
            </value>
            <value>
                <fullName>Investigations - Complaint</fullName>
            </value>
            <value>
                <fullName>Investigations - Proactive</fullName>
            </value>
            <value>
                <fullName>Expert Services - Legal Review</fullName>
            </value>
            <value>
                <fullName>Expert Services - Subject Matter</fullName>
            </value>
            <value>
                <fullName>Expert Services - Forensic Science</fullName>
            </value>
            <value>
                <fullName>Sheltering Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Please check this box if this case is counted as a deployment.</inlineHelpText>
    <label>Deployment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Forensics_Case__c.field-meta.xml
<CustomField>
    <fullName>Forensics_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Forensics Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lead_Attorney__c.field-meta.xml
<CustomField>
    <fullName>Lead_Attorney__c</fullName>
    <label>Lead Attorney</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Donna Lassa</fullName>
            </value>
            <value>
                <fullName>Elizabeth Brandler</fullName>
            </value>
            <value>
                <fullName>Erin Satterthwaite</fullName>
            </value>
            <value>
                <fullName>Jennifer Chin</fullName>
            </value>
            <value>
                <fullName>Natasha Major</fullName>
            </value>
            <value>
                <fullName>Nathan Zilak</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Secondary_Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Case_Type__c</fullName>
    <label>Secondary Case Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Neglect</fullName>
            </value>
            <value>
                <fullName>Non-Accidental Injury</fullName>
            </value>
            <value>
                <fullName>Animal Fighting</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
            <value>
                <fullName>Abandonment</fullName>
            </value>
            <value>
                <fullName>Disaster</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/dao/dao_Case.cls
/**
 * Created by barne on 5/13/2021.
 */

public with sharing class dao_Case extends sql_Dao {
    public dao_Case() {
        setSObject(Case.SObjectType);

        addField(Case.Id);
        addField(Case.RecordTypeId);
        addField(Case.Agency_Name__c);
        addField(Case.Agency_Case__c);
        addField(Case.Agency_Case_2__c);
        addField(Case.AccountId);
        addField(Case.Borough__c);
        addField(Case.ASPCA_Liaison__c);
        addField(Case.Animal_Breed_from_TIP_details__c);
        addField(Case.Call_Center__c);
        addField(Case.Category__c);
        addField(Case.Case_Origin_2__c);
        addField(Case.Case_Subtype__c);
        addField(Case.Deployment__c);
        addField(Case.Forensics_Case__c);
        addField(Case.Lead_Attorney__c);
        addField(Case.Secondary_Case_Type__c);
    }


}