force-app/main/default/objects/Case/fields/Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Case_Subtype__c</fullName>
    <label>Case Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Case_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Inadequate Nutrition</fullName>
            </value>
            <value>
                <fullName>Lack of Vet Care</fullName>
            </value>
            <value>
                <fullName>Environmental Conditions</fullName>
            </value>
            <value>
                <fullName>Pet Store</fullName>
            </value>
            <value>
                <fullName>Puppy Mill</fullName>
            </value>
            <value>
                <fullName>Multiple</fullName>
            </value>
            <value>
                <fullName>Blunt Force Trauma</fullName>
            </value>
            <value>
                <fullName>Penetrating Trauma</fullName>
            </value>
            <value>
                <fullName>Burn Injuries</fullName>
            </value>
            <value>
                <fullName>Asphyxia</fullName>
            </value>
            <value>
                <fullName>Drowning</fullName>
            </value>
            <value>
                <fullName>Poisoning</fullName>
            </value>
            <value>
                <fullName>Sexual Abuse</fullName>
            </value>
            <value>
                <fullName>Cockfighting</fullName>
            </value>
            <value>
                <fullName>Dogfighting</fullName>
            </value>
            <value>
                <fullName>Dog and Chicken Fighting</fullName>
            </value>
            <value>
                <fullName>Ritual Abuse</fullName>
            </value>
            <value>
                <fullName>Breeder</fullName>
            </value>
            <value>
                <fullName>Farm</fullName>
            </value>
            <value>
                <fullName>Private Citizen</fullName>
            </value>
            <value>
                <fullName>Rescue/Sanctuary</fullName>
            </value>
            <value>
                <fullName>Shelter</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Earthquake</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Flooding</fullName>
            </value>
            <value>
                <fullName>Hurricane</fullName>
            </value>
            <value>
                <fullName>Tornado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Intelligence_Report__c.field-meta.xml
<CustomField>
    <fullName>Intelligence_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intelligence Report ID</label>
    <referenceTo>Tips_Intel__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Total_Animals__c.field-meta.xml
<CustomField>
    <fullName>Total_Animals__c</fullName>
    <formula>Total_Animals_Reported__c +  Total_Animals_Rescued__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Animals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Total_Animals_Reported__c.field-meta.xml
<CustomField>
    <fullName>Total_Animals_Reported__c</fullName>
    <label>Total Animals Reported</label>
    <summarizedField>Estimated_Animals_Reported__c.Reported_Quantity__c</summarizedField>
    <summaryForeignKey>Estimated_Animals_Reported__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Total_Animals_Rescued__c.field-meta.xml
<CustomField>
    <fullName>Total_Animals_Rescued__c</fullName>
    <formula>Total_Avians_Rescued__c +  Total_Cats_Logged__c +  Total_Cows_Rescued__c +  Total_Dogs_Logged__c +  Total_Equine_Logged__c +  Total_Exotic_Logged__c +  Total_Fowl_Logged__c +  Total_Goats_Rescued__c +  Total_Other_Animals_Logged__c +  Total_Pigs_Rescued__c +  Total_Rabbits_Rescued__c +  Total_Reptiles_Rescued__c +  Total_Sheep_Rescued__c +  Total_Wildlife_Rescued__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Animals Rescued</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Intelligence_Report__c.field-meta.xml
<CustomField>
    <fullName>Intelligence_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the intelligence report the contact record was created from</description>
    <label>Intelligence Report</label>
    <referenceTo>Tips_Intel__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/dao/dao_Cases.cls
/**
 * Class description
 * @author Lamar Barnett
 * @version 1.0.0
 */

public with sharing class dao_Cases extends sql_Dao {
    public dao_Cases() {
        setSObject(Case.SObjectType);

        addField(Case.Id);
        addField(Case.AccountId);
        addField(Case.ContactId);
        addField(Case.Agency_Name__c);
        addField(Case.Intelligence_Report__c);
        addField(Case.Case_Subtype__c);
        addField(Case.Total_Animals__c);
        addField(Case.Total_Animals_Reported__c);
        addField(Case.Total_Animals_Rescued__c);
        addField(Case.OwnerId);
        addField(Case.RecordTypeId);
        addField(Case.Type);
    }

    public List<Contact> findAll(){
        return (List<Contact>)getAll();
    }

    public List<Contact> findById(Set<Id> ids){
        return (List<Contact>) getWhere(sql_Criteria.ValueIn(Case.Id, ids));
    }
}