force-app/main/default/objects/Case/fields/CASE_STATUS_SUBTYPE__c.field-meta.xml
<CustomField>
    <fullName>CASE_STATUS_SUBTYPE__c</fullName>
    <label>Case Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Case Review</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Consultation</fullName>
            </value>
            <value>
                <fullName>Court Charges Filed</fullName>
            </value>
            <value>
                <fullName>Deployment</fullName>
            </value>
            <value>
                <fullName>Forensic Analysis</fullName>
            </value>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Placement</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Emergency Sheltering</fullName>
            </value>
            <value>
                <fullName>Supply Request</fullName>
            </value>
            <value>
                <fullName>Crime Scene Assistance</fullName>
            </value>
            <value>
                <fullName>Case Packaging</fullName>
            </value>
            <value>
                <fullName>Expert Testimony</fullName>
            </value>
            <value>
                <fullName>General Case Consultation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investigations - Consultation</fullName>
            </value>
            <value>
                <fullName>Investigations - Complaint</fullName>
            </value>
            <value>
                <fullName>Investigations - Proactive</fullName>
            </value>
            <value>
                <fullName>Expert Services - Legal Review</fullName>
            </value>
            <value>
                <fullName>Expert Services - Subject Matter</fullName>
            </value>
            <value>
                <fullName>Expert Services - Forensic Science</fullName>
            </value>
            <value>
                <fullName>Sheltering Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Investigator__c.field-meta.xml
<CustomField>
    <fullName>Investigator__c</fullName>
    <label>Case Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Kyle Held</fullName>
            </value>
            <value>
                <fullName>Terry Mills</fullName>
            </value>
            <value>
                <fullName>Leigh Anne Wilson</fullName>
            </value>
            <value>
                <fullName>Donna Lassa</fullName>
            </value>
            <value>
                <fullName>Teresa Ladner</fullName>
            </value>
            <value>
                <fullName>Nathan Zilak</fullName>
            </value>
            <value>
                <fullName>Rachel Touroo, DVM</fullName>
            </value>
            <value>
                <fullName>Alison Kennedy-Benson</fullName>
            </value>
            <value>
                <fullName>Amanda Fitch</fullName>
            </value>
            <value>
                <fullName>Elizabeth Pearlman, DVM</fullName>
            </value>
            <value>
                <fullName>Kristina Baucom, DVM</fullName>
            </value>
            <value>
                <fullName>Ashley Saver, DVM</fullName>
            </value>
            <value>
                <fullName>Tim Perciful</fullName>
            </value>
            <value>
                <fullName>Tim Rickey</fullName>
            </value>
            <value>
                <fullName>Susan Anderson</fullName>
            </value>
            <value>
                <fullName>Wanda Merling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseContactRoleExt_Test.cls
@istest
private class CaseContactRoleExt_Test
{
  static testMethod void ReportTest() {
     //Creating the case object  
      Case newCaseObj = new case(Category__C = 'Consultation',Status = 'New',CASE_STATUS_SUBTYPE__c = 'Placement', Investigator__c = 'Terry Mills',Origin = 'Phone');
      insert newCaseObj;
     
     //Creating Contact obj for Case Contact Role 
      Contact con = new Contact(FirstName = 'testName', LastName = 'lName',MailingCity = 'testCity', MailingState='testState');
      insert con;
      
     //Creating multiple Case Contact Role objects to cover Suspect and Complainant Role. 
      List<CaseContactRole> listCaseContactRole = new List<CaseContactRole>();
      CaseContactRole caseContactRoleObj1 = new CaseContactRole(CasesId = newCaseObj.Id, ContactId = con.Id, Role = 'Suspect/Defendant');
      listCaseContactRole.add(caseContactRoleObj1);
      CaseContactRole caseContactRoleObj2 = new CaseContactRole(CasesId = newCaseObj.Id, ContactId = con.Id, Role = 'Complainant');
      listCaseContactRole.add(caseContactRoleObj2);
      insert listCaseContactRole;
     
     //Instantiating the class 
      ApexPages.StandardController std = new ApexPages.StandardController(newCaseObj);
      ApexPages.currentPage().getParameters().put('Id', newCaseObj.id);
      CaseContactRoleExtension spObj = new CaseContactRoleExtension(std);
//      spObj.getrepeatDiv();
  }  
}