force-app/main/default/objects/Case/fields/Defendant__c.field-meta.xml
<CustomField>
    <fullName>Defendant__c</fullName>
    <label>Defendant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/Charge_Information__c.object-meta.xml
<CustomObject>
    <description>The information in this section pertains to the criminal charges relating to the subjects in this case</description>
    <label>Charge Information</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Charge ID #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charge Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge_Information__c/fields/Amount_of_Fine__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_Fine__c</fullName>
    <description>Amount that the court ordered the defendant to pay</description>
    <label>Amount of Fine (In Dollars)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Appeal__c.field-meta.xml
<CustomField>
    <fullName>Appeal__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if there is an appeal. Update the Criminal Court Timeline with any relevant appeal dates</inlineHelpText>
    <label>Appeal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Charge Information</relationshipLabel>
    <relationshipName>Charge_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Charge_Count__c.field-meta.xml
<CustomField>
    <fullName>Charge_Count__c</fullName>
    <description>This is the number of times subject was charged</description>
    <inlineHelpText>Enter the number of counts this defendant was charged with under the above statute #</inlineHelpText>
    <label>Number of Counts</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Charge_Title__c.field-meta.xml
<CustomField>
    <fullName>Charge_Title__c</fullName>
    <inlineHelpText>NYC: This field will auto-populate after statute # is filled in</inlineHelpText>
    <label>Charge Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Community_Service_Hours__c.field-meta.xml
<CustomField>
    <fullName>Community_Service_Hours__c</fullName>
    <label>Community Service Hours</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Counts_ACD_Given__c.field-meta.xml
<CustomField>
    <fullName>Counts_ACD_Given__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Counts ACD Given</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Counts_Acquitted__c.field-meta.xml
<CustomField>
    <fullName>Counts_Acquitted__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Counts Acquitted</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Counts_Convicted__c.field-meta.xml
<CustomField>
    <fullName>Counts_Convicted__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Counts Convicted</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Counts_Dismissed__c.field-meta.xml
<CustomField>
    <fullName>Counts_Dismissed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Counts Dismissed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Court_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Court_Disposition__c</fullName>
    <description>final outcome of court procedings for this charge</description>
    <inlineHelpText>Enter the final judgment for this charge</inlineHelpText>
    <label>Court Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abated</fullName>
            </value>
            <value>
                <fullName>ACD</fullName>
            </value>
            <value>
                <fullName>Acquitted</fullName>
            </value>
            <value>
                <fullName>Convicted After Trial</fullName>
            </value>
            <value>
                <fullName>Convicted - Alford Plea/No Contest</fullName>
            </value>
            <value>
                <fullName>Convicted - Pleaded to Lesser Charge (See Notes)</fullName>
            </value>
            <value>
                <fullName>Convicted - Pled Guilty</fullName>
            </value>
            <value>
                <fullName>Convicted - Trial</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Dismissed – 30.30 (other)</fullName>
            </value>
            <value>
                <fullName>Dismissed – 30.30 (witness uncooperative)</fullName>
            </value>
            <value>
                <fullName>Dismissed – Defendant Deceased</fullName>
            </value>
            <value>
                <fullName>Dismissed – Insufficient evidence</fullName>
            </value>
            <value>
                <fullName>Dismissed - Pled to Other Charge</fullName>
            </value>
            <value>
                <fullName>Dismissed - Prosecutor Discretion</fullName>
            </value>
            <value>
                <fullName>Dismissed – Witness uncooperative</fullName>
            </value>
            <value>
                <fullName>Diversion</fullName>
            </value>
            <value>
                <fullName>DP</fullName>
            </value>
            <value>
                <fullName>Found Unfit to Proceed</fullName>
            </value>
            <value>
                <fullName>Grand Jury- Indicted</fullName>
            </value>
            <value>
                <fullName>Grand Jury- No Bill</fullName>
            </value>
            <value>
                <fullName>Nolle prosequi</fullName>
            </value>
            <value>
                <fullName>PG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Courtdisposition_Date__c.field-meta.xml
<CustomField>
    <fullName>Courtdisposition_Date__c</fullName>
    <inlineHelpText>Enter the date of the final judgment for this charge</inlineHelpText>
    <label>Court Disposition Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Defendant__c.field-meta.xml
<CustomField>
    <fullName>Defendant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Person charged with violation of a federal, state or local crime.</description>
    <label>Defendant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Charge Information</relationshipLabel>
    <relationshipName>Charge_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Defendant_Case_s_Closed__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Case_s_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box when all counts related to this charge are disposed of</inlineHelpText>
    <label>Charge/s Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Length_of_Confinement__c.field-meta.xml
<CustomField>
    <fullName>Length_of_Confinement__c</fullName>
    <description>Please enter the length the court ordered for prison/jail- indicate if any/all is suspended</description>
    <label>Length of Confinement (In Months)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Length_of_No_animal_Order__c.field-meta.xml
<CustomField>
    <fullName>Length_of_No_animal_Order__c</fullName>
    <label>Length of No Animal Order (In Years)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Length_of_probation__c.field-meta.xml
<CustomField>
    <fullName>Length_of_probation__c</fullName>
    <defaultValue>&quot;None Ordered&quot;</defaultValue>
    <label>Length of Probation (In Months)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Length_of_Supervised_Release__c.field-meta.xml
<CustomField>
    <fullName>Length_of_Supervised_Release__c</fullName>
    <defaultValue>&quot;None Ordered&quot;</defaultValue>
    <label>Length of Supervised Release (In Years)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Sentence_Details_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Sentence_Details_Picklist__c</fullName>
    <label>Sentence Details</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Court_Disposition__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Animal Ban</fullName>
            </value>
            <value>
                <fullName>Anger Management Counseling</fullName>
            </value>
            <value>
                <fullName>Animals Forfeited</fullName>
            </value>
            <value>
                <fullName>Community Service</fullName>
            </value>
            <value>
                <fullName>Conditional Discharge</fullName>
            </value>
            <value>
                <fullName>Drug/Alcohol Counseling</fullName>
            </value>
            <value>
                <fullName>Fine</fullName>
            </value>
            <value>
                <fullName>FOOP</fullName>
            </value>
            <value>
                <fullName>Home Confinement/House Arrest</fullName>
            </value>
            <value>
                <fullName>Jail</fullName>
            </value>
            <value>
                <fullName>Other (Describe in Notes)</fullName>
            </value>
            <value>
                <fullName>Prison</fullName>
            </value>
            <value>
                <fullName>Probation (Supervised)</fullName>
            </value>
            <value>
                <fullName>Probation (Unsupervised)</fullName>
            </value>
            <value>
                <fullName>Psychological Counseling</fullName>
            </value>
            <value>
                <fullName>Registry</fullName>
            </value>
            <value>
                <fullName>Restitution</fullName>
            </value>
            <value>
                <fullName>Supervised Release</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Statute__c.field-meta.xml
<CustomField>
    <fullName>Statute__c</fullName>
    <description>This is the statute, chapter, section and sub-section of the charge law</description>
    <inlineHelpText>Write as: Statute.Chapter (section)(sub-section)
163.13(a)(1)</inlineHelpText>
    <label>Statute #</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Statute_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Statute_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NY Statute #</label>
    <referenceTo>NY_Offense__c</referenceTo>
    <relationshipLabel>Charge Information</relationshipLabel>
    <relationshipName>Charge_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NY_Offense__c/NY_Offense__c.object-meta.xml
<CustomObject>
    <label>NY Offense</label>
    <nameField>
        <label>Code Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NY Offenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/updateChargesClass.cls
public class updateChargesClass {
    @AuraEnabled
	public static List<Charge_Information__c> getCharges(String caseID){
    	List<Charge_Information__c> chargeList = [SELECT Id, Name, Defendant__c, Defendant__r.Name, Statute__c, Statute_Lookup__c,
                                                  Statute_Lookup__r.Name, Charge_Title__c, Charge_Count__c, Court_Disposition__c,
                                                  Courtdisposition_Date__c, Sentence_Details_Picklist__c, Counts_Convicted__c,
                                                  Counts_Acquitted__c, Counts_Dismissed__c, Counts_ACD_Given__c, Length_of_Confinement__c,
                                                  Community_Service_Hours__c, Length_of_No_animal_Order__c, Amount_of_Fine__c, 
                                                  Length_of_probation__c, Length_of_Supervised_Release__c, Appeal__c, Defendant_Case_s_Closed__c
                                                  FROM Charge_Information__c WHERE Case__r.Id = :caseID];
        
		return chargeList;
	}
    @AuraEnabled
	public static List<String> dispositionOptions(){
    	List<String> dispositionOptions = new List<String>();
        Schema.DescribeFieldResult dispositionField = Charge_Information__c.Court_Disposition__c.getDescribe();
        List<Schema.PicklistEntry> dispositionValues = dispositionField.getPicklistValues();
        for(Schema.PicklistEntry dispositionValue : dispositionValues){
            dispositionOptions.add(dispositionValue.getValue());
        }
		return dispositionOptions;
	}
    @AuraEnabled
	public static List<String> sentenceOptions(){
    	List<String> sentenceOptions = new List<String>();
        Schema.DescribeFieldResult sentenceField = Charge_Information__c.Sentence_Details_Picklist__c.getDescribe();
        List<Schema.PicklistEntry> sentenceValues = sentenceField.getPicklistValues();
        for(Schema.PicklistEntry sentenceValue : sentenceValues){
            sentenceOptions.add(sentenceValue.getValue());
        }
        System.debug('Return results: ' + sentenceOptions);
		return sentenceOptions;
	}
    @AuraEnabled
    public static void updateCharges(List<Charge_Information__c> updatedCharges){
		update updatedCharges;
	}
}