force-app/main/default/objects/Case/fields/Defendant__c.field-meta.xml
<CustomField>
    <fullName>Defendant__c</fullName>
    <label>Defendant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/Charge_Information__c.object-meta.xml
<CustomObject>
    <description>The information in this section pertains to the criminal charges relating to the subjects in this case</description>
    <label>Charge Information</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Charge ID #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charge Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge_Information__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Charge Information</relationshipLabel>
    <relationshipName>Charge_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Defendant__c.field-meta.xml
<CustomField>
    <fullName>Defendant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Person charged with violation of a federal, state or local crime.</description>
    <label>Defendant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Charge Information</relationshipLabel>
    <relationshipName>Charge_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestMassEdit_Charges.cls
@isTest
private class TestMassEdit_Charges {
    
    static testMethod void unitTest(){
        
	Case cs = new Case();
	insert cs;  
                
    Contact con = new Contact(FirstName = 'Test',LastName = 'Test');
    insert con;
        
    Charge_Information__c charge = new Charge_Information__c(Case__c=cs.Id, Defendant__c=con.Id);
    insert charge;
        
    MassEdit_Charges_Controller objME  = new MassEdit_Charges_Controller (new ApexPages.StandardController(cs));
        
    objME.saveChanges();
       
    

	}
}