force-app/main/default/objects/Protocol_Scale__c/Protocol_Scale__c.object-meta.xml
<CustomObject>
    <label>Protocol Scale</label>
    <nameField>
        <label>Protocol Scale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocol Scales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Protocol_Scale__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <inlineHelpText>semicolon separated</inlineHelpText>
    <label>Options</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/Session_Protocol__c.object-meta.xml
<CustomObject>
    <label>Session Protocol</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Session Protocol Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocols</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/fields/Overall_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score__c</fullName>
    <label>Overall Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Beginning/Acquisition</fullName>
            </value>
            <value>
                <fullName>2. Catching On/ Fluency</fullName>
            </value>
            <value>
                <fullName>3. Almost There/ Generalization</fullName>
            </value>
            <value>
                <fullName>4. Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/ProtocolId__c.field-meta.xml
<CustomField>
    <fullName>ProtocolId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/TreatmentSessionId__c.field-meta.xml
<CustomField>
    <fullName>TreatmentSessionId__c</fullName>
    <label>Treatment Session</label>
    <referenceTo>Treatment_Session__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/Session_Protocol_Scale__c.object-meta.xml
<CustomObject>
    <label>Session Protocol Scale</label>
    <nameField>
        <displayFormat>SPSN-{00000}</displayFormat>
        <label>Session Protocol Scale Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocol Scales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Protocol_Scale__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Scale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol Scale</label>
    <referenceTo>Protocol_Scale__c</referenceTo>
    <relationshipLabel>Session Protocol Scales</relationshipLabel>
    <relationshipName>Session_Protocol_Scales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Protocol_Score__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Score__c</fullName>
    <label>Protocol Score</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Session_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Session_Protocol__c</fullName>
    <label>Session Protocol</label>
    <referenceTo>Session_Protocol__c</referenceTo>
    <relationshipLabel>Session Protocol Scales</relationshipLabel>
    <relationshipName>Session_Protocol_Scales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Session__c/Treatment_Session__c.object-meta.xml
<CustomObject>
    <label>Treatment Session</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Treatment Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Session__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <label>Treatment Plan</label>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Treatment Sessions</relationshipLabel>
    <relationshipName>Treatment_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/test/test_LastTreatmentsController.cls
@isTest
public with sharing class test_LastTreatmentsController {
    @isTest
    static void getRecords() {
        Treatment_Session__c session = TestDataFactory.createSession();
        // Session_Protocol__c proto = [SELECT Id FROM Session_Protocol__c WHERE TreatmentSessionId__c = :session.Id LIMIT 1];

        //score the session so it's complete:
        Session_Protocol__c[] spList = [
            SELECT Id, Overall_Score__c, ProtocolId__c,
            ( SELECT Id, Protocol_Score__c, Protocol_Scale__r.Options__c
                FROM Session_Protocol_Scales__r
            )
            FROM Session_Protocol__c
            WHERE TreatmentSessionId__c = :session.Id
            LIMIT 1
        ];

        Session_Protocol_Scale__c[] scales = new Session_Protocol_Scale__c[0];
        for(Session_Protocol__c sp : spList){
            sp.Overall_Score__c = '1. Beginning/Acquisition';
            for(Session_Protocol_Scale__c sps : sp.Session_Protocol_Scales__r){
                String[] options = sps.Protocol_Scale__r.Options__c.split(';');
                sps.Protocol_Score__c = options[getRandomNumber(options.size())];
                scales.add(sps);
            }
        }

        update spList;
        update scales;



        Test.startTest();
        List<SessionProtocol> contList = LastTreatmentsController.getLastTreatments(session.Treatment_Plan__c, spList[0].ProtocolId__c, 5);
        Test.stopTest();
        System.assertEquals(1, contList.size());
    }

    public static Integer getRandomNumber(Integer max){
        Double randomNumber = Math.random(); 
        Integer randomIndex = (randomNumber *(max-1)).intValue(); 
        //Output the element at the list index generated above
        return randomIndex;
    }
}