force-app/main/default/objects/Session_Protocol__c/Session_Protocol__c.object-meta.xml
<CustomObject>
    <label>Session Protocol</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Session Protocol Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocols</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/fields/Overall_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score__c</fullName>
    <label>Overall Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Beginning/Acquisition</fullName>
            </value>
            <value>
                <fullName>2. Catching On/ Fluency</fullName>
            </value>
            <value>
                <fullName>3. Almost There/ Generalization</fullName>
            </value>
            <value>
                <fullName>4. Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/Session_Protocol_Scale__c.object-meta.xml
<CustomObject>
    <label>Session Protocol Scale</label>
    <nameField>
        <displayFormat>SPSN-{00000}</displayFormat>
        <label>Session Protocol Scale Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocol Scales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Protocol_Scale_Name__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Scale_Name__c</fullName>
    <formula>Protocol_Scale__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Protocol Scale Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Protocol_Score__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Score__c</fullName>
    <label>Protocol Score</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Session_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Session_Protocol__c</fullName>
    <label>Session Protocol</label>
    <referenceTo>Session_Protocol__c</referenceTo>
    <relationshipLabel>Session Protocol Scales</relationshipLabel>
    <relationshipName>Session_Protocol_Scales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/domain/SessionProtocolScaleDomain.cls
public with sharing class SessionProtocolScaleDomain extends DomainActionBase {
    public override void ProcessAction(TriggerRequest request) {
        if (request.targetSObject == Session_Protocol_Scale__c.SObjectType) {
            String triggerAction = request.action + request.process;

            switch on triggerAction {
                when 'BeforeInsert' { beforeInsert(request); }
                when 'BeforeUpdate' { beforeUpdate(request); }
                when 'BeforeDelete' { beforeDelete(request);}
                when 'AfterInsert' { afterInsert(request);}
                when 'AfterUpdate' { afterUpdate(request);}
                when 'AfterDelete' { afterDelete(request);}
            }
        }
        return;
    }

    @SuppressWarnings('ApexUnresolvableReference')
    public void beforeInsert(TriggerRequest request) {
        System.debug('SESSION PROTOCOL SCALE BEFORE INSERT IS EXECUTING');
    }
    
    public void beforeUpdate (TriggerRequest request) {
        System.debug('SESSION PROTOCOL SCALE BEFORE UPDATE IS EXECUTING');
        Session_Protocol_Scale__c[] newRecords = (Session_Protocol_Scale__c[]) request.newRecords;
        Map<Id, Session_Protocol_Scale__c> oldMap = (Map<Id, Session_Protocol_Scale__c>) request.oldRecordMap;
        //need to update the overall score field on the session protocol if it was updated
        // Session_Protocol__c[] sProtocols = new Session_Protocol__c[0];
        Map<Id, Session_Protocol__c> sProtocolMap = new Map<Id, Session_Protocol__c>();
        for(Session_Protocol_Scale__c sps : newRecords){
            Session_Protocol_Scale__c oldRecord = oldMap.get(sps.Id);
            if(sps.Protocol_Scale_Name__c == 'Overall Score' && sps.Protocol_Score__c != oldRecord.Protocol_Score__c){
                System.debug('**sps: ' + sps);
                if(sProtocolMap.containsKey(sps.Session_Protocol__c)){
                    sProtocolMap.get(sps.Session_Protocol__c).Overall_Score__c = sps.Protocol_Score__c;
                } else {
                    Session_Protocol__c sProtocol = new Session_Protocol__c(
                        Id = sps.Session_Protocol__c,
                        Overall_Score__c = sps.Protocol_Score__c
                    );
                    sProtocolMap.put(sps.Session_Protocol__c, sProtocol);
                }
            }
        }

        update sProtocolMap.values();
        System.debug('sProtocolMap: ' + sProtocolMap);
    }

    public void beforeDelete (TriggerRequest request) { 
        System.debug('SESSION PROTOCOL SCALE BEFORE DELETE IS EXECUTING'); 
    }

    @SuppressWarnings('ApexUnresolvableReference')
    public void afterInsert(TriggerRequest request) {
        System.debug('SESSION PROTOCOL SCALE AFTER INSERT IS EXECUTING');
    }

    public void afterUpdate (TriggerRequest request) {
        System.debug('SESSION PROTOCOL SCALE AFTER UPDATE IS EXECUTING');
    }
    public void afterDelete (TriggerRequest request) { System.debug('SESSION PROTOCOL SCALE AFTER INSERT IS EXECUTING'); }
}