force-app/main/default/objects/Session_Protocol__c/Session_Protocol__c.object-meta.xml
<CustomObject>
    <label>Session Protocol</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Session Protocol Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocols</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol_Scale__c/Session_Protocol_Scale__c.object-meta.xml
<CustomObject>
    <label>Session Protocol Scale</label>
    <nameField>
        <displayFormat>SPSN-{00000}</displayFormat>
        <label>Session Protocol Scale Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocol Scales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Protocol_Scale_Name__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Scale_Name__c</fullName>
    <formula>Protocol_Scale__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Protocol Scale Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Protocol_Score__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Score__c</fullName>
    <label>Protocol Score</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Protocol_Score_Number__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Score_Number__c</fullName>
    <formula>VALUE(LEFT(Protocol_Score__c,1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Protocol Score (Number)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Session_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Session_Protocol__c</fullName>
    <label>Session Protocol</label>
    <referenceTo>Session_Protocol__c</referenceTo>
    <relationshipLabel>Session Protocol Scales</relationshipLabel>
    <relationshipName>Session_Protocol_Scales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SessionProtocol.cls
public with sharing class SessionProtocol {
    public Session_Protocol__c sProto {get; set;}
    public ProtocolScore aggressiveWorst {get; set;}
    public ProtocolScore arousalBest {get; set;}
    public ProtocolScore arousalWorst {get; set;}
    public ProtocolScore fearBest {get; set;}
    public ProtocolScore fearWorst {get; set;}
    public ProtocolScore socialBest {get; set;}

    public SessionProtocol(Session_Protocol__c sp){
        this.sProto = sp;
        for(Session_Protocol_Scale__c protoScale : sProto.Session_Protocol_Scales__r){
            switch on protoScale.Protocol_Scale_Name__c {
                when 'Aggression - Movement' {
                    this.aggressiveWorst = new ProtocolScore(protoScale);
                }	
                when 'Arousal - Best' {
                    this.arousalBest = new ProtocolScore(protoScale);
                }
                when 'Arousal - Worst' {
                    this.arousalWorst = new ProtocolScore(protoScale);
                }
                when 'Fear - Best' {
                    this.fearBest = new ProtocolScore(protoScale);
                }
                when 'Fear - Worst' {
                    this.fearWorst = new ProtocolScore(protoScale);
                }
                when 'Fear - Sociability Best' {
                    this.socialBest = new ProtocolScore(protoScale);
                }
            }                
        }
    }

    public class ProtocolScore{
        public String score {get; set;}
        public Decimal scoreNumber {get; set;}
        
        ProtocolScore(Session_Protocol_Scale__c scale){
            this.score = scale.Protocol_Score__c;
            this.scoreNumber = scale.Protocol_Score_Number__c;

        }
    }
}