force-app/main/default/objects/Session_Protocol__c/Session_Protocol__c.object-meta.xml
<CustomObject>
    <label>Session Protocol</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Session Protocol Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocols</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/fields/Novel_Person__c.field-meta.xml
<CustomField>
    <fullName>Novel_Person__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Novel Person</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Overall_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score__c</fullName>
    <label>Overall Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Beginning/Acquisition</fullName>
            </value>
            <value>
                <fullName>2. Catching On/ Fluency</fullName>
            </value>
            <value>
                <fullName>3. Almost There/ Generalization</fullName>
            </value>
            <value>
                <fullName>4. Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Protocol_Notes__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Notes__c</fullName>
    <label>Protocol Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/ProtocolId__c.field-meta.xml
<CustomField>
    <fullName>ProtocolId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Session Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Status_Text__c.field-meta.xml
<CustomField>
    <fullName>Status_Text__c</fullName>
    <formula>IF(IsSkipped__c = TRUE, &quot;Skipped&quot;, 
				(IF(Scored_Count__c &lt; Required_Count__c , &quot;Not Complete&quot; ,
					&quot;Complete&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/TreatmentSessionId__c.field-meta.xml
<CustomField>
    <fullName>TreatmentSessionId__c</fullName>
    <label>Treatment Session</label>
    <referenceTo>Treatment_Session__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/Session_Protocol_Scale__c.object-meta.xml
<CustomObject>
    <label>Session Protocol Scale</label>
    <nameField>
        <displayFormat>SPSN-{00000}</displayFormat>
        <label>Session Protocol Scale Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocol Scales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Protocol_Scale_Name__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Scale_Name__c</fullName>
    <formula>Protocol_Scale__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Protocol Scale Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Protocol_Score__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Score__c</fullName>
    <label>Protocol Score</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Protocol_Score_Number__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Score_Number__c</fullName>
    <formula>VALUE(LEFT(Protocol_Score__c,1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Protocol Score (Number)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Session_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Session_Protocol__c</fullName>
    <label>Session Protocol</label>
    <referenceTo>Session_Protocol__c</referenceTo>
    <relationshipLabel>Session Protocol Scales</relationshipLabel>
    <relationshipName>Session_Protocol_Scales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Session__c/Treatment_Session__c.object-meta.xml
<CustomObject>
    <label>Treatment Session</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Treatment Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Session__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <label>Treatment Plan</label>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Treatment Sessions</relationshipLabel>
    <relationshipName>Treatment_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/controller/LastTreatmentsController.cls
public with sharing class LastTreatmentsController {
    @AuraEnabled(cacheable=true)
    public static SessionProtocol[] getLastTreatments(Id treatmentPlanId, Id protocolId, Integer recordCount) {
        System.debug('**lastTreatments');
        List<SessionProtocol[]> protocolLists = new List<SessionProtocol[]>();
        Map<Id, SessionProtocol[]> sProtocolMap = new Map<Id, SessionProtocol[]>();
        SessionProtocol[] sProtocolList = new SessionProtocol[0];
        for(Session_Protocol__c sp : [
            SELECT Id, Overall_Score__c, Protocol_Notes__c, CreatedDate, Novel_Person__c, TreatmentSessionId__c, TreatmentSessionId__r.Session_Date__c,
            (
                SELECT Id, Protocol_Scale_Name__c, Protocol_Score__c, Protocol_Score_Number__c 
                FROM Session_Protocol_Scales__r
            )
            FROM Session_Protocol__c
            WHERE TreatmentSessionId__r.Treatment_Plan__c = :treatmentPlanId
            AND ProtocolId__c = :protocolId
            AND Status_Text__c = 'Complete'
            ORDER BY TreatmentSessionId__r.Session_Date__c DESC
            LIMIT :recordCount
        ]){
            SessionProtocol proto = new SessionProtocol(sp);
            System.debug('proto: ' + proto);
            sProtocolList.add(proto);
        }

        System.debug('sProtocolList: ' + sProtocolList);

        return sProtocolList;
    }
}