force-app/main/default/objects/Session_Protocol__c/Session_Protocol__c.object-meta.xml
<CustomObject>
    <label>Session Protocol</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Session Protocol Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocols</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/fields/Overall_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score__c</fullName>
    <label>Overall Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Beginning/Acquisition</fullName>
            </value>
            <value>
                <fullName>2. Catching On/ Fluency</fullName>
            </value>
            <value>
                <fullName>3. Almost There/ Generalization</fullName>
            </value>
            <value>
                <fullName>4. Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/Session_Protocol_Scale__c.object-meta.xml
<CustomObject>
    <label>Session Protocol Scale</label>
    <nameField>
        <displayFormat>SPSN-{00000}</displayFormat>
        <label>Session Protocol Scale Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocol Scales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Protocol_Scale_Name__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Scale_Name__c</fullName>
    <formula>Protocol_Scale__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Protocol Scale Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Protocol_Score__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Score__c</fullName>
    <label>Protocol Score</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Scale__c/fields/Session_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Session_Protocol__c</fullName>
    <label>Session Protocol</label>
    <referenceTo>Session_Protocol__c</referenceTo>
    <relationshipLabel>Session Protocol Scales</relationshipLabel>
    <relationshipName>Session_Protocol_Scales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_SessionProtocolScaleDomain.cls
@isTest
private class Test_SessionProtocolScaleDomain {
    @isTest 
    static void updateSessionProtocolScaleSuccess() {
        Session_Protocol_Scale__c[] spsList = TestDataFactory.createSessionProtocolScales();
        spsList = [SELECT Id, Protocol_Scale_Name__c, Protocol_Score__c, Session_Protocol__c FROM Session_Protocol_Scale__c WHERE Id IN :spsList];
        System.debug('**spsList: ' + spsList);

        for(Session_Protocol_Scale__c sps : spsList){
            if(sps.Protocol_Scale_Name__c == 'Overall Score'){
                sps.Protocol_Score__c = '1. Beginning/Acquisition';
            }
        }
        Test.startTest();
            update spsList;
        Test.stopTest();

        Session_Protocol__c sp = [SELECT Id, Overall_Score__c FROM Session_Protocol__c WHERE Id = :spsList[0].Session_Protocol__c LIMIT 1];
        System.assertNotEquals(null, sp);
        System.assertEquals('1. Beginning/Acquisition', sp.Overall_Score__c);
    }

    @isTest 
    static void updateSessionProtocolScaleNotOverallScore() {
        Session_Protocol_Scale__c[] spsList = TestDataFactory.createSessionProtocolScales();
        spsList = [SELECT Id, Protocol_Scale_Name__c, Protocol_Score__c, Session_Protocol__c FROM Session_Protocol_Scale__c WHERE Id IN :spsList];
        System.debug('**spsList: ' + spsList);

        for(Session_Protocol_Scale__c sps : spsList){
            if(sps.Protocol_Scale_Name__c != 'Overall Score'){
                sps.Protocol_Score__c = '1 test score';
            }
        }
        Test.startTest();
            update spsList;
        Test.stopTest();

        Session_Protocol__c sp = [SELECT Id, Overall_Score__c FROM Session_Protocol__c WHERE Id = :spsList[0].Session_Protocol__c LIMIT 1];
        System.assertNotEquals(null, sp);
        System.assertEquals(null, sp.Overall_Score__c);
    }
}