force-app/main/default/objects/Session_Protocol__c/Session_Protocol__c.object-meta.xml
<CustomObject>
    <label>Session Protocol</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Session Protocol Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocols</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/fields/Aggressive_Worst__c.field-meta.xml
<CustomField>
    <fullName>Aggressive_Worst__c</fullName>
    <label>Aggressive - Worst</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. None Observed</fullName>
            </value>
            <value>
                <fullName>2. Hard stare, whale eye, rigid, freezes</fullName>
            </value>
            <value>
                <fullName>3. Head whips, lifts lip, growls or alarm barks</fullName>
            </value>
            <value>
                <fullName>4. Air snaps or muzzle punches</fullName>
            </value>
            <value>
                <fullName>5. Tries to bite or bites</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Arousal_Best__c.field-meta.xml
<CustomField>
    <fullName>Arousal_Best__c</fullName>
    <label>Arousal - Best</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Low/Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mild</fullName>
            </value>
            <value>
                <fullName>3. Moderate</fullName>
            </value>
            <value>
                <fullName>4. Extreme</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Arousal_Worst__c.field-meta.xml
<CustomField>
    <fullName>Arousal_Worst__c</fullName>
    <label>Arousal - Worst</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Low/Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mild</fullName>
            </value>
            <value>
                <fullName>3. Moderate</fullName>
            </value>
            <value>
                <fullName>4. Extreme</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Fear_Best__c.field-meta.xml
<CustomField>
    <fullName>Fear_Best__c</fullName>
    <label>Fear - Best</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>1. Excited, playful, interested</fullName>
            </value>
            <value>
                <fullName>2. Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mildly fearful</fullName>
            </value>
            <value>
                <fullName>3. Moderately fearful</fullName>
            </value>
            <value>
                <fullName>4. Extremely fearful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Fear_Worst__c.field-meta.xml
<CustomField>
    <fullName>Fear_Worst__c</fullName>
    <label>Fear - Worst</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>1. Excited, playful, interested</fullName>
            </value>
            <value>
                <fullName>2. Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mildly fearful</fullName>
            </value>
            <value>
                <fullName>3. Moderately fearful</fullName>
            </value>
            <value>
                <fullName>4. Extremely fearful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/IsSkipped__c.field-meta.xml
<CustomField>
    <fullName>IsSkipped__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Protocol</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Preferred_Motivators__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Motivators__c</fullName>
    <label>Preferred Motivators</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Social_Best__c.field-meta.xml
<CustomField>
    <fullName>Social_Best__c</fullName>
    <label>Fear - Sociability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Solicitation, sustained proximity</fullName>
            </value>
            <value>
                <fullName>2. Solicitation, short proximity</fullName>
            </value>
            <value>
                <fullName>3. Solicitation, no proximity</fullName>
            </value>
            <value>
                <fullName>4. No Solicitation, sustained proxmity</fullName>
            </value>
            <value>
                <fullName>5. No Solicitation, short proximity</fullName>
            </value>
            <value>
                <fullName>6. No Solicitation, no proximity</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/domain/SessionProtocolDomain.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class SessionProtocolDomain extends DomainActionBase {
    public override void ProcessAction(TriggerRequest request) {
        if (request.targetSObject == Session_Protocol__c.SObjectType) {
            String triggerAction = request.action + request.process;

            switch on triggerAction {
                when 'BeforeInsert' { beforeInsert(request); }
                when 'BeforeUpdate' { beforeUpdate(request); }
                when 'BeforeDelete' { beforeDelete(request);}
                when 'AfterInsert' { afterInsert(request);}
                when 'AfterUpdate' { afterUpdate(request);}
                when 'AfterDelete' { afterDelete(request);}
            }
        }
        return;
    }

    public void beforeInsert (TriggerRequest request) {System.debug('SESSION PROTOCOL BEFORE INSERT IS EXECUTING'); }
    public void beforeUpdate (TriggerRequest request) {
        System.debug('SESSION PROTOCOL BEFORE UPDATE IS EXECUTING');
        Map<Id, Session_Protocol__c> newRecordMap = (Map<Id, Session_Protocol__c>) request.newRecordMap;

        for (Session_Protocol__c protocol : newRecordMap.values()) {
            if(protocol.IsSkipped__c == true) {
                protocol.Preferred_Motivators__c = '';
                protocol.Arousal_Best__c = 'None';
                protocol.Arousal_Worst__c = 'None';
                protocol.Fear_Best__c = 'None';
                protocol.Fear_Worst__c = 'None';
                protocol.Social_Best__c = 'None';
                protocol.Aggressive_Worst__c = 'None';
            }
        }
    }
    public void beforeDelete (TriggerRequest request) { System.debug('SESSION PROTOCOL BEFORE DELETE IS EXECUTING'); }
    public void afterInsert (TriggerRequest request) { System.debug('SESSION PROTOCOL AFTER INSERT IS EXECUTING'); }
    public void afterUpdate (TriggerRequest request) { System.debug('SESSION PROTOCOL AFTER INSERT IS EXECUTING'); }
    public void afterDelete (TriggerRequest request) { System.debug('SESSION PROTOCOL AFTER INSERT IS EXECUTING'); }

}