force-app/main/default/objects/Session_Protocol__c/Session_Protocol__c.object-meta.xml
<CustomObject>
    <label>Session Protocol</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Session Protocol Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocols</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/fields/TreatmentSessionId__c.field-meta.xml
<CustomField>
    <fullName>TreatmentSessionId__c</fullName>
    <label>Treatment Session</label>
    <referenceTo>Treatment_Session__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/Treatment_Session__c.object-meta.xml
<CustomObject>
    <label>Treatment Session</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Treatment Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/test/test_InvocableActionHandler.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

@IsTest
private class test_InvocableActionHandler {
    @IsTest
    static void validateSessionCoverage() {
        InvocableActionHandler.InvocableActionRequest request = new InvocableActionHandler.InvocableActionRequest();



        List<Session_Protocol__c> sessionProtocols = TestDataFactory.createSessionProtocols();
        Treatment_Session__c session = new Treatment_Session__c();
        Session_Protocol__c protocol = sessionProtocols[0];
        session.Id = protocol.TreatmentSessionId__c;

        request.recordId = session.Id;
        request.targetSObject = 'Quote';
        request.action = 'validateSession';
        request.name = 'Test';

        List<InvocableActionHandler.InvocableActionRequest> requests = new List<InvocableActionHandler.InvocableActionRequest>();
        requests.add(request);

        List<InvocableActionHandler.InvocableActionResponse> responses = InvocableActionHandler.invocableAction
                (requests);

    }

    @IsTest
    static void validateSessionCoverageRegressionTest() {
        InvocableActionHandler.InvocableActionRequest request = new InvocableActionHandler.InvocableActionRequest();

        Treatment_Session__c session = TestDataFactory.createSession();

        request.recordId = session.Id;
        request.targetSObject = 'Quote';
        request.action = 'validateSession';
        request.name = 'Test';

        List<InvocableActionHandler.InvocableActionRequest> requests = new List<InvocableActionHandler.InvocableActionRequest>();
        requests.add(request);

        List<InvocableActionHandler.InvocableActionResponse> responses = InvocableActionHandler.invocableAction
                (requests);

        Test.startTest();

        System.debug(responses);

        Test.stopTest();
    }
}