force-app/main/default/objects/Test_Config__mdt/Test_Config__mdt.object-meta.xml
<CustomObject>
    <label>Test Config</label>
    <pluralLabel>Test Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Test_Config__mdt/fields/Picklist_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Picklist_API_Name__c</fullName>
    <label>Picklist API Name</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Test_Config__mdt/fields/Test_Comment_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Comment_Field_Name__c</fullName>
    <description>API Name of Test Comments Field</description>
    <label>Test Comment Field Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Config__mdt/fields/Test_Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Test_Display_Order__c</fullName>
    <label>Test Display Order</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/test/SummaryWrapperTest.cls
@isTest
private class SummaryWrapperTest {
    @isTest 
    static void SummaryWrapperTest() {
        List<SummaryWrapper> puppySummary = new List<SummaryWrapper>();

        test.startTest();
        puppySummary.add(new SummaryWrapper(1, 'testLabel'));

        test.stopTest();
        System.assertEquals(1, puppySummary[0].labelOrder);
        System.assertEquals('testLabel', puppySummary[0].labelValue);
    }

    @isTest 
    static void SummaryWrapperTestWithName() {
        List<SummaryWrapper> puppySummary = new List<SummaryWrapper>();

        test.startTest();
        puppySummary.add(new SummaryWrapper(1, 'testLabel', 'testName'));

        test.stopTest();
        System.assertEquals(1, puppySummary[0].labelOrder);
        System.assertEquals('testLabel', puppySummary[0].labelValue);
        System.assertEquals('testName', puppySummary[0].testName);
    }

    @isTest 
    static void SummaryWrapperTestWithConfig() {
        List<SummaryWrapper> puppySummary = new List<SummaryWrapper>();
        Test_Config__mdt config = new Test_Config__mdt(
            Label = 'Behavior Test',
            DeveloperName = 'Behavior_Test',
            Test_Comment_Field_Name__c = 'Name',
            Picklist_API_Name__c = 'Field__c',
            Test_Display_Order__c = '1'
        );

        test.startTest();
        puppySummary.add(new SummaryWrapper(1, 'testName', config));

        test.stopTest();
        System.assertEquals(1, puppySummary[0].labelOrder);
        System.assertEquals('testName', puppySummary[0].testName);
        System.assertEquals(config, puppySummary[0].config);
    }

    @isTest 
    static void SummaryWrapperCompare() {
        List<SummaryWrapper> puppySummary = new List<SummaryWrapper>();
        Test_Config__mdt config = new Test_Config__mdt(
            Label = 'Behavior Test',
            DeveloperName = 'Behavior_Test',
            Test_Comment_Field_Name__c = 'Name',
            Picklist_API_Name__c = 'Field__c',
            Test_Display_Order__c = '1'
        );

        puppySummary.add(new SummaryWrapper(1, 'testName', config));

        SummaryWrapper sWrap = new SummaryWrapper();

        test.startTest();
        Integer i = sWrap.compareTo(puppySummary[0]);

        test.stopTest();
        System.assertEquals(0, i);
    }
}