force-app/main/default/objects/Plan_Protocol__c/Plan_Protocol__c.object-meta.xml
<CustomObject>
    <label>Plan Protocol</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Plan Protocol Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Protocol__c/fields/IsRemoved__c.field-meta.xml
<CustomField>
    <fullName>IsRemoved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to Remove value from Treatment Plan</description>
    <label>Removed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Plan Protocols</relationshipLabel>
    <relationshipName>Plan_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Plan Protocols</relationshipLabel>
    <relationshipName>Plan_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/Session_Protocol__c.object-meta.xml
<CustomObject>
    <label>Session Protocol</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Session Protocol Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocols</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/fields/Add_to_Plan__c.field-meta.xml
<CustomField>
    <fullName>Add_to_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add to Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Aggressive_Worst__c.field-meta.xml
<CustomField>
    <fullName>Aggressive_Worst__c</fullName>
    <label>Aggressive - Worst</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. None Observed</fullName>
            </value>
            <value>
                <fullName>2. Hard stare, whale eye, rigid, freezes</fullName>
            </value>
            <value>
                <fullName>3. Head whips, lifts lip, growls or alarm barks</fullName>
            </value>
            <value>
                <fullName>4. Air snaps or muzzle punches</fullName>
            </value>
            <value>
                <fullName>5. Tries to bite or bites</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Arousal_Best__c.field-meta.xml
<CustomField>
    <fullName>Arousal_Best__c</fullName>
    <label>Arousal - Best</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Low/Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mild</fullName>
            </value>
            <value>
                <fullName>3. Moderate</fullName>
            </value>
            <value>
                <fullName>4. Extreme</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Arousal_Worst__c.field-meta.xml
<CustomField>
    <fullName>Arousal_Worst__c</fullName>
    <label>Arousal - Worst</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Low/Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mild</fullName>
            </value>
            <value>
                <fullName>3. Moderate</fullName>
            </value>
            <value>
                <fullName>4. Extreme</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Fear_Best__c.field-meta.xml
<CustomField>
    <fullName>Fear_Best__c</fullName>
    <label>Fear - Best</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>1. Excited, playful, interested</fullName>
            </value>
            <value>
                <fullName>2. Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mildly fearful</fullName>
            </value>
            <value>
                <fullName>3. Moderately fearful</fullName>
            </value>
            <value>
                <fullName>4. Extremely fearful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Fear_Worst__c.field-meta.xml
<CustomField>
    <fullName>Fear_Worst__c</fullName>
    <label>Fear - Worst</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>1. Excited, playful, interested</fullName>
            </value>
            <value>
                <fullName>2. Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mildly fearful</fullName>
            </value>
            <value>
                <fullName>3. Moderately fearful</fullName>
            </value>
            <value>
                <fullName>4. Extremely fearful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/IsRemoved__c.field-meta.xml
<CustomField>
    <fullName>IsRemoved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Removed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/IsSkipped__c.field-meta.xml
<CustomField>
    <fullName>IsSkipped__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Protocol</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Overall_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score__c</fullName>
    <label>Overall Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Beginning/Acquisition</fullName>
            </value>
            <value>
                <fullName>2. Catching On/ Fluency</fullName>
            </value>
            <value>
                <fullName>3. Almost There/ Generalization</fullName>
            </value>
            <value>
                <fullName>4. Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Preferred_Motivators__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Motivators__c</fullName>
    <label>Preferred Motivators</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/ProtocolId__c.field-meta.xml
<CustomField>
    <fullName>ProtocolId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Social_Best__c.field-meta.xml
<CustomField>
    <fullName>Social_Best__c</fullName>
    <label>Fear - Sociability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Solicitation, sustained proximity</fullName>
            </value>
            <value>
                <fullName>2. Solicitation, short proximity</fullName>
            </value>
            <value>
                <fullName>3. Solicitation, no proximity</fullName>
            </value>
            <value>
                <fullName>4. No Solicitation, sustained proxmity</fullName>
            </value>
            <value>
                <fullName>5. No Solicitation, short proximity</fullName>
            </value>
            <value>
                <fullName>6. No Solicitation, no proximity</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/TreatmentSessionId__c.field-meta.xml
<CustomField>
    <fullName>TreatmentSessionId__c</fullName>
    <label>Treatment Session</label>
    <referenceTo>Treatment_Session__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Preferred_Motivators__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Motivators__c</fullName>
    <label>Preferred Motivators</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/Treatment_Session__c.object-meta.xml
<CustomObject>
    <label>Treatment Session</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Treatment Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Session__c/fields/Preferred_Motivators__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Motivators__c</fullName>
    <label>Preferred Motivators</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <label>Treatment Plan</label>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Treatment Sessions</relationshipLabel>
    <relationshipName>Treatment_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/test_SessionProtocolDomain.cls
@isTest
private class test_SessionProtocolDomain {
    @isTest 
    static void beforeUpdate_isSkipped(){
        Session_Protocol__c sp = TestDataFactory.createSessionProtocols()[0];

        sp.Preferred_Motivators__c = 'newspaper';
        sp.Arousal_Best__c = '2. Mild';
        sp.Arousal_Worst__c = '2. Mild';
        sp.Fear_Best__c = '2. Neutral';
        sp.Fear_Worst__c = '2. Neutral';
        sp.Social_Best__c = '1. Solicitation, sustained proximity';
        sp.Aggressive_Worst__c = '2. Hard stare, whale eye, rigid, freezes';
        sp.Overall_Score__c = '2. Catching On/ Fluency';
        update sp;

        Test.startTest();
            sp.IsSkipped__c = true;
            update sp;
        Test.stopTest();

        Session_Protocol__c updatedSP = [
            SELECT 
                Id,
                Aggressive_Worst__c,
                Arousal_Best__c,
                Arousal_Worst__c,
                Fear_Best__c,
                Fear_Worst__c,
                IsSkipped__c,
                Social_Best__c,
                Overall_Score__c,
                Preferred_Motivators__c
            FROM Session_Protocol__c
            WHERE Id =: sp.Id 
            LIMIT 1
        ];

        System.assertEquals(null, updatedSP.Aggressive_Worst__c);
        System.assertEquals(null, updatedSP.Arousal_Best__c);
        System.assertEquals(null, updatedSP.Arousal_Worst__c);
        System.assertEquals(null, updatedSP.Fear_Best__c);
        System.assertEquals(null, updatedSP.Fear_Worst__c);        
        System.assertEquals(null, updatedSP.Social_Best__c);
        System.assertEquals(null, updatedSP.Overall_Score__c);
        System.assertEquals(null, updatedSP.Preferred_Motivators__c);
        System.assertEquals(true, updatedSP.IsSkipped__c);
    }

    @isTest 
    static void beforeUpdate_addToPlan(){
        Treatment_Session__c session = TestDataFactory.createSession();
        Protocol__c protocol = new Protocol__c(
            Name = 'Test Protocol',
            IsActive__c = true
        );
        insert protocol;

        Session_Protocol__c sp = new Session_Protocol__c(
            ProtocolId__c = protocol.Id,
            TreatmentSessionId__c = session.Id
        );
        insert sp;

        Test.startTest();
            sp.Add_To_Plan__c = true;
            update sp;
        Test.stopTest();

        Plan_Protocol__c pr = [SELECT Id, Protocol__c FROM Plan_Protocol__c WHERE Treatment_Plan__c =: session.Treatment_Plan__c AND Protocol__c =: protocol.Id LIMIT 1];

        System.assert(pr != null, 'a Plan Protocol should have been returned');
        System.assertEquals(protocol.Id, pr.Protocol__c);
    }

    @isTest 
    static void beforeUpdate_removeFromPlan(){
        Session_Protocol__c protocol = TestDataFactory.createSessionProtocols()[0];
        Treatment_Session__c session = [SELECT Id, Treatment_Plan__c FROM Treatment_Session__c WHERE Id =: protocol.TreatmentSessionId__c LIMIT 1];
        Plan_Protocol__c pr = new Plan_Protocol__c(
            Protocol__c = protocol.ProtocolId__c,
            Treatment_Plan__c = session.Treatment_Plan__c
        );

        insert pr;

        Test.startTest();
            protocol.IsRemoved__c = true;
            update protocol;
        Test.stopTest();

        Plan_Protocol__c updatedPr = [SELECT Id, Protocol__c, IsRemoved__c FROM Plan_Protocol__c WHERE Id =: pr.Id LIMIT 1];
        System.assertEquals(true, updatedPr.IsRemoved__c);
    }    
}