force-app/main/default/objects/Plan_Protocol__c/Plan_Protocol__c.object-meta.xml
<CustomObject>
    <label>Plan Protocol</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Plan Protocol Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Protocol__c/fields/Protocol_Name__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Name__c</fullName>
    <formula>Protocol__r.Name</formula>
    <label>Protocol Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Plan Protocols</relationshipLabel>
    <relationshipName>Plan_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TreatmentToDoPDFController.cls
public class TreatmentToDoPDFController {
    public List<TreatmentPlanWithProtocols> treatmentPlansWithProtocols{get;set;}
    public TreatmentToDoPDFController (){
        String locationsFilter = ApexPages.currentPage()?.getparameters()?.get('locations');
        Boolean useFilter = Boolean.valueOf(ApexPages.currentPage()?.getparameters()?.get('useFilter'));

        TreatmentPlanWithProtocols[] treatmentPlanList = new TreatmentPlanWithProtocols[0];

        for(Treatment_Plan__c plan : new TreatmentToDoListController.QueryTreatmentPlansForList(locationsFilter, useFilter).treatmentPlanList){

            TreatmentPlanWithProtocols tPlan = new TreatmentPlanWithProtocols();
            tPlan.treatmentPlan = plan;

            List<String> protocolNames = new List<String>();
            for(Plan_Protocol__c protocolObj : plan.Plan_Protocols__r){
                protocolNames.add(protocolObj.Protocol_Name__c);
            }
            tPlan.protocols = string.join(protocolNames, '; ');

            treatmentPlanList.add(tPlan);
        }

        treatmentPlansWithProtocols = treatmentPlanList;
    }

    public class TreatmentPlanWithProtocols{
        public Treatment_Plan__c treatmentPlan {get; set;}
        public String protocols {get; set;}
    }
}