force-app/main/default/objects/Case/recordTypes/Action_Item.recordType-meta.xml
<RecordType>
    <fullName>Action_Item</fullName>
    <active>false</active>
    <businessProcess>ASPCA AI</businessProcess>
    <label>Action Item</label>
</RecordType>

force-app/main/default/objects/Facility_Outcome__c/Facility_Outcome__c.object-meta.xml
<CustomObject>
    <label>Facility/Outcome</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>F/O #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facilities/Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Facility_Outcome__c/fields/Facility_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Facility_Outcome__c</fullName>
    <label>Facility/Outcome</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Facility_or_Outcome__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAH</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Adoption Center</fullName>
            </value>
            <value>
                <fullName>Adoption Center (Temp Boarding)</fullName>
            </value>
            <value>
                <fullName>Animal Hospital</fullName>
            </value>
            <value>
                <fullName>Animal Shelter</fullName>
            </value>
            <value>
                <fullName>ARC</fullName>
            </value>
            <value>
                <fullName>ASNA</fullName>
            </value>
            <value>
                <fullName>ASPCA Shelter</fullName>
            </value>
            <value>
                <fullName>Board and Train</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>BRC</fullName>
            </value>
            <value>
                <fullName>Bronx CVC</fullName>
            </value>
            <value>
                <fullName>Brooklyn CVC</fullName>
            </value>
            <value>
                <fullName>CARE</fullName>
            </value>
            <value>
                <fullName>Clinic</fullName>
            </value>
            <value>
                <fullName>Community Medicine</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
            <value>
                <fullName>CRC-MRC</fullName>
            </value>
            <value>
                <fullName>Cremation</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Euthanized</fullName>
            </value>
            <value>
                <fullName>Field Temp Shelter</fullName>
            </value>
            <value>
                <fullName>Foster-Based Rescue</fullName>
            </value>
            <value>
                <fullName>Foster Home</fullName>
            </value>
            <value>
                <fullName>Foster Home - Adoption Center</fullName>
            </value>
            <value>
                <fullName>Foster Home - ARC</fullName>
            </value>
            <value>
                <fullName>Foster Home - CARE</fullName>
            </value>
            <value>
                <fullName>Hound Hotel</fullName>
            </value>
            <value>
                <fullName>Kitten Nursery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Facility_Outcome__c/fields/Point_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Point_of_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Point of Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Facilities/Outcomes</relationshipLabel>
    <relationshipName>Facilities_Outcomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/test/test_Util.cls
@isTest
public class test_Util {
    @TestSetup
    static void setupData() {
        EmailTemplate template = new EmailTemplate(
            developerName = EMAIL_TEMPLATE_DEVELOPER_NAME,
            TemplateType = EMAIL_TEMPLATE_TYPE,
            Name = EMAIL_TEMPLATE_NAME,
            FolderId = UserInfo.getOrganizationId(),
            IsActive = true);
        insert template;
    }

    @isTest
    static void getRecordTypeIdTest() {
        Id recordTypeId;
        System.assertEquals(null, recordTypeId);
        Test.startTest();
        recordTypeId = Util.getRecordTypeId('Case', 'Action_Item');
        Test.stopTest();
        System.assertNotEquals(null, recordTypeId);
    }

    @isTest
    static void getOrgWideEmailAddressValid() {
        Test.startTest();
        OrgWideEmailAddress emailAddress = Util.getOrgWideEmailAddress(VALID_ORG_WIDE_EMAIL);
        Test.stopTest();
        System.assertNotEquals(null, emailAddress);
        System.assertEquals(VALID_ORG_WIDE_EMAIL, emailAddress.DisplayName);
    }

    @isTest
    static void getOrgWideEmailAddressInvalid() {
        Test.startTest();
        OrgWideEmailAddress emailAddress = Util.getOrgWideEmailAddress(INVALID_ORG_WIDE_EMAIL);
        Test.stopTest();
        System.assertEquals(null, emailAddress);
    }

    @isTest
    static void getEmailTemplateIdValid() {
        Test.startTest();
        Id foundTemplateId = Util.getEmailTemplateId(EMAIL_TEMPLATE_DEVELOPER_NAME);
        Test.stopTest();
        EmailTemplate template = [SELECT Id FROM EmailTemplate WHERE DeveloperName = :EMAIL_TEMPLATE_DEVELOPER_NAME LIMIT 1];
        System.assertEquals(template.Id, foundTemplateId);
    }

    @isTest
    static void getEmailTemplateIdInvalid() {
        Test.startTest();
        Id foundTemplateId = Util.getEmailTemplateId(EMAIL_TEMPLATE_NAME);
        Test.stopTest();
        System.assertEquals(null, foundTemplateId);
    }

    @isTest
    static void createContactEmailNoOrg() {
        Facility_Outcome__c facility = TestDataFactory.createFacilityOutcome();
        Id templateId = Util.getEmailTemplateId(EMAIL_TEMPLATE_DEVELOPER_NAME);
        Test.startTest();
        Messaging.SingleEmailMessage message = Util.createContactEmail(templateId, facility.Point_of_Contact__c, facility.Id, true);
        Test.stopTest();
        System.assertEquals(templateId, message.getTemplateId());
        System.assertEquals(facility.Point_of_Contact__c, message.getTargetObjectId());
        System.assertEquals(facility.Id, message.getWhatId());
        System.assertEquals(null, message.getOrgWideEmailAddressId());
    }

    @isTest
    static void createContactEmailWithOrg() {
        Facility_Outcome__c facility = TestDataFactory.createFacilityOutcome();
        Id templateId = Util.getEmailTemplateId(EMAIL_TEMPLATE_DEVELOPER_NAME);
        OrgWideEmailAddress orgWide = Util.getOrgWideEmailAddress(VALID_ORG_WIDE_EMAIL);
        Test.startTest();
        Messaging.SingleEmailMessage message = Util.createContactEmail(templateId, facility.Point_of_Contact__c, facility.Id, true, orgWide.Id);
        Test.stopTest();
        System.assertEquals(templateId, message.getTemplateId());
        System.assertEquals(facility.Point_of_Contact__c, message.getTargetObjectId());
        System.assertEquals(facility.Id, message.getWhatId());
        System.assertEquals(orgWide.Id, message.getOrgWideEmailAddressId());
    }

    private static final String
        EMAIL_TEMPLATE_DEVELOPER_NAME = 'Test_Email_Template',
        EMAIL_TEMPLATE_NAME = 'Test Email Template',
        EMAIL_TEMPLATE_TYPE = 'Text',
        VALID_ORG_WIDE_EMAIL = 'FIR Sheltering',
        INVALID_ORG_WIDE_EMAIL = 'Test';
}