force-app/main/default/objects/Behavior_Evaluation__c/Behavior_Evaluation__c.object-meta.xml
<CustomObject>
    <label>Behavior Evaluation</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>Behavior Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior Evaluations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Behavior_Evaluation__c/fields/Behavior_Evaluation_Summary__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Evaluation_Summary__c</fullName>
    <label>Behavior Evaluation Summary</label>
    <length>7232</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation_Summary__c/Behavior_Evaluation_Summary__c.object-meta.xml
<CustomObject>
    <label>Behavior Evaluation Summary</label>
    <nameField>
        <displayFormat>BES-{0000}</displayFormat>
        <label>Behavior Evaluation Summary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Behavior Evaluation Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Behavior_Evaluation_Summary__c/fields/Behavior_Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Behavior_Evaluation__c</fullName>
    <label>Behavior Evaluation</label>
    <referenceTo>Behavior_Evaluation__c</referenceTo>
    <relationshipLabel>Behavior Evaluation Summaries</relationshipLabel>
    <relationshipName>Behavior_Evaluation_Summaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation_Summary__c/fields/ConfigId__c.field-meta.xml
<CustomField>
    <fullName>ConfigId__c</fullName>
    <label>ConfigId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation_Summary__c/fields/Skip_Reason__c.field-meta.xml
<CustomField>
    <fullName>Skip_Reason__c</fullName>
    <label>Skip Reason</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation_Summary__c/fields/Summary_Comments__c.field-meta.xml
<CustomField>
    <fullName>Summary_Comments__c</fullName>
    <label>Summary Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation_Summary__c/fields/Test_Comments__c.field-meta.xml
<CustomField>
    <fullName>Test_Comments__c</fullName>
    <label>Test Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Behavior_Evaluation_Summary__c/fields/Test_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Name__c</fullName>
    <label>Test Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Description_Config__mdt/Picklist_Description_Config__mdt.object-meta.xml
<CustomObject>
    <label>Picklist Description Config</label>
    <pluralLabel>Picklist Description Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Picklist_Description_Config__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Behavior_in_Kennel__c</fullName>
            </value>
            <value>
                <fullName>Behavior_on_Leash__c</fullName>
            </value>
            <value>
                <fullName>Social_Behavior_P1__c</fullName>
            </value>
            <value>
                <fullName>Social_Behavior_P2_2__c</fullName>
            </value>
            <value>
                <fullName>Pleasant_Touch__c</fullName>
            </value>
            <value>
                <fullName>Unpleasant_Touch_1st__c</fullName>
            </value>
            <value>
                <fullName>Unpleasant_Touch_2nd__c</fullName>
            </value>
            <value>
                <fullName>Play_Test_Tug_P1__c</fullName>
            </value>
            <value>
                <fullName>Play_Test_Tug_P2__c</fullName>
            </value>
            <value>
                <fullName>Tag_Test__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P1_Push_Face__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P2_Push_Face__c</fullName>
            </value>
            <value>
                <fullName>Toddler_Doll_P1__c</fullName>
            </value>
            <value>
                <fullName>Toddler_Doll_P2__c</fullName>
            </value>
            <value>
                <fullName>Scolding_Person_P1__c</fullName>
            </value>
            <value>
                <fullName>Scolding_Person_P2__c</fullName>
            </value>
            <value>
                <fullName>Fake_Dog__c</fullName>
            </value>
            <value>
                <fullName>Same_Sex_P1__c</fullName>
            </value>
            <value>
                <fullName>Same_Sex_P2__c</fullName>
            </value>
            <value>
                <fullName>Same_Sex_P3__c</fullName>
            </value>
            <value>
                <fullName>Opposite_Sex_P1__c</fullName>
            </value>
            <value>
                <fullName>Opposite_Sex_P2__c</fullName>
            </value>
            <value>
                <fullName>Opposite_Sex_P3__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P1_Touch_Face__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P1_Touch_Neck__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P1_Touch_Body__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P2_Touch_Face__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P2_Touch_Neck__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P2_Touch_Body__c</fullName>
            </value>
            <value>
                <fullName>Puppy_Behavior_in_Kennel__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Picklist_Description_Config__mdt/fields/Field_Description__c.field-meta.xml
<CustomField>
    <fullName>Field_Description__c</fullName>
    <description>Descriptive text for Field</description>
    <label>Field Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Description_Config__mdt/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <label>Field Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Description_Config__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Description_Config__mdt/fields/Picklist_Order__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Order__c</fullName>
    <label>Picklist Display Order</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Description_Config__mdt/fields/Test_Config__c.field-meta.xml
<CustomField>
    <fullName>Test_Config__c</fullName>
    <label>Parent Test Config</label>
    <referenceTo>Test_Config__mdt</referenceTo>
    <relationshipLabel>Picklist Description Configs</relationshipLabel>
    <relationshipName>Picklist_Description_Configs</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Picklist_Description_Config__mdt/fields/Value_Category__c.field-meta.xml
<CustomField>
    <fullName>Value_Category__c</fullName>
    <description>Category of Picklist Value. 1= Not Concerning, 2 = Red Flag, 3 = Alert, 4 = Skipped/Inconclusive</description>
    <inlineHelpText>1= Not Concerning, 2 = Red Flag, 3 = Alert, 4 = Skipped/Inconclusive</inlineHelpText>
    <label>Value Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Config__mdt/Test_Config__mdt.object-meta.xml
<CustomObject>
    <label>Test Config</label>
    <pluralLabel>Test Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Test_Config__mdt/fields/Test_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Name__c</fullName>
    <label>Test Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BehaviorEvaluationLWCController.cls
public with sharing class BehaviorEvaluationLWCController {
    @AuraEnabled (cacheable=true)
    public static EvalSummaryInfo getEvalTests(Id evalId) {
        try {
            EvalSummaryInfo info = new EvalSummaryInfo();
            info.eval = [
                SELECT Id
                FROM Behavior_Evaluation__c
                WHERE Id = :evalId
                LIMIT 1
            ];
            Behavior_Evaluation_Summary__c[] testList = [
                SELECT Id, ConfigId__c, Skip_Reason__c, Summary_Comments__c, Test_Comments__c, Test_Name__c
                FROM Behavior_Evaluation_Summary__c
                WHERE Behavior_Evaluation__c = : evalId
                AND Display_Order__c > 0
                AND ConfigId__c != null
                ORDER BY Display_Order__c ASC
                LIMIT 4
            ];
            info.tabList = new TabInfo[0];
            for(Behavior_Evaluation_Summary__c summary : testList){
                TabInfo tab = new TabInfo();
                tab.iconName = 'utility:warning';
                tab.status = 'warning';
                tab.id = summary.Id;
                tab.label = summary.Test_Name__c;
                tab.testSummary = summary;
                info.tabList.add(tab);

            }
            return info;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled (cacheable=true)
    public static EvalConfig getEvalConfig(Id recordId){
        try {
            EvalConfig configInfo = new EvalConfig();
            configInfo.testConfig = Test_Config__mdt.getInstance(recordId);
            configInfo.pdListOfLists = prepPicklistDescriptions(recordId);
            
            System.debug('configInfo.testConfig: ' + configINfo.testConfig.DeveloperName);
            // System.debug('picklistDescriptions: ' + picklistDescriptions);
            return configInfo;
        } catch (Exception e) {
            System.debug('Error: ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static List<Picklist_Description_Config__mdt[]> prepPicklistDescriptions(Id recordId){
        Picklist_Description_Config__mdt[] picklistDescriptions = [
            SELECT Id, DeveloperName, MasterLabel, Field_API_Name__c, Field_Description__c, Field_Value__c, Object_API_Name__c, Picklist_Order__c, Value_Category__c, Test_Config__c
            FROM Picklist_Description_Config__mdt
            WHERE Test_Config__c = :recordId
            ORDER BY Value_Category__c ASC, Picklist_Order__c ASC
        ];

        Map<String, Picklist_Description_Config__mdt[]> pdMap = new Map<String, Picklist_Description_Config__mdt[]>();

        for(Picklist_Description_Config__mdt pd : picklistDescriptions){
            if(pdMap.containsKey(pd.Value_Category__c)){
                pdMap.get(pd.Value_Category__c).add(pd);
            } else {
                pdMap.put(pd.Value_Category__c, new Picklist_Description_Config__mdt[]{pd});
            }
        }

        List<Picklist_Description_Config__mdt[]> pdListOfLists = new List<Picklist_Description_Config__mdt[]>();
        for(String i : pdMap.keySet()){
            pdListOfLists.add(pdMap.get(i));
        }
        return pdListOfLists;
    }

    public class EvalConfig {
        @AuraEnabled public Test_Config__mdt testConfig;
        @AuraEnabled public List<Picklist_Description_Config__mdt[]> pdListOfLists;

    }

    // public class PicklistDescriptions{
    //     @AuraEnabled public Test_Config__mdt testConfig;
    // }

    public class EvalSummaryInfo{
        @AuraEnabled public Behavior_Evaluation__c eval;
        @AuraEnabled public TabInfo[] tabList;
    }

    public class TabInfo{
        @AuraEnabled public String iconName;
        @AuraEnabled public String status;
        @AuraEnabled public String label;
        @AuraEnabled public String id;
        @AuraEnabled public Behavior_Evaluation_Summary__c testSummary;
    }
}