force-app/main/default/objects/Bundle_Entry__c/Bundle_Entry__c.object-meta.xml
<CustomObject>
    <label>Bundle Entry</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Bundle Entries Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle_Entry__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Bundle Entries</relationshipLabel>
    <relationshipName>Bundle_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/Plan_Protocol__c.object-meta.xml
<CustomObject>
    <label>Plan Protocol</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Plan Protocol Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Protocol__c/fields/Bundle_Entry__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Entry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bundle Entry</label>
    <referenceTo>Bundle_Entry__c</referenceTo>
    <relationshipLabel>Plan Protocols</relationshipLabel>
    <relationshipName>Plan_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/fields/IsRemoved__c.field-meta.xml
<CustomField>
    <fullName>IsRemoved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to Remove value from Treatment Plan</description>
    <label>Removed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Plan Protocols</relationshipLabel>
    <relationshipName>Plan_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/fields/Treatment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treatment Plan</label>
    <referenceTo>Treatment_Plan__c</referenceTo>
    <relationshipLabel>Plan Protocols</relationshipLabel>
    <relationshipName>Plan_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Protocol_Scale__c/Protocol_Scale__c.object-meta.xml
<CustomObject>
    <label>Protocol Scale</label>
    <nameField>
        <label>Protocol Scale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocol Scales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Protocol_Scale_Junction__c/Protocol_Scale_Junction__c.object-meta.xml
<CustomObject>
    <label>Protocol Scale Junction</label>
    <nameField>
        <displayFormat>PSJN-{00000}</displayFormat>
        <label>Protocol Scale Junction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Protocol Scale Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Protocol_Scale_Junction__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Protocol Scale Junctions</relationshipLabel>
    <relationshipName>Protocol_Scale_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Protocol_Scale_Junction__c/fields/Protocol_Scale__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Scale__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol Scale</label>
    <referenceTo>Protocol_Scale__c</referenceTo>
    <relationshipLabel>Protocol Scale Junctions</relationshipLabel>
    <relationshipName>Protocol_Scale_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProtocolSelector.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class ProtocolSelector extends SObjectSelector{
    public ProtocolSelector() {
        super(Protocol__c.SObjectType);
    }
    public override Set<SObjectField> GetDefaultFields() {
        return new Set<SObjectField> {
                Protocol__c.Name,
                Protocol__c.CreatedById ,
                Protocol__c.CreatedDate ,
                Protocol__c.Description__c ,
                Protocol__c.LastModifiedById ,
                Protocol__c.Id ,
                Protocol__c.IsActive__c
        };
    }

    public override List<iOrderBy> GetDefaultOrderBy() {
        return new List<iOrderBy> {
                OrderBy.Ascending(Product2.Name) ,
                OrderBy.Ascending(Product2.Id)
        };
    }

    public List<Protocol__c> GetById(Set<Id> ids) {
        return queryById(ids);
    }

    public List<Protocol__c> GetByName(String name) {
        return queryByName(name);
    }

    //dont think this is being used
    // public List<Protocol__c> GetByExternalId(String key) {
    //     List<Protocol__c> lineItems = GetQueryFactory().WithCriteria(Criteria.Equals(Product2.ExternalId, key)).Execute();
    //     return lineItems;
    // }

    public Protocol__c[] getByPlan(Id planId) {
        return [
            SELECT 
                Id,
                (SELECT Id, Protocol_Scale__c, Protocol__c, Protocol_Scale__r.Required__c FROM Protocol_Scale_Junctions__r WHERE Protocol_Scale__r.isActive__c = true),
                (SELECT Id, Bundle_Entry__c, IsRemoved__c FROM Plan_Protocols__r WHERE Treatment_Plan__c = :planId)
            FROM Protocol__c
            WHERE Id IN (SELECT Protocol__c FROM Plan_Protocol__c  WHERE Treatment_Plan__c = :planId)
        ];
    }
    
    public Protocol__c[] getProtocolWithChildProtocolScaleJunctionByIds(Set<Id> protocolIds) {
        return [
            SELECT 
                Id,
                (SELECT Id, Protocol_Scale__c, Protocol__c, Protocol_Scale__r.Required__c FROM Protocol_Scale_Junctions__r WHERE Protocol_Scale__r.isActive__c = true)
            FROM Protocol__c
            WHERE Id IN  :protocolIds
        ];
    }

}