force-app/main/default/objects/Bundle_Entry__c/Bundle_Entry__c.object-meta.xml
<CustomObject>
    <label>Bundle Entry</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Bundle Entries Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/Session_Protocol__c.object-meta.xml
<CustomObject>
    <label>Session Protocol</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Session Protocol Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocols</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/fields/Add_to_Plan__c.field-meta.xml
<CustomField>
    <fullName>Add_to_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add to Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Aggressive_Worst__c.field-meta.xml
<CustomField>
    <fullName>Aggressive_Worst__c</fullName>
    <label>Aggressive - Worst</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. None Observed</fullName>
            </value>
            <value>
                <fullName>2. Hard stare, whale eye, rigid, freezes</fullName>
            </value>
            <value>
                <fullName>3. Head whips, lifts lip, growls or alarm barks</fullName>
            </value>
            <value>
                <fullName>4. Air snaps or muzzle punches</fullName>
            </value>
            <value>
                <fullName>5. Tries to bite or bites</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Arousal_Best__c.field-meta.xml
<CustomField>
    <fullName>Arousal_Best__c</fullName>
    <label>Arousal - Best</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Low/Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mild</fullName>
            </value>
            <value>
                <fullName>3. Moderate</fullName>
            </value>
            <value>
                <fullName>4. Extreme</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Arousal_Worst__c.field-meta.xml
<CustomField>
    <fullName>Arousal_Worst__c</fullName>
    <label>Arousal - Worst</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Low/Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mild</fullName>
            </value>
            <value>
                <fullName>3. Moderate</fullName>
            </value>
            <value>
                <fullName>4. Extreme</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Bundle_Entry__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Entry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bundle Entry</label>
    <referenceTo>Bundle_Entry__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Fear_Best__c.field-meta.xml
<CustomField>
    <fullName>Fear_Best__c</fullName>
    <label>Fear - Best</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>1. Excited, playful, interested</fullName>
            </value>
            <value>
                <fullName>2. Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mildly fearful</fullName>
            </value>
            <value>
                <fullName>3. Moderately fearful</fullName>
            </value>
            <value>
                <fullName>4. Extremely fearful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Fear_Worst__c.field-meta.xml
<CustomField>
    <fullName>Fear_Worst__c</fullName>
    <label>Fear - Worst</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>1. Excited, playful, interested</fullName>
            </value>
            <value>
                <fullName>2. Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mildly fearful</fullName>
            </value>
            <value>
                <fullName>3. Moderately fearful</fullName>
            </value>
            <value>
                <fullName>4. Extremely fearful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/IsRemoved__c.field-meta.xml
<CustomField>
    <fullName>IsRemoved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Removed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/IsSkipped__c.field-meta.xml
<CustomField>
    <fullName>IsSkipped__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Protocol</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Novel_Person__c.field-meta.xml
<CustomField>
    <fullName>Novel_Person__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Novel Person</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Novel_Person_Notes__c.field-meta.xml
<CustomField>
    <fullName>Novel_Person_Notes__c</fullName>
    <label>Novel Person Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Overall_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score__c</fullName>
    <label>Overall Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Beginning/Acquisition</fullName>
            </value>
            <value>
                <fullName>2. Catching On/ Fluency</fullName>
            </value>
            <value>
                <fullName>3. Almost There/ Generalization</fullName>
            </value>
            <value>
                <fullName>4. Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Protocol_Notes__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Notes__c</fullName>
    <label>Protocol Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/ProtocolId__c.field-meta.xml
<CustomField>
    <fullName>ProtocolId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Social_Best__c.field-meta.xml
<CustomField>
    <fullName>Social_Best__c</fullName>
    <label>Fear - Sociability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Solicitation, sustained proximity</fullName>
            </value>
            <value>
                <fullName>2. Solicitation, short proximity</fullName>
            </value>
            <value>
                <fullName>3. Solicitation, no proximity</fullName>
            </value>
            <value>
                <fullName>4. No Solicitation, sustained proxmity</fullName>
            </value>
            <value>
                <fullName>5. No Solicitation, short proximity</fullName>
            </value>
            <value>
                <fullName>6. No Solicitation, no proximity</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/TreatmentSessionId__c.field-meta.xml
<CustomField>
    <fullName>TreatmentSessionId__c</fullName>
    <label>Treatment Session</label>
    <referenceTo>Treatment_Session__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SObjectSelectors/SessionProtocolSelector.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class SessionProtocolSelector extends SObjectSelector {
    public SessionProtocolSelector() {
        super(Session_Protocol__c.SObjectType);
    }

    public override Set<SObjectField> GetDefaultFields() {
        return new Set<SObjectField> {
                Session_Protocol__c.Id,
                Session_Protocol__c.Bundle_Entry__c,
                Session_Protocol__c.CreatedById,
                Session_Protocol__c.CreatedDate,
                Session_Protocol__c.LastModifiedById,
                Session_Protocol__c.LastModifiedDate,
                Session_Protocol__c.Fear_Best__c,
                Session_Protocol__c.Fear_Worst__c,
                Session_Protocol__c.Aggressive_Worst__c,
                Session_Protocol__c.Arousal_Best__c,
                Session_Protocol__c.Arousal_Worst__c,
                Session_Protocol__c.Social_Best__c,
                Session_Protocol__c.Overall_Score__c,
                Session_Protocol__c.Novel_Person_Notes__c,
                Session_Protocol__c.Novel_Person__c,
                Session_Protocol__c.Protocol_Notes__c,
                Session_Protocol__c.Protocol_Box_Link__c,
                Session_Protocol__c.IsSkipped__c,
                Session_Protocol__c.IsRemoved__c,
                Session_Protocol__c.IsDeleted ,
                Session_Protocol__c.ProtocolId__c ,
                Session_Protocol__c.TreatmentSessionId__c ,
                Session_Protocol__c.Add_to_Plan__c
        };
    }
    public override List<iOrderBy> GetDefaultOrderBy() {
        return new List<iOrderBy> {
                OrderBy.Ascending(Session_Protocol__c.Name) ,
                OrderBy.Ascending(Session_Protocol__c.Id)
        };
    }

    public List<Session_Protocol__c> GetByIds(Set<Id> ids) {
        return queryById(ids);
    }

    public List<Session_Protocol__c> GetByQuote(Id key) {
        List<Session_Protocol__c> lineItems = GetQueryFactory().WithCriteria(Criteria.Equals(Session_Protocol__c.TreatmentSessionId__c,
                key))
                .Execute();
        return lineItems;
    }

}