force-app/main/default/objects/Bundle_Entry__c/Bundle_Entry__c.object-meta.xml
<CustomObject>
    <label>Bundle Entry</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Bundle Entries Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bundle Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle_Entry__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Bundle Entries</relationshipLabel>
    <relationshipName>Bundle_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bundle_Entry__c/fields/Treatment_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Bundle__c</fullName>
    <label>Treatment Bundle</label>
    <referenceTo>Treatment_Bundle__c</referenceTo>
    <relationshipLabel>Bundle Entries</relationshipLabel>
    <relationshipName>Bundle_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Bundle__c/Treatment_Bundle__c.object-meta.xml
<CustomObject>
    <label>Treatment Bundle</label>
    <nameField>
        <label>Treatment Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Treatment Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/AssignedTreatmentBundleId__c.field-meta.xml
<CustomField>
    <fullName>AssignedTreatmentBundleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Treatment Bundle</label>
    <referenceTo>Treatment_Bundle__c</referenceTo>
    <relationshipLabel>Treatment Plans (Assigned Treatment Bundle)</relationshipLabel>
    <relationshipName>Assigned_Treatment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/MasterTreatmentBundleId__c.field-meta.xml
<CustomField>
    <fullName>MasterTreatmentBundleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Treatment Bundle</label>
    <referenceTo>Treatment_Bundle__c</referenceTo>
    <relationshipLabel>Treatment Plans</relationshipLabel>
    <relationshipName>Treatment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Preferred_Motivators__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Motivators__c</fullName>
    <label>Preferred Motivators</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/fields/Treatment_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Treatment_Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Treatment Bundle</label>
    <referenceTo>Treatment_Bundle__c</referenceTo>
    <relationshipLabel>Treatment Plans (Assigned Treatment Bundle)</relationshipLabel>
    <relationshipName>Assigned_Treatment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/test/test_TreatmentPlanService.cls
/**
 * Created by CloudQnect on 9/20/2021.
 */

@IsTest
private class test_TreatmentPlanService {
    @IsTest
    static void treatmentPlanRegressionTest() {

        Treatment_Bundle__c master = TestDataFactory.createMasterBundle();
        Treatment_Bundle__c bundle = TestDataFactory.createTreatmentBundle();
        Treatment_Bundle__c bundleTwo = TestDataFactory.createTreatmentBundle();
        bundleTwo.Name = 'Bundle Two';
        update bundleTwo;

        List<Protocol__c> protocols = TestDataFactory.createProtocols(5);
        List<Protocol__c> protocolsTwo = TestDataFactory.createProtocols(8);

        List<Bundle_Entry__c> masterEntries = TestDataFactory.assignEntries(master, protocols);
        List<Bundle_Entry__c> masterEntriesTwo = TestDataFactory.assignEntries(master, protocolsTwo);

        List<Bundle_Entry__c> bundleEntries = TestDataFactory.assignEntries(bundle, protocols);
        List<Bundle_Entry__c> bundleTwoEntries = TestDataFactory.assignEntries(bundleTwo, protocolsTwo);

        Treatment_Plan__c plan = new Treatment_Plan__c();
        plan.MasterTreatmentBundleId__c = master.Id;
        insert plan;

        plan.Preferred_Motivators__c = 'Test';
        plan.AssignedTreatmentBundleId__c = bundle.Id;
        update plan;

        plan.AssignedTreatmentBundleId__c = bundleTwo.Id;
        update plan;

    }

    @IsTest
    static void assignNewBundleTest() {
        Treatment_Bundle__c master = TestDataFactory.createMasterBundle();
        Treatment_Bundle__c bundle = TestDataFactory.createTreatmentBundle();
        Treatment_Bundle__c bundleTwo = TestDataFactory.createTreatmentBundle();
        bundleTwo.Name = 'Bundle Two';
        update bundleTwo;

        List<Protocol__c> protocols = TestDataFactory.createProtocols(5);
        List<Protocol__c> protocolsTwo = TestDataFactory.createProtocols(8);

        List<Bundle_Entry__c> masterEntries = TestDataFactory.assignEntries(master, protocols);
        List<Bundle_Entry__c> masterEntriesTwo = TestDataFactory.assignEntries(master, protocolsTwo);

        List<Bundle_Entry__c> bundleEntries = TestDataFactory.assignEntries(bundle, protocols);
        List<Bundle_Entry__c> bundleTwoEntries = TestDataFactory.assignEntries(bundleTwo, protocolsTwo);

        Treatment_Plan__c plan = new Treatment_Plan__c();
        plan.MasterTreatmentBundleId__c = master.Id;
        insert plan;

        plan.Preferred_Motivators__c = 'Test';
        plan.AssignedTreatmentBundleId__c = bundle.Id;
        update plan;
    }

    @IsTest
    static void bundleReassignmentTest() {
        Treatment_Bundle__c master = TestDataFactory.createMasterBundle();
        Treatment_Bundle__c bundle = TestDataFactory.createTreatmentBundle();
        Treatment_Bundle__c bundleTwo = TestDataFactory.createTreatmentBundle();
        bundleTwo.Name = 'Bundle Two';
        update bundleTwo;

        List<Protocol__c> protocols = TestDataFactory.createProtocols(5);
        List<Protocol__c> protocolsTwo = TestDataFactory.createProtocols(8);

        List<Bundle_Entry__c> masterEntries = TestDataFactory.assignEntries(master, protocols);
        List<Bundle_Entry__c> masterEntriesTwo = TestDataFactory.assignEntries(master, protocolsTwo);

        List<Bundle_Entry__c> bundleEntries = TestDataFactory.assignEntries(bundle, protocols);
        List<Bundle_Entry__c> bundleTwoEntries = TestDataFactory.assignEntries(bundleTwo, protocolsTwo);

        Treatment_Plan__c plan = new Treatment_Plan__c();
        plan.MasterTreatmentBundleId__c = master.Id;
        insert plan;

        plan.Preferred_Motivators__c = 'Test';
        plan.AssignedTreatmentBundleId__c = bundle.Id;
        update plan;
        plan.AssignedTreatmentBundleId__c = bundleTwo.Id;
        update plan;

    }
}