force-app/main/default/objects/Animal_Location_Config__mdt.object
<CustomObject>
    <description>Used by locationFilter LWC to determine which locations to expose to the user for selection</description>
    <label>Animal Location Config</label>
    <pluralLabel>Animal Location Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Animal_Location_Config__mdt/fields/Animal_Locations__c.field-meta.xml
<CustomField>
    <fullName>Animal_Locations__c</fullName>
    <description>comma separated list of animal locations (Current_Location__c)</description>
    <label>Animal Locations</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Location_Config__mdt/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <description>The type of application the locationFilter component was added to, i.e. ToDoList, ActiveAnimal</description>
    <label>Application Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Location_Config__mdt/fields/User_Location__c.field-meta.xml
<CustomField>
    <fullName>User_Location__c</fullName>
    <inlineHelpText>This will determine which list of animal locations is returned based on the users Location__c field</inlineHelpText>
    <label>User Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ARC/CARE</fullName>
                <default>true</default>
                <label>ARC/CARE</label>
            </value>
            <value>
                <fullName>CRC/MRC</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ARC/CARE</fullName>
            </value>
            <value>
                <fullName>MRC</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LocationFilterController.cls
public with sharing class LocationFilterController {
    @AuraEnabled(cacheable=true)
    public static List<Map<String, Object>> getAnimalLocations(String applicationType){
        try {
            Animal_Location_Config__mdt locConfig = new Animal_Location_Config__mdt();
            User u = [SELECT Id, Location__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
            if(u.Location__c != null){
                locConfig = [
                    SELECT Id, Animal_Locations__c 
                    FROM Animal_Location_Config__mdt 
                    WHERE User_Location__c = :u.Location__c
                    AND Application_Type__c = :applicationType
                ];
            }
            System.debug('locConfig: ' + locConfig);
            String locations = locConfig != null && locConfig.Animal_Locations__c != null ? '{"locs":' + locConfig.Animal_Locations__c + '}' : null;

            Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(locations);
            System.debug('m: ' + m);

            List<Map<String, Object>> myMaps = new List<Map<String, Object>>();
            List<Object> myMapObjects = (List<Object>) m.get('locs');
            for (Object obj : myMapObjects) {
                myMaps.add((Map<String, Object>)obj);
            }
            System.debug('myMaps: ' + myMaps);

            // System.debug('locations: ' + locations);
            return myMaps;
        } catch (Exception e) {
            System.debug('e.stacktrace: '+ e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }
}