force-app/main/default/objects/Additional_Dog_Present__c/Additional_Dog_Present__c.object-meta.xml
<CustomObject>
    <label>Additional Dog Present</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Additional Dog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Dogs Present</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Dog_Present__c/fields/Session_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Session_Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Protocol</label>
    <referenceTo>Session_Protocol__c</referenceTo>
    <relationshipLabel>Additional Dogs Present</relationshipLabel>
    <relationshipName>Additional_Dogs_Present</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/Plan_Protocol__c.object-meta.xml
<CustomObject>
    <label>Plan Protocol</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Plan Protocol Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Protocol__c/fields/IsRemoved__c.field-meta.xml
<CustomField>
    <fullName>IsRemoved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to Remove value from Treatment Plan</description>
    <label>Removed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Plan Protocols</relationshipLabel>
    <relationshipName>Plan_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/fields/Protocol_Box_Link__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Box_Link__c</fullName>
    <label>Protocol Box Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/fields/Protocol_Name__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Name__c</fullName>
    <formula>Protocol__r.Name</formula>
    <label>Protocol Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan_Protocol__c/fields/Protocol_Notes__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Notes__c</fullName>
    <label>Protocol Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Protocol__c/fields/Protocol_Box_Link__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Box_Link__c</fullName>
    <label>Protocol Box Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/Session_Protocol__c.object-meta.xml
<CustomObject>
    <label>Session Protocol</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Session Protocol Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocols</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol__c/fields/Aggressive_Worst__c.field-meta.xml
<CustomField>
    <fullName>Aggressive_Worst__c</fullName>
    <label>Aggressive - Worst</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. None Observed</fullName>
            </value>
            <value>
                <fullName>2. Hard stare, whale eye, rigid, freezes</fullName>
            </value>
            <value>
                <fullName>3. Head whips, lifts lip, growls or alarm barks</fullName>
            </value>
            <value>
                <fullName>4. Air snaps or muzzle punches</fullName>
            </value>
            <value>
                <fullName>5. Tries to bite or bites</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Arousal_Best__c.field-meta.xml
<CustomField>
    <fullName>Arousal_Best__c</fullName>
    <label>Arousal - Best</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Low/Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mild</fullName>
            </value>
            <value>
                <fullName>3. Moderate</fullName>
            </value>
            <value>
                <fullName>4. Extreme</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Arousal_Worst__c.field-meta.xml
<CustomField>
    <fullName>Arousal_Worst__c</fullName>
    <label>Arousal - Worst</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Low/Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mild</fullName>
            </value>
            <value>
                <fullName>3. Moderate</fullName>
            </value>
            <value>
                <fullName>4. Extreme</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Fear_Best__c.field-meta.xml
<CustomField>
    <fullName>Fear_Best__c</fullName>
    <label>Fear - Best</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>1. Excited, playful, interested</fullName>
            </value>
            <value>
                <fullName>2. Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mildly fearful</fullName>
            </value>
            <value>
                <fullName>3. Moderately fearful</fullName>
            </value>
            <value>
                <fullName>4. Extremely fearful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Fear_Worst__c.field-meta.xml
<CustomField>
    <fullName>Fear_Worst__c</fullName>
    <label>Fear - Worst</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>1. Excited, playful, interested</fullName>
            </value>
            <value>
                <fullName>2. Neutral</fullName>
            </value>
            <value>
                <fullName>2. Mildly fearful</fullName>
            </value>
            <value>
                <fullName>3. Moderately fearful</fullName>
            </value>
            <value>
                <fullName>4. Extremely fearful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/IsRemoved__c.field-meta.xml
<CustomField>
    <fullName>IsRemoved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Removed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/IsSkipped__c.field-meta.xml
<CustomField>
    <fullName>IsSkipped__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Protocol</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Manager_Review_Notes__c.field-meta.xml
<CustomField>
    <fullName>Manager_Review_Notes__c</fullName>
    <label>Manager Review Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Needs_Review__c.field-meta.xml
<CustomField>
    <fullName>Needs_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marks a Session Protocol as in Need of Review</description>
    <label>Needs Review</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Novel_Person_Notes__c.field-meta.xml
<CustomField>
    <fullName>Novel_Person_Notes__c</fullName>
    <label>Novel Person Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Overall_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score__c</fullName>
    <label>Overall Score</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Beginning/Acquisition</fullName>
            </value>
            <value>
                <fullName>2. Catching On/ Fluency</fullName>
            </value>
            <value>
                <fullName>3. Almost There/ Generalization</fullName>
            </value>
            <value>
                <fullName>4. Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Preferred_Motivators__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Motivators__c</fullName>
    <label>Preferred Motivators</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Protocol_Name__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Name__c</fullName>
    <formula>ProtocolId__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Protocol Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Protocol_Notes__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Notes__c</fullName>
    <label>Protocol Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/ProtocolId__c.field-meta.xml
<CustomField>
    <fullName>ProtocolId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/Social_Best__c.field-meta.xml
<CustomField>
    <fullName>Social_Best__c</fullName>
    <label>Fear - Sociability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. Solicitation, sustained proximity</fullName>
            </value>
            <value>
                <fullName>2. Solicitation, short proximity</fullName>
            </value>
            <value>
                <fullName>3. Solicitation, no proximity</fullName>
            </value>
            <value>
                <fullName>4. No Solicitation, sustained proxmity</fullName>
            </value>
            <value>
                <fullName>5. No Solicitation, short proximity</fullName>
            </value>
            <value>
                <fullName>6. No Solicitation, no proximity</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Protocol__c/fields/TreatmentSessionId__c.field-meta.xml
<CustomField>
    <fullName>TreatmentSessionId__c</fullName>
    <label>Treatment Session</label>
    <referenceTo>Treatment_Session__c</referenceTo>
    <relationshipLabel>Session Protocols</relationshipLabel>
    <relationshipName>Session_Protocols</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Protocol_Contact__c/Session_Protocol_Contact__c.object-meta.xml
<CustomObject>
    <label>Session Protocol Contact</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Protocol Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Protocol Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Protocol_Contact__c/fields/Session_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Session_Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Protocol</label>
    <referenceTo>Session_Protocol__c</referenceTo>
    <relationshipLabel>Session Protocol Contacts</relationshipLabel>
    <relationshipName>Session_Protocol_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treatment_Plan__c/Treatment_Plan__c.object-meta.xml
<CustomObject>
    <label>Treatment Plan</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Treatment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Plan__c/fields/Preferred_Motivators__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Motivators__c</fullName>
    <label>Preferred Motivators</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Treatment_Session__c/Treatment_Session__c.object-meta.xml
<CustomObject>
    <label>Treatment Session</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Treatment Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Treatment_Session__c/fields/Preferred_Motivators__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Motivators__c</fullName>
    <label>Preferred Motivators</label>
    <length>2768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TreatmentSessionLWCController.cls
public with sharing class TreatmentSessionLWCController {
    @AuraEnabled (cacheable=true)
    public static Session_Protocol__c[] getActiveProtocols(Id sessionId){
        try {
            return [
                SELECT 
                    Id, 
                    ProtocolId__r.Name,
                    Aggressive_Worst__c,
                    Arousal_Best__c,
                    Arousal_Worst__c,
                    Fear_Best__c,
                    Fear_Worst__c,
                    IsSkipped__c,
                    Social_Best__c,
                    Overall_Score__c,
                    Needs_Review__c,
                    Protocol_Name__c
                FROM Session_Protocol__c 
                WHERE TreatmentSessionId__c =: sessionId
                ORDER BY Protocol_Name__c ASC
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @testVisible
    private static Session_Protocol__c getProtocol(Id protocolId){
        if(protocolId == null) return null;
        return [
            SELECT 
                Id, 
                ProtocolId__r.Name,
                Aggressive_Worst__c,
                Arousal_Best__c,
                Arousal_Worst__c,
                Fear_Best__c,
                Fear_Worst__c,
                IsSkipped__c,
                IsRemoved__c,
                Social_Best__c,
                Overall_Score__c,
                Needs_Review__c,
                Protocol_Name__c,
                Protocol_Notes__c,
                Novel_Person_Notes__c,
                Manager_Review_Notes__c,
                Preferred_Motivators__c,
                ProtocolId__r.Protocol_Box_Link__c
            FROM Session_Protocol__c 
            WHERE Id =: protocolId
        ];
    }

    @AuraEnabled
    public static Session_Protocol__c getProtocolSkippedInfo(Id protocolId){
        Session_Protocol__c[] protocols = [SELECT Id, IsSkipped__c, IsRemoved__c, Add_to_Plan__c FROM Session_Protocol__c WHERE Id =: protocolId LIMIT 1];
        return !protocols.isEmpty() ? protocols[0] : null;
    }

    private static Session_Protocol__c[] getAssignedSessionProtocols(Id sessionId){
        if(sessionId == null) return null;
        return [SELECT Id, ProtocolId__c, Protocol_Name__c, IsSkipped__c, IsRemoved__c FROM Session_Protocol__c WHERE TreatmentSessionId__c =: sessionId ORDER BY Protocol_Name__c ASC];
    }

    @AuraEnabled (cacheable=true)
    public static sObject[] getChildList(Id protocolId, String objectApi){
        if(protocolId == null || objectApi == null) return null;
        try {
            sObject[] childList = new sObject[0];
            if(objectApi == 'Session_Protocol_Contact__c'){
                childList = getProtocolContacts(protocolId);
            }
            else if(objectApi == 'Additional_Dog_Present__c'){
                childList = getDogsPresent(protocolId);
            }
            return childList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Session_Protocol_Contact__c[] getProtocolContacts(Id protocolId){
        return [SELECT Id, Contact__c, Contact__r.Name, Novel_Not_Novel__c FROM Session_Protocol_Contact__c WHERE Session_Protocol__c =: protocolId];
    }

    @AuraEnabled
    public static Additional_Dog_Present__c[] getDogsPresent(Id protocolId){
        return [SELECT Id, Additional_Dog__c FROM Additional_Dog_Present__c WHERE Session_Protocol__c =: protocolId];
    }

    @AuraEnabled
    public static protocolInfo getActiveProtocolAndFields(Id protocolId){
        if(protocolId == null) return null;
        try {
            Session_Protocol__c sessionProtocol = getProtocol(protocolId);
            ProtocolInfo protocolInfo = new ProtocolInfo(sessionProtocol);

            System.debug('protocolInfo = ' + protocolInfo);
            return protocolInfo;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled (cacheable=true)
    public static protocolAssignment getProtocolLists(Id sessionId, Id planId){
        protocolAssignment assignments = new protocolAssignment();   
        if(sessionId != null)     {
            assignments.assignedSessionProtocols = getAssignedSessionProtocols(sessionId);
            assignments.unassignedProtocols = getUnassignedProtocolsFromSessionProtocols(assignments.assignedSessionProtocols);
            assignments.preferredMotivators = getSessionPreferredMotivator(sessionId);
        }
        else if(planId != null){
            assignments.assignedPlanProtocols = getAssignedPlanProtocols(planId);
            assignments.unassignedProtocols = getUnassignedProtocolsFromPlanProtocols(assignments.assignedPlanProtocols);
        }
        
        return assignments;
    }

    private static String getSessionPreferredMotivator(Id sessionId){
        return [SELECT Preferred_Motivators__c FROM Treatment_Session__c WHERE Id =: sessionId LIMIT 1].Preferred_Motivators__c;
    }

    private static Plan_Protocol__c[] getAssignedPlanProtocols(Id planId){
        return [SELECT Id, Protocol__c, Protocol__r.Name, Protocol_Description__c, IsRemoved__c FROM Plan_Protocol__c WHERE Treatment_Plan__c =: planId ORDER BY Protocol__r.Name ASC];
    }

    private static Protocol__c[] getUnassignedProtocolsFromPlanProtocols(Plan_Protocol__c[] assignedProtocols){
        Set<Id> assignedIds = new Set<Id>();
        for(Plan_Protocol__c sp : assignedProtocols){
            assignedIds.add(sp.Protocol__c);
        }
        return getUnassignedProtocols(assignedIds);
    }

    private static Protocol__c[] getUnassignedProtocolsFromSessionProtocols(Session_Protocol__c[] assignedProtocols){
        Set<Id> assignedIds = new Set<Id>();
        for(Session_Protocol__c sp : assignedProtocols){
            assignedIds.add(sp.ProtocolId__c);
        }
        return getUnassignedProtocols(assignedIds);
    }

    private static Protocol__c[] getUnassignedProtocols(Set<Id> protocolIdsToExclude){
        return [SELECT Id, Name FROM Protocol__c WHERE IsActive__c = true AND Id NOT IN :protocolIdsToExclude ORDER BY Name ASC];
    }

    @AuraEnabled
    public static String updateProtocolAssignments(Session_Protocol__c[] protocolsToUpdate, String[] protocolIds, String[] planProtocolIds, String sessionId, String planId){
        try{
            if(sessionId != null){
                update protocolsToUpdate;
                addNewProtocolsToSessionAndPlan(protocolIds, sessionId);
            } 
            else if(planId != null){
                updatePlanProtocols(planProtocolIds);
                addNewProtocolsToPlan(protocolIds, planId);
            }
            return 'success';
        } catch (Exception e){
            return 'Error occured: ' + e.getMessage();
        }
    }

    private static void updatePlanProtocols(String[] planProtocolIds){
        Plan_Protocol__c[] pProtocols = [SELECT Id, IsRemoved__c FROM Plan_Protocol__c WHERE Id IN: planProtocolIds];
        for(Plan_Protocol__c p : pProtocols){
            p.IsRemoved__c = !p.IsRemoved__c;
        }
        update pProtocols;
    }

    private static void addNewProtocolsToPlan(String[] protocolIds, String planId){
        // Treatment_Plan__c tPlan = [SELECT Id, Preferred_Motivators__c FROM Treatment_Plan__c WHERE Id =: planId LIMIT 1];
        Plan_Protocol__c[] newPProtocols = new Plan_Protocol__c[0];

        for(String pId : protocolIds){
            Plan_Protocol__c pp = new Plan_Protocol__c(
                Protocol__c = pId,
                Treatment_Plan__c = planId
            );
            newPProtocols.add(pp);
        }

        insert newPProtocols;
    }

    public static void addNewProtocolsToSessionAndPlan(String[] protocolIds, String sessionId){
        Treatment_Session__c session = [SELECT Id, Preferred_Motivators__c FROM Treatment_Session__c WHERE Id =: sessionId LIMIT 1];
        Session_Protocol__c[] newSProtocols = new Session_Protocol__c[0];

        for(String pId : protocolIds){
            Session_Protocol__c sp = new Session_Protocol__c(
                ProtocolId__c = pId,
                TreatmentSessionId__c = sessionId,
                Add_to_Plan__c = true,
                Preferred_Motivators__c = session.Preferred_Motivators__c,
                Session_Date__c = date.today()
            );
            newSProtocols.add(sp);
        }

        insert newSProtocols;
    }

    public class protocolAssignment {
        @AuraEnabled public Session_Protocol__c[] assignedSessionProtocols { get; set; }
        @AuraEnabled public Plan_Protocol__c[] assignedPlanProtocols { get; set; }
        @AuraEnabled public Protocol__c[] unassignedProtocols { get; set; }
        @AuraEnabled public String preferredMotivators;
    }

    public class ProtocolInfo{
        @AuraEnabled public String id { get; set; }
        @AuraEnabled public String name { get; set; }
        @AuraEnabled public String nameUrl {get; set;}
        @AuraEnabled public Boolean needsReview { get; set; }
        @AuraEnabled public Boolean isSkipped { get; set; }
        @AuraEnabled public Boolean isRemoved { get; set; }
        @AuraEnabled public picklistField[] picklistFields {get; set;}
        @AuraEnabled public String preferredMotivators { get; set; }
        @AuraEnabled public String novelPersonNotes { get; set; }
        @AuraEnabled public String protocolNotes { get; set; }
        @AuraEnabled public String managerReviewNotes { get; set; }
        @AuraEnabled public String boxLink {get; set;}


        ProtocolInfo(Session_Protocol__c sp){
            this.id = sp.Id;
            this.name = sp.Protocol_Name__c;
            this.nameUrl = '/' + sp.Id;
            this.needsReview = sp.Needs_Review__c;
            this.isSkipped = sp.IsSkipped__c;
            this.isRemoved = sp.IsRemoved__c;
            this.picklistFields = new PicklistField[0];
            this.preferredMotivators = sp.Preferred_Motivators__c;
            this.novelPersonNotes = sp.Novel_Person_Notes__c;
            this.protocolNotes = sp.Protocol_Notes__c;
            this.managerReviewNotes = sp.Manager_Review_Notes__c;
            this.boxLink = sp.ProtocolId__r.Protocol_Box_Link__c;

            String[] fieldList = new String[]{
                'Aggressive_Worst__c',
                'Arousal_Best__c',
                'Arousal_Worst__c',
                'Fear_Best__c',
                'Fear_Worst__c',
                'Social_Best__c',
                'Overall_Score__c'
            };

            for(String fieldAPI : fieldList){
                PicklistField pf = new PicklistField(fieldAPI, String.valueOf(sp.get(fieldAPI)));
                this.picklistFields.add(pf);
            }
        }
    }

    public class PicklistField{
        @AuraEnabled public String name { get; set; }
        @AuraEnabled public String apiName { get; set; }
        @AuraEnabled public String currentValue { get; set; }
        @AuraEnabled public String initialValue { get; set; }
        @AuraEnabled public selectionOption[] options { get; set; }

        PicklistField(String fieldAPI, String currentValue){
            this.apiName = fieldAPI;
            String objectAPI = 'Session_Protocol__c';
            this.currentValue = currentValue;
            this.initialValue = currentValue;
            this.name = String.valueOf(Schema.getGlobalDescribe().get(ObjectApi).getDescribe().fields.getMap().get(FieldApi).getDescribe().getLabel());

            Schema.SObjectField fieldInfo = SchemaHelper.DetermineSObjectFieldByLabel(objectAPI, name);            
            String[] picklistValues = SchemaHelper.GetPicklistValues(fieldInfo);
            this.options = new SelectionOption[0];
            for(String option : picklistValues){
                this.options.add(new SelectionOption(option));
            }
        }
    }

    public class SelectionOption{
        @AuraEnabled public String label;
        @AuraEnabled public String value;

        selectionOption(String item){
            this.label = item;
            this.value = item;
        }
    }
}