force-app/main/default/objects/Animal_Playgroup__c/Animal_Playgroup__c.object-meta.xml
<CustomObject>
    <label>Animal Playgroup</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Animal Playgroup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Playgroups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Playgroup__c/fields/Playgroup_Session__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Session</label>
    <referenceTo>Playgroup_Session__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/Playgroup_Session__c.object-meta.xml
<CustomObject>
    <label>Playgroup Session</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroup Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup_Session__c/fields/Animal_Playgroup__c.field-meta.xml
<CustomField>
    <fullName>Animal_Playgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Playgroup</label>
    <referenceTo>Animal_Playgroup__c</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AnimalPlaygroupTriggerHandler.cls
public with sharing class AnimalPlaygroupTriggerHandler {
    public static void afterUpdate(Map<Id, Animal_Playgroup__c> newMap) {

        AnimalPlaygroupUpdateQueueable updateAnimalPlaygroups = new AnimalPlaygroupUpdateQueueable(
            getSessionIds(newMap.values())
        );
        // enqueue the job for processing
        ID jobID = System.enqueueJob(updateAnimalPlaygroups);
    }

    public static void afterDelete(Map<Id, Animal_Playgroup__c> oldMap){
        AnimalPlaygroupUpdateQueueable updateAnimalPlaygroups = new AnimalPlaygroupUpdateQueueable(
            getSessionIds(oldMap.values())
        );
        // enqueue the job for processing
        ID jobID = System.enqueueJob(updateAnimalPlaygroups);
    }

    private static Set<Id> getSessionIds(Animal_Playgroup__c[] animalPlaygroups){
        Set<Id> sessionIds = new Set<Id>();
        for(Animal_Playgroup__c ap : animalPlaygroups){
            sessionIds.add(ap.Playgroup_Session__c);
        }
        return sessionIds;
    }
}