force-app/main/default/objects/Animal_Playgroup__c/Animal_Playgroup__c.object-meta.xml
<CustomObject>
    <label>Animal Playgroup</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Animal Playgroup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Playgroups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Playgroup__c/fields/Other_Dogs__c.field-meta.xml
<CustomField>
    <fullName>Other_Dogs__c</fullName>
    <label>Other Dogs</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Playgroup__c/fields/Playgroup_Session__c.field-meta.xml
<CustomField>
    <fullName>Playgroup_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Playgroup Session</label>
    <referenceTo>Playgroup_Session__c</referenceTo>
    <relationshipLabel>Animal Playgroups</relationshipLabel>
    <relationshipName>Animal_Playgroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Playgroup_Session__c/Playgroup_Session__c.object-meta.xml
<CustomObject>
    <label>Playgroup Session</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Playgroup Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Playgroup Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Playgroup_Session__c/fields/Animal_Playgroup__c.field-meta.xml
<CustomField>
    <fullName>Animal_Playgroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal Playgroup</label>
    <referenceTo>Animal_Playgroup__c</referenceTo>
    <relationshipLabel>Playgroup Sessions</relationshipLabel>
    <relationshipName>Playgroup_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AnimalPlaygroupUpdateQueueable.cls
public with sharing class AnimalPlaygroupUpdateQueueable implements Queueable{
    private Set<Id> pgSessionIds;

    public AnimalPlaygroupUpdateQueueable(Set<Id> pgSessionIds) {
        this.pgSessionIds = pgSessionIds;

    }
    public void execute(QueueableContext context) {
        Playgroup_Session__c[] sessions = [
            SELECT Id,
            (SELECT Id, Animal_Name__c, Other_Dogs__c FROM Animal_Playgroups__r)
            FROM Playgroup_Session__c
            WHERE Id IN :pgSessionIds
        ];

        Animal_Playgroup__c[] apsToUpdate = new Animal_Playgroup__c[0];
        for(Playgroup_Session__c session : sessions){
            String[] animalNameList = new String[0];
            for(Animal_Playgroup__c ap : session.Animal_Playgroups__r){
                animalNameList.add(ap.Animal_Name__c);
            }

            for(Animal_Playgroup__c ap : session.Animal_Playgroups__r){
                String[] tempNameList = animalNameList.clone();

                Integer index = tempNameList.indexOf(ap.Animal_Name__c);
                tempNameList.remove(index);
                ap.Other_Dogs__c = String.join(tempNameList, ',');
                apsToUpdate.add(ap);
            }
        }

        update apsToUpdate;
    }
}