force-app/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EIN_Number__c.field-meta.xml
<CustomField>
    <fullName>EIN_Number__c</fullName>
    <label>EIN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Agency_Case__c.field-meta.xml
<CustomField>
    <fullName>Agency_Case__c</fullName>
    <label>Agency Case #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <label>Alias</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Drivers_License_or_State_ID__c.field-meta.xml
<CustomField>
    <fullName>Drivers_License_or_State_ID__c</fullName>
    <label>Driver&apos;s License #</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Financial_Resources__c.field-meta.xml
<CustomField>
    <fullName>Financial_Resources__c</fullName>
    <label>Financial Resources</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/License_or_ID_State__c.field-meta.xml
<CustomField>
    <fullName>License_or_ID_State__c</fullName>
    <label>License or ID State</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>DC - District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Guam</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/Scene_Locations__c.object-meta.xml
<CustomObject>
    <label>Scene Location</label>
    <nameField>
        <label>Address Line 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scene Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scene_Locations__c/fields/Address_1__c.field-meta.xml
<CustomField>
    <fullName>Address_1__c</fullName>
    <label>Address 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <label>Address Line 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Scene Locations</relationshipLabel>
    <relationshipName>Scene_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/Primary_Incident_Location__c.field-meta.xml
<CustomField>
    <fullName>Primary_Incident_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Incident Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Northeast</fullName>
            </value>
            <value>
                <fullName>Midwest</fullName>
            </value>
            <value>
                <fullName>Southeast</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <label>Zipcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/extSupplimentalReport.cls
public class extSupplimentalReport{

public list<Contact> lstContacts {get;set;}
public list<Contact> lstContactRoleComplainant {get;set;}
public Case ObjCase {get;set;}
set<Id>ConIdSet = new set<Id>();
set<Id>ComplinantConIdSet = new set<Id>();
public list<Scene_Locations__c> lstSceneLocation{get;set;}

 public list<integer> getrepeatDiv(){
        list<integer> repeatDiv = new list<integer>();
        for(integer i=0;i<3;i++){
                repeatDiv.add(i); 
        }
        return repeatDiv; 
    } 
      
    public extSupplimentalReport(ApexPages.StandardController controller) {
        id caseId=Apexpages.currentPage().getParameters().get('id');
            if(caseId!=null){
                 ObjCase = [Select c.contact.email,c.contact.title,c.contact.phone,c.contact.mobilephone,c.contact.fax,c.contact.name,AccountId,c.Account.Type,c.Account.Name,c.account.Phone, c.CaseNumber, c.Agency_Case__c,c.Account.BillingCountry, c.Account.BillingPostalCode,
                                 c.Account.BillingState, c.Account.BillingCity, c.Account.BillingStreet, c.Account.Fax,c.Description,c.contactid  From Case c Where Id =: caseId];
                
                for(CaseContactRole  Casecon :[Select c.Id, c.ContactId, c.Role, c.CasesId From CaseContactRole c where CasesId =:caseId]){
                    if(Casecon.role=='Suspect'){
                       ConIdSet.add(Casecon.ContactId);     
                    }
                        if(Casecon.Role=='Complainant' ){
                                ComplinantConIdSet.add(Casecon.ContactId);
                        }
                }
                
                 lstSceneLocation=[Select  s.name,s.Zipcode__c, s.State__c, s.Region__c, s.Primary_Incident_Location__c, s.CreatedDate, s.County__c,
                 s.City__c, s.Case__c, s.Address_Line_2__c, s.Address_1__c From Scene_Locations__c s where Case__c =:caseId AND Primary_Incident_Location__c= true];
                
                if(ConIdSet!=null && ConIdSet.Size()>0){
                lstContacts=[ Select  c.Account.EIN_Number__c,c.Salutation,c.Phone,c.Account.Name, c.Name, c.MobilePhone,   
                                      c.MailingStreet, c.MailingState, c.MailingPostalCode, c.MailingCountry, c.MailingCity,     
                                      c.License_or_ID_State__c, c.Account.website,c.Account.BillingCity,c.Account.BillingCountry,c.Account.BillingState, c.Account.Billingstreet,
                                      c.Account.BillingPostalCode,c.Account.Phone,c.LastName, c.Gender__c, c.FirstName, c.Financial_Resources__c, 
                                      c.Fax, c.Email,  c.Drivers_License_or_State_ID__c, c.Description,c.Birthdate,c.Alias__c,c.Age__c, c.AccountId,c.title From Contact c 
                                      Where Id IN :ConIdSet];    
                                        
                 }                       
                lstContactRoleComplainant=[Select c.Title, c.Salutation, 
                                         c.Phone, c.OwnerId, c.OtherStreet, c.OtherState, c.OtherPostalCode, c.OtherPhone, 
                                         c.OtherCountry, c.OtherCity, c.Name, c.MobilePhone,
                                         c.MasterRecordId, c.Marital_Status__c, c.MailingStreet, c.MailingState, c.MailingPostalCode, c.MailingCountry, c.MailingCity, 
                                         c.HomePhone, c.FirstName, c.Financial_Resources__c,c.Fax, c.Email From Contact c Where Id IN :ComplinantConIdSet]; 
                                
                Apexpages.currentPage().getHeaders().put( 'content-disposition', 'inline; filename=SupplementalReport.pdf' );
            
            }
    }

}