force-app/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Item__c/Action_Item__c.object-meta.xml
<CustomObject>
    <label>Cruelty Report</label>
    <nameField>
        <displayFormat>CR-{YYYY}-{0000}</displayFormat>
        <label>Cruelty Report #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cruelty Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Item__c/fields/Case_Origin__c.field-meta.xml
<CustomField>
    <fullName>Case_Origin__c</fullName>
    <label>Complaint Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Animal Welfare Agency</fullName>
            </value>
            <value>
                <fullName>Law Enforcement Agency</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Donor Call Center</fullName>
            </value>
            <value>
                <fullName>President&apos;s Office</fullName>
            </value>
            <value>
                <fullName>Poison Control Center</fullName>
            </value>
            <value>
                <fullName>Midwest Office</fullName>
            </value>
            <value>
                <fullName>HLE</fullName>
            </value>
            <value>
                <fullName>Public Information/8th Ave. Front Desk</fullName>
            </value>
            <value>
                <fullName>NFR</fullName>
            </value>
            <value>
                <fullName>Letter by Mail</fullName>
            </value>
            <value>
                <fullName>Private Citizen</fullName>
            </value>
            <value>
                <fullName>GR</fullName>
            </value>
            <value>
                <fullName>Puppy Mill Referral</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
                <isActive>false</isActive>
                <label>Email</label>
            </value>
            <value>
                <fullName>Internal Referral</fullName>
                <isActive>false</isActive>
                <label>Internal Referral</label>
            </value>
            <value>
                <fullName>Phone</fullName>
                <isActive>false</isActive>
                <label>Phone</label>
            </value>
            <value>
                <fullName>Web</fullName>
                <isActive>false</isActive>
                <label>Web</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Item__c/fields/Complaint_Summary__c.field-meta.xml
<CustomField>
    <fullName>Complaint_Summary__c</fullName>
    <label>Complaint Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Action_Item__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date Received</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Action_Item_Role__c/Action_Item_Role__c.object-meta.xml
<CustomObject>
    <label>Cruelty Report Contact Role</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>CR Role #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cruelty Report Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Item_Role__c/fields/Action_Item__c.field-meta.xml
<CustomField>
    <fullName>Action_Item__c</fullName>
    <label>Cruelty Report</label>
    <referenceTo>Action_Item__c</referenceTo>
    <relationshipName>Action_Item_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Action_Item_Scene_Location__c/Action_Item_Scene_Location__c.object-meta.xml
<CustomObject>
    <label>Action Item Scene Location</label>
    <nameField>
        <label>Action Item Scene Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Item Scene Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Item_Scene_Location__c/fields/Action_Item__c.field-meta.xml
<CustomField>
    <fullName>Action_Item__c</fullName>
    <label>Action Item</label>
    <referenceTo>Action_Item__c</referenceTo>
    <relationshipLabel>Action Item Scene Locations</relationshipLabel>
    <relationshipName>Action_Item_Scene_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Action_Item_Scene_Location__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Item_Scene_Location__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Item_Scene_Location__c/fields/Primary_Incident_Location__c.field-meta.xml
<CustomField>
    <fullName>Primary_Incident_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Incident Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Action_Item_Scene_Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Item_Scene_Location__c/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <label>Zipcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Citizen</fullName>
            </value>
            <value>
                <fullName>Agency Representative</fullName>
            </value>
            <value>
                <fullName>Animal Control Officer</fullName>
            </value>
            <value>
                <fullName>Animal Owner</fullName>
            </value>
            <value>
                <fullName>Animal Rescue</fullName>
            </value>
            <value>
                <fullName>Animal Welfare Professional</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Code Enforcement Officer</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>County/Civil Attorney</fullName>
            </value>
            <value>
                <fullName>Defense Attorney</fullName>
            </value>
            <value>
                <fullName>Law Enforcement Contact</fullName>
            </value>
            <value>
                <fullName>Law Enforcement Officer</fullName>
            </value>
            <value>
                <fullName>Local Elected Official</fullName>
            </value>
            <value>
                <fullName>Officer/Complainant</fullName>
            </value>
            <value>
                <fullName>Prosecuting Attorney</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
            <value>
                <fullName>Senator</fullName>
            </value>
            <value>
                <fullName>Shelter Contact</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>State Representative</fullName>
            </value>
            <value>
                <fullName>State Senator</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Suspect</fullName>
            </value>
            <value>
                <fullName>US Representative</fullName>
            </value>
            <value>
                <fullName>US Senator</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Relocation Driver</fullName>
            </value>
            <value>
                <fullName>Behavior Case Worker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>DC - District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Guam</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestCreateActionItem_Obj.cls
@isTest
private class TestCreateActionItem_Obj{
/*    static testMethod void testIncident(){
        Profile pf = [Select Id from Profile where Name = 'System Administrator'];
        User u4 = new User();
        u4.Username='bakul@gmail.com';
        u4.email = 'dileep.kumar@aspiresoftwareconsultancy.com';
        u4.lastname = 'tester';
        u4.firstname = 'u4user';
        u4.emailencodingkey='UTF-8';
        u4.alias = 'u4user';
        u4.languagelocalekey='en_US';  
        u4.localesidkey='en_US';
        u4.timezonesidkey='America/Los_Angeles';
        u4.profileid = pf.Id;
        u4.isactive = True;
        insert u4;
        
        List<Contact> coList = new List<Contact>();
        Contact c1 = new Contact();
        c1.FirstName = 'Dileep';
        c1.LastName = 'Kumar';
        c1.MailingStreet = 'Btm';
        c1.MailingCity = 'Bangalore';
        c1.MailingState = 'NY'; 
        c1.County__c = 'India';
        c1.Contact_Type__c = 'Abc';
        coList.add(c1);
        //insert c1;
        Contact c2 = new Contact();
        c2.FirstName = 'Dileep';
        c2.LastName = 'Kumar';
        c2.MailingStreet = 'Btm';
        c2.MailingCity = 'Bangalore';
        c2.MailingState = 'NY'; 
        c2.County__c = 'India';
        c2.Contact_Type__c = 'Abc';
        coList.add(c2);
        insert coList;

        List<Contact> contactList = [select Id,Name,FirstName,LastName,Contact_Type__c,MailingCity,MailingState,MailingStreet,Account.Name from Contact where Id IN:coList];
        system.debug('@@contactList@@'+contactList);
        
        Action_Item__c c = new Action_Item__c();
        c.Complaint_Summary__c = 'hello'; 
        c.Case_Origin__c = 'Email';
		c.Date_Received__c = System.today();        
        insert c;
		
        List<Action_Item_Scene_Location__c>  sceneList = new List<Action_Item_Scene_Location__c> ();
        Action_Item_Scene_Location__c scene = new  Action_Item_Scene_Location__c();
        scene.Action_Item__c = c.Id;
        scene.Name = 'SceneOne';
        scene.Address_Line_1__c = 'Btm';
        scene.City__c = 'Bangalore';
        scene.State__c = 'NY';
        scene.Zipcode__c = '123456';
        scene.County__c = 'India';
        scene.Description__c = 'Welcome';
        scene.Primary_Incident_Location__c =true;
        sceneList.add(scene);
        
        List<Contact> conList = new List<Contact>();
        Contact con = new Contact();
        con.FirstName = 'Dileep';
        con.LastName = 'Kumar';
        con.MailingStreet = 'Btm';
        con.MailingCity = 'Bangalore';
        con.MailingState = 'Karnataka'; 
        con.County__c = 'India';
        con.Contact_Type__c = 'Abc';
        
        Contact conOne = new Contact();
        conOne.FirstName = 'Manohar';
        conOne.LastName = 'Kumar';
        conOne.MailingStreet = 'Btm';
        conOne.MailingCity = 'Bangalore';
        conOne.MailingState = 'Karnataka'; 
        conOne.County__c = 'India';
        conOne.Contact_Type__c = 'Abc';
        
        List<Action_Item_Role__c> cRoleList = new List<Action_Item_Role__c>(); 
        Action_Item_Role__c  ccRole = new Action_Item_Role__c ();
        ccRole.Action_Item__c = c.Id;
        ccRole.Role__c = 'Officer'; 
        Action_Item_Role__c  ccRoleThree = new Action_Item_Role__c ();
        ccRoleThree.Action_Item__c = c.Id;
        ccRoleThree.Role__c = 'Officer';
        
        
        List<SelectOption> searchResults = new List<SelectOption>();
        List<SelectOption> searchResult = new List<SelectOption>();
        for(Contact cont :contactList ){
        	searchResult.add(new SelectOption(cont.Id,cont.Name + ' - ' + cont.MailingStreet +' , '+ cont.MailingCity +' , '+ cont.MailingState +' - '+ ' Account: ' + cont.Account.Name + ' - ' + 'Contact Type' + ': ' + cont.Contact_Type__c));
        	system.debug('@@searchResult@@'+searchResult);
        }
        for(Contact contac : contactList){
        	searchResults.add(new SelectOption(contac.Id,contac.Name + ' - ' + contac.MailingStreet +' , '+ contac.MailingCity +' , '+ contac.MailingState +' - '+ ' Account: ' + contac.Account.Name + ' - ' + 'Contact Type' + ': ' + contac.Contact_Type__c));
        	system.debug('@@searchResults@@'+searchResults);
        }
        string useOrAddContact;
        useOrAddContact='Add';
        string useOrAddContactOne;
        useOrAddContactOne='Use';
        
        string useOrAddContactTwo;
        useOrAddContactTwo='Add';
        string useOrAddContactThree;
        useOrAddContactThree='Use';
        CreateActionItem_Obj ci = new CreateActionItem_Obj();
        ci.sceneList = sceneList; 
        ci.complainants[0].con=con;
        ci.complainants[0].conSearchText ='k';
        ci.subjects[0].con=conOne;
        
        ci.conList = conList;   
       	//ci.ccRole= ccRole; 
         
        
        ci.complainants[0].useOrAddContact = useOrAddContact;
        ci.complainants[0].useOrAddContact = useOrAddContactOne;
        ci.complainants[0].searchResults = searchResult;
        ci.complainants[0].ccRole.Contact__c = con.Id;
        ci.complainants[0].ccRole.Role__c ='we';
        ci.complainants[0].ccRole.Action_Item__c = c.Id;
        ci.complainants[0].ccRole = ccRole;
        ci.cRoleList =cRoleList;
        
        
        ci.subjects[0].useOrAddContact = useOrAddContactTwo;
        //ci.subjects[0].useOrAddContact = useOrAddContactThree;
        ci.subjects[0].searchResults = searchResults;
        ci.subjects[0].ccRole.Contact__c = con.Id;
        ci.subjects[0].ccRole.Role__c ='';
        ci.subjects[0].ccRole.Action_Item__c = c.Id;
        ci.subjects[0].ccRole = ccRole;
        //ci.subjects[0].cRoleList = cRoleList;
        ci.cRoleList = cRoleList;
        ci.addComplainant();
        ci.addSubject(); 
        Apexpages.currentPage().getParameters().put('index', '1');
        Apexpages.currentPage().getParameters().put('type', '');
        ci.searchContact(); 
        ci.addNewLocation();
         system.runAs(u4){
        	ci.saveData();
        } 
    }
    static testMethod void testIncidentOne(){
        Profile pf = [Select Id from Profile where Name = 'System Administrator'];
        User u4 = new User();
        u4.Username='bakul@gmail.com';
        u4.email = 'dileep.kumar@aspiresoftwareconsultancy.com';
        u4.lastname = 'tester';
        u4.firstname = 'u4user';
        u4.emailencodingkey='UTF-8';
        u4.alias = 'u4user';
        u4.languagelocalekey='en_US';  
        u4.localesidkey='en_US';
        u4.timezonesidkey='America/Los_Angeles';
        u4.profileid = pf.Id;
        u4.isactive = True;
        insert u4;
         
        Action_Item__c c = new Action_Item__c();
        c.Complaint_Summary__c = 'hello';
        c.Case_Origin__c = 'Email';
        c.Date_Received__c = Date.newInstance(2016, 12, 9);
        insert c;
		
        List<Action_Item_Scene_Location__c>  sceneList = new List<Action_Item_Scene_Location__c> ();
        Action_Item_Scene_Location__c scene = new  Action_Item_Scene_Location__c();
        scene.Action_Item__c = c.Id;
        scene.Name = 'SceneOne';
        scene.Address_Line_1__c = 'Btm';
        scene.City__c = 'Bangalore';
        scene.State__c = 'NY';
        scene.Zipcode__c = '123456';
        scene.County__c = 'India';
        scene.Description__c = 'Welcome';
        scene.Primary_Incident_Location__c =true;
        sceneList.add(scene);
        
        List<Contact> conList = new List<Contact>();
        Contact con = new Contact();
        con.FirstName = 'Dileep';
        con.LastName = 'Kumar';
        con.MailingStreet = 'Btm';
        con.MailingCity = 'Bangalore';
        con.MailingState = 'NY'; 
        con.County__c = 'India';
        con.Contact_Type__c = 'Abc';
        conList.add(con);
        
        Contact conOne = new Contact();
        conOne.FirstName = 'Manohar';
        conOne.LastName = 'Kumar';
        conOne.MailingStreet = 'Btm';
        conOne.MailingCity = 'Bangalore';
        conOne.MailingState = 'NY'; 
        conOne.County__c = 'India';
        conOne.Contact_Type__c = 'Abc';
        conList.add(conOne);
        
        List<Action_Item_Role__c> cRoleList = new List<Action_Item_Role__c>(); 
        Action_Item_Role__c  ccRole = new Action_Item_Role__c ();
        ccRole.Action_Item__c = c.Id;
        ccRole.Role__c = 'Officer';
        cRoleList.add(ccRole);
        Action_Item_Role__c  ccRoleThree = new Action_Item_Role__c ();
        ccRoleThree.Action_Item__c = c.Id;
        ccRoleThree.Role__c = 'Officer';
        cRoleList.add(ccRoleThree);
        
        List<Contact> contactList = [select Id,Name,FirstName,LastName,Contact_Type__c,MailingCity,MailingState,MailingStreet,Account.Name from Contact];
        List<SelectOption> searchResults = new List<SelectOption>();
        List<SelectOption> searchResult = new List<SelectOption>();
        for(Contact cont :contactList ){
        	searchResult.add(new SelectOption(cont.Id,cont.Name + ' - ' + cont.MailingStreet +' , '+ cont.MailingCity +' , '+ cont.MailingState +' - '+ ' Account: ' + cont.Account.Name + ' - ' + 'Contact Type' + ': ' + cont.Contact_Type__c));
        }
        for(Contact contac : contactList){
        	searchResults.add(new SelectOption(contac.Id,contac.Name + ' - ' + contac.MailingStreet +' , '+ contac.MailingCity +' , '+ contac.MailingState +' - '+ ' Account: ' + contac.Account.Name + ' - ' + 'Contact Type' + ': ' + contac.Contact_Type__c));
        }
        
        string useOrAddContact;
        useOrAddContact='Add';
        string useOrAddContactOne;
        useOrAddContactOne='Use';
         
        CreateActionItem_Obj ci = new CreateActionItem_Obj();
        ci.sceneList = sceneList; 
        
        
        // ci.complainants[0].con=con; 
        ci.subjects[0].con=con;
        ci.conList = conList;   
       	//ci.ccRole= ccRole; 
         
        
        ci.subjects[0].useOrAddContact = useOrAddContact;
        ci.subjects[0].useOrAddContact = useOrAddContactOne;
        ci.subjects[0].searchResults = searchResult;
        ci.subjects[0].ccRole.Contact__c = con.Id;
        ci.subjects[0].ccRole.Role__c='we';
        ci.subjects[0].ccRole.Action_Item__c= c.Id;
        ci.subjects[0].ccRole = ccRole;
        ci.cRoleList =cRoleList;
        
        
        ci.addComplainant();
        ci.addSubject();
        Apexpages.currentPage().getParameters().put('index', '1');
        Apexpages.currentPage().getParameters().put('type', '');
        ci.searchContact(); 
        ci.addNewLocation();
        
        system.runAs(u4){
        	ci.saveData();
        } 
    }*/
    static testMethod void testIncidentTwo(){
        Profile pf = [Select Id from Profile where Name = 'System Administrator'];
        User u4 = new User();
        u4.Username='bakul@gmail.com';
        u4.email = 'dileep.kumar@aspiresoftwareconsultancy.com';
        u4.lastname = 'tester';
        u4.firstname = 'u4user';
        u4.emailencodingkey='UTF-8';
        u4.alias = 'u4user';
        u4.languagelocalekey='en_US';  
        u4.localesidkey='en_US';
        u4.timezonesidkey='America/Los_Angeles';
        u4.profileid = pf.Id;
        u4.isactive = True;
        insert u4;
        
        Action_Item__c c = new Action_Item__c();
        c.Complaint_Summary__c = 'hello';
        c.Case_Origin__c = 'Social Media';
        c.Date_Received__c = Date.newInstance(2018, 12, 9);
        insert c;
		
        List<Action_Item_Scene_Location__c>  sceneList = new List<Action_Item_Scene_Location__c> ();
        Action_Item_Scene_Location__c scene = new  Action_Item_Scene_Location__c();
        scene.Action_Item__c = c.Id;
        scene.Name = 'SceneOne';
        scene.Address_Line_1__c = 'Btm';
        scene.City__c = 'Bangalore';
        scene.State__c = 'NY';
        scene.Zipcode__c = '123456';
        scene.County__c = 'India';
        scene.Description__c = 'Welcome';
        scene.Primary_Incident_Location__c =true;
        sceneList.add(scene);
        
        List<Contact> conList = new List<Contact>();
        Contact con = new Contact();
        con.FirstName = 'Dileep';
        con.LastName = 'Kumar';
        con.MailingStreet = 'Btm';
        con.MailingCity = 'Bangalore';
        con.MailingState = 'NY'; 
        con.County__c = 'India';
        con.Contact_Type__c = 'Abc';
        conList.add(con);
        
        Contact conOne = new Contact();
        conOne.FirstName = 'Manohar';
        conOne.LastName = 'Kumar';
        conOne.MailingStreet = 'Btm';
        conOne.MailingCity = 'Bangalore';
        conOne.MailingState = 'NY'; 
        conOne.County__c = 'India';
        conOne.Contact_Type__c = 'Abc';
        conList.add(conOne);
        
        List<Action_Item_Role__c> cRoleList = new List<Action_Item_Role__c>(); 
        Action_Item_Role__c  ccRole = new Action_Item_Role__c ();
        ccRole.Action_Item__c = c.Id;
        ccRole.Role__c = 'Officer';
        cRoleList.add(ccRole);
        Action_Item_Role__c  ccRoleThree = new Action_Item_Role__c ();
        ccRoleThree.Action_Item__c = c.Id;
        ccRoleThree.Role__c = 'Officer';
        cRoleList.add(ccRoleThree);
         
        CreateActionItem_Obj ci = new CreateActionItem_Obj();
        ci.sceneList = sceneList; 
        
        system.runAs(u4){
        	ci.saveData();
        }
        
         
        CreateActionItem_Obj.ContactWrapper aa = new CreateActionItem_Obj.ContactWrapper();
        ci.addComplainant();
        ci.addSubject();
        Apexpages.currentPage().getParameters().put('index', '1');
        Apexpages.currentPage().getParameters().put('type', '');
        ci.searchContact(); 
        ci.addNewLocation(); 
    }
    static testMethod void testIncidentThree(){
        Profile pf = [Select Id from Profile where Name = 'System Administrator'];
        User u4 = new User();
        u4.Username='bakul@gmail.com';
        u4.email = 'dileep.kumar@aspiresoftwareconsultancy.com';
        u4.lastname = 'tester';
        u4.firstname = 'u4user';
        u4.emailencodingkey='UTF-8';
        u4.alias = 'u4user';
        u4.languagelocalekey='en_US';  
        u4.localesidkey='en_US';
        u4.timezonesidkey='America/Los_Angeles';
        u4.profileid = pf.Id;
        u4.isactive = True;
        insert u4;
        
        Action_Item__c c = new Action_Item__c();
        c.Complaint_Summary__c = 'hello';
        c.Case_Origin__c = 'Social Media';
        c.Date_Received__c = Date.newInstance(2019, 12, 9);
        insert c;
		
        List<Action_Item_Scene_Location__c>  sceneList = new List<Action_Item_Scene_Location__c> ();
        Action_Item_Scene_Location__c scene = new  Action_Item_Scene_Location__c();
        scene.Action_Item__c = c.Id;
        scene.Name = 'SceneOne';
        scene.Address_Line_1__c = 'Btm';
        scene.City__c = 'Bangalore';
        scene.State__c = 'NY';
        scene.Zipcode__c = '123456';
        scene.County__c = 'India';
        scene.Description__c = 'Welcome';
        scene.Primary_Incident_Location__c =true;
        sceneList.add(scene);
        
        List<Contact> conList = new List<Contact>();
        Contact con = new Contact();
        con.FirstName = 'Dileep';
        con.LastName = 'Kumar';
        con.MailingStreet = 'Btm';
        con.MailingCity = 'Bangalore';
        con.MailingState = 'NY'; 
        con.County__c = 'India';
        con.Contact_Type__c = 'Abc';
        conList.add(con);
        
        Contact conOne = new Contact();
        conOne.FirstName = 'Manohar';
        conOne.LastName = 'Kumar';
        conOne.MailingStreet = 'Btm';
        conOne.MailingCity = 'Bangalore';
        conOne.MailingState = 'NY'; 
        conOne.County__c = 'India';
        conOne.Contact_Type__c = 'Abc';
        conList.add(conOne);
        
        List<Action_Item_Role__c> cRoleList = new List<Action_Item_Role__c>(); 
        Action_Item_Role__c  ccRole = new Action_Item_Role__c ();
        ccRole.Action_Item__c = c.Id;
        ccRole.Role__c = 'Officer';
        cRoleList.add(ccRole);
        Action_Item_Role__c  ccRoleThree = new Action_Item_Role__c ();
        ccRoleThree.Action_Item__c = c.Id;
        ccRoleThree.Role__c = 'Officer';
        cRoleList.add(ccRoleThree);
         
        CreateActionItem_Obj ci = new CreateActionItem_Obj();
        ci.sceneList = sceneList; 
        
        system.runAs(u4){
        	ci.saveData();
        }
        
        CreateActionItem_Obj.ContactWrapper aa = new CreateActionItem_Obj.ContactWrapper();
        ci.addComplainant();
        ci.addSubject();
        Apexpages.currentPage().getParameters().put('index', '1');
        Apexpages.currentPage().getParameters().put('type', '');
        ci.searchContact(); 
        ci.addNewLocation(); 
    }
    static testMethod void testIncidentFour(){
        Profile pf = [Select Id from Profile where Name = 'System Administrator'];
        User u4 = new User();
        u4.Username='bakul@gmail.com';
        u4.email = 'dileep.kumar@aspiresoftwareconsultancy.com';
        u4.lastname = 'tester';
        u4.firstname = 'u4user';
        u4.emailencodingkey='UTF-8';
        u4.alias = 'u4user';
        u4.languagelocalekey='en_US';  
        u4.localesidkey='en_US';
        u4.timezonesidkey='America/Los_Angeles';
        u4.profileid = pf.Id;
        u4.isactive = True;
        insert u4;
        
        Action_Item__c c = new Action_Item__c();
        c.Complaint_Summary__c = 'hello';
        c.Case_Origin__c = 'Social Media';
        c.Date_Received__c = System.today();
        insert c;     
		
        List<Action_Item_Scene_Location__c>  sceneList = new List<Action_Item_Scene_Location__c> ();
        Action_Item_Scene_Location__c scene = new  Action_Item_Scene_Location__c();
        scene.Action_Item__c = c.Id;
        scene.Name = 'SceneOne';
        scene.Address_Line_1__c = 'Btm';
        scene.City__c = 'Bangalore';
        scene.State__c = 'NY';
        scene.Zipcode__c = '123456';
        scene.County__c = 'India';
        scene.Description__c = 'Welcome';
        scene.Primary_Incident_Location__c =true;
        sceneList.add(scene);
        
        List<Contact> conList = new List<Contact>();
        Contact con = new Contact();
        con.FirstName = 'Dileep';
        con.LastName = 'Kumar';
        con.MailingStreet = 'Btm';
        con.MailingCity = 'Bangalore';
        con.MailingState = 'NY'; 
        con.County__c = 'India';
        con.Contact_Type__c = 'Abc';
        conList.add(con);
        
        Contact conOne = new Contact();
        conOne.FirstName = 'Manohar';
        conOne.LastName = 'Kumar';
        conOne.MailingStreet = 'Btm';
        conOne.MailingCity = 'Bangalore';
        conOne.MailingState = 'NY'; 
        conOne.County__c = 'India';
        conOne.Contact_Type__c = 'Abc';
        conList.add(conOne);
        
        List<Action_Item_Role__c> cRoleList = new List<Action_Item_Role__c>(); 
        Action_Item_Role__c  ccRole = new Action_Item_Role__c ();
        ccRole.Action_Item__c = c.Id;
        ccRole.Role__c = 'Officer';
        cRoleList.add(ccRole);
        Action_Item_Role__c  ccRoleThree = new Action_Item_Role__c ();
        ccRoleThree.Action_Item__c = c.Id;
        ccRoleThree.Role__c = 'Officer';
        cRoleList.add(ccRoleThree);
         
        CreateActionItem_Obj ci = new CreateActionItem_Obj();
        ci.sceneList = sceneList; 
        
        system.runAs(u4){
        	ci.saveData();
        }
        
         
        CreateActionItem_Obj.ContactWrapper aa = new CreateActionItem_Obj.ContactWrapper();
        ci.addComplainant();
        ci.addSubject();
        Apexpages.currentPage().getParameters().put('index', '1');
        Apexpages.currentPage().getParameters().put('type', '');
        ci.searchContact(); 
        ci.addNewLocation(); 
    }
    static testMethod void testIncidentFive(){
        Profile pf = [Select Id from Profile where Name = 'System Administrator'];
        User u4 = new User();
        u4.Username='bakul@gmail.com';
        u4.email = 'dileep.kumar@aspiresoftwareconsultancy.com';
        u4.lastname = 'tester';
        u4.firstname = 'u4user';
        u4.emailencodingkey='UTF-8';
        u4.alias = 'u4user';
        u4.languagelocalekey='en_US';  
        u4.localesidkey='en_US';
        u4.timezonesidkey='America/Los_Angeles';
        u4.profileid = pf.Id;
        u4.isactive = True;
        insert u4;
        
        Action_Item__c c = new Action_Item__c();
        c.Complaint_Summary__c = 'hello';
        c.Case_Origin__c = 'Social Media'; 
        c.Date_Received__c = System.today();
        insert c;
		
        List<Action_Item_Scene_Location__c>  sceneList = new List<Action_Item_Scene_Location__c> ();
        Action_Item_Scene_Location__c scene = new  Action_Item_Scene_Location__c();
        scene.Action_Item__c = c.Id;
        scene.Name = 'SceneOne';
        scene.Address_Line_1__c = 'Btm';
        scene.City__c = 'Bangalore';
        scene.State__c = 'NY';
        scene.Zipcode__c = '123456';
        scene.County__c = 'India';
        scene.Description__c = 'Welcome';
        scene.Primary_Incident_Location__c =true;
        sceneList.add(scene);
        
        List<Contact> conList = new List<Contact>();
        Contact con = new Contact();
        con.FirstName = 'Dileep';
        con.LastName = 'Kumar';
        con.MailingStreet = 'Btm';
        con.MailingCity = 'Bangalore';
        con.MailingState = 'NY'; 
        con.County__c = 'India';
        con.Contact_Type__c = 'Abc';
        conList.add(con);
        
        Contact conOne = new Contact();
        conOne.FirstName = 'Manohar';
        conOne.LastName = 'Kumar';
        conOne.MailingStreet = 'Btm';
        conOne.MailingCity = 'Bangalore';
        conOne.MailingState = 'NY'; 
        conOne.County__c = 'India';
        conOne.Contact_Type__c = 'Abc';
        conList.add(conOne);
        
        List<Action_Item_Role__c> cRoleList = new List<Action_Item_Role__c>(); 
        Action_Item_Role__c  ccRole = new Action_Item_Role__c ();
        ccRole.Action_Item__c = c.Id;
        ccRole.Role__c = 'Officer';
        cRoleList.add(ccRole);
        Action_Item_Role__c  ccRoleThree = new Action_Item_Role__c ();
        ccRoleThree.Action_Item__c = c.Id;
        ccRoleThree.Role__c = 'Officer';
        cRoleList.add(ccRoleThree);
         
        CreateActionItem_Obj ci = new CreateActionItem_Obj();
        ci.sceneList = sceneList; 
        
        system.runAs(u4){
        	ci.saveData();
        }
        
         
        CreateActionItem_Obj.ContactWrapper aa = new CreateActionItem_Obj.ContactWrapper();
        ci.addComplainant();
        ci.addSubject();
        Apexpages.currentPage().getParameters().put('index', '1');
        Apexpages.currentPage().getParameters().put('type', '');
        ci.searchContact(); 
        ci.addNewLocation(); 
    }
    static testMethod void testIncidentSix(){
        Profile pf = [Select Id from Profile where Name = 'System Administrator'];
        User u4 = new User();
        u4.Username='bakul@gmail.com';
        u4.email = 'dileep.kumar@aspiresoftwareconsultancy.com';
        u4.lastname = 'tester';
        u4.firstname = 'u4user';
        u4.emailencodingkey='UTF-8';
        u4.alias = 'u4user';
        u4.languagelocalekey='en_US';  
        u4.localesidkey='en_US';
        u4.timezonesidkey='America/Los_Angeles';
        u4.profileid = pf.Id;
        u4.isactive = True;
        insert u4;
        
        Action_Item__c c = new Action_Item__c();
        c.Complaint_Summary__c = 'hello';
        c.Case_Origin__c = 'Social Media';
        c.Date_Received__c = System.today();
        insert c;
        
        List<Action_Item_Scene_Location__c>  sceneList = new List<Action_Item_Scene_Location__c> ();
        Action_Item_Scene_Location__c scene = new  Action_Item_Scene_Location__c();
        scene.Action_Item__c = c.Id;
        scene.Name = 'SceneOne';
        scene.Address_Line_1__c = 'Btm';
        scene.City__c = 'Bangalore';
        scene.State__c = 'NY';
        scene.Zipcode__c = '123456';
        scene.County__c = 'India';
        scene.Description__c = 'Welcome';
        scene.Primary_Incident_Location__c =true;
        sceneList.add(scene);
        
        List<Contact> conList = new List<Contact>();
        Contact con = new Contact();
        con.FirstName = 'Dileep';
        con.LastName = 'Kumar';
        con.MailingStreet = 'Btm';
        con.MailingCity = 'Bangalore';
        con.MailingState = 'NY'; 
        con.County__c = 'India';
        con.Contact_Type__c = 'Abc';
        conList.add(con);
        
        Contact conOne = new Contact();
        conOne.FirstName = 'Manohar';
        conOne.LastName = 'Kumar';
        conOne.MailingStreet = 'Btm';
        conOne.MailingCity = 'Bangalore';
        conOne.MailingState = 'NY'; 
        conOne.County__c = 'India';
        conOne.Contact_Type__c = 'Abc';
        conList.add(conOne);
        insert conList;
         
        CreateActionItem_Obj ci = new CreateActionItem_Obj();
        ci.sceneList = sceneList; 
        
        ci.complainants[0].conSearchText = 'Kumar';
        Apexpages.currentPage().getParameters().put('index', '1');
        Apexpages.currentPage().getParameters().put('type', 'complainant');
        ci.searchContact();
        ci.complainants[0].selectedConId = ci.complainants[0].searchResults[0].getValue();
        ci.complainants[0].useOrAddContact = 'Use';
        ci.complainants[0].ccRole.Role__c = 'Alternative Contact/Relative';
        
        ci.subjects[0].conSearchText = 'Kumar';
        Apexpages.currentPage().getParameters().put('index', '1');
        Apexpages.currentPage().getParameters().put('type', 'subject');
        ci.searchContact(); 
        ci.subjects[0].con = new Contact(LastName='sdfds', FirstName = 'sfdsf', Email = 'sadrr@kdfj.com', MailingCountry = 'United States', MailingCity = 'sdfd',MailingState = 'NY', County__c = 'dfd',Contact_Type__c = 'Complainant');
        ci.subjects[0].useOrAddContact = 'Add';
        ci.subjects[0].ccRole.Role__c = 'Alternative Contact/Relative';
        
        ci.saveData(); 
    }
}