force-app/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EIN_Number__c.field-meta.xml
<CustomField>
    <fullName>EIN_Number__c</fullName>
    <label>EIN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Agency_Case__c.field-meta.xml
<CustomField>
    <fullName>Agency_Case__c</fullName>
    <label>Agency Case #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Investigator__c.field-meta.xml
<CustomField>
    <fullName>Investigator__c</fullName>
    <label>Case Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Kyle Held</fullName>
            </value>
            <value>
                <fullName>Terry Mills</fullName>
            </value>
            <value>
                <fullName>Leigh Anne Wilson</fullName>
            </value>
            <value>
                <fullName>Donna Lassa</fullName>
            </value>
            <value>
                <fullName>Teresa Ladner</fullName>
            </value>
            <value>
                <fullName>Nathan Zilak</fullName>
            </value>
            <value>
                <fullName>Rachel Touroo, DVM</fullName>
            </value>
            <value>
                <fullName>Alison Kennedy-Benson</fullName>
            </value>
            <value>
                <fullName>Amanda Fitch</fullName>
            </value>
            <value>
                <fullName>Elizabeth Pearlman, DVM</fullName>
            </value>
            <value>
                <fullName>Kristina Baucom, DVM</fullName>
            </value>
            <value>
                <fullName>Ashley Saver, DVM</fullName>
            </value>
            <value>
                <fullName>Tim Perciful</fullName>
            </value>
            <value>
                <fullName>Tim Rickey</fullName>
            </value>
            <value>
                <fullName>Susan Anderson</fullName>
            </value>
            <value>
                <fullName>Wanda Merling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Charge_Information__c/Charge_Information__c.object-meta.xml
<CustomObject>
    <description>The information in this section pertains to the criminal charges relating to the subjects in this case</description>
    <label>Charge Information</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Charge ID #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charge Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge_Information__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Charge Information</relationshipLabel>
    <relationshipName>Charge_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Charge_Count__c.field-meta.xml
<CustomField>
    <fullName>Charge_Count__c</fullName>
    <description>This is the number of times subject was charged</description>
    <inlineHelpText>Enter the number of counts this defendant was charged with under the above statute #</inlineHelpText>
    <label>Number of Counts</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/Charge_Level__c.field-meta.xml
<CustomField>
    <fullName>Charge_Level__c</fullName>
    <label>Charge Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Felony</fullName>
            </value>
            <value>
                <fullName>Infraction</fullName>
            </value>
            <value>
                <fullName>Violation</fullName>
            </value>
            <value>
                <fullName>Misdemeanor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Charge_Information__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Richmond County</fullName>
            </value>
            <value>
                <fullName>Kings County</fullName>
            </value>
            <value>
                <fullName>Queens County</fullName>
            </value>
            <value>
                <fullName>New York County</fullName>
            </value>
            <value>
                <fullName>Bronx County</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <label>Alias</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Drivers_License_or_State_ID__c.field-meta.xml
<CustomField>
    <fullName>Drivers_License_or_State_ID__c</fullName>
    <label>Driver&apos;s License #</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/License_or_ID_State__c.field-meta.xml
<CustomField>
    <fullName>License_or_ID_State__c</fullName>
    <label>License or ID State</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>DC - District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Guam</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/Scene_Locations__c.object-meta.xml
<CustomObject>
    <label>Scene Location</label>
    <nameField>
        <label>Address Line 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scene Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scene_Locations__c/fields/Address_1__c.field-meta.xml
<CustomField>
    <fullName>Address_1__c</fullName>
    <label>Address 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <label>Address Line 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Scene Locations</relationshipLabel>
    <relationshipName>Scene_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/Primary_Incident_Location__c.field-meta.xml
<CustomField>
    <fullName>Primary_Incident_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Incident Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Northeast</fullName>
            </value>
            <value>
                <fullName>Midwest</fullName>
            </value>
            <value>
                <fullName>Southeast</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scene_Locations__c/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <label>Zipcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseContactRoleExtension.cls
public class CaseContactRoleExtension{

    public List<CaseContactRole> ContactRoles{get;set;}
    public List<CaseContactRole> CompRoles{get;set;}
    public List<CaseContactRole> WitnessRoles{get;set;}
    public List<Charge_Information__c> Charges{get; set;}
    public List<Scene_Locations__c> Locations{get;set;}
    public Date Today { get { return Date.today(); }}
    public list<Case> Cases{get;set;}
    public Case objCase{get;set;}
   
    public CaseContactRoleExtension(ApexPages.StandardController controller){ 
        Cases = [Select Id, CaseNumber, Account.Name, Account.BillingStreet, Account.BillingCity, Account.County__c, Account.BillingState, Account.BillingPostalCode, Account.Phone,Agency_Case__c, Contact.Name, Contact.Title, Contact.Phone, Contact.MobilePhone, Contact.Fax, Contact.Email, Description, Investigator__c  FROM Case WHERE Id = :ApexPages.currentPage().getparameters().get('Id')];
        if(Cases.size()>0)
            objCase = Cases[0];
        ContactRoles = [SELECT Contact.Name, Contact.Email, Contact.Gender__c, Contact.Alias__c, Contact.MailingStreet, Contact.MailingCity, Contact.MailingState, Contact.MailingPostalCode, Contact.County__c, Contact.Phone, Contact.MobilePhone, Role, Contact.License_or_ID_State__c, Contact.Drivers_License_or_State_ID__c, Contact.Account.Name, Contact.Account.Website, Contact.Account.BillingStreet, Contact.Account.BillingCity, Contact.Account.County__c, Contact.Account.BillingState, Contact.Account.BillingPostalCode, Contact.Account.Phone, Contact.Account.EIN_Number__c FROM CaseContactRole WHERE Role = 'Subject/Defendant' AND CasesId =:((Case)controller.getRecord()).Id];
        CompRoles = [SELECT Contact.Name, Contact.Email, Contact.MailingStreet, Contact.MailingCity, Contact.MailingState, Contact.MailingPostalCode, Contact.County__c, Contact.Phone, Contact.MobilePhone, Role FROM CaseContactRole WHERE Role = 'Complainant' AND CasesId =:((Case)controller.getRecord()).Id];
        WitnessRoles = [SELECT Contact.Name, Contact.Email, Contact.MailingStreet, Contact.MailingCity, Contact.MailingState, Contact.MailingPostalCode, Contact.County__c, Contact.Phone, Contact.MobilePhone, Role FROM CaseContactRole WHERE Role = 'Witness' AND CasesId =:((Case)controller.getRecord()).Id];
        Locations = [SELECT Name, Address_1__c, Address_Line_2__c, City__c, County__c, Primary_Incident_Location__c, Region__c, State__c, Zipcode__c FROM Scene_Locations__c WHERE Case__c =:((Case)controller.getRecord()).Id AND Primary_Incident_Location__c=True ORDER BY CreatedDate ASC];
        Charges = [SELECT Name, Charge_Level__c, Charge_Count__c FROM Charge_Information__c WHERE Case__c =:((Case)controller.getRecord()).Id ];
    }
}