force-app/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Item__c/Action_Item__c.object-meta.xml
<CustomObject>
    <label>Cruelty Report</label>
    <nameField>
        <displayFormat>CR-{YYYY}-{0000}</displayFormat>
        <label>Cruelty Report #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cruelty Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Item_Role__c/Action_Item_Role__c.object-meta.xml
<CustomObject>
    <label>Cruelty Report Contact Role</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>CR Role #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cruelty Report Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Item_Role__c/fields/Action_Item__c.field-meta.xml
<CustomField>
    <fullName>Action_Item__c</fullName>
    <label>Cruelty Report</label>
    <referenceTo>Action_Item__c</referenceTo>
    <relationshipName>Action_Item_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Action_Item_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Action_Item_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Action_Item_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alternative Contact/Relative</fullName>
            </value>
            <value>
                <fullName>Animal Discharge Contact</fullName>
            </value>
            <value>
                <fullName>Animal Owner</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>County/Civil Attorney</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
            <value>
                <fullName>Officer</fullName>
            </value>
            <value>
                <fullName>Placement Shelter Contact</fullName>
            </value>
            <value>
                <fullName>Prosecutor</fullName>
            </value>
            <value>
                <fullName>Public Information Officer (PIO)</fullName>
            </value>
            <value>
                <fullName>Receiving Shelter Contact</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Witness</fullName>
            </value>
            <value>
                <fullName>Subject/Defendant</fullName>
                <isActive>false</isActive>
                <label>Subject/Defendant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Item_Scene_Location__c/Action_Item_Scene_Location__c.object-meta.xml
<CustomObject>
    <label>Action Item Scene Location</label>
    <nameField>
        <label>Action Item Scene Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Item Scene Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Item_Scene_Location__c/fields/Action_Item__c.field-meta.xml
<CustomField>
    <fullName>Action_Item__c</fullName>
    <label>Action Item</label>
    <referenceTo>Action_Item__c</referenceTo>
    <relationshipLabel>Action Item Scene Locations</relationshipLabel>
    <relationshipName>Action_Item_Scene_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Action_Item_Scene_Location__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+ Id ,  FirstName + &quot; &quot; + LastName )</formula>
    <label>Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Citizen</fullName>
            </value>
            <value>
                <fullName>Agency Representative</fullName>
            </value>
            <value>
                <fullName>Animal Control Officer</fullName>
            </value>
            <value>
                <fullName>Animal Owner</fullName>
            </value>
            <value>
                <fullName>Animal Rescue</fullName>
            </value>
            <value>
                <fullName>Animal Welfare Professional</fullName>
            </value>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Code Enforcement Officer</fullName>
            </value>
            <value>
                <fullName>Complainant</fullName>
            </value>
            <value>
                <fullName>County/Civil Attorney</fullName>
            </value>
            <value>
                <fullName>Defense Attorney</fullName>
            </value>
            <value>
                <fullName>Law Enforcement Contact</fullName>
            </value>
            <value>
                <fullName>Law Enforcement Officer</fullName>
            </value>
            <value>
                <fullName>Local Elected Official</fullName>
            </value>
            <value>
                <fullName>Officer/Complainant</fullName>
            </value>
            <value>
                <fullName>Prosecuting Attorney</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
            <value>
                <fullName>Senator</fullName>
            </value>
            <value>
                <fullName>Shelter Contact</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>State Representative</fullName>
            </value>
            <value>
                <fullName>State Senator</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Suspect</fullName>
            </value>
            <value>
                <fullName>US Representative</fullName>
            </value>
            <value>
                <fullName>US Senator</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Relocation Driver</fullName>
            </value>
            <value>
                <fullName>Behavior Case Worker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateActionItem_Obj.cls
public with sharing class CreateActionItem_Obj {

    public Action_Item__c caseVar{get;set;}
    
    
    public List<ContactWrapper> complainants {get;set;}
    public List<ContactWrapper> subjects {get;set;}
    public List<Action_Item_Scene_Location__c> sceneList{get;set;}
    public List<Contact> conList{get;set;}
    public List<Action_Item_Role__c> cRoleList{get;set;} 
    
    public CreateActionItem_Obj() {
        
        caseVar = new Action_Item__c();
        sceneList = new List<Action_Item_Scene_Location__c>();
        sceneList.add(new Action_Item_Scene_Location__c	());
        
        
        complainants = new List<ContactWrapper>();
        subjects = new List<ContactWrapper>();
        
        ContactWrapper cw = new ContactWrapper();
        cw.ccRole.role__c = 'Complainant';
        complainants.add(cw);
        cw.index = complainants.size();
        
        ContactWrapper cw1 = new ContactWrapper();
        cw1.ccRole.role__c = 'Subject/Defendant';
        subjects.add(cw1);
        cw1.index = subjects.size();
    }
    
    public pageReference saveData(){


/*        for(ContactWrapper cw : complainants) {
             if(cw.useOrAddContact == null ){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please provide contact details')); 
                return null;
            }
            if((cw.useOrAddContact == 'Add') && (cw.con.LastName == null || cw.con.MailingCity == null || cw.con.MailingState == null || cw.con.County__c == null  || cw.con.Contact_Type__c == null || cw.ccRole.Role__c == null)){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'We can not leave blank these contact fields: LastName,Mailing City,Mailing state,County,Role for this contact on this case,Contact Type'));
                return null;
            }
            if(cw.useOrAddContact == 'Use' && cw.ccRole.Role__c == null){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please provide Contact Role '));
                return null;
            }  
        }
        for(ContactWrapper cw : subjects) {
            if(cw.useOrAddContact == null ){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please provide contact details')); 
                return null;
            }
            if((cw.useOrAddContact == 'Add') && (cw.con.LastName == null || cw.con.MailingCity == null || cw.con.MailingState == null || cw.con.County__c == null || cw.ccRole.Role__c == null || cw.con.Contact_Type__c == null)){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'We can not leave blank these contact fields: Last Name, Mailing City, Mailing State, County, Role, Contact Type'));
                return null;
            }
            if(cw.useOrAddContact == 'Use' && cw.ccRole.Role__c == null){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please provide Contact Role '));
                return null;
            } 
        }*/
         
        insert caseVar;
        
        for(Action_Item_Scene_Location__c sl : sceneList){ 
            sl.Action_Item__c = caseVar.Id;
        }
        insert sceneList;
         conList = new List<Contact>();
        for(ContactWrapper cw : complainants) {
            if(cw.useOrAddContact == 'Add') {
                conList.add(cw.con);
            }
        }
        for(ContactWrapper cw : subjects) {
            if(cw.useOrAddContact == 'Add') {
                conList.add(cw.con);
            }
        }
        insert conList;
        cRoleList = new List<Action_Item_Role__c>();
        for(ContactWrapper cw : complainants) {
            if(cw.useOrAddContact == 'Add') {
                
                cw.ccRole.Contact__c = cw.con.Id;
                cw.ccRole.Action_Item__c = caseVar.Id;
            } else {
                cw.ccRole.Contact__c = cw.selectedConId;
                cw.ccRole.Action_Item__c = caseVar.Id;
            }
            if (cw.ccRole.Contact__c != null){
                cRoleList.add(cw.ccRole);
            }
        }

        for(ContactWrapper cw : subjects) {
            if(cw.useOrAddContact == 'Add') {
                cw.ccRole.Contact__c = cw.con.Id;
                cw.ccRole.Action_Item__c = caseVar.Id; 
            } else {
                cw.ccRole.Contact__c = cw.selectedConId;
                cw.ccRole.Action_Item__c = caseVar.Id;  
            }
            if (cw.ccRole.Contact__c != null){
                cRoleList.add(cw.ccRole);
            }
            
        }
        system.debug(cRoleList);
        if (cRoleList != null){
       		insert cRoleList;
        }
        
        Schema.DescribeSObjectResult result = Action_Item__c.SObjectType.getDescribe();
        PageReference ref = new PageReference('/' + result.getKeyPrefix());
        ref.setRedirect(true); 
        return ref; 
    }
    
    public void back(){
        String indexStr = Apexpages.currentPage().getParameters().get('index');
        String typeStr = Apexpages.currentPage().getParameters().get('type');
        system.debug('indexStr:'+indexStr);
        Integer index = Integer.valueOf(indexStr);
        if(index != 1){
            complainants.remove(index-1);
        }
    }
    
    public void backSubject(){
        String indexStr = Apexpages.currentPage().getParameters().get('index');
        String typeStr = Apexpages.currentPage().getParameters().get('type');
        system.debug('indexStr:'+indexStr);
        Integer index = Integer.valueOf(indexStr);
        if(index != 1){
            subjects.remove(index-1);
        }
    }
    
    public void Remove(){
        String indexStr = Apexpages.currentPage().getParameters().get('index');
        String typeStr = Apexpages.currentPage().getParameters().get('type');
        system.debug('indexStr:'+indexStr);
        Integer index = Integer.valueOf(indexStr);
        if(index != 1){
            sceneList.remove(index-1);
        }
    }
    
    public void searchContact(){
        String indexStr = Apexpages.currentPage().getParameters().get('index');
        String typeStr = Apexpages.currentPage().getParameters().get('type');
        system.debug('indexStr:'+indexStr);
        Integer index = Integer.valueOf(indexStr); 
        ContactWrapper cw = null;
        if(typeStr == 'complainant') {
            for(ContactWrapper cw1 : complainants) {
                cw = cw1;
                if(cw1.index == index) {
                    break;
                }
            }
        } else {
            for(ContactWrapper cw1 : subjects) {
                cw = cw1;
                if(cw1.index == index) {
                    break;
                }
            }
        }
        
        system.debug('cw::'+cw);
        system.debug('cw.conSearchText:'+cw.conSearchText);
        string whereCondOne = cw.conSearchText+'%';
        if(cw.conSearchText!=null && cw.conSearchText != ''){
            
            List<Contact> conListOne = [select Id,Name,FirstName,LastName,Contact_Type__c,MailingCity,MailingState,MailingStreet,Account.Name from Contact where (LastName like :whereCondOne or FirstName like :whereCondOne)];
            cw.searchResults = new List<SelectOption>();
            for(Contact cont : conListOne){
                cw.searchResults.add(new SelectOption(cont.Id,cont.Name + ' - ' + cont.MailingStreet +' , '+ cont.MailingCity +' , '+ cont.MailingState +' - '+ ' Account: ' + cont.Account.Name + ' - ' + 'Contact Type' + ': ' + cont.Contact_Type__c));
            }
        }
        system.debug('--cw.searchResults---'+cw.searchResults);
    }
    
    public void addNewLocation() {
        Action_Item_Scene_Location__c sc = new Action_Item_Scene_Location__c();
        sceneList.add(sc);
        system.debug('@@sceneList@@'+sceneList);
    }
    
    public void addComplainant() {
        ContactWrapper cw = new ContactWrapper();
        cw.ccRole.role__c = 'Complainant';
        complainants.add(cw);
        cw.index = complainants.size();
    }
    
    public void addSubject() {
        ContactWrapper cw = new ContactWrapper();
        cw.ccRole.role__c = 'Subject/Defendant';
        subjects.add(cw);
        cw.index = subjects.size();
    }
    
    public class ContactWrapper {   
        public String conSearchText {get;set;}
        public String selectedConId {get;set;}
        public Contact con {get;set;} 
        public integer index {get;set;}  
        public List<SelectOption> searchResults {get;set;}
        public String useOrAddContact {get;set;}
        public Action_Item_Role__c ccRole{get;set;}
        public String validationError {get;set;}
       
        public ContactWrapper() { 
            con = new Contact();
            ccRole = new Action_Item_Role__c(); 
            
            
        }
    }
}