force-app/main/default/objects/Domain_Action_Binding__mdt/Domain_Action_Binding__mdt.object-meta.xml
<CustomObject>
    <description>Stores BINDINGS to cq_iDomainAction implementations for Trigger processing.</description>
    <label>CQ Domain Action Binding</label>
    <pluralLabel>CQ Domain Action Bindings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Domain_Action_Binding__mdt/fields/DomainActionImplementation__c.field-meta.xml
<CustomField>
    <fullName>DomainActionImplementation__c</fullName>
    <description>What cq_IDomainAction class to .Execute</description>
    <inlineHelpText>What cq_IDomainAction class to .Execute</inlineHelpText>
    <label>DomainActionImplementation</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Domain_Action_Binding__mdt/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Order in which to fire Trigger actions on the same SObject for the same Trigger state. Multiple can exist at the same Sequence.</description>
    <inlineHelpText>Order in which to fire Trigger actions on the same SObject for the same Trigger state. Multiple can exist at the same Sequence.</inlineHelpText>
    <label>Sequence</label>
    <precision>9</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Domain_Action_Binding__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>The SObject to process the Trigger action for</description>
    <inlineHelpText>The SObject to process the Trigger action for</inlineHelpText>
    <label>SObject</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Domain_Action_Binding__mdt/fields/TriggeredWhen__c.field-meta.xml
<CustomField>
    <fullName>TriggeredWhen__c</fullName>
    <label>TriggeredWhen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insert</fullName>
                <default>true</default>
                <label>Insert</label>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Domain_Action_Binding__mdt/fields/WhenToProcess__c.field-meta.xml
<CustomField>
    <fullName>WhenToProcess__c</fullName>
    <label>WhenToProcess</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Before</fullName>
                <default>true</default>
                <label>Before</label>
            </value>
            <value>
                <fullName>After</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/framework/cqfwlite/Base/DomainActionBindingSelector.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public without sharing class DomainActionBindingSelector  extends SObjectSelector{
    public DomainActionBindingSelector() { super(Domain_Action_Binding__mdt.SObjectType); }

    // implement required GetDefaultFields() method
    public override Set<Schema.SObjectField> GetDefaultFields() {
        return new Set<Schema.SObjectField> {
                Domain_Action_Binding__mdt.SObject__c,
                Domain_Action_Binding__mdt.WhenToProcess__c,
                Domain_Action_Binding__mdt.TriggeredWhen__c,
                Domain_Action_Binding__mdt.DomainActionImplementation__c,
                Domain_Action_Binding__mdt.Sequence__c
        };
    }

    // implement required GetDefaultOrderBy() method
    public override List<iOrderBy> GetDefaultOrderBy() {
        return new List<iOrderBy> {
                (iOrderBy) OrderBy.Ascending(Domain_Action_Binding__mdt.Sequence__c),
                (iOrderBy) OrderBy.Ascending(Domain_Action_Binding__mdt.DomainActionImplementation__c)
        };
    }

    /**
     * Query for retrieving Trigger-specific DomainAction bindings
     * @param  targetSObject String     The SObject the Trigger is executing on
     * @param  process       process    Before/After
     * @param  action        action     Insert/Update/Delete
     * @return  List of Domain_Action_Binding__mdt entries
     */
    public List<Domain_Action_Binding__mdt> GetForTrigger(String targetSObject, String process, String action) {
        iQueryFactory qf = GetQueryFactory()
                .WithCriteria(Criteria.Equals(Domain_Action_Binding__mdt.SObject__c, targetSObject))
                .WithCriteria(Criteria.Equals(Domain_Action_Binding__mdt.WhenToProcess__c, process))
                .WithCriteria(Criteria.Equals(Domain_Action_Binding__mdt.TriggeredWhen__c, action));
        // THE PROCESS BELOW SHOULD ONLY BE REPEATED FOR CMDT SOBJECTS
        // YOU CAN NOT INSERT CMDT DURING A UNIT TEST, SO THIS HACK LETS THE UNIT TESTS HAPPEN
        // DO NOT REPEAT THIS PATTERN IN A NORMAL SOBJECT SELECTOR
        if (Test.isRunningTest()) {
            String sObjectName = Account.getSObjectType().getDescribe().getName();
            return new List<Domain_Action_Binding__mdt>{
                    new Domain_Action_Binding__mdt(
                            SObject__c = sObjectName,
                            WhenToProcess__c = 'Before',
                            TriggeredWhen__c = 'Insert',
                            DomainActionImplementation__c = 'cqtest_SObjectDomain.testDomainActionOne',
                            Sequence__c = 10
                    ),
                    new Domain_Action_Binding__mdt(
                            SObject__c = sObjectName,
                            WhenToProcess__c = 'Before',
                            TriggeredWhen__c = 'Insert',
                            DomainActionImplementation__c = 'cqtest_SObjectDomain.testDomainActionOnenTwo',
                            Sequence__c = 10
                    )
            };
        } else {
            return (List<Domain_Action_Binding__mdt>) qf.Execute();
        }
    }
}