force-app/main/default/objects/Domain_Action_Binding__mdt/Domain_Action_Binding__mdt.object-meta.xml
<CustomObject>
    <description>Stores BINDINGS to cq_iDomainAction implementations for Trigger processing.</description>
    <label>CQ Domain Action Binding</label>
    <pluralLabel>CQ Domain Action Bindings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Domain_Action_Binding__mdt/fields/DomainActionImplementation__c.field-meta.xml
<CustomField>
    <fullName>DomainActionImplementation__c</fullName>
    <description>What cq_IDomainAction class to .Execute</description>
    <inlineHelpText>What cq_IDomainAction class to .Execute</inlineHelpText>
    <label>DomainActionImplementation</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Config__c/Trigger_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger Config</label>
</CustomObject>

force-app/main/default/objects/Trigger_Config__c/fields/Disable_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Disable_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CHECKING THIS BOX DISABLES ALL TRIGGER PROCESSING</description>
    <inlineHelpText>CHECKING THIS BOX DISABLES ALL TRIGGER PROCESSING</inlineHelpText>
    <label>Disable Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/framework/cqfwlite/Base/SObjectDomain.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class SObjectDomain implements iSObjectDomain{
    private TriggerProcess triggerProcess;
    private TriggerRequest request;
    private Boolean disableTrigger = false;

    public SObjectDomain(TriggerRequest triggerRequest) {
        request = triggerRequest;
        if (request == null) { disableTrigger = true; }
    }

    private Boolean TriggersDisabled() {
        if (disableTrigger) { return disableTrigger; }
        Trigger_Config__c triggerConfig = Trigger_Config__c.getInstance();
        return (triggerConfig != null && triggerConfig.Disable_Triggers__c == true);
    }

    /**
     * Queries Domain_Action_Binding__mdt to find all DomainAction implementations
     * Then executes them in sequence, passing in the Trigger's state & data
     */
    public void ExecuteTriggerActions() {
        if (TriggersDisabled()) { return; }
        List<Domain_Action_Binding__mdt> bindings = cq.App.DomainActionBindings().GetForTrigger(request.targetSObject.getDescribe().getName(), request.action, request.process);
        for (Domain_Action_Binding__mdt binding : bindings) {
            String actionName = binding.DomainActionImplementation__c;
            //System.debug('Domain Action Bindings ==> ' + actionName);
            if (String.isBlank(actionName)) { continue; }
            Type actionType = Type.forName(actionName);
            //System.debug('Action Type ==> ' + actionType);
            if (actionType instanceOf iDomainAction) {
                iDomainAction dynamicAction = (iDomainAction) actionType.newInstance();
                //System.debug('Domain Action ==> ' + dynamicAction);
                ServiceResponse response = dynamicAction.Execute(
                        new ServiceRequest(actionName, request.process + ' ' + request.action).WithParams
                                ('TriggerRequest', request)
                );
                //System.debug(response);
                if (response.Status == RequestStatus.ERROR) {
                    LogHandler.Instance.Error(response.ThrownException);
                }
            }
        }
    }
}