force-app/main/default/objects/Picklist_Description_Config__mdt/Picklist_Description_Config__mdt.object-meta.xml
<CustomObject>
    <label>Picklist Description Config</label>
    <pluralLabel>Picklist Description Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Picklist_Description_Config__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Behavior_in_Kennel__c</fullName>
            </value>
            <value>
                <fullName>Behavior_on_Leash__c</fullName>
            </value>
            <value>
                <fullName>Social_Behavior_P1__c</fullName>
            </value>
            <value>
                <fullName>Social_Behavior_P2_2__c</fullName>
            </value>
            <value>
                <fullName>Pleasant_Touch__c</fullName>
            </value>
            <value>
                <fullName>Unpleasant_Touch_1st__c</fullName>
            </value>
            <value>
                <fullName>Unpleasant_Touch_2nd__c</fullName>
            </value>
            <value>
                <fullName>Play_Test_Tug_P1__c</fullName>
            </value>
            <value>
                <fullName>Play_Test_Tug_P2__c</fullName>
            </value>
            <value>
                <fullName>Tag_Test__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P1_Push_Face__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P2_Push_Face__c</fullName>
            </value>
            <value>
                <fullName>Toddler_Doll_P1__c</fullName>
            </value>
            <value>
                <fullName>Toddler_Doll_P2__c</fullName>
            </value>
            <value>
                <fullName>Scolding_Person_P1__c</fullName>
            </value>
            <value>
                <fullName>Scolding_Person_P2__c</fullName>
            </value>
            <value>
                <fullName>Fake_Dog__c</fullName>
            </value>
            <value>
                <fullName>Same_Sex_P1__c</fullName>
            </value>
            <value>
                <fullName>Same_Sex_P2__c</fullName>
            </value>
            <value>
                <fullName>Same_Sex_P3__c</fullName>
            </value>
            <value>
                <fullName>Opposite_Sex_P1__c</fullName>
            </value>
            <value>
                <fullName>Opposite_Sex_P2__c</fullName>
            </value>
            <value>
                <fullName>Opposite_Sex_P3__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P1_Touch_Face__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P1_Touch_Neck__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P1_Touch_Body__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P2_Touch_Face__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P2_Touch_Neck__c</fullName>
            </value>
            <value>
                <fullName>Resource_Guarding_P2_Touch_Body__c</fullName>
            </value>
            <value>
                <fullName>Puppy_Behavior_in_Kennel__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Config__mdt/Test_Config__mdt.object-meta.xml
<CustomObject>
    <label>Test Config</label>
    <pluralLabel>Test Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Test_Config__mdt/fields/Picklist_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Picklist_API_Name__c</fullName>
    <label>Picklist API Name</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Test_Config__mdt/fields/Test_Comment_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Test_Comment_Field_Name__c</fullName>
    <description>API Name of Test Comments Field</description>
    <label>Test Comment Field Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Test_Config__mdt/fields/Test_Skip_Reason_Field__c.field-meta.xml
<CustomField>
    <fullName>Test_Skip_Reason_Field__c</fullName>
    <label>Test Skip Reason Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MetadataUtil.cls
/**
 * Created by barne on 5/24/2021.
 */

public with sharing class MetadataUtil {

    public static Map<String, Test_Config__mdt> mapOfPicklistAndMetadata() {
        Map<String, Test_Config__mdt> configMap = Test_Config__mdt.getAll();
        Map<String, Test_Config__mdt> nStrings = new Map<String, Test_Config__mdt>();

        for (Test_Config__mdt mConfig : configMap.values()) {
            nStrings.put(mConfig.Picklist_API_Name__c , mConfig);
        }
        //System.debug('$$$ Map of Test Config Metadata ===> ' + nStrings.size());
        return nStrings;
    }

    public static Map<String, Picklist_Description_Config__mdt> mapOfPicklistDescriptions() {
        Map<String, Picklist_Description_Config__mdt> configMap = Picklist_Description_Config__mdt.getAll();
        return configMap;
    }

    public static String commentField(String field) {
        //System.debug('@@@@@@@@@@@@@@@@@@@@Executing Comment Field Method');
        Map<String, Test_Config__mdt> configMap = mapOfPicklistAndMetadata();

        String commentField = '';

        if (configMap.containsKey(field)) {
            Test_Config__mdt testConfig = configMap.get(field);
            //System.debug('@@@ Test Config Found ===> ' + testConfig);
            if (String.isNotEmpty(testConfig.Test_Comment_Field_Name__c)) {
                //System.debug('IS NOT EMPTY');
                commentField = testConfig.Test_Comment_Field_Name__c;
                //System.debug('#### this is a comment field ===> ' + commentField);
            }else {
                //System.debug('NONE FOUND');
            }
        }

        return commentField;
    }


    public static String skipField(String field) {
       // System.debug('Executing Skip Field Method');
        Map<String, Test_Config__mdt> configMap = mapOfPicklistAndMetadata();

        String skipField = '';

        if (configMap.containsKey(field)) {
            Test_Config__mdt testConfig = configMap.get(field);
            //System.debug('@@@ Test Config Found ===> ' + testConfig);
            if (String.isNotEmpty(testConfig.Test_Skip_Reason_Field__c)) {
                //System.debug('IS NOT EMPTY');
                skipField = testConfig.Test_Skip_Reason_Field__c;
                System.debug('SKIP FIELD VALUE ===> ' + skipField);

            }
        }else {
            System.debug('NOT FOUND =====> ' + field);
            return null;
        }

        return skipField;
    }

    public static List<Picklist_Description_Config__mdt> getFieldValues(String field) {
        Map<String, Picklist_Description_Config__mdt> configMap = mapOfPicklistDescriptions();
        List<Picklist_Description_Config__mdt> configs = new List<Picklist_Description_Config__mdt>();
        List<Picklist_Description_Config__mdt> nfound = new List<Picklist_Description_Config__mdt>();
        //System.debug('Config Map Values: ' +  configMap.values());
        //System.debug('Config Map Size: ' +  configMap.size());
        //System.debug(field);

        for (Picklist_Description_Config__mdt config : configMap.values()) {
            if (config.Field_API_Name__c.startsWith(field)) {
                configs.add(config);
            }else {
                nfound.add(config);
            }
        }
        //System.debug(nfound.size());
        //System.debug(configs.size());
        return configs;
    }

}