force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>What user will this Contact log into Salesforce ass</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WeeklyOff__c.field-meta.xml
<CustomField>
    <fullName>WeeklyOff__c</fullName>
    <label>Weekly Off</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OutOfOfficeControllerTest.cls
@isTest
public class OutOfOfficeControllerTest {
    
    @isTest
    static void testOutOfOfficeRT(){
        List<Map<String, String>> rtList = OutOfOfficeController.getOutOfOfficeRTs();
        System.assertNotEquals(null, rtList);
    }
    
    @isTest
    static void testGetContactId(){
        Contact c = New Contact(FirstName = 'test',
                                LastName = 'user',
                                Email = 'test@user.example.com',
                                WeeklyOff__c = 'Monday;Wednesday',
                               User__c = UserInfo.getUserId());
        insert c;
        OutOfOfficeController.ContactResult result = OutOfOfficeController.getContactId();
        System.assertEquals(result.isSuccess, true);
    }
    
    @isTest
    static void testGetContactIdNegative(){
        Contact c = New Contact(FirstName = 'test',
                                LastName = 'user',
                                Email = 'test@user.example.com',
                                WeeklyOff__c = 'Monday;Wednesday');
        insert c;
        OutOfOfficeController.ContactResult result = OutOfOfficeController.getContactId();
        System.assertEquals(result.isSuccess, false);
    }
    
    @isTest
    static void testhandleOutOfOfficeSchedule(){
        Contact c = New Contact(FirstName = 'test',
                                LastName = 'user',
                                Email = 'test@user.example.com',
                                WeeklyOff__c = 'Monday;Wednesday',
                               User__c = UserInfo.getUserId());
        insert c;
        OutOfOfficeController.handleOutOfOfficeSchedule();
        ControllerHelper.getFieldProperties(Contact.FirstName);
        ControllerHelper.Properties cp = new ControllerHelper.Properties('id', 'Test', new List<PicklistEntry>{}, Account.Type.getDescribe());
    	System.assertNotEquals(cp, null);
    }
}