force-app/main/default/objects/Contact/fields/WeeklyOff__c.field-meta.xml
<CustomField>
    <fullName>WeeklyOff__c</fullName>
    <label>Weekly Off</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OutOfOffice__c/OutOfOffice__c.object-meta.xml
<CustomObject>
    <label>OutOfOffice</label>
    <nameField>
        <displayFormat>{YYYY}/{MM}/{DD}-{0}</displayFormat>
        <label>OutOfOffice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OutOfOffices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactTriggerHandlerTest.cls
@isTest
public class ContactTriggerHandlerTest {
	
    @testSetup
    static void setupData(){
        TestDataFactory.init();
        Contact c = New Contact(FirstName = 'test',
                                LastName = 'user',
                                Email = 'test@user.example.com',
                                WeeklyOff__c = 'Monday;Wednesday');
        insert c;
    } 
    
    @isTest
    static void testWeeklyOffs(){
        List<Contact> contacts = [Select WeeklyOff__c from Contact];
        for(Contact c : contacts){
        	c.WeeklyOff__c = 'Saturday;Sunday';
        }
        update contacts;
        List<OutOfOffice__c> outofoffices = [Select Id from OutOfOffice__c];
        System.assertNotEquals(null, outofoffices);
    }
}