force-app/main/default/objects/Daily_Enrichment__c/Daily_Enrichment__c.object-meta.xml
<CustomObject>
    <label>Daily Enrichment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Daily Enrichment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Enrichment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Enrichment__c/fields/Enrichment_Activities__c.field-meta.xml
<CustomField>
    <fullName>Enrichment_Activities__c</fullName>
    <label>Enrichment Activities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Enrichment_Activities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Enrichment__c/fields/Enrichment_Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Enrichment_Coordinator__c</fullName>
    <label>Enrichment Coordinator</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hailey Kohl</fullName>
            </value>
            <value>
                <fullName>Carrie Bretz</fullName>
            </value>
            <value>
                <fullName>Tony Rankin</fullName>
            </value>
            <value>
                <fullName>Courtney Leigh</fullName>
            </value>
            <value>
                <fullName>Kay Duffy Taylor</fullName>
            </value>
            <value>
                <fullName>Bill Duvall</fullName>
            </value>
            <value>
                <fullName>Jess Drew</fullName>
            </value>
            <value>
                <fullName>Joanne Smith</fullName>
            </value>
            <value>
                <fullName>Vicky Watkins</fullName>
            </value>
            <value>
                <fullName>Heather Boothe</fullName>
            </value>
            <value>
                <fullName>Scott Sherlock</fullName>
            </value>
            <value>
                <fullName>Tom Griswold</fullName>
            </value>
            <value>
                <fullName>EG Aguilar</fullName>
            </value>
            <value>
                <fullName>Adam Gebauer</fullName>
            </value>
            <value>
                <fullName>Cindy Walden</fullName>
            </value>
            <value>
                <fullName>Andrea Stout</fullName>
            </value>
            <value>
                <fullName>Catherine Adair</fullName>
            </value>
            <value>
                <fullName>Jacqui Moreland</fullName>
            </value>
            <value>
                <fullName>Tiffany Van Hook</fullName>
            </value>
            <value>
                <fullName>Lois Michael</fullName>
            </value>
            <value>
                <fullName>Jeremy Robichaud</fullName>
            </value>
            <value>
                <fullName>Jeannie Pittman</fullName>
            </value>
            <value>
                <fullName>Joe Gordon</fullName>
            </value>
            <value>
                <fullName>Sarah Getman</fullName>
            </value>
            <value>
                <fullName>Lacie Davis</fullName>
            </value>
            <value>
                <fullName>Joe Hinkle</fullName>
            </value>
            <value>
                <fullName>Lindsey Cooke</fullName>
            </value>
            <value>
                <fullName>Raymond Willis</fullName>
            </value>
            <value>
                <fullName>Salina Wenzel</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Enrichment_Activities.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 on 1</fullName>
    </customValue>
    <customValue>
        <fullName>Backyard</fullName>
    </customValue>
    <customValue>
        <fullName>Ball/rock pit (foraging)</fullName>
    </customValue>
    <customValue>
        <fullName>Basic Training</fullName>
    </customValue>
    <customValue>
        <fullName>Dig pit</fullName>
    </customValue>
    <customValue>
        <fullName>Fetch with rules</fullName>
    </customValue>
    <customValue>
        <fullName>Foster overnights</fullName>
    </customValue>
    <customValue>
        <fullName>Four on the Floor for Leash</fullName>
    </customValue>
    <customValue>
        <fullName>Gym</fullName>
    </customValue>
    <customValue>
        <fullName>IPY</fullName>
    </customValue>
    <customValue>
        <fullName>Kennel Presence</fullName>
    </customValue>
    <customValue>
        <fullName>LLW</fullName>
    </customValue>
    <customValue>
        <fullName>Nose Work</fullName>
    </customValue>
    <customValue>
        <fullName>Outside ExPen</fullName>
    </customValue>
    <customValue>
        <fullName>Office Time</fullName>
    </customValue>
    <customValue>
        <fullName>Offsite Trips</fullName>
    </customValue>
    <customValue>
        <fullName>OPY</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Outside Walks</fullName>
    </customValue>
    <customValue>
        <fullName>PC Tug</fullName>
    </customValue>
    <customValue>
        <fullName>Puppy Enrichment/Socialization</fullName>
    </customValue>
    <customValue>
        <fullName>Puppy Handling</fullName>
    </customValue>
    <customValue>
        <fullName>Quiet Time</fullName>
    </customValue>
    <customValue>
        <fullName>Real-Life Room</fullName>
    </customValue>
    <customValue>
        <fullName>Shelter Notes</fullName>
    </customValue>
    <customValue>
        <fullName>Snuffle mat</fullName>
    </customValue>
    <customValue>
        <fullName>Trick Training</fullName>
    </customValue>
    <customValue>
        <fullName>Tug pully</fullName>
    </customValue>
    <customValue>
        <fullName>Tug with rules</fullName>
    </customValue>
    <customValue>
        <fullName>Walk</fullName>
    </customValue>
    <masterLabel>Enrichment Activities</masterLabel>
</GlobalValueSet>

force-app/main/default/test/test_MultiPickToCheckboxGroupController.cls
@isTest
public with sharing class test_MultiPickToCheckboxGroupController {
    @isTest
    static void getCoordinatorPicklistValues() {
        Test.startTest();
        List<MultiPickToCheckboxGroupController.PicklistOption> options = MultiPickToCheckboxGroupController.getPicklistValues('Daily_Enrichment__c', 'Enrichment_Coordinator__c');
        Test.stopTest();
        System.assert(options.size() > 0);
    }

    @isTest
    static void getActivitiesPicklistValues() {
        Test.startTest();
        List<MultiPickToCheckboxGroupController.PicklistOption> options = MultiPickToCheckboxGroupController.getPicklistValues('Daily_Enrichment__c', 'Enrichment_Activities__c');
        Test.stopTest();
        System.assert(options.size() > 0);
    }

    @isTest
    static void baseClass() {
        Test.startTest();
        MultiPickToCheckboxGroupController.PicklistOption pO1 = new MultiPickToCheckboxGroupController.PicklistOption();
        pO1.label = 'label';
        pO1.value = 'value';
        MultiPickToCheckboxGroupController.PicklistOption pO2 = new MultiPickToCheckboxGroupController.PicklistOption('label', 'value');
        Test.stopTest();
        System.assertEquals(pO1.label, pO2.label);
        System.assertEquals(pO1.value, pO2.value);
    }
}