force-app/main/default/objects/Activity/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <formula>TEXT(Animal__r.Gender__c)</formula>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General Task</fullName>
            </value>
            <value>
                <fullName>Treatment</fullName>
            </value>
            <value>
                <fullName>MRC_BRC_Follow_UP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>This object will house all the details related to animals related to a case</description>
    <label>Animal</label>
    <nameField>
        <label>Animal ID #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age Estimate at Intake</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Age_Estimate_at_Intake</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/BRC_Status__c.field-meta.xml
<CustomField>
    <fullName>BRC_Status__c</fullName>
    <label>BRC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Candidate</fullName>
            </value>
            <value>
                <fullName>Survey Complete</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;Unspecified&quot;</defaultValue>
    <label>Primary Color</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Primary_Color</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <label>Current Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Current_Recent_Shelter_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Recent_Shelter_Location__c</fullName>
    <label>Current/Recent Shelter Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Discharged_to_Contact__c.field-meta.xml
<CustomField>
    <fullName>Discharged_to_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Discharged to Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Animals (Discharged to Contact)</relationshipLabel>
    <relationshipName>Animals1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Email_Notification__c.field-meta.xml
<CustomField>
    <fullName>Email_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Automatic email sent to caseworker and manager when ownership is granted use the surrender field to trigger</description>
    <label>Email Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Feeding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Feeding_Amount__c</fullName>
    <label>Feeding Amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Final_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Final_Outcome__c</fullName>
    <label>Final Outcome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Formatted_Address__c.field-meta.xml
<CustomField>
    <fullName>Formatted_Address__c</fullName>
    <label>Formatted Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;Unknown&quot;</defaultValue>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Animal__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sex</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Handling_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Handling_Instructions__c</fullName>
    <label>Handling Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/MRC_Status__c.field-meta.xml
<CustomField>
    <fullName>MRC_Status__c</fullName>
    <label>MRC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MRC Candidate</fullName>
                <label>Candidate</label>
            </value>
            <value>
                <fullName>MRC Accepted</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>MRC Declined</fullName>
                <label>Declined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Seizure_Surrender_Date__c.field-meta.xml
<CustomField>
    <fullName>Seizure_Surrender_Date__c</fullName>
    <label>Seizure/Surrender Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DG</fullName>
            </value>
            <value>
                <fullName>TP</fullName>
            </value>
            <value>
                <fullName>TR</fullName>
            </value>
            <value>
                <fullName>KH</fullName>
            </value>
            <value>
                <fullName>LG</fullName>
            </value>
            <value>
                <fullName>JR</fullName>
            </value>
            <value>
                <fullName>NR</fullName>
            </value>
            <value>
                <fullName>MW</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>LD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Type_of_Animal__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Animal__c</fullName>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Species</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/Animal_Daily_Care__c.object-meta.xml
<CustomObject>
    <label>Animal Daily Care</label>
    <nameField>
        <displayFormat>ADCN-{0000}</displayFormat>
        <label>Animal Daily Care Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals Daily Care</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Animals Daily Care</relationshipLabel>
    <relationshipName>Animals_Daily_Care</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Daily_Care__c.field-meta.xml
<CustomField>
    <fullName>Daily_Care__c</fullName>
    <label>Daily Care</label>
    <referenceTo>Daily_Care__c</referenceTo>
    <relationshipLabel>Animals Daily Care</relationshipLabel>
    <relationshipName>Animals_Daily_Care</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Feeding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Feeding_Amount__c</fullName>
    <label>Feeding Amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Handling_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Handling_Instructions__c</fullName>
    <label>Handling Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Movements_For_Cleaning__c.field-meta.xml
<CustomField>
    <fullName>Movements_For_Cleaning__c</fullName>
    <label>Movements For Cleaning</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <label>Round</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Special_Care_Outside_TX__c.field-meta.xml
<CustomField>
    <fullName>Special_Care_Outside_TX__c</fullName>
    <label>Special Care Outside TX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Daily_Care__c/fields/Special_Care_TX__c.field-meta.xml
<CustomField>
    <fullName>Special_Care_TX__c</fullName>
    <label>Special Care TX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Care__c/Daily_Care__c.object-meta.xml
<CustomObject>
    <label>Daily Care</label>
    <nameField>
        <displayFormat>DCN-{0000}</displayFormat>
        <label>Daily Care Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Care</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Config__c/Trigger_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger Config</label>
</CustomObject>

force-app/main/default/objects/Trigger_Config__c/fields/Animal_Trigger_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Animal_Trigger_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Animal Trigger Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Age_Estimate_at_Intake.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Juvenile w/dam</fullName>
    </customValue>
    <customValue>
        <fullName>&lt; 6 months</fullName>
    </customValue>
    <customValue>
        <fullName>0-4 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-8 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>8-12 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>12-16 weeks</fullName>
    </customValue>
    <customValue>
        <fullName>4-6 months</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>6 months - 1 year</fullName>
    </customValue>
    <customValue>
        <fullName>1 year - 2 years</fullName>
    </customValue>
    <customValue>
        <fullName>2-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>5-7 years</fullName>
    </customValue>
    <customValue>
        <fullName>7-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>greater than 10 yrs</fullName>
    </customValue>
    <customValue>
        <fullName>Egg</fullName>
    </customValue>
    <customValue>
        <fullName>Chick: Up To 8 Weeks</fullName>
    </customValue>
    <customValue>
        <fullName>Pullet: Female &lt; 2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Adult: &gt;2 YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Stag: Male &lt;2YRS</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (with dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Foal (without dam)</fullName>
    </customValue>
    <customValue>
        <fullName>Weanling</fullName>
    </customValue>
    <customValue>
        <fullName>Yearling</fullName>
    </customValue>
    <customValue>
        <fullName>2-3 years</fullName>
    </customValue>
    <customValue>
        <fullName>4-5 years</fullName>
    </customValue>
    <customValue>
        <fullName>6-10 years</fullName>
    </customValue>
    <customValue>
        <fullName>11-15 years</fullName>
    </customValue>
    <customValue>
        <fullName>15-20 years</fullName>
    </customValue>
    <customValue>
        <fullName>20+ years</fullName>
    </customValue>
    <customValue>
        <fullName>Chick (0-10 wks.)</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown At Intake</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
        <isActive>false</isActive>
        <label>Unknown</label>
    </customValue>
    <masterLabel>Age Estimate at Intake</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Primary_Color.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Bay roan</fullName>
    </customValue>
    <customValue>
        <fullName>Beige</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Blue</fullName>
    </customValue>
    <customValue>
        <fullName>Blue roan</fullName>
    </customValue>
    <customValue>
        <fullName>Brindle</fullName>
    </customValue>
    <customValue>
        <fullName>Brown</fullName>
    </customValue>
    <customValue>
        <fullName>Buckskin</fullName>
    </customValue>
    <customValue>
        <fullName>Buff</fullName>
    </customValue>
    <customValue>
        <fullName>Calico</fullName>
    </customValue>
    <customValue>
        <fullName>Charcoal</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Chestnut/Sorrel</fullName>
    </customValue>
    <customValue>
        <fullName>Chocolate</fullName>
    </customValue>
    <customValue>
        <fullName>Cream</fullName>
    </customValue>
    <customValue>
        <fullName>Dun</fullName>
    </customValue>
    <customValue>
        <fullName>Fawn</fullName>
    </customValue>
    <customValue>
        <fullName>Golden</fullName>
    </customValue>
    <customValue>
        <fullName>Green</fullName>
    </customValue>
    <customValue>
        <fullName>Grey</fullName>
    </customValue>
    <customValue>
        <fullName>Grulla</fullName>
    </customValue>
    <customValue>
        <fullName>Hairless</fullName>
    </customValue>
    <customValue>
        <fullName>Liver chestnut</fullName>
    </customValue>
    <customValue>
        <fullName>Orange</fullName>
    </customValue>
    <customValue>
        <fullName>Palomino</fullName>
    </customValue>
    <customValue>
        <fullName>Red</fullName>
    </customValue>
    <customValue>
        <fullName>Red roan</fullName>
    </customValue>
    <customValue>
        <fullName>Roan</fullName>
    </customValue>
    <customValue>
        <fullName>Seal</fullName>
    </customValue>
    <customValue>
        <fullName>Unspecified</fullName>
    </customValue>
    <masterLabel>Primary Color</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sex.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <customValue>
        <fullName>FS</fullName>
    </customValue>
    <customValue>
        <fullName>FU</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MU</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Stallion</fullName>
    </customValue>
    <customValue>
        <fullName>Mare</fullName>
    </customValue>
    <customValue>
        <fullName>Gelding</fullName>
    </customValue>
    <customValue>
        <fullName>Colt (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Filly (&lt;3 years)</fullName>
    </customValue>
    <customValue>
        <fullName>Male intact</fullName>
    </customValue>
    <customValue>
        <fullName>Male altered</fullName>
    </customValue>
    <customValue>
        <fullName>Male unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Female altered</fullName>
    </customValue>
    <customValue>
        <fullName>Female intact</fullName>
    </customValue>
    <customValue>
        <fullName>Female unknown</fullName>
    </customValue>
    <customValue>
        <fullName>(Unknown)</fullName>
        <isActive>false</isActive>
        <label>(Unknown)</label>
    </customValue>
    <masterLabel>Sex</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Species.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avian</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Cow</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Equine</fullName>
    </customValue>
    <customValue>
        <fullName>Exotic</fullName>
    </customValue>
    <customValue>
        <fullName>Fowl</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <masterLabel>Species</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AnimalTriggerHandler.cls
public with sharing class AnimalTriggerHandler {
    @testVisible
    Private static Boolean alreadyRan = false;

    public static void Execute() {
        if (!Trigger.isExecuting) { return; }
        Trigger_Config__c config = Trigger_Config__c.getInstance();
        if (config != null  && config.Animal_Trigger_Enabled__c == false) { return; }
        if (Trigger.isUpdate && Trigger.isBefore ) {
            beforeUpdateHandler();
        }
    }
    
    public static void insertHandler(){
        reviewForMRCDailyCare((Animal__c[])Trigger.new);
/*        CaseContactRole conrole = new CaseContactRole();
        for (Animal__c a : (List<Animal__c>)Trigger.new){
            List<CaseContactRole> curroles = [SELECT Id from CaseContactRole WHERE CasesId =: a.Case__c AND ContactId =: a.Discharged_to_Contact__c AND Role = 'Animal Discharge Contact'];
            if (a.Discharged_to_Contact__c != null){
                conrole.CasesId = a.Case__c;
                conrole.ContactId = a.Discharged_to_Contact__c;
                conrole.Role = 'Animal Discharge Contact';   
                if (curroles.size() > 0){
                    break;
                } 
                else {
                insert conrole;
                }
            }
            
            if (a.Location__Latitude__s !=null){
                reverseGeoloc(a.Location__Latitude__s, a.Location__Longitude__s, a.Id);
                
            }

        }  */
    }
    
/*    public static void insertHandlerBefore(){
        string initials = '';
        for (Animal__c a : (List<Animal__c>)Trigger.new){
            if (a.Gender__c == null){
                a.Gender__c = 'Unknown';
            }
            
            if (a.Age__c == null){
                a.Age__c = 'Unknown At Intake';
            }
            
            if (a.Color__c == null){
                a.Color__c = 'Unspecified';
            }
            
//            if (a.Name.contains('Form')){
//                initials = UserInfo.getFirstName().substring(0,1) + UserInfo.getLastName().substring(0,1);
//                a.Team__c = initials;
//            }           
            
     
        }  
    }*/

    public static void beforeUpdateHandler() {
        Map<Id, SObject> toUpdate = Trigger.newMap;

    }

    public static void onBeforeUpdateHandler(List<Animal__c> anms, Map<Id, Animal__c> oldAnms){
        if(alreadyRan == true) return;
        Animal__c[] brcMrcApprovedAnimals = new Animal__c[0];
        for (Animal__c a : anms){
            Animal__c oldAnimal = oldAnms.get(a.Id);
            System.debug('anim: ' + a);
            System.debug('oldAnimal: ' + oldAnimal);
            if(
                a.Type_of_Animal__c == 'Dog' &&
                ((a.MRC_Status__c == 'MRC Accepted' && oldAnimal.MRC_Status__c != 'MRC Accepted' && a.Current_Recent_Shelter_Location__c != 'MRC') ||
                (a.BRC_Status__c == 'BRC Accepted' && oldAnimal.MRC_Status__c != 'BRC Accepted' && a.Current_Recent_Shelter_Location__c != 'BRC'))
            ){
                brcMrcApprovedAnimals.add(a);
            }
        }
        if(!brcMrcApprovedAnimals.isEmpty()){
            createBrcMrcTasks(brcMrcApprovedAnimals);
        }

        alreadyRan = true;
    }
    
    public static void updateHandler(List<Animal__c> anms, Map<Id, Animal__c> oldAnms){
        reviewForMRCDailyCare(anms, oldAnms);
        CaseContactRole[] conroles = new CaseContactRole[0];
        Map<Id, CaseContactRole> animalToCaseContactRoleMap = queryCaseContactRoles(anms);
        for (Animal__c a : anms){
            Id oldCon = oldAnms.get(a.id).Discharged_to_Contact__c;    
			if (a.Discharged_to_Contact__c != oldCon && a.Discharged_to_Contact__c != null){
                CaseContactRole ccr = animalToCaseContactRoleMap.containsKey(a.Id) ? animalToCaseContactRoleMap.get(a.Id) : null;
                if(ccr == null){
                    CaseContactRole conrole = new CaseContactRole(
                        CasesId = a.Case__c,
                        ContactId = a.Discharged_to_Contact__c,
                        Role = 'Animal Discharge Contact'
                    );
                    conRoles.add(conRole);
                }
            }
        }
        System.debug(conroles);
        insert conroles;
        if(RecursiveTriggerHandler.isFirstTime){
            RecursiveTriggerHandler.isFirstTime = false;
            LogHistory.LogHistory(oldAnms, anms);
        }
    }

    private static Map<Id, CaseContactRole> queryCaseContactRoles(Animal__c[] animals){
        Map<Id, Animal__c> caseToAnimalMap = new Map<Id, Animal__c>();
        Set<Id> caseIds = new Set<Id>();
        Set<Id> contactIds = new Set<Id>();
        Map<Id, CaseContactRole> animalToCCRMap = new Map<Id, CaseContactRole>();
        for(Animal__c anim: animals){
            //skip if discharge to contact is blank
            if(anim.Discharged_to_Contact__c == null) continue;
            caseToAnimalMap.put(anim.Case__c, anim);
            caseIds.add(anim.Case__c);
            contactIds.add(anim.Discharged_to_Contact__c);
        }

        for(CaseContactRole ccr : [SELECT Id, CasesId, ContactId FROM CaseContactRole WHERE CasesId IN: caseIds AND ContactId IN: contactIds]){
            //just in case we get a ccr without a matchinga case
            if(!caseToAnimalMap.containsKey(ccr.CasesId)) continue;

            Animal__c anim = caseToAnimalMap.get(ccr.CasesId);
            if(ccr.ContactId == anim.Discharged_to_Contact__c){
                animalToCCRMap.put(anim.Id, ccr);
            }
        }

        return animalToCCRMap;
    }
    
	@future(callout=true)
	public static void reverseGeoloc(Decimal lat, Decimal longit, Id animalId) {
        
		String address = '';
        Http h = new Http();
		HttpRequest req = new HttpRequest();
        address = 'https://maps.googleapis.com/maps/api/geocode/json?latlng='+String.valueOf(lat)+','+String.valueOf(longit)+'&result_type=street_address&key=AIzaSyB_vRSHbde-6dByBFtnz-shb4CjuG8OPH0';
       	req.setMethod('GET');
        req.setEndpoint(address);
        HttpResponse res = h.send(req);
        
        system.debug(address);

        if (res.getStatusCode() == 200){
        	Map<String,Object> gr = (Map<String,Object>)JSON.deserializeUntyped(res.getBody());
			List<Object> results = (List<Object>)gr.get('results');
        	Map<String,Object> firstResult = (Map<String,Object>)results[0];  
        	if (firstResult != null){            
        		String fullAddress = (String)firstResult.get('formatted_address');
        		List<Animal__c> lstAnim = [SELECT Formatted_Address__c FROM Animal__c WHERE Id = :animalId];
            	if (!lstAnim.isEmpty()){
                	lstAnim[0].Formatted_Address__c = fullAddress;
                	system.debug(lstAnim[0].Formatted_Address__c);
            	}
        		update lstAnim;
        	}
        }
    }

    @testVisible
    private static void createBrcMrcTasks(Animal__c[] animals){
        try {
            //make sure we're not creating duplicate tasks
            System.debug('**createBrcMrcTasks');
            Map<Id, Animal__c> queriedAnimals = new Map<Id, Animal__c>([
                SELECT Id, (
                    SELECT Id, ActivityDate, Record_Type__c 
                    FROM Activities__r 
                    WHERE Record_Type__c =: AutoScheduleTasksUtil.MRC_BRC_FOLLOW_UP_TASK_RECORD_TYPE_NAME 
                    ORDER BY ActivityDate DESC 
                    LIMIT 1
                ) 
                FROM Animal__c WHERE Id IN: animals]
            );
            Task[] toInsert = new Task[0];
            for(Animal__c anim : animals){
                if(!queriedAnimals.get(anim.Id).Activities__r.isEmpty()){
                    if(queriedAnimals.get(anim.Id).Activities__r[0].ActivityDate < date.today()){
                        toInsert.add(ScheduleAnimalBRCMRC.prepTask(anim, date.today().addDays(14), false));
                    }
                }
                else {
                    toInsert.add(ScheduleAnimalBRCMRC.prepTask(anim, date.today().addDays(14), false));
                }
            }
            insert toInsert;
        } catch (Exception e) {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(new String[]{'steven.workman@aspca.com'});
            mail.setSenderDisplayName('Animal Trigger Error:');
            mail.setSubject('Animal Trigger Error');
            mail.setHtmlBody(
                'Error with createBrcMrcTasks: ' + e.getMessage() +' </br>'+
                'StackTrace: ' + e.getStackTraceString() + '</br>' + 
                'userName: ' + userInfo.getName()
            );
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }

    private static void reviewForMRCDailyCare(Animal__c[] animals, Map<Id, Animal__c> oldAnimals){
        Animal_Daily_Care__c[] newAdcs = new Animal_Daily_Care__c[0];
        //this list is for animals that have had certain updates that need to be pushed to the current animal daily care.
        Animal__c[] updatedAnimals = new Animal__c[0];
        for(Animal__c anim : animals){
            if(anim.Current_Location__c == 'MRC' && anim.Final_Outcome__c == null){
                Animal__c oldAnim = oldAnimals.get(anim.Id);
                if(oldAnim.Current_Location__c != anim.Current_Location__c){
                    newAdcs.add(prepADC(anim));
                }
                else if(anim.Handling_Instructions__c != oldAnim.Handling_Instructions__c){
                    updatedAnimals.add(anim);
                }
                else if(anim.Feeding_Amount__c != oldAnim.Feeding_Amount__c){
                    updatedAnimals.add(anim);
                }
            }
        }

        if(!newAdcs.isEmpty()){
            insertNewAnimalDailyCares(newAdcs);
        }

        if(!updatedAnimals.isEmpty()){
            updateAnimalDailyCares(updatedAnimals);
        }
    }

    private static void updateAnimalDailyCares(Animal__c[] animals){
        Animal_Daily_Care__c[] adcs = [SELECT Id, Handling_Instructions__c, Feeding_Amount__c, Animal__r.Handling_Instructions__c, Animal__r.Feeding_Amount__c FROM Animal_Daily_Care__c WHERE Animal__c IN: animals AND Daily_Care__r.Date__c = TODAY];
        for(Animal_Daily_Care__c adc : adcs){
            adc.Handling_Instructions__c = adc.Animal__r.Handling_Instructions__c;
            adc.Feeding_Amount__c = adc.Animal__r.Feeding_Amount__c;
        }

        update adcs;
    }

    private static void reviewForMRCDailyCare(Animal__c[] animals){
        Animal_Daily_Care__c[] newAdcs = new Animal_Daily_Care__c[0];
        for(Animal__c anim : animals){
            if(anim.Current_Location__c == 'MRC' && anim.Final_Outcome__c == null){
                newAdcs.add(
                    prepADC(anim)
                );
            }
        }

        if(!newAdcs.isEmpty()){
            insertNewAnimalDailyCares(newAdcs);
        }
    }

    private static void insertNewAnimalDailyCares(Animal_Daily_Care__c[] newAdcs){
        Daily_Care__c[] dcs = [SELECT Id FROM Daily_Care__c WHERE Date__c = TODAY ORDER BY Date__c DESC LIMIT 1];
        if(!dcs.isEmpty()){
            Daily_Care__c dc = dcs[0];
            for(Animal_Daily_Care__c adc : newAdcs){
                adc.Daily_Care__c = dc.Id;
            }
            insert newAdcs;
        }
    }

    private static Animal_Daily_Care__c prepADC(Animal__c anim){
        return new Animal_Daily_Care__c(
            Animal__c = anim.Id,
            Handling_Instructions__c = anim.Handling_Instructions__c,
            Round__c = '1',
            Special_Care_Outside_TX__c = 'Dry',
            Special_Care_TX__c = 'Dry + Wet',
            Movements_For_Cleaning__c = null
        );
    }
    
     public static void beforeFieldUpdateHandler(List<Animal__c> anms, Map<Id, Animal__c> oldAnms){
        for(Animal__c anm: anms){
            if(anm.Seizure_Surrender_Date__c != oldAnms.get(anm.Id).Seizure_Surrender_Date__c ){
                anm.Email_Notification__c = true;
            }
        }
    }

}